salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Type__c.field-meta.xml
<CustomField>
    <fullName>Query_Type__c</fullName>
    <label>Query Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assessments</fullName>
            </value>
            <value>
                <fullName>Attendance</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Changes to personal details</fullName>
            </value>
            <value>
                <fullName>Changes to studies</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Finance and Billing</fullName>
            </value>
            <value>
                <fullName>Graduation and Certificates</fullName>
            </value>
            <value>
                <fullName>IoS (Interruption of Studies)</fullName>
            </value>
            <value>
                <fullName>Letter requests</fullName>
            </value>
            <value>
                <fullName>My Apprenticeship</fullName>
            </value>
            <value>
                <fullName>My Course</fullName>
            </value>
            <value>
                <fullName>My Online Learning and The HUB</fullName>
            </value>
            <value>
                <fullName>My Study Materials</fullName>
            </value>
            <value>
                <fullName>Online learning</fullName>
            </value>
            <value>
                <fullName>Registration and enrolment</fullName>
            </value>
            <value>
                <fullName>Review Meeting</fullName>
            </value>
            <value>
                <fullName>Student Finance</fullName>
            </value>
            <value>
                <fullName>Student Loans</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Undetermined Query</fullName>
            </value>
            <value>
                <fullName>Prior Learning/Exemptions information</fullName>
            </value>
            <value>
                <fullName>Additional Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <label>Programme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intensive</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Integrated no gap</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>KGS</fullName>
            </value>
            <value>
                <fullName>School leaver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Application_Decision_Comment__c.field-meta.xml
<CustomField>
    <fullName>BNR_Application_Decision_Comment__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Application Decision Comment</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Cycle_Override__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Override__c</fullName>
    <description>Cycle override is used to set the cycle for the opportunity if it differs from the student.  By default it will select &quot;Use Student Cycle&quot;.</description>
    <label>Cycle Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Use Student Cycle</fullName>
                <default>true</default>
                <label>Use Student Cycle</label>
            </value>
            <value>
                <fullName>Pursue</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Enrolment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Status__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <description>Stages to enrolment once application has been accepted</description>
    <label>Enrolment Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Post-Registration (non-attendees)</fullName>
            </value>
            <value>
                <fullName>First Instalment Paid</fullName>
            </value>
            <value>
                <fullName>Temporarily Registered</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_ADMT_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_ADMT_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions ADMT Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9~ UCAS</fullName>
            </value>
            <value>
                <fullName>AG~ Agent</fullName>
            </value>
            <value>
                <fullName>DI~ Direct</fullName>
            </value>
            <value>
                <fullName>LC~ Law CABs</fullName>
            </value>
            <value>
                <fullName>MI~ Milkround</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_RESD_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_RESD_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions RESD Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U~ UK National</fullName>
            </value>
            <value>
                <fullName>L~ Indefinite Leave to Remain</fullName>
            </value>
            <value>
                <fullName>R~ Right of Abode</fullName>
            </value>
            <value>
                <fullName>E~ EU National</fullName>
            </value>
            <value>
                <fullName>F~ EU National Family Member</fullName>
            </value>
            <value>
                <fullName>M~ EEA Family Member</fullName>
            </value>
            <value>
                <fullName>R~ Refugee</fullName>
            </value>
            <value>
                <fullName>B~ Refugee Family Member</fullName>
            </value>
            <value>
                <fullName>H~ Humanitarian Protection</fullName>
            </value>
            <value>
                <fullName>P~ Humanitarian Protection Family</fullName>
            </value>
            <value>
                <fullName>T~ Child of a Turkish worker</fullName>
            </value>
            <value>
                <fullName>C~ Child of a Swiss National</fullName>
            </value>
            <value>
                <fullName>A~ EEA</fullName>
            </value>
            <value>
                <fullName>O~ Non-EEA VISA  required</fullName>
            </value>
            <value>
                <fullName>V~ Non-EEA no VISA required</fullName>
            </value>
            <value>
                <fullName>G~ England</fullName>
            </value>
            <value>
                <fullName>S~ Scotland</fullName>
            </value>
            <value>
                <fullName>W~ Wales</fullName>
            </value>
            <value>
                <fullName>N~ Northern Ireland</fullName>
            </value>
            <value>
                <fullName>I~ Islands (Man, Channel)</fullName>
            </value>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_STYPE_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_STYPE_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions STYPE Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
            <value>
                <fullName>N~ New</fullName>
            </value>
            <value>
                <fullName>R~ Returning</fullName>
            </value>
            <value>
                <fullName>C~ Continuing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Attribute_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Attribute_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Attribute Code Select - Reference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FT~ Full Time Student</fullName>
            </value>
            <value>
                <fullName>PT~ Part Time Student</fullName>
            </value>
            <value>
                <fullName>FL~ Flex</fullName>
            </value>
            <value>
                <fullName>T4~ Tier 4 International Student</fullName>
            </value>
            <value>
                <fullName>S1~ Year 1 / Stage 1</fullName>
            </value>
            <value>
                <fullName>S2~ Year 2 / Stage 2</fullName>
            </value>
            <value>
                <fullName>S3~ Year 3 / Stage 3</fullName>
            </value>
            <value>
                <fullName>SP~ Sponsor</fullName>
            </value>
            <value>
                <fullName>ACCE~ Accelerated</fullName>
            </value>
            <value>
                <fullName>ONLN~ Online</fullName>
            </value>
            <value>
                <fullName>BLEN~ Blended</fullName>
            </value>
            <value>
                <fullName>FTF~ Face to Face</fullName>
            </value>
            <value>
                <fullName>DLA~ Distance Learning Mode A</fullName>
            </value>
            <value>
                <fullName>EVE~ Evening</fullName>
            </value>
            <value>
                <fullName>SATU~ Saturday</fullName>
            </value>
            <value>
                <fullName>SUN~ Sunday</fullName>
            </value>
            <value>
                <fullName>WEK~ Weekend</fullName>
            </value>
            <value>
                <fullName>KC~ Key Client</fullName>
            </value>
            <value>
                <fullName>IH~ In House client</fullName>
            </value>
            <value>
                <fullName>EXAM~ Store Exam Results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/CaseTriggerHandlerTest.cls
@isTest
public class CaseTriggerHandlerTest {
    @TestSetup
    private static void setup() {
        Id studentAccount = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get('Student Account')
            .getRecordTypeId();

        Id apprenticeOnboarding = Schema.Sobjecttype.Case.getRecordTypeInfosByName()
            .get('Apprentice Onboarding')
            .getRecordTypeId();

        Id apprenticeApplication = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
            .get('Apprentice Application')
            .getRecordTypeId();

        insert new List<Case>{
            new Case(
                Subject = 'Test Case',
                RecordTypeId = apprenticeOnboarding,
                Query_Type__c = 'General Query',
                Origin = 'Email',
                Status = 'New'
            )
        };

        List<Account> accounts = new List<Account>{
            new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = studentAccount),
            new Account(FirstName = 'Test2', LastName = 'Test2', RecordTypeId = studentAccount)
        };

        insert accounts;

        insert new List<Opportunity>{
            new Opportunity(
                RecordTypeId = apprenticeApplication,
                AccountId = accounts[0].Id,
                Name = 'Test Opportunity1',
                StageName = 'Application',
                Application_Id__c = 'test-1234',
                CloseDate = Date.today() + 30
            ),
            new Opportunity(
                RecordTypeId = apprenticeApplication,
                AccountId = accounts[1].Id,
                Name = 'Test Opportunity2',
                StageName = 'Application',
                Application_Id__c = 'test-4321',
                CloseDate = Date.today() + 30
            ),
            new Opportunity(
                RecordTypeId = apprenticeApplication,
                AccountId = accounts[1].Id,
                Name = 'Test Opportunity3',
                StageName = 'Application',
                Application_Id__c = 'test-4444',
                CloseDate = Date.today() + 30
            )
        };
    }

    static testMethod void testSendStatusHolidayLetter() {
        Test.startTest();
        country_list__c cntry = CreateTestData.createCountry1();

        Account a1 = CreateTestData.createAccount1(cntry);
        a1.BNR_Banner_ID__pc = 'BP1234567';
        update a1;

        Id conId = [SELECT Id, name, PersonContactId FROM Account WHERE Id = :a1.Id].PersonContactId;

        State_Province__c stt = CreateTestData.createStateProvince();
        Locality__c lct = CreateTestData.createLocality();
        Contact tmC = CreateTestData.createTMContact();
        Address__c addr = CreateTestData.createAddress(a1, null, tmC, cntry, stt, lct, true, 'Mailing');
        try {
            addr = CreateTestData.createAddress(a1, null, tmC, cntry, stt, lct, false, 'Home');
        } catch (Exception e) {
        }

        Programme__c prgrm = CreateTestData.createProgram();
        Product2 prd = CreateTestData.createProduct(prgrm, 'OFFERING');

        Opportunity opp1 = new Opportunity();
        opp1.AccountId = a1.id;
        opp1.Name = 'test';
        opp1.StageName = 'Accepted - Conditional Firm';
        opp1.Enrolment_Status__c = 'Acceptance';
        opp1.Cycle_Override__c = 'Use Student Cycle';
        opp1.CloseDate = Date.valueOf('2015-02-27');
        opp1.BNR_Application_Decision_Comment__c = 'ABCD';
        opp1.SFDC_Attribute_Code_Select__c = 'FT~ Full Time Student';
        opp1.SFDC_Admissions_ADMT_Code_Select__c = 'DI~ Direct';
        opp1.SFDC_Admissions_STYPE_Code_Select__c = 'R~ Returning';
        opp1.SFDC_Admissions_RESD_Code_Select__c = 'E~ EU National';
        opp1.SFDC_Cohort_Code_Select__c = 'C6~ Cohort June';
        opp1.BNR_Curriculum_Status_Code__c = 'REGISTERED';
        opp1.Course_Instance__c = prd.Id;
        opp1.Programme_Application__c = prgrm.Id;
        insert opp1;

        Case cse = new Case();
        cse.RecordTypeId = Schema.sObjectType.Case.getRecordTypeInfosByName().get('Student Query').getRecordTypeId();
        cse.Query_Type__c = 'Letter requests';
        cse.Query_Subtype__c = 'I would like to request a Bank, Status or Council Tax letter';
        cse.Origin = 'Web';
        cse.Status = 'New';
        cse.ContactId = conId;
        cse.Study_Location__c = 'Doncaster';
        cse.School__c = 'Business';
        cse.SuppliedEmail = 'john@john.com';
        cse.Student_ID_Number__c = 'BP1234567';
        insert cse;
        Test.stopTest();
    }

    @isTest
    private static void doNotUpdateApprenticeOnboardingCasesForMultipleOpportunities() {
        //GIVEN an Apprentice Onboarding Case
        Case caseObj = [
            SELECT AccountId
            FROM Case
            WHERE Subject = 'Test Case'
        ];
        //AND a Student with only one valid Opportunity against it
        Account acc = [SELECT Id, FirstName, LastName, RecordTypeId FROM Account WHERE LastName = 'Test2'];

        //WHEN the Case has been updated to relate to the Student Account
        System.Test.startTest();

        caseObj.AccountId = acc.Id;
        update caseObj;

        System.Test.stopTest();
        //THEN I expect the Opportunity field on the Case to be updated to the existing Opportunity
        Case caseOut = [
            SELECT Opportunity__c
            FROM Case
            WHERE Id = :caseObj.Id
        ];

        Assert.areEqual(caseOut.Opportunity__c, null);
    }

    @isTest
    private static void updateApprenticeOnboardingCasesForSingleOpportunity() {
        //GIVEN an Apprentice Onboarding Case
        Case caseObj = [
            SELECT AccountId
            FROM Case
            WHERE Subject = 'Test Case'
        ];

        //AND a Student with only one valid Opportunity against it
        Account acc = [SELECT Id, FirstName, LastName, RecordTypeId FROM Account WHERE LastName = 'Test'];

        //WHEN the Case has been updated to relate to the Student Account
        System.Test.startTest();

        caseObj.AccountId = acc.Id;
        update caseObj;

        System.Test.stopTest();

        //THEN I expect the Opportunity field on the Case to be updated to the existing Opportunity
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-1234'];

        Case caseOut = [
            SELECT Opportunity__c
            FROM Case
            WHERE Id = :caseObj.Id
        ];

        Assert.areEqual(caseOut.Opportunity__c, opp.Id);
    }
}