salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/Test_updateFormattedPhoneonAccount.cls
/**
 * This class contains unit tests for validating the behavior of Apex class AddressTriggerHandler
 */
@isTest
private class Test_updateFormattedPhoneonAccount {

    static testMethod void myUnitTest() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = CreateTestData.createStateProvince();
        Locality__c lct = CreateTestData.createLocality();
        Account a = CreateTestData.createAccount1(cntry);
        
        Contact tmC = CreateTestData.createTMContact();
        Test.startTest();
        Address__c addr = CreateTestData.createAddress(a, null, tmC, cntry, stt, lct, true, 'Mailing');
        try{
            addr = CreateTestData.createAddress(a, null, tmC, cntry, stt, lct, false, 'Home');
        }catch(Exception e){
            system.debug(e.getMessage());
        }
        Test.stopTest();
    }
    static testMethod void myUnitTest1() {
        country_list__c cntry = CreateTestData.createCountry1();
        cntry.Name = 'United Kingdom';
        update cntry;
        State_Province__c stt = CreateTestData.createStateProvince();
        Locality__c lct = CreateTestData.createLocality();
        Account a = CreateTestData.createAccount1(cntry);
        a.PersonMobilePhone = '9999999999';
        update a;
        Contact tmC = CreateTestData.createTMContact();
        Test.startTest();
        Address__c addr = CreateTestData.createAddress(a, null, tmC, cntry, stt, lct, true, 'Mailing');
        
        try{
            addr = CreateTestData.createAddress(a, null, tmC, cntry, stt, lct, false, 'Home');
            addr.Type__c = 'Mailing';
            update addr;
        }catch(Exception e){
            system.debug(e.getMessage());
        }
        Test.stopTest();
    }
    static testMethod void myUnitTest2() {
        country_list__c cntry = CreateTestData.createCountry1();
        cntry.Name = 'United Kingdom';
        update cntry;
        State_Province__c stt = CreateTestData.createStateProvince();
        Locality__c lct = CreateTestData.createLocality();
        Account a = CreateTestData.createAccount1(cntry);
        a.PersonMobilePhone = '9999999999';
        update a;
        Contact tmC = CreateTestData.createTMContact();
        Test.startTest();
        
        try{
           Address__c addr = CreateTestData.createAddress(a, null, tmC, cntry, stt, lct, false, 'Home');
            addr.Type__c = 'Mailing';
            update addr;
        }catch(Exception e){
            system.debug(e.getMessage());
        }
        Test.stopTest();
    }
}