salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Product Catalog Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PCItem #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity_Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Catalog Items</relationshipLabel>
    <relationshipName>Product_Catalog_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity_Product__c/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <formula>Product__r.Programme__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/Test_OfferingSelectorController.cls
/**
 * This class contains unit tests for validating the behavior of Apex class OfferingSelectorController.
 */
@isTest
private class Test_OfferingSelectorController {

    static testMethod void myUnitTest() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = CreateTestData.createStateProvince();
        Locality__c lct = CreateTestData.createLocality();
        Account a = CreateTestData.createAccount1(cntry);
        Address__c addr = CreateTestData.createAddress(a, null, null, cntry, stt, lct, true, 'Billing');
        Opportunity o = CreateTestData.createOpportunity(a);
        Programme__c pgrm = CreateTestData.createProgram();
        Product2 pd = CreateTestData.createProduct(pgrm,'OFFERING');
        //Opportunity_Product__c oppPrd = CreateTestData.createOppProduct(o, pd, true);
        Product2 pd1 = CreateTestData.createProduct(pgrm, 'OFFERING', 'name1', '0001', null, null);
        PC_Bundle__c pcB = CreateTestData.createBundle('bId33242', 'fName', 3243.3);
        PC_Bundle__c pcB1 = CreateTestData.createBundle('bId33240', 'fName1', 324.3);
        PC_Bundle_Extension__c pce = CreateTestData.createBundleExtension(pcB, pcB1);
        PC_Item__c pcI = CreateTestData.createPCItem(pd1, pcB, pgrm);
        PC_Item__c pcI1 = CreateTestData.createPCItem(pd1, null, pgrm);
        Test.startTest();
        Opportunity_Product__c oppPrd1 = new Opportunity_Product__c();
        oppPrd1.Opportunity__c = o.Id;
        Pagereference pg = new Pagereference('/apex/OfferingSelectorController');
        Test.setCurrentPage(pg);
        ApexPages.StandardController con = new ApexPages.StandardController(oppPrd1);   
        OfferingSelectorController osc = new OfferingSelectorController(con);
        
        osc.searchText = '';
        osc.searchOfferings();
        osc.searchProduct = 'name';
        osc.searchOfferings();
        
        List<OfferingSelectorController.ProductWrapper> p = osc.offeringSearchResults;
        p[0].isSelected = true;
        
        pg.getParameters().put('selectedOfferingId',pd1.Id);
        osc.offeringSelected();
        List<OfferingSelectorController.BundleWrapper> bw = osc.bundleSearchResults;
        bw[0].isSelected = true;
        pg.getParameters().put('selectedBundleId',pcb.Id);
        osc.bundleSelected();
        
        List<OfferingSelectorController.ItemWrapper> iw = osc.bundleContents;
        iw[0].isPrimary = true;
        pg.getParameters().put('selectedProductId',pd1.Id);
        osc.productPrimarySelected();
        
        osc.addProducts();
        osc.returnToOpportunity();
        
        
        oppPrd1 = new Opportunity_Product__c();
        oppPrd1.Opportunity__c = o.Id;
        con = new ApexPages.StandardController(oppPrd1);   
        osc = new OfferingSelectorController(con);
        Test.stopTest();
    }
}