salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Record_Source__c.field-meta.xml
<CustomField>
    <fullName>Record_Source__c</fullName>
    <description>Indicates from what data source the record was created. &quot;Salesforce&quot; indicates a record that was manually entered.</description>
    <inlineHelpText>Indicates from what data source the record was created. &quot;Salesforce&quot; indicates a record that was manually entered.</inlineHelpText>
    <label>Record Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Direct Apps</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>UCAS</fullName>
            </value>
            <value>
                <fullName>BARSAS</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Hub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/Institute_Body__c.object-meta.xml
<CustomObject>
    <description>Institute Bodies that a student is a member of</description>
    <label>Institute Body</label>
    <nameField>
        <displayFormat>IB{00000000}</displayFormat>
        <label>Institute Body ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institute Bodies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Body__c.field-meta.xml
<CustomField>
    <fullName>Institute_Body__c</fullName>
    <description>Institute Body</description>
    <label>Institute Body</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>Apprenticeships</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CBI</fullName>
            </value>
            <value>
                <fullName>CFA</fullName>
            </value>
            <value>
                <fullName>CII</fullName>
            </value>
            <value>
                <fullName>CIMA</fullName>
            </value>
            <value>
                <fullName>CIPD</fullName>
            </value>
            <value>
                <fullName>CISI</fullName>
            </value>
            <value>
                <fullName>CMI</fullName>
            </value>
            <value>
                <fullName>CTA</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>IAD</fullName>
            </value>
            <value>
                <fullName>ICAEW</fullName>
            </value>
            <value>
                <fullName>ICAS</fullName>
            </value>
            <value>
                <fullName>ICSA</fullName>
            </value>
            <value>
                <fullName>IMC</fullName>
            </value>
            <value>
                <fullName>Insolvency</fullName>
            </value>
            <value>
                <fullName>IOC</fullName>
            </value>
            <value>
                <fullName>ITP</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>PMI</fullName>
            </value>
            <value>
                <fullName>Association of Accounting Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Accounting Technicians</label>
            </value>
            <value>
                <fullName>Association of Chartered Certified Accountants</fullName>
                <isActive>false</isActive>
                <label>Association of Chartered Certified Accountants</label>
            </value>
            <value>
                <fullName>Association of Tax Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Tax Technicians</label>
            </value>
            <value>
                <fullName>CII Diploma in Regulated Financial Planning</fullName>
                <isActive>false</isActive>
                <label>CII Diploma in Regulated Financial Planning</label>
            </value>
            <value>
                <fullName>CISI Apprenticeship Programmes</fullName>
                <isActive>false</isActive>
                <label>CISI Apprenticeship Programmes</label>
            </value>
            <value>
                <fullName>CISI Capital Markets</fullName>
                <isActive>false</isActive>
                <label>CISI Capital Markets</label>
            </value>
            <value>
                <fullName>CISI Cert in Private Client Investment Advice&amp;Mgmt</fullName>
                <isActive>false</isActive>
                <label>CISI Cert in Private Client Investment Advice&amp;Mgmt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Number__c.field-meta.xml
<CustomField>
    <fullName>Institute_Number__c</fullName>
    <description>Student&apos;s membership number of the institute body</description>
    <label>Institute Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Student account that is a member of the professional body institution</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Must be a student account</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institute Bodies</relationshipLabel>
    <relationshipName>Institute_Bodies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/StudentSync.cls
/**
 * Handles serializing payloads for the `userAccountUpdated` event
 */
public without sharing class StudentSync implements Serializer {
    /**
     * A set of account ids
     */
    public Set<Id> accountIds;

    /**
     * A List of accounts to process
     */
    @TestVisible
    private List<Account> accounts;

    /**
     * A map of Auth0 Id's keyed by Account Id
     */
    private Map<Id, List<String>> authIds;

    /**
     * A collection of address payloads
     */
    private Map<Id, List<Map<String, Object>>> addressPayloads;

    /**
     * A collection of Institute Body payloads
     */
    private Map<Id, List<Map<String, Object>>> institutePayloads;

    public StudentSync() {
        accounts = new List<Account>();
        accountIds = new Set<Id>();
    }

    /**
     * Adds the given account to the map to process
     * @param record Account to process
     */
    public void addRecord(SObject record) {
        // Figure out which Sobject type is being added
        switch on record.getSObjectType().getDescribe().getName() {
            when 'Account' {
                accountIds.add(record.Id);
            }
            when 'Address__c', 'Hub_Account__c', 'Institute_Body__c' {
                accountIds.add((Id) record.get('Student__c'));
            }
        }
    }

    /**
     * Collects the various dependent records and creates payloads
     * @return  Payloads to send to an Emitter
     */
    public List<Map<String, Object>> serialize() {
        List<Map<String, Object>> payloads = new List<Map<String, Object>>();

        fetchAccounts();
        fetchAuthIds();
        fetchAddresses();
        fetchInstituteBodies();

        for (Account account : accounts) {
            List<Object> qualifications = new List<Object>();
            if (institutePayloads.containsKey(account.Id)) {
                qualifications = institutePayloads.get(account.Id);
            }

            if (!authIds.containsKey(account.Id)) {
                continue;
            }

            Map<String, Object> payload = new Map<String, Object>{
                'userIds' => authIds.get(account.Id),
                'studentReferenceNumber' => account.BNR_Banner_ID__pc,
                'personalInfo' => new Map<String, Object>{
                    'title' => account.Salutation,
                    'firstName' => account.FirstName,
                    'lastName' => account.LastName,
                    'middleName' => account.Middle_Name__pc,
                    'preferredName' => account.Preferred_First_Name__pc,
                    'emailAddress' => account.PersonEmail,
                    'dateOfBirth' => account.PersonBirthdate,
                    'mobilePhone' => account.PersonMobilePhone,
                    'workPhone' => account.Work_Phone__pc,
                    'homePhone' => account.PersonHomePhone,
                    'preferredPronouns' => account.PersonPronouns
                },
                'marketingPreferences' => getMarketingPreferences(account),
                'addresses' => addressPayloads.get(account.Id),
                'emergencyContact' => new Map<String, Object>{
                    'relationship' => account.Emergency_Contact_Relationship__pc,
                    'firstName' => account.Emergency_Contact_First_Name__pc,
                    'lastName' => account.Emergency_Contact_Last_Name__pc,
                    'emailAddress' => account.Emergency_Contact_Email__pc,
                    'mobilePhone' => account.Emergency_Contact_Mobile__pc
                },
                'professionalQualifications' => qualifications
            };

            payloads.add(payload);
        }

        return payloads;
    }

    /**
     * Fetches the accounts using the related account set
     */
    private void fetchAccounts() {
        for (Account account : [
            SELECT
                Id,
                Salutation,
                FirstName,
                LastName,
                Middle_Name__pc,
                Preferred_First_Name__pc,
                PersonEmail,
                PersonBirthdate,
                PersonMobilePhone,
                Work_Phone__pc,
                PersonHomePhone,
                Emergency_Contact_Email__pc,
                Emergency_Contact_First_Name__pc,
                Emergency_Contact_Last_Name__pc,
                Emergency_Contact_Mobile__pc,
                Emergency_Contact_Relationship__pc,
                PersonPronouns,
                Post_Opt_In__pc,
                Email_Opt_In__pc,
                Phone_Opt_In__pc,
                Social_Media_Opt_In__pc,
                SMS_Opt_In__pc,
                App_Notifications_Opt_In__pc,
                BNR_Banner_ID__pc
            FROM Account
            WHERE Id IN :accountIds
        ]) {
            accounts.add(account);
        }
    }

    /**
     * Collects the various dependent Address records and creates payloads
     */
    private void fetchAddresses() {
        addressPayloads = new Map<Id, List<Map<String, Object>>>();
        Map<Id, Map<String, Address__c>> studentToAddress = new Map<Id, Map<String, Address__c>>();

        for (Address__c address : [
            SELECT
                Type__c,
                Street_1__c,
                Street_2__c,
                Street_3__c,
                City__c,
                Zip_Postal_Code__c,
                Record_Source__c,
                Student__c,
                Lookup_Country__r.country_code_2__c
            FROM Address__c
            WHERE Student__c IN :accountIds AND Active__c = TRUE AND Type__c != NULL
        ]) {
            // De-dupe addresses
            Map<String, Address__c> typeToAddress = studentToAddress.get(address.Student__c);

            if (typeToAddress == null) {
                typeToAddress = new Map<String, Address__c>();
            }

            typeToAddress.put(address.Type__c, address);

            studentToAddress.put(address.Student__c, typeToAddress);
        }

        // add addresses to payload map
        for (Id studentId : studentToAddress.keySet()) {
            List<Map<String, Object>> addressList = new List<Map<String, Object>>();

            Map<String, Address__c> typeToAddress = studentToAddress.get(studentId);
            for (String addressType : typeToAddress.keySet()) {
                Address__c address = typeToAddress.get(addressType);

                // use addressType instead of the type field, as it may be from the flag
                Map<String, Object> addressPayload = new Map<String, Object>{
                    'type' => addressType == 'Mailing' ? 'Delivery' : addressType,
                    'line1' => address.Street_1__c,
                    'line2' => address.Street_2__c,
                    'line3' => address.Street_3__c,
                    'town' => address.City__c,
                    'postalCode' => address.Zip_Postal_Code__c,
                    'recordSource' => address.Record_Source__c,
                    'country' => address.Lookup_Country__r.country_code_2__c
                };

                addressList.add(addressPayload);
            }

            addressPayloads.put(studentId, addressList);
        }
    }

    /**
     * Collects the various dependent Institute Bodies records and creates payloads
     */
    private void fetchInstituteBodies() {
        institutePayloads = new Map<Id, List<Map<String, Object>>>();

        for (Institute_Body__c institute : [
            SELECT Institute_Body__c, Institute_Number__c, Student__c
            FROM Institute_Body__c
            WHERE Student__c IN :accountIds
        ]) {
            Map<String, Object> institutePayload = new Map<String, Object>{
                'awardingBody' => institute.Institute_Body__c,
                'reference' => institute.Institute_Number__c
            };

            List<Map<String, Object>> instituteList = institutePayloads.get(institute.Student__c);

            if (instituteList == null) {
                instituteList = new List<Map<String, Object>>();
            }

            instituteList.add(institutePayload);
            institutePayloads.put(institute.Student__c, instituteList);
        }
    }

    /**
     * Checks for field values in selected Marketing Preference fields
     * and adds them to the used list of preferences if values are present
     * @param account  Account to extract Marketing Preferences from
     * @return A list of extracted Marketing Preferences
     */

    private List<String> getMarketingPreferences(Account account) {
        List<String> preferences = new List<String>();

        if (account.Post_Opt_In__pc) {
            preferences.add('Post');
        }
        if (account.Email_Opt_In__pc) {
            preferences.add('Email');
        }
        if (account.Phone_Opt_In__pc) {
            preferences.add('Phone');
        }
        if (account.Social_Media_Opt_In__pc) {
            preferences.add('Social media');
        }
        if (account.SMS_Opt_In__pc) {
            preferences.add('SMS');
        }
        if (account.App_Notifications_Opt_In__pc) {
            preferences.add('Push notification');
        }
        return preferences;
    }

    /**
     * Fetches the related Hub Account records and processes the Auth0 Id's
     */
    private void fetchAuthIds() {
        authIds = new Map<Id, List<String>>();

        for (Hub_Account__c hubAccount : [
            SELECT Auth0_Id__c, Student__c
            FROM Hub_Account__c
            WHERE Student__c IN :accountIds AND Auth0_Id__c != NULL
        ]) {
            List<String> ids = authIds.get(hubAccount.Student__c);

            if (ids == null) {
                ids = new List<String>();
            }

            ids.Add(hubAccount.Auth0_Id__c);
            authIds.put(hubAccount.Student__c, ids);
        }
    }
}