salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Student)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Application_Decision_Comment__c.field-meta.xml
<CustomField>
    <fullName>BNR_Application_Decision_Comment__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Application Decision Comment</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Curriculum_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>BNR_Curriculum_Status_Code__c</fullName>
    <label>Curriculum Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Cycle_Override__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Override__c</fullName>
    <description>Cycle override is used to set the cycle for the opportunity if it differs from the student.  By default it will select &quot;Use Student Cycle&quot;.</description>
    <label>Cycle Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Use Student Cycle</fullName>
                <default>true</default>
                <label>Use Student Cycle</label>
            </value>
            <value>
                <fullName>Pursue</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Enrolment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Status__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <description>Stages to enrolment once application has been accepted</description>
    <label>Enrolment Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Post-Registration (non-attendees)</fullName>
            </value>
            <value>
                <fullName>First Instalment Paid</fullName>
            </value>
            <value>
                <fullName>Temporarily Registered</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_ADMT_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_ADMT_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions ADMT Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9~ UCAS</fullName>
            </value>
            <value>
                <fullName>AG~ Agent</fullName>
            </value>
            <value>
                <fullName>DI~ Direct</fullName>
            </value>
            <value>
                <fullName>LC~ Law CABs</fullName>
            </value>
            <value>
                <fullName>MI~ Milkround</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_RESD_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_RESD_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions RESD Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U~ UK National</fullName>
            </value>
            <value>
                <fullName>L~ Indefinite Leave to Remain</fullName>
            </value>
            <value>
                <fullName>R~ Right of Abode</fullName>
            </value>
            <value>
                <fullName>E~ EU National</fullName>
            </value>
            <value>
                <fullName>F~ EU National Family Member</fullName>
            </value>
            <value>
                <fullName>M~ EEA Family Member</fullName>
            </value>
            <value>
                <fullName>R~ Refugee</fullName>
            </value>
            <value>
                <fullName>B~ Refugee Family Member</fullName>
            </value>
            <value>
                <fullName>H~ Humanitarian Protection</fullName>
            </value>
            <value>
                <fullName>P~ Humanitarian Protection Family</fullName>
            </value>
            <value>
                <fullName>T~ Child of a Turkish worker</fullName>
            </value>
            <value>
                <fullName>C~ Child of a Swiss National</fullName>
            </value>
            <value>
                <fullName>A~ EEA</fullName>
            </value>
            <value>
                <fullName>O~ Non-EEA VISA  required</fullName>
            </value>
            <value>
                <fullName>V~ Non-EEA no VISA required</fullName>
            </value>
            <value>
                <fullName>G~ England</fullName>
            </value>
            <value>
                <fullName>S~ Scotland</fullName>
            </value>
            <value>
                <fullName>W~ Wales</fullName>
            </value>
            <value>
                <fullName>N~ Northern Ireland</fullName>
            </value>
            <value>
                <fullName>I~ Islands (Man, Channel)</fullName>
            </value>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_STYPE_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_STYPE_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions STYPE Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
            <value>
                <fullName>N~ New</fullName>
            </value>
            <value>
                <fullName>R~ Returning</fullName>
            </value>
            <value>
                <fullName>C~ Continuing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Attribute_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Attribute_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Attribute Code Select - Reference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FT~ Full Time Student</fullName>
            </value>
            <value>
                <fullName>PT~ Part Time Student</fullName>
            </value>
            <value>
                <fullName>FL~ Flex</fullName>
            </value>
            <value>
                <fullName>T4~ Tier 4 International Student</fullName>
            </value>
            <value>
                <fullName>S1~ Year 1 / Stage 1</fullName>
            </value>
            <value>
                <fullName>S2~ Year 2 / Stage 2</fullName>
            </value>
            <value>
                <fullName>S3~ Year 3 / Stage 3</fullName>
            </value>
            <value>
                <fullName>SP~ Sponsor</fullName>
            </value>
            <value>
                <fullName>ACCE~ Accelerated</fullName>
            </value>
            <value>
                <fullName>ONLN~ Online</fullName>
            </value>
            <value>
                <fullName>BLEN~ Blended</fullName>
            </value>
            <value>
                <fullName>FTF~ Face to Face</fullName>
            </value>
            <value>
                <fullName>DLA~ Distance Learning Mode A</fullName>
            </value>
            <value>
                <fullName>EVE~ Evening</fullName>
            </value>
            <value>
                <fullName>SATU~ Saturday</fullName>
            </value>
            <value>
                <fullName>SUN~ Sunday</fullName>
            </value>
            <value>
                <fullName>WEK~ Weekend</fullName>
            </value>
            <value>
                <fullName>KC~ Key Client</fullName>
            </value>
            <value>
                <fullName>IH~ In House client</fullName>
            </value>
            <value>
                <fullName>EXAM~ Store Exam Results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Cohort_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Cohort_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Cohort Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1~ Cohort January</fullName>
            </value>
            <value>
                <fullName>C2~ Cohort February</fullName>
            </value>
            <value>
                <fullName>C3~ Cohort March</fullName>
            </value>
            <value>
                <fullName>C4~ Cohort April</fullName>
            </value>
            <value>
                <fullName>C5~ Cohort May</fullName>
            </value>
            <value>
                <fullName>C6~ Cohort June</fullName>
            </value>
            <value>
                <fullName>C7~ Cohort July</fullName>
            </value>
            <value>
                <fullName>C8~ Cohort August</fullName>
            </value>
            <value>
                <fullName>C9~ Cohort September</fullName>
            </value>
            <value>
                <fullName>C10~ Cohort October</fullName>
            </value>
            <value>
                <fullName>C11~ Cohort November</fullName>
            </value>
            <value>
                <fullName>C12~ Cohort December</fullName>
            </value>
            <value>
                <fullName>S1~ SLC May</fullName>
            </value>
            <value>
                <fullName>S2~ SLC Sep</fullName>
            </value>
            <value>
                <fullName>S3~ SLC Jan</fullName>
            </value>
            <value>
                <fullName>H1~ HESA 11/12</fullName>
            </value>
            <value>
                <fullName>H2~ HESA 12/13</fullName>
            </value>
            <value>
                <fullName>H3~ HESA 13/14</fullName>
            </value>
            <value>
                <fullName>H4~ HESA 14/15</fullName>
            </value>
            <value>
                <fullName>H5~ HESA 15/16</fullName>
            </value>
            <value>
                <fullName>H6~ HESA 16/17</fullName>
            </value>
            <value>
                <fullName>H7~ HESA 17/18</fullName>
            </value>
            <value>
                <fullName>H8~ HESA 18/19</fullName>
            </value>
            <value>
                <fullName>H9~ HESA 19/20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/StatusLetterPDFCtrlTest.cls
@isTest
private class StatusLetterPDFCtrlTest
{
    static testMethod void StatusLetterTest() 
    {
        
        country_list__c cntry = CreateTestData.createCountry1();
        
        Account a1 = CreateTestData.createAccount1(cntry);
        a1.BNR_Banner_ID__pc = 'BP1234567';
        update a1;
        
        Id conId = [select Id, name, PersonContactId from Account where Id =:a1.Id].PersonContactId;
        
        Address__c addr = new Address__c();
        addr.Active__c = true;
        addr.Student__c = a1.Id;
        addr.Street_1__c = 'Test Address Line 1';
        addr.City__c = 'Test City';
        addr.Zip_Postal_Code__c = 'ABC DEF';
        addr.Lookup_Country__c = cntry.Id;
        addr.Type__c = 'Mailing';
        insert addr;
        
        Address__c homeAddr = new Address__c();
        homeAddr.Active__c = true;
        homeAddr.Student__c = a1.Id;
        homeAddr.Street_1__c = 'Test Address Line 2';
        homeAddr.City__c = 'Test City1';
        homeAddr.Zip_Postal_Code__c = 'ABC DEFG';
        homeAddr.Lookup_Country__c = cntry.Id;
        homeAddr.Type__c = 'Home';
        insert homeAddr;
        
        Programme__c prgrm = CreateTestData.createProgram();
        
        Product2 prd = CreateTestData.createProduct(prgrm,'OFFERING');
        
        Opportunity opp1 = new Opportunity();
        opp1.AccountId = a1.id;
        opp1.Name = 'test';
        opp1.StageName = 'Accepted - Conditional Firm';
        opp1.Enrolment_Status__c = 'Acceptance';
        opp1.Cycle_Override__c = 'Use Student Cycle';
        opp1.CloseDate = Date.valueOf('2015-02-27'); 
        opp1.BNR_Application_Decision_Comment__c = 'ABCD';
        opp1.SFDC_Attribute_Code_Select__c = 'FT~ Full Time Student';
        opp1.SFDC_Admissions_ADMT_Code_Select__c = 'DI~ Direct';
        opp1.SFDC_Admissions_STYPE_Code_Select__c = 'R~ Returning';
        opp1.SFDC_Admissions_RESD_Code_Select__c = 'E~ EU National';
        opp1.SFDC_Cohort_Code_Select__c = 'C6~ Cohort June';
        opp1.BNR_Curriculum_Status_Code__c = 'REGISTERED';
        opp1.Course_Instance__c=prd.Id;
        opp1.Programme_Application__c =prgrm .Id;
        insert opp1;
        
        Test.startTest();
        Case cse = new Case();
        cse.RecordTypeId=Schema.sObjectType.Case.getRecordTypeInfosByName().get('Student Query').getRecordTypeId();
        cse.Query_Type__c = 'Letter requests';
        cse.Query_Subtype__c = 'Status Letter';
        cse.Origin = 'Web';
        cse.Status = 'New';
        cse.ContactId = conId;
        cse.Study_Location__c = 'Doncaster';
        cse.School__c='Business';
        cse.SuppliedEmail = 'john@john.com';
        insert cse;

        PageReference PDf =  Page.StatusLetterPDF;
        PDf.getParameters().put('Id',cse.Id);
        PDf.getParameters().put('oppId',opp1.id);
        PDf.getParameters().put('addId',addr.Id);
        PDf.getParameters().put('homeAddId',homeAddr.Id);
        PDf.getParameters().put('subquery','Status Letter');
        Test.setCurrentPage(PDf);
        StatusLetterPDFCtrl ctrl = new StatusLetterPDFCtrl();
        //Test.stopTest();
        
        //Test.startTest();
        Case cse1 = new Case();
        cse1.RecordTypeId=Schema.sObjectType.Case.getRecordTypeInfosByName().get('Student Query').getRecordTypeId();
        cse1.Query_Type__c = 'Letter requests';
        cse1.Query_Subtype__c = 'Bank';
        cse1.Bank_Name__c = 'HSBC';
        cse1.Origin = 'Web';
        cse1.Status = 'New';
        cse1.ContactId = conId;
        cse1.Study_Location__c = 'Doncaster';
        cse1.School__c='Business';
        cse1.SuppliedEmail = 'john@john.com';
        insert cse1;

        PageReference PDf1 =  Page.StatusLetterPDF;
        PDf1.getParameters().put('Id',cse1.Id);
        PDf1.getParameters().put('oppId',opp1.id);
        PDf1.getParameters().put('addId',addr.Id);
        PDf1.getParameters().put('homeAddId',homeAddr.Id);
        PDf1.getParameters().put('subquery','Bank');
        Test.setCurrentPage(PDf1);
        StatusLetterPDFCtrl ctrl1 = new StatusLetterPDFCtrl();
        //Test.stopTest();
        
        //Test.startTest();
        Case cse2 = new Case();
        cse2.RecordTypeId=Schema.sObjectType.Case.getRecordTypeInfosByName().get('Student Query').getRecordTypeId();
        cse2.Query_Type__c = 'Letter requests';
        cse2.Query_Subtype__c = 'I would like a Council Tax letter';
        cse2.Origin = 'Web';
        cse2.Status = 'New';
        cse2.ContactId = conId;
        cse2.Study_Location__c = 'Doncaster';
        cse2.School__c='Business';
        cse2.SuppliedEmail = 'john@john.com';
        insert cse2;

        PageReference PDf2 =  Page.StatusLetterPDF;
        PDf2.getParameters().put('Id',cse2.Id);
        PDf2.getParameters().put('oppId',opp1.id);
        PDf2.getParameters().put('addId',addr.Id);
        PDf2.getParameters().put('homeAddId',homeAddr.Id);
        PDf2.getParameters().put('subquery','I would like a Council Tax letter');
        Test.setCurrentPage(PDf2);
        StatusLetterPDFCtrl ctrl2 = new StatusLetterPDFCtrl();
        Test.stopTest();
    }
}