salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Query_Subtype__c</fullName>
    <label>Query Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Query_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Authorised Leave</fullName>
            </value>
            <value>
                <fullName>How do I access my EBook?</fullName>
            </value>
            <value>
                <fullName>How do I access my results and feedback</fullName>
            </value>
            <value>
                <fullName>How do I collect my ID card?</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from accessing my e-materials</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from studying</fullName>
            </value>
            <value>
                <fullName>I am in financial difficulty, what are my options?</fullName>
            </value>
            <value>
                <fullName>I am on Interruption of Studies and wish to extend</fullName>
            </value>
            <value>
                <fullName>I am taking an interruption of studies, how does that affect my payment plan and fees?</fullName>
            </value>
            <value>
                <fullName>I can&apos;t access my forum</fullName>
            </value>
            <value>
                <fullName>I can’t see my course within my online learning platform</fullName>
            </value>
            <value>
                <fullName>I have a different problem with my online learning</fullName>
            </value>
            <value>
                <fullName>I have a query about applying for Post Study Work/Graduate Route Visa</fullName>
            </value>
            <value>
                <fullName>I have a query about exemptions</fullName>
            </value>
            <value>
                <fullName>I have a query about inviting visitors to the UK</fullName>
            </value>
            <value>
                <fullName>I have a query about my attendance</fullName>
            </value>
            <value>
                <fullName>I have a query about my balance</fullName>
            </value>
            <value>
                <fullName>I have a query about my End Point Assessment</fullName>
            </value>
            <value>
                <fullName>I have a query about my submission</fullName>
            </value>
            <value>
                <fullName>I have a query about my timetable</fullName>
            </value>
            <value>
                <fullName>I have a question about my assessments feedback</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam arrangements</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam learning support</fullName>
            </value>
            <value>
                <fullName>I have a question about my graduation ceremony</fullName>
            </value>
            <value>
                <fullName>I have a question about my mock/assessment</fullName>
            </value>
            <value>
                <fullName>I have a question about my Oyster card</fullName>
            </value>
            <value>
                <fullName>I have a question about my results</fullName>
            </value>
            <value>
                <fullName>I have a question about my review/gate-way call</fullName>
            </value>
            <value>
                <fullName>I have a question about my student loan</fullName>
            </value>
            <value>
                <fullName>I have a question about my term dates</fullName>
            </value>
            <value>
                <fullName>I would like to request a Bank, Status or Council Tax letter</fullName>
            </value>
            <value>
                <fullName>I would like to request a holiday letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Type__c.field-meta.xml
<CustomField>
    <fullName>Query_Type__c</fullName>
    <label>Query Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assessments</fullName>
            </value>
            <value>
                <fullName>Attendance</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Changes to personal details</fullName>
            </value>
            <value>
                <fullName>Changes to studies</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Finance and Billing</fullName>
            </value>
            <value>
                <fullName>Graduation and Certificates</fullName>
            </value>
            <value>
                <fullName>IoS (Interruption of Studies)</fullName>
            </value>
            <value>
                <fullName>Letter requests</fullName>
            </value>
            <value>
                <fullName>My Apprenticeship</fullName>
            </value>
            <value>
                <fullName>My Course</fullName>
            </value>
            <value>
                <fullName>My Online Learning and The HUB</fullName>
            </value>
            <value>
                <fullName>My Study Materials</fullName>
            </value>
            <value>
                <fullName>Online learning</fullName>
            </value>
            <value>
                <fullName>Registration and enrolment</fullName>
            </value>
            <value>
                <fullName>Review Meeting</fullName>
            </value>
            <value>
                <fullName>Student Finance</fullName>
            </value>
            <value>
                <fullName>Student Loans</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Undetermined Query</fullName>
            </value>
            <value>
                <fullName>Prior Learning/Exemptions information</fullName>
            </value>
            <value>
                <fullName>Additional Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Status_Letter_Sent__c.field-meta.xml
<CustomField>
    <fullName>Status_Letter_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status Letter Sent</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Student)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Thread_Id__c.field-meta.xml
<CustomField>
    <fullName>Thread_Id__c</fullName>
    <description>Case Thread Id to be used in Apex coding for status and bank letters</description>
    <formula>&quot;ref:_&quot; &amp; LEFT($Organization.Id,5) &amp; SUBSTITUTE(RIGHT( $Organization.Id ,10), &quot;0&quot;, &quot;&quot; )&amp; &quot;._&quot; &amp; LEFT(Id,5) &amp; SUBSTITUTE(Left(RIGHT(Id,10), 5), &quot;0&quot;, &quot;&quot;) &amp; RIGHT(Id,5) &amp; &quot;:ref&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Thread Id</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Curriculum_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>BNR_Curriculum_Status_Code__c</fullName>
    <label>Curriculum Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligible_for_Automated_Holiday_Letter__c.field-meta.xml
<CustomField>
    <fullName>Eligible_for_Automated_Holiday_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the &apos;Eligible for Automated Holiday Letter&apos; check box is ticked on the Opportunity Object and a student requests a Holiday Letter via the student query form, then the auto case flow should send the holiday letter automatically.</description>
    <label>Eligible for Automated Holiday Letter</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler extends TriggerHandler {
    private StreamingService stream;

    private List<Case> newCases;
    private List<Case> oldCases;

    private Map<Id, Case> newCasesMap;
    private Map<Id, Case> oldCasesMap;

    /**
     *  Constructor
     */
    public CaseTriggerHandler() {
        TriggerHandler.processOnce('CaseTriggerHandler');
        stream = new StreamingService();

        newCases = Trigger.new;
        oldCases = Trigger.old;

        newCasesMap = (Map<ID, Case>) Trigger.NewMap;
        oldCasesMap = (Map<ID, Case>) Trigger.OldMap;
    }

    public override void beforeInsert() {
    }

    public override void beforeUpdate() {
        CaseTriggerHandler.associateApprenticeOnboardingCaseToOpp(newCases, oldCasesMap);
    }

    public override void beforeDelete() {
    }

    public override void afterInsert() {
        if (!TriggerSettings__c.getInstance().CaseTrigger_SendStatusHolidayLetter__c) {
            CaseTriggerHandler.SendStatusHolidayLetter(newCases);
        }
        stream.process(newCases, new Map<Id, SObject>());
    }

    public override void afterUpdate() {
        stream.process(newCases, oldCasesMap);
    }

    public override void afterDelete() {
    }

    public override void afterUndelete() {
    }

    public static void SendStatusHolidayLetter(List<Case> newCaseList) {
        if (newCaseList.size() == 1) {
            Case currentCase = newCaseList[0];

            List<String> validSubtypes = new List<String>{
                'I would like to request a Bank, Status or Council Tax letter',
                'I would like to request a holiday letter',
                'Holiday'
            };

            List<String> validStatusCodes = new List<String>{
                'REGISTERED',
                'NOT_PROGRESSING',
                'ON PLACEMENT',
                'RESIT ONLY',
                'TEMP_REGISTERED'
            };
            if (
                currentCase.RecordTypeId ==
                Schema.SObjectType.Case.getRecordTypeInfosByName().get('Student Query').getRecordTypeId()
            ) {
                if (
                    (!currentCase.Status_Letter_Sent__c) &&
                    validSubtypes.contains(currentCase.Query_Subtype__c) &&
                    currentCase.Status == 'New' &&
                    currentCase.ContactId != null &&
                    currentCase.Contact_Email__c != null &&
                    currentCase.Query_Type__c == 'Letter requests'
                ) {
                    String recipientEmail;
                    if (currentCase.SuppliedEmail != null) {
                        recipientEmail = currentCase.SuppliedEmail;
                    } else if (currentCase.Contact_Email__c != null) {
                        recipientEmail = currentCase.Contact_Email__c;
                    }
                    String subQueryValue = currentCase.Query_Subtype__c;

                    List<Account> accountList = [
                        SELECT Id, FirstName, Name, BNR_Banner_ID__pc, PersonBirthdate
                        FROM Account
                        WHERE PersonContactId = :currentCase.ContactId
                    ];
                    if (accountList.size() > 0 && accountList[0].BNR_Banner_ID__pc != null) {
                        Account account = accountList[0];
                        List<Opportunity> opportunityList = new List<Opportunity>();
                        for (Opportunity opp : [
                            SELECT
                                Id,
                                Name,
                                BNR_Curriculum_Status_Code__c,
                                Course_Instance__c,
                                Course_Instance__r.Name,
                                Course_Instance__r.End_Date__c,
                                Course_Instance__r.Start_Date__c,
                                Eligible_for_Automated_Holiday_Letter__c
                            FROM Opportunity
                            WHERE AccountId = :account.Id
                            ORDER BY Course_Instance__r.End_Date__c DESC NULLS LAST
                        ]) {
                            if (
                                validStatusCodes.contains(opp.BNR_Curriculum_Status_Code__c) &&
                                opp.Course_Instance__c != null &&
                                (subQueryValue == validSubtypes[0] || opp.Eligible_for_Automated_Holiday_Letter__c)
                            ) {
                                opportunityList.add(opp);
                            }
                        }

                        if (opportunityList.size() > 0) {
                            List<Address__c> addressList = [
                                SELECT
                                    Id,
                                    Type__c,
                                    Street_1__c,
                                    Street_2__c,
                                    Street_3__c,
                                    Street_4__c,
                                    Zip_Postal_Code__c
                                FROM Address__c
                                WHERE Student__c = :account.Id AND Active__c = TRUE
                            ];
                            String mailingAddressId, homeAddressId;
                            for (Address__c address : addressList) {
                                if (address.Type__c == 'Mailing') {
                                    mailingAddressId = address.Id;
                                }
                                if (address.Type__c == 'Home') {
                                    homeAddressId = address.Id;
                                }
                            }
                            if (recipientEmail != null && mailingAddressId != null) {
                                sendPDfEmail.sendPDf(
                                    currentCase.CaseNumber,
                                    currentCase.Thread_Id__c,
                                    currentCase.Id,
                                    recipientEmail,
                                    account.FirstName,
                                    opportunityList[0].Id,
                                    mailingAddressId,
                                    homeAddressId,
                                    subQueryValue
                                );
                            }
                        }
                    }
                }
            }
        }
    }

    public static void associateApprenticeOnboardingCaseToOpp(List<Case> cases, Map<Id, Case> oldCases) {
        Id apprenticeOnboarding = Schema.Sobjecttype.Case.getRecordTypeInfosByName()
            .get('Apprentice Onboarding')
            .getRecordTypeId();

        Map<Case, Id> caseToStudentIds = new Map<Case, Id>();

        for (Case currentCase : cases) {
            if (
                currentCase.RecordTypeId == apprenticeOnboarding &&
                currentCase.AccountId != null &&
                oldCases.get(currentCase.Id).AccountId != currentCase.AccountId
            ) {
                caseToStudentIds.put(currentCase, currentCase.AccountId);
            }
        }

        if (caseToStudentIds.isEmpty()) {
            return;
        }

        List<AggregateResult> agregateOpportunities = [
            SELECT AccountId, Max(Id) OpportunityId
            FROM Opportunity
            WHERE Recordtype.Name = 'Apprentice Application' AND AccountId IN :caseToStudentIds.values()
            GROUP BY AccountId
            HAVING COUNT(AccountId) = 1
        ];

        Map<Id, Id> accountIdToOppId = new Map<Id, Id>();
        for (AggregateResult currentAgreGateOpp : agregateOpportunities) {
            Id opportunityId = (Id) currentAgreGateOpp.get('OpportunityId');
            Id accountId = (Id) currentAgreGateOpp.get('AccountId');

            accountIdToOppId.put(accountId, opportunityId);
        }

        for (Case currentCase : caseToStudentIds.keySet()) {
            if (!accountIdToOppId.containsKey(currentCase.AccountId)) {
                continue;
            }

            currentCase.Opportunity__c = accountIdToOppId.get(currentCase.AccountId);
        }
    }
}