salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/Institute_Body__c.object-meta.xml
<CustomObject>
    <description>Institute Bodies that a student is a member of</description>
    <label>Institute Body</label>
    <nameField>
        <displayFormat>IB{00000000}</displayFormat>
        <label>Institute Body ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institute Bodies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Body__c.field-meta.xml
<CustomField>
    <fullName>Institute_Body__c</fullName>
    <description>Institute Body</description>
    <label>Institute Body</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>Apprenticeships</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CBI</fullName>
            </value>
            <value>
                <fullName>CFA</fullName>
            </value>
            <value>
                <fullName>CII</fullName>
            </value>
            <value>
                <fullName>CIMA</fullName>
            </value>
            <value>
                <fullName>CIPD</fullName>
            </value>
            <value>
                <fullName>CISI</fullName>
            </value>
            <value>
                <fullName>CMI</fullName>
            </value>
            <value>
                <fullName>CTA</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>IAD</fullName>
            </value>
            <value>
                <fullName>ICAEW</fullName>
            </value>
            <value>
                <fullName>ICAS</fullName>
            </value>
            <value>
                <fullName>ICSA</fullName>
            </value>
            <value>
                <fullName>IMC</fullName>
            </value>
            <value>
                <fullName>Insolvency</fullName>
            </value>
            <value>
                <fullName>IOC</fullName>
            </value>
            <value>
                <fullName>ITP</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>PMI</fullName>
            </value>
            <value>
                <fullName>Association of Accounting Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Accounting Technicians</label>
            </value>
            <value>
                <fullName>Association of Chartered Certified Accountants</fullName>
                <isActive>false</isActive>
                <label>Association of Chartered Certified Accountants</label>
            </value>
            <value>
                <fullName>Association of Tax Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Tax Technicians</label>
            </value>
            <value>
                <fullName>CII Diploma in Regulated Financial Planning</fullName>
                <isActive>false</isActive>
                <label>CII Diploma in Regulated Financial Planning</label>
            </value>
            <value>
                <fullName>CISI Apprenticeship Programmes</fullName>
                <isActive>false</isActive>
                <label>CISI Apprenticeship Programmes</label>
            </value>
            <value>
                <fullName>CISI Capital Markets</fullName>
                <isActive>false</isActive>
                <label>CISI Capital Markets</label>
            </value>
            <value>
                <fullName>CISI Cert in Private Client Investment Advice&amp;Mgmt</fullName>
                <isActive>false</isActive>
                <label>CISI Cert in Private Client Investment Advice&amp;Mgmt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Number__c.field-meta.xml
<CustomField>
    <fullName>Institute_Number__c</fullName>
    <description>Student&apos;s membership number of the institute body</description>
    <label>Institute Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Student account that is a member of the professional body institution</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Must be a student account</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institute Bodies</relationshipLabel>
    <relationshipName>Institute_Bodies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/StudentSyncTest.cls
@isTest
private class StudentSyncTest {
    @TestSetup
    private static void setup() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get('Student Account')
            .getRecordTypeId();

        Account account = new Account(
            RecordTypeId = recordTypeId,
            FirstName = 'Test',
            LastName = 'Tester',
            Salutation = 'Mr',
            Personal_Email__pc = 'test@bpp.com',
            Preferred_Email__pc = 'Personal',
            BNR_Banner_ID__pc = 'test-1'
        );

        insert account;

        insert new Hub_Account__c(
            Student__c = account.Id,
            Auth0_Id__c = 'sub|12345',
            Hub_Username__c = 'testuser@bpp.com'
        );

        // Add an address which relates to the student
        insert new List<Address__c>{
            new Address__c(
                Student__c = account.Id,
                Street_1__c = '5 fake drive',
                City__c = 'England',
                Zip_Postal_Code__c = '123',
                Type__c = 'Mailing'
            ),
            new Address__c(
                Student__c = account.Id,
                Street_1__c = '2 pretend house',
                City__c = 'Phoneyton',
                Zip_Postal_Code__c = 'L1E',
                Type__c = 'Home'
            )
        };
        // Add an Institute body which relates to the student
        insert new Institute_Body__c(Institute_Body__c = 'AAT', Institute_Number__c = '1', Student__c = account.Id);
    }

    @isTest
    private static void itShouldSerializeFromAnAccount() {
        // GIVEN we have an account
        Account account = [
            SELECT Id
            FROM Account
            WHERE LastName = 'Tester'
        ];

        // WHEN passed to the StudentSync class
        StudentSync sync = new StudentSync();
        sync.addRecord(account);

        List<Map<String, Object>> output = sync.serialize();
        Map<String, Object> detail = (Map<String, Object>) output.get(0);
        String SRN = (String) detail.get('studentReferenceNumber');
        Map<String, Object> personalInfo = (Map<String, Object>) detail.get('personalInfo');
        List<String> authIds = (List<String>) detail.get('userIds');
        List<Object> addresses = (List<Object>) detail.get('addresses');
        List<Object> instituteBodies = (List<Object>) detail.get('professionalQualifications');

        // THEN I expect it to serialize it correctly
        Assert.areEqual('test@bpp.com', personalInfo.get('emailAddress'), 'I expect the correct email address');
        Assert.areEqual('test-1', SRN);
        Assert.areEqual(1, output.size(), 'I expect one payload');
        Assert.areEqual(1, authIds.size(), 'I expect one hub id');
        Assert.areEqual(2, addresses.size(), 'I expect two Addresses');
        Assert.areEqual(1, instituteBodies.size(), 'I expect one Institute Body');
    }

    @isTest
    private static void itShouldSerializeFromAnAddress() {
        // GIVEN we have an address
        Address__c address = [SELECT Student__c FROM Address__c WHERE Type__c = 'Mailing' LIMIT 1];

        // WHEN passed to the StudentSync class
        StudentSync sync = new StudentSync();
        sync.addRecord(address);

        List<Map<String, Object>> output = sync.serialize();
        Map<String, Object> detail = (Map<String, Object>) output.get(0);
        List<String> authIds = (List<String>) detail.get('userIds');
        List<Object> addresses = (List<Object>) detail.get('addresses');
        List<Object> instituteBodies = (List<Object>) detail.get('professionalQualifications');

        // THEN I expect it to fetch the required objects and serialize it correctly
        Assert.areEqual(1, output.size(), 'I expect one payload');
        Assert.areEqual(1, authIds.size(), 'I expect one hub id');
        Assert.areEqual(2, addresses.size(), 'I expect two Addresses');
        Assert.areEqual(1, instituteBodies.size(), 'I expect one Institute Body');

        //AND If the Address Type is'Mailing', it should be serialized as 'Delivery'
        Map<String, Object> serializedAddress = (Map<String, Object>) addresses.get(0);
        Assert.areEqual('Delivery', serializedAddress.get('type'));
    }

    @isTest
    private static void itShouldSerializeExcludingAccountsWithNoHubAccount() {
        // GIVEN we have an account
        Account account = [
            SELECT Id
            FROM Account
            WHERE LastName = 'Tester'
        ];

        // AND there are no Hub Accounts
        delete [SELECT Id FROM Hub_Account__c];

        // WHEN passed to the StudentSync class
        StudentSync sync = new StudentSync();
        sync.addRecord(account);

        List<Map<String, Object>> output = sync.serialize();

        // THEN I expect it to serialize it correctly
        Assert.isTrue(output.isEmpty(), 'I expect there to be no payloads');
    }

    @isTest
    private static void itShouldSerializeExcludingAddressesWithNoDeterminableType() {
        // GIVEN we have an account
        Account account = [
            SELECT Id
            FROM Account
            WHERE LastName = 'Tester'
        ];

        // AND one of the Accounts addresses has no determinable type and the other only has its checkbox set
        Process_Bypasses__c setting = new Process_Bypasses__c();
        setting.Bypass_All_Triggers__c = true;
        setting.SetupOwnerId = UserInfo.getUserId();
        insert setting;

        List<Address__c> addresses = [SELECT Id FROM Address__c];
        addresses[0].Type__c = 'Term Time';
        addresses[1].Type__c = '';
        update addresses;

        delete [SELECT Id FROM Process_Bypasses__c];

        // WHEN passed to the StudentSync class
        StudentSync sync = new StudentSync();
        sync.addRecord(account);

        List<Map<String, Object>> output = sync.serialize();
        Map<String, Object> detail = (Map<String, Object>) output.get(0);
        List<String> authIds = (List<String>) detail.get('userIds');
        List<Object> addressResults = (List<Object>) detail.get('addresses');
        List<Object> instituteBodies = (List<Object>) detail.get('professionalQualifications');
        // THEN I expect it to serialize it correctly
        Assert.areEqual(1, output.size(), 'I expect one payload');
        Assert.areEqual(1, authIds.size(), 'I expect one hub id');
        Assert.areEqual(1, instituteBodies.size(), 'I expect one Institute Body');
        Assert.areEqual(1, addressResults.size(), 'I expect one Address');

        Map<String, Object> serializedAddress = (Map<String, Object>) addressResults.get(0);
        Assert.areEqual('Term time', serializedAddress.get('type'));
    }
}