salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>HSBC</fullName>
            </value>
            <value>
                <fullName>Barclays</fullName>
            </value>
            <value>
                <fullName>TSB</fullName>
            </value>
            <value>
                <fullName>Halifax</fullName>
            </value>
            <value>
                <fullName>Lloyds Bank</fullName>
            </value>
            <value>
                <fullName>NatWest</fullName>
            </value>
            <value>
                <fullName>Santander</fullName>
            </value>
            <value>
                <fullName>Royal Bank of Scotland</fullName>
            </value>
            <value>
                <fullName>Metro Bank</fullName>
            </value>
            <value>
                <fullName>The Co-Operative Bank</fullName>
            </value>
            <value>
                <fullName>Yorkshire Bank</fullName>
            </value>
            <value>
                <fullName>Clydesdale Bank</fullName>
            </value>
            <value>
                <fullName>Nationwide</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Bank_Name_Text__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name_Text__c</fullName>
    <label>Bank Name Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>This field is used to store the location of the student</description>
    <label>Location</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Query_Subtype__c</fullName>
    <label>Query Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Query_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Authorised Leave</fullName>
            </value>
            <value>
                <fullName>How do I access my EBook?</fullName>
            </value>
            <value>
                <fullName>How do I access my results and feedback</fullName>
            </value>
            <value>
                <fullName>How do I collect my ID card?</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from accessing my e-materials</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from studying</fullName>
            </value>
            <value>
                <fullName>I am in financial difficulty, what are my options?</fullName>
            </value>
            <value>
                <fullName>I am on Interruption of Studies and wish to extend</fullName>
            </value>
            <value>
                <fullName>I am taking an interruption of studies, how does that affect my payment plan and fees?</fullName>
            </value>
            <value>
                <fullName>I can&apos;t access my forum</fullName>
            </value>
            <value>
                <fullName>I can’t see my course within my online learning platform</fullName>
            </value>
            <value>
                <fullName>I have a different problem with my online learning</fullName>
            </value>
            <value>
                <fullName>I have a query about applying for Post Study Work/Graduate Route Visa</fullName>
            </value>
            <value>
                <fullName>I have a query about exemptions</fullName>
            </value>
            <value>
                <fullName>I have a query about inviting visitors to the UK</fullName>
            </value>
            <value>
                <fullName>I have a query about my attendance</fullName>
            </value>
            <value>
                <fullName>I have a query about my balance</fullName>
            </value>
            <value>
                <fullName>I have a query about my End Point Assessment</fullName>
            </value>
            <value>
                <fullName>I have a query about my submission</fullName>
            </value>
            <value>
                <fullName>I have a query about my timetable</fullName>
            </value>
            <value>
                <fullName>I have a question about my assessments feedback</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam arrangements</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam learning support</fullName>
            </value>
            <value>
                <fullName>I have a question about my graduation ceremony</fullName>
            </value>
            <value>
                <fullName>I have a question about my mock/assessment</fullName>
            </value>
            <value>
                <fullName>I have a question about my Oyster card</fullName>
            </value>
            <value>
                <fullName>I have a question about my results</fullName>
            </value>
            <value>
                <fullName>I have a question about my review/gate-way call</fullName>
            </value>
            <value>
                <fullName>I have a question about my student loan</fullName>
            </value>
            <value>
                <fullName>I have a question about my term dates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Curriculum_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>BNR_Curriculum_Status_Code__c</fullName>
    <label>Curriculum Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Indicates the location that the student has applied to or expressed interest.</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>London - City</fullName>
            </value>
            <value>
                <fullName>London - Waterloo</fullName>
            </value>
            <value>
                <fullName>London - Holborn</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>Leeds</fullName>
            </value>
            <value>
                <fullName>Croydon</fullName>
            </value>
            <value>
                <fullName>Milton Keynes</fullName>
            </value>
            <value>
                <fullName>eLearning Center</fullName>
            </value>
            <value>
                <fullName>Cambridge</fullName>
            </value>
            <value>
                <fullName>Maidstone</fullName>
            </value>
            <value>
                <fullName>Glasgow</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Nottingham</fullName>
            </value>
            <value>
                <fullName>Cardiff</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Southampton</fullName>
            </value>
            <value>
                <fullName>Manchester</fullName>
            </value>
            <value>
                <fullName>Liverpool</fullName>
            </value>
            <value>
                <fullName>Swindon</fullName>
            </value>
            <value>
                <fullName>Abingdon - McTimoney</fullName>
            </value>
            <value>
                <fullName>London (City)</fullName>
            </value>
            <value>
                <fullName>London (Waterloo)</fullName>
            </value>
            <value>
                <fullName>London (Holborn)</fullName>
            </value>
            <value>
                <fullName>Abingdon (McTimoney)</fullName>
            </value>
            <value>
                <fullName>Doncaster-RDASH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <description>Mode that student has applied or expressed interest in studying.</description>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Full Time - Accelerated</fullName>
            </value>
            <value>
                <fullName>Full Time - Fast Track</fullName>
            </value>
            <value>
                <fullName>Part Time Day</fullName>
            </value>
            <value>
                <fullName>Part Time Weekend</fullName>
            </value>
            <value>
                <fullName>Part Time 1 Evening</fullName>
            </value>
            <value>
                <fullName>Part Time 2 Evening</fullName>
            </value>
            <value>
                <fullName>Part Time Saturday</fullName>
            </value>
            <value>
                <fullName>Part Time Distance Learning</fullName>
            </value>
            <value>
                <fullName>Full Time Distance Learning</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Full Time Accelerated</fullName>
            </value>
            <value>
                <fullName>On-Line</fullName>
            </value>
            <value>
                <fullName>Part Time 2 Evenings</fullName>
            </value>
            <value>
                <fullName>Short Course</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Programme_Application__c.field-meta.xml
<CustomField>
    <fullName>Programme_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Programme of interest or application.</description>
    <label>Programme</label>
    <referenceTo>Programme__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/classes/StatusLetterPDFCtrl.cls
public class StatusLetterPDFCtrl{

public Case caserecord{get;set;}
public Account acc{get;set;}
public Opportunity opptoshow{get;set;}
public List<Term_Date__c> termDatesOnProduct{get;set;}
public Address__c addr{get;set;}
public Address__c homeAddr{get;set;}
public integer currday{get;set;}
public string currmonth{get;set;}
public integer curryear{get;set;}
public integer nextyear{get;set;}    
public string dateofbirth{get;set;}
public string todayDateFormat{get;set;}    
public string letterValidUntil{get;set;}
public integer coursestartdate{get;set;}
public string coursestartmonth{get;set;}
public integer coursestartyear{get;set;}
public integer courseenddate{get;set;}
public string courseendmonth{get;set;}
public integer courseendyear{get;set;}
public string bankname{get;set;}
public string subvalue{get;set;}

public List<Case> caserecords = new list<Case>();

    public StatusLetterPDFCtrl(){
        Id caseId = apexpages.Currentpage().getparameters().get('Id');
        Id oppId = apexpages.Currentpage().getparameters().get('oppId');
        Id addId = apexpages.Currentpage().getparameters().get('addId');
        Id homeAddId = apexpages.Currentpage().getparameters().get('homeAddId');
        subvalue = apexpages.Currentpage().getparameters().get('subquery');
        system.debug('@@caseId@'+caseId);
        system.debug('@@oppId@'+oppId);
        system.debug('@@addId@'+addId);
        system.debug('@@homeAddId@'+homeAddId);
        system.debug('@@subvalue@'+subvalue);

        if(caseId!= null && oppId!=null && addId!=null)
        {
            caserecord = [Select id, Status, contactId, Query_Subtype__c, Bank_Name__c,Bank_Name_Text__c from Case where id=:caseId]; 
           // caserecords= withoutsharinghelper.getSObjects('select id,caseNumber from Case where PersonContactId =\'' + bAccId + '\' limit 1');
           
           if(caserecord.Query_Subtype__c == 'Bank')
           {
               if(caserecord.Bank_Name__c != 'other')
               {
                   bankname = caserecord.Bank_Name__c;
               }
               else if(caserecord.Bank_Name__c == 'other')
               {
                   bankname = caserecord.Bank_Name_Text__c;
               }
           }
            
            if(caserecord.contactId != null)
            {
                acc = [Select id, name, firstname, lastname, BNR_Banner_ID__pc,PersonBirthdate from Account where PersonContactId =:caserecord.contactId];
                if(acc.Id != null)
                {
                    dateofbirth = acc.PersonBirthdate.format();
                    currday = System.now().day();
                    curryear = System.now().year();
                    nextyear = System.now().addYears(1).year();
                    DateTime dt = DateTime.now();
                    currmonth= dt.format('MMMMM');
                    System.debug('Month Name : ' + currmonth);
                    Date todayDate = Date.today();
                    todayDateFormat = todayDate.format();
                    Date todayDate_plus_90days = todayDate.addDays(90);
                    letterValidUntil = todayDate_plus_90days.format();
                    system.debug('todayDateFormat: ' + todayDateFormat);
                    system.debug('letterValidUntil: ' + letterValidUntil);

                    opptoshow = [Select id,name,Location__c,Mode__c,Programme_Application__r.name,BNR_Curriculum_Status_Code__c,Course_Instance__c,Course_Instance__r.Name,Course_Instance__r.id,Course_Instance__r.End_Date__c,Course_Instance__r.Start_Date__c from Opportunity where Id =:oppId];
                    if(opptoshow!=null)
                    {
                        system.debug('@opp@'+opptoshow.Course_Instance__r.Start_Date__c);
                        system.debug('@opp@'+opptoshow.Course_Instance__r.Start_Date__c.format());
                        date coursedate = opptoshow.Course_Instance__r.Start_Date__c;
                        coursestartdate = coursedate.day();
                        coursestartyear = coursedate.year();
                       
                        DateTime dtConverted = Datetime.newInstance(coursedate.year(), coursedate.month(),coursedate.day(),0,0,0);
                        system.debug('@opp111@'+dtConverted.format('MMMM'));
                        coursestartmonth = dtConverted.format('MMMM');
                        
                        date coursedate2 = opptoshow.Course_Instance__r.End_Date__c;
                        courseenddate = coursedate2.day();
                        courseendyear = coursedate2.year();
                        
                        DateTime temp = Datetime.newInstance(coursedate2.year(), coursedate2.month(),coursedate2.day(),0,0,0);
                        courseendmonth = temp.format('MMMM');
                        if(opptoshow.Course_Instance__r.id != null){
                        	termDatesOnProduct = [SELECT id, Name, Start_Date__c, End_Date__c,product__c FROM Term_Date__c where product__c=:opptoshow.Course_Instance__r.id ORDER BY Start_Date__c ASC NULLS LAST];
                            System.debug('Term Dates on Product'+termDatesOnProduct);
                        }
                    }
                    addr = [Select id,Type__c,Street_1__c,Street_2__c,Street_3__c,Street_4__c,Zip_Postal_Code__c,Locality__r.name,State_Province__r.name,Lookup_Country__r.name,City__c from Address__c where Id =:addId and Type__c='Mailing' and Active__c = true];   
                    if (homeAddId!= null) {
                        homeAddr = [Select id,Type__c,Street_1__c,Street_2__c,Street_3__c,Street_4__c,Zip_Postal_Code__c,Locality__r.name,State_Province__r.name,Lookup_Country__r.name,City__c from Address__c where Id =:homeAddId and Type__c='Home' and Active__c = true];
                        System.debug('Home Address'+homeAddr);
                    }
                }
                
            }

        }
    }
}