salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Used for SIS Integrations.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appilcations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Review__c/Application_Review__c.object-meta.xml
<CustomObject>
    <description>This object tracks reviews against Applications(Opportunities) and provides an audit including comments and reviewing users.</description>
    <label>Application Review</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Application Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The Application (Opportunity) that this review is related to</description>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Reviews</relationshipLabel>
    <relationshipName>Application_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Feedback_Required__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Feedback Required</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/AuthorisedOn__c.field-meta.xml
<CustomField>
    <fullName>AuthorisedOn__c</fullName>
    <description>The datetime that the application was moved into Acceptance, used in applicationStageChange event</description>
    <label>AuthorisedOn</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Authoriser__c.field-meta.xml
<CustomField>
    <fullName>Authoriser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the user that approved the application, this is sent to Join in an applicationStageChanged event</description>
    <label>Authoriser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AuthorisedOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact that is used to identify the Line Manager for Application requests</description>
    <label>Line Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Line Manager can&apos;t be a Student Account</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Line Manager)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/OOTJTH_Calculated__c.field-meta.xml
<CustomField>
    <fullName>OOTJTH_Calculated__c</fullName>
    <description>The calculated total hours spent on training activities.</description>
    <formula>CEILING(
      0.2*(
        30
        * /* duration (weeks) */ (ROUND(ROUND((((Course_Instance__r.End_Date__c - EPA__c * 7)-Course_Instance__r.Start_Date__c)+1)/7,0),0)
        - /* Statutory leave duration (weeks) */(ROUND((ROUND((((Course_Instance__r.End_Date__c - EPA__c * 7)-Course_Instance__r.Start_Date__c)+1)/7,0)-(ROUND((((Course_Instance__r.End_Date__c - EPA__c * 7)-Course_Instance__r.Start_Date__c)+1)/7,0)/1.1207)),1)))
      )
    )</formula>
    <label>Overall Off The Job Training Hours Calc</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/OOTJTH_Preserved__c.field-meta.xml
<CustomField>
    <fullName>OOTJTH_Preserved__c</fullName>
    <description>Used for preserving the calculation and manual input</description>
    <label>Overall Off The Job Training Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/classes/ApplicationReviewController.cls
public without sharing class ApplicationReviewController {
    /**
     * Moves the opportunity into In Progress sub stage which allows
     * a review to take place
     * @param opportunityId The related opportunity
     */
    @AuraEnabled
    public static void startReview(String opportunityId) {
        try {
            update new Opportunity(
                Id = opportunityId,
                StageName = 'BPP Review',
                BPP_Sub_Status__c = 'In Progress',
                OwnerId = UserInfo.getUserId()
            );
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Moves an opportunity to In progress where it is in the Acceptance stage
     * @param opportunityId The related opportunity
     */
    @AuraEnabled
    public static void startFinalReview(String opportunityId) {
        try {
            Opportunity opp = [
                SELECT BPP_Sub_Status__c
                FROM Opportunity
                WHERE Id = :opportunityId
            ];
            opp.BPP_Sub_Status__c = 'In Progress';
            update opp;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Fetches the home address related to an Application
     * @param accountId The account related to the application
     * @return  The ID of the Home Address
     */
    @AuraEnabled(cacheable=true)
    public static Id getHomeAddress(String accountId) {
        try {
            Address__c address = [SELECT Id FROM Address__c WHERE Student__c = :accountId AND Type__c = 'Home'];

            return address.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Submits a review against the given application
     * @param opportunityId The related application
     * @param comment The feedback comment if present
     * @param feedbackRequired A boolean to determine
     */
    @AuraEnabled
    public static void submitReview(String opportunityId, String comment, Boolean feedbackRequired) {
        try {
            // Create feedback record
            Application_Review__c review = new Application_Review__c(
                Application__c = opportunityId,
                Feedback_Required__c = feedbackRequired,
                Comment__c = comment
            );

            insert review;

            // Update opportunity
            Opportunity opp = [
                SELECT Line_Manager__c, StageName, BPP_Sub_Status__c
                FROM Opportunity
                WHERE Id = :opportunityId
            ];

            if (opp.Line_Manager__c == null && !feedbackRequired) {
                throw new SObjectException('A Line manager is required before this application can be pre-approved.');
            }

            if (feedbackRequired) {
                opp.BPP_Sub_Status__c = 'Awaiting Information';
            } else {
                opp.StageName = 'Line Manager Review';
                opp.BPP_Sub_Status__c = 'In Progress';
            }

            update opp;
        } catch (DmlException e) {
            throw new AuraHandledException(e.getDmlMessage(0));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Updates the given Opportunities Start and End Date to the given values and sets the OOTJTH Preserved field if applicable
     * to null allowing it to be re-calculated if applicable
     * @param opportunityId The related application
     */
    @AuraEnabled
    public static void updateOpportunityProductDates(String opportunityId) {
        try {
            Opportunity oppToUpdate = [
                SELECT
                    Id,
                    StageName,
                    OOTJTH_Calculated__c,
                    Course_Instance__r.Start_Date__c,
                    Course_Instance__r.End_Date__c
                FROM Opportunity
                WHERE Id = :opportunityId
            ];

            oppToUpdate.Start_Date__c = oppToUpdate.Course_Instance__r.Start_Date__c;
            oppToUpdate.End_Date__c = oppToUpdate.Course_Instance__r.End_Date__c;

            if (oppToUpdate.StageName == 'BPP Review' || oppToUpdate.StageName == 'Acceptance') {
                oppToUpdate.OOTJTH_Preserved__c = oppToUpdate.OOTJTH_Calculated__c;
            }

            update oppToUpdate;
        } catch (DmlException e) {
            throw new AuraHandledException(e.getDmlMessage(0));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Submits the final review
     * @param opportunityId The opportunity id
     * @param comment the comment associated with the final review
     */
    @AuraEnabled
    public static void submitFinalReview(String opportunityId, String comment, Boolean awaitingInformation) {
        try {
            if (!String.isEmpty(comment)) {
                Application_Review__c review = new Application_Review__c(
                    Application__c = opportunityId,
                    Feedback_Required__c = false,
                    Comment__c = comment
                );

                insert review;
            }

            Opportunity opp = [
                SELECT BPP_Sub_Status__c, Authoriser__c, AuthorisedOn__c
                FROM Opportunity
                WHERE Id = :opportunityId
            ];

            if (awaitingInformation) {
                opp.BPP_Sub_Status__c = 'On Hold';
            } else {
                opp.BPP_Sub_Status__c = 'Completed';
                opp.Authoriser__c = UserInfo.getUserId();
                opp.AuthorisedOn__c = DateTime.now();
            }

            update opp;
        } catch (DmlException e) {
            throw new AuraHandledException(e.getDmlMessage(0));
        } catch (Exception e) {
            throw new AuraHandledException(
                'Unable to submit final review, please try again or contact an administrator if this persists'
            );
        }
    }

    @AuraEnabled
    public static String autoPopulateReview() {
        try {
            return [SELECT Id, Body FROM StaticResource WHERE Name = 'BPP_Review_Feedback'].Body.toString();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}