salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Permanent_Home__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Home__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This denotes if the address is the student&apos;s designated permanent home address</description>
    <label>Permanent Home?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary_Billing__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Billing?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Delivery?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Term_Time__c.field-meta.xml
<CustomField>
    <fullName>Term_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This denotes if the address is the students designated term time address</description>
    <label>Term Time?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/AddressAlignBatch.cls
public class AddressAlignBatch implements Database.Batchable<SObject> {
    /**
     * Queries all Accounts which have Addresses
     * @param bc BatchableContext
     * @return  Database QueryLocator
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id
                FROM Account
                WHERE
                    Id IN (
                        SELECT Student__c
                        FROM Address__c
                        WHERE
                            Active__c = TRUE
                            AND ((Permanent_Home__c = TRUE
                            AND Type__c != 'Home')
                            OR (Type__c = 'Home'
                            AND Permanent_Home__c = FALSE)
                            OR (Primary_Billing__c = TRUE
                            AND Type__c != 'Billing')
                            OR (Type__c = 'Billing'
                            AND Primary_Billing__c = FALSE)
                            OR (Primary_Delivery__c = TRUE
                            AND Type__c != 'Mailing')
                            OR (Type__c = 'Mailing'
                            AND Primary_Delivery__c = FALSE)
                            OR (Term_Time__c = TRUE
                            AND Type__c != 'Term Time')
                            OR (Type__c = 'Term Time'
                            AND Term_Time__c = FALSE))
                    )
            ]
        );
    }

    /**
     * Creates one address record per type. Updates type checkboxes
     * @param bc Batchable Context
     * @param accounts List of Accounts to query Addresses from
     */
    public void execute(Database.BatchableContext bc, List<Account> accounts) {
        List<Id> accountIds = new List<Id>();
        for (Account account : accounts) {
            accountIds.add(account.Id);
        }

        TriggerHandler.bypassAllTriggers = true;
        upsert AddressAlign.queryAndAlignAddresses(accountIds);
    }

    public void finish(Database.BatchableContext bc) {
    }
}