salesforce-main/src/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>Date student applied for this particular application.  Automatically populated through Salesforce via workflow rule.  Should not be populated through external systems.</description>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Bypass_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass_Validation_Rule</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact that is used to identify the Line Manager for Application requests</description>
    <label>Line Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Line Manager can&apos;t be a Student Account</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Line Manager)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventStageProcessorTest.cls
@isTest
public class EventStageProcessorTest {
    private static String applicationId1 = 'test-4321';
    private static String applicationId2 = 'test-1234';
    private static Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Student_Account')
        .getRecordTypeId();

    private static Map<String, Id> opportunityRecordTypeIds = new Map<String, Id>{
        'Apprentice_Application' => getOpportunityRecordTypeId('Apprentice_Application'),
        'Student_Interest' => getOpportunityRecordTypeId('Student_Interest'),
        'Student_Application' => getOpportunityRecordTypeId('Student_Application')
    };

    private static Id getOpportunityRecordTypeId(String recordType) {
        return Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId();
    }

    @TestSetup
    private static void setup() {
        Account acc = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);
        insert acc;

        Contact contact = new Contact(FirstName = 'Test', LastName = 'Tester', Email = 'test@bpp.com');
        insert contact;

        Opportunity opp1 = createOpportunity('Apprentice_Application', applicationId2, 'Application', acc, contact);
        insert opp1;

        Opportunity opp2 = createOpportunity('Apprentice_Application', applicationId1, 'Application', acc, contact);
        insert opp2;

        opp2.Bypass_Validation_Rule__c = true;
        opp2.StageName = 'Line Manager Review';
        update opp2;

        Opportunity opp3 = createOpportunity('Student_Interest', 'test-12345', 'Application Started', acc, contact);
        insert opp3;
    }

    private static Opportunity createOpportunity(
        String recordType,
        String applicationId,
        String stageName,
        Account acc,
        Contact contact
    ) {
        return new Opportunity(
            RecordTypeId = opportunityRecordTypeIds.get(recordType),
            name = 'Test',
            Application_Id__c = applicationId,
            accountid = acc.Id,
            Line_Manager__c = contact.Id,
            StageName = stageName,
            CloseDate = Date.today()
        );
    }

    @isTest
    private static void itShouldUpdateTheOppWithNewStageAndSubStage() {
        //Given a queue job that provides the stage "BPP_REVIEW"
        ApplicationStageSchema schema = new ApplicationStageSchema(applicationId2, 'BPP_REVIEW', 'Not Started');

        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Content__c = JSON.serialize(schema),
            Event_Time__c = DateTime.now()
        );

        //WHEN the event processor is run
        System.Test.startTest();

        EventStageProcessor processor = new EventStageProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN the queue job is successful
        Assert.areEqual(1, processor.successfulJobs.size(), 'Expected one successful job');
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        Opportunity oppAfter = [
            SELECT StageName, BPP_Sub_Status__c, Application_Date__c
            FROM Opportunity
            WHERE Application_Id__c = :applicationId2
        ];

        //AND the field values have been updated
        Assert.areEqual(oppAfter.StageName, 'BPP Review');
        Assert.areEqual(oppAfter.BPP_Sub_Status__c, 'Not Started');
        Assert.areEqual(oppAfter.Application_Date__c, Date.today());
    }

    @isTest
    private static void itShouldUpdateTheOppWithNewRecordTypeAndStageName() {
        //Given a queue job that provides the stage "BPP_REVIEW"
        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Content__c = JSON.serialize(new ApplicationStageSchema('test-12345', 'BPP_REVIEW', 'IN_PROGRESS')),
            Event_Time__c = DateTime.now()
        );
        // WHEN the event is processed
        System.Test.startTest();
        new EventStageProcessor().processImpl(new List<Queue_Job__c>{ queueJob });
        System.Test.stopTest();

        Opportunity oppAfter = [
            SELECT StageName, Application_Date__c, RecordTypeId
            FROM Opportunity
            WHERE Application_Id__c = 'test-12345'
        ];

        //THEN the field values have been updated
        Assert.areEqual(oppAfter.StageName, 'Application');
        Assert.areEqual(oppAfter.RecordTypeId, opportunityRecordTypeIds.get('Student_Application'));
        Assert.areEqual(oppAfter.Application_Date__c, Date.today());
    }

    @isTest
    private static void itShouldFailQueueJobWhenStageNameIsNotApplication() {
        // GIVEN we have an event for an application that is already in BPP REVIEW
        ApplicationStageSchema schema = new ApplicationStageSchema(applicationId1, 'BPP_REVIEW', 'Not Started');

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(schema));

        // WHEN the processor runs
        System.Test.startTest();

        EventStageProcessor processor = new EventStageProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN I expect it to fail the queue job
        Assert.areEqual(1, processor.failedJobs.size(), 'Expect 1 failed job');
    }

    @isTest
    private static void itShouldCaterForReSubmissions() {
        // GIVEN we have an opportunity
        Opportunity opp = [
            SELECT Bypass_Validation_Rule__c, StageName, BPP_Sub_Status__c
            FROM Opportunity
            WHERE Application_Id__c = :applicationId2
        ];
        // AND the opportunity is awaiting feedback
        opp.Bypass_Validation_Rule__c = true;
        opp.StageName = 'BPP Review';
        opp.BPP_Sub_Status__c = 'Awaiting Information';

        update opp;

        // WHEN the event is processed
        ApplicationStageSchema schema = new ApplicationStageSchema(applicationId2, 'BPP_REVIEW', 'IN PROGRESS');

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(schema));

        System.Test.startTest();

        EventStageProcessor processor = new EventStageProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN I expect it to go back to Not Started
        Opportunity oppAfter = [
            SELECT BPP_Sub_Status__c
            FROM Opportunity
            WHERE Application_Id__c = :applicationId2
        ];

        Assert.areEqual(oppAfter.BPP_Sub_Status__c, 'Not Started');
    }

    @isTest
    private static void itShouldMoveIntoAwaitingSignOff() {
        // GIVEN we have an event for an opportunity at line manager review stage
        ApplicationStageSchema schema = new ApplicationStageSchema(
            applicationId1,
            'LINE_MANAGER_REVIEW',
            'AWAITING_APPLICANT_SIGNOFF'
        );

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(schema));

        // WHEN the event is processed
        System.Test.startTest();

        EventStageProcessor processor = new EventStageProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN I expect it to move into awaiting sign off
        Opportunity oppAfter = [
            SELECT StageName, BPP_Sub_Status__c
            FROM Opportunity
            WHERE Application_Id__c = :applicationId1
        ];

        Assert.areEqual('Line Manager Review', oppAfter.StageName);
        Assert.areEqual('Awaiting Applicant Signoff', oppAfter.BPP_Sub_Status__c);
    }

    @isTest
    private static void itShouldMoveIntoAcceptance() {
        // GIVEN we have an event for an opportunity at acceptance stage
        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Content__c = JSON.serialize(new ApplicationStageSchema(applicationId1, 'ACCEPTANCE', 'NEW'))
        );

        // WHEN the event is processed
        System.Test.startTest();

        new EventStageProcessor().processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN I expect it to move into Acceptance with status of new
        Opportunity opp = [
            SELECT StageName, BPP_Sub_Status__c
            FROM Opportunity
            WHERE Application_Id__c = :applicationId1
        ];

        Assert.areEqual('Acceptance', opp.StageName);
        Assert.areEqual('New', opp.BPP_Sub_Status__c);
    }
}