salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cancellation_Reason__c</fullName>
    <description>Cancellation Reason field to be mandatory if Status is set to Cancelled or Declined on Student Application Opportunity</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unable to fund the programme</fullName>
            </value>
            <value>
                <fullName>Change of profession</fullName>
            </value>
            <value>
                <fullName>Taken up a job</fullName>
            </value>
            <value>
                <fullName>Gone to a competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Failed previous qualification</fullName>
            </value>
            <value>
                <fullName>Location/Mode not available</fullName>
            </value>
            <value>
                <fullName>Family Emergency</fullName>
            </value>
            <value>
                <fullName>VISA/CAS/EU Delay</fullName>
            </value>
            <value>
                <fullName>Prefer not to say</fullName>
            </value>
            <value>
                <fullName>VISA Refusal</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>CAS requirement not met</fullName>
            </value>
            <value>
                <fullName>Academic/English entry not met</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Chosen to study at another BPP location</fullName>
            </value>
            <value>
                <fullName>Chosen to study another BPP programme</fullName>
            </value>
            <value>
                <fullName>appMissedDeadline</fullName>
                <label>Failed to submit application before deadline</label>
            </value>
            <value>
                <fullName>appWithdrawApplicant</fullName>
                <label>Learner withdrawn</label>
            </value>
            <value>
                <fullName>appNoResponseApplicant</fullName>
                <label>No response from applicant</label>
            </value>
            <value>
                <fullName>appNoResponseEmployer</fullName>
                <label>No response from employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedEmployer</fullName>
                <label>Cancelled due to change of employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedProgramme</fullName>
                <label>Change of programme</label>
            </value>
            <value>
                <fullName>appRejectIneligibleResidency</fullName>
                <label>Ineligible status (Residency)</label>
            </value>
            <value>
                <fullName>appRejectIneligibleVisa</fullName>
                <label>Ineligible status (VISA)</label>
            </value>
            <value>
                <fullName>appRejectRoleOnboarding</fullName>
                <label>Job role does not match criteria (Onboarding)</label>
            </value>
            <value>
                <fullName>appRejectRoleHop</fullName>
                <label>Job role does not match criteria (Hop)</label>
            </value>
            <value>
                <fullName>appRejectOverqualified</fullName>
                <label>Applicant is not suitable for selected programme</label>
            </value>
            <value>
                <fullName>appRejectFundingIssue</fullName>
                <label>Application has a funding issue</label>
            </value>
            <value>
                <fullName>appNotEligible</fullName>
                <label>Not Eligible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Not eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_JSON__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_JSON__c</fullName>
    <description>Stores the entire Eligibility payload provided in the inbound event for use in rendering the eligibilityData LWC.</description>
    <label>Eligibility JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <description>The current eligibility status of the application</description>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT_CHECKED</fullName>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>ELIGIBLE</fullName>
                <label>Eligible</label>
            </value>
            <value>
                <fullName>NOT_ELIGIBLE</fullName>
                <label>Not Eligible</label>
            </value>
            <value>
                <fullName>Eligibility Incomplete</fullName>
                <default>true</default>
                <label>Eligibility Incomplete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_Text__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Text__c</fullName>
    <description>Stores the Eligibility in a readable way to be displayed in printable view</description>
    <label>Eligibility</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventEligibilityProcessorTest.cls
@isTest
public class EventEligibilityProcessorTest {
    static Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Student_Account')
        .getRecordTypeId();

    static Id opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
        .get('Apprentice Application')
        .getRecordTypeId();

    static String TEST_APPLICATION_ID = 'cd6a04b6-9990-4e30-8421-5ed7819c13c9';

    @TestSetup
    static void setup() {
        Account account = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);
        insert account;

        insert new Opportunity(
            name = 'Test',
            Application_Id__c = TEST_APPLICATION_ID,
            accountid = account.Id,
            StageName = 'Application',
            CloseDate = Date.today(),
            RecordTypeId = opportunityRecordTypeId
        );
    }

    @isTest
    static void itShouldUpdateEligibilityFields() {
        // GIVEN an Opportunity (Setup)

        // AND a queue job
        EligibilitySchema eventSchema = createTestSchema();

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the event processor is run
        Test.startTest();
        EventEligibilityProcessor processor = new EventEligibilityProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN the queue job is successful
        Assert.areEqual(1, processor.successfulJobs.size(), 'Expected one successful job');
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        // AND the eligability fields should be updated
        List<Opportunity> opps = [
            SELECT Id, Application_Id__c, Eligibility_Status__c, Eligibility_JSON__c, Eligibility_Text__c
            FROM Opportunity
        ];
        Assert.areEqual(1, opps.size());
        Opportunity oppAfter = opps[0];

        EligibilitySchema deserializedEligibility = (EligibilitySchema) JSON.deserialize(
            oppAfter.Eligibility_JSON__c,
            EligibilitySchema.class
        );
        Assert.areEqual(eventSchema.applicationId, oppAfter.Application_Id__c);
        Assert.areEqual(eventSchema.eligibility.templateCode, deserializedEligibility.eligibility.templateCode);
        Assert.areEqual(eventSchema.eligibility.submittedOn, deserializedEligibility.eligibility.submittedOn);
        Assert.areEqual(eventSchema.eligibility.isEligible, oppAfter.Eligibility_Status__c);
        Assert.isTrue(
            oppAfter.Eligibility_Text__c.contains(
                'Eligibility Status: ELIGIBLE | Date Submitted: 08/08/2023 | Template: August2023'
            )
        );
        Assert.areEqual(eventSchema.eligibility.summaryText, deserializedEligibility.eligibility.summaryText);
    }

    @isTest
    static void itShouldCloseIllegibleOpportunities() {
        // GIVEN an Opportunity (Setup)

        // AND a queue job with a illegible status
        EligibilitySchema eventSchema = createTestSchema();
        eventSchema.eligibility.isEligible = 'NOT_ELIGIBLE';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the event processor is run
        Test.startTest();
        EventEligibilityProcessor processor = new EventEligibilityProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN the queue job is successful
        Assert.areEqual(1, processor.successfulJobs.size(), 'Expected one successful job');
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        // AND the eligibility fields should be updated
        List<Opportunity> opps = [
            SELECT
                Id,
                Application_Id__c,
                Eligibility_Status__c,
                Eligibility_JSON__c,
                StageName,
                BPP_Cancellation_Reason__c,
                BPP_Sub_Status__c
            FROM Opportunity
        ];
        Assert.areEqual(1, opps.size());
        Opportunity oppAfter = opps[0];

        EligibilitySchema deserializedEligibility = (EligibilitySchema) JSON.deserialize(
            oppAfter.Eligibility_JSON__c,
            EligibilitySchema.class
        );
        Assert.areEqual(eventSchema.applicationId, oppAfter.Application_Id__c);
        Assert.areEqual(eventSchema.eligibility.templateCode, deserializedEligibility.eligibility.templateCode);
        Assert.areEqual(eventSchema.eligibility.submittedOn, deserializedEligibility.eligibility.submittedOn);
        Assert.areEqual(eventSchema.eligibility.isEligible, oppAfter.Eligibility_Status__c);

        // AND the Opportunity should have been closed
        Assert.areEqual('Closed Lost', oppAfter.StageName);
        Assert.areEqual('Not eligible', oppAfter.BPP_Sub_Status__c);
        Assert.areEqual('appNotEligible', oppAfter.BPP_Cancellation_Reason__c);
    }

    @isTest
    static void itShouldFailIfNoOppFound() {
        // GIVEN a queue job with an event that does not have a matching Opportunity
        EligibilitySchema eventSchema = createTestSchema();
        eventSchema.applicationId = 'InvalidApplicationId';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the event processor is run
        Test.startTest();
        EventEligibilityProcessor processor = new EventEligibilityProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN the queue job is successful
        Assert.areEqual(0, processor.successfulJobs.size(), 'Expected one successful job');
        Assert.areEqual(1, processor.failedJobs.size(), 'Expected no failed jobs');

        // AND no opp has been created
        List<Opportunity> opps = [
            SELECT Id, Application_Id__c, Eligibility_Status__c, Eligibility_JSON__c
            FROM Opportunity
            WHERE Application_Id__c = :eventSchema.applicationId
        ];
        Assert.areEqual(0, opps.size());
    }

    @isTest
    static void itShouldHandleMissingEventData() {
        // GIVEN a queue job with no event data
        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = '{}');

        // WHEN the event processor is run
        Test.startTest();
        EventEligibilityProcessor processor = new EventEligibilityProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN the queue job has failed
        Assert.areEqual(0, processor.successfulJobs.size(), 'Expected no successful jobs');
        Assert.areEqual(1, processor.failedJobs.size(), 'Expected one failed job');
        Assert.areEqual(
            'Required value null in event payload',
            processor.failedJobs.values()[0],
            'Expected one failed job'
        );
    }

    @isTest
    static void itShouldHandleMultipleJobsForOneOpportunity() {
        // GIVEN an Opportunity (Setup)

        // AND two queue jobs to update the same Opportunity with the second job being newer
        // Job One
        EligibilitySchema eventSchemaOne = createTestSchema();
        eventSchemaOne.eligibility.isEligible = 'ELIGIBLE';

        Queue_Job__c queueJobOne = new Queue_Job__c(
            Job_Content__c = JSON.serialize(eventSchemaOne),
            Event_Time__c = DateTime.now() - 7
        );

        // Job Two
        EligibilitySchema eventSchemaTwo = createTestSchema();
        eventSchemaTwo.eligibility.isEligible = 'NOT_ELIGIBLE';

        Queue_Job__c queueJobTwo = new Queue_Job__c(
            Job_Content__c = JSON.serialize(eventSchemaTwo),
            Event_Time__c = DateTime.now()
        );

        // WHEN the event processor is run
        Test.startTest();
        EventEligibilityProcessor processor = new EventEligibilityProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJobOne, queueJobTwo });
        Test.stopTest();

        // THEN both queue jobs should be successful
        Assert.areEqual(2, processor.successfulJobs.size(), 'Expected two successful jobs');
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        // AND only one Opportunity should have been updated
        List<Opportunity> opps = [
            SELECT Eligibility_Status__c
            FROM Opportunity
        ];

        // AND the Opportunity should have been updated from the latest Event
        Assert.areEqual(1, opps.size());
        Assert.areEqual(eventSchemaTwo.eligibility.isEligible, opps[0].Eligibility_Status__c);
    }

    static EligibilitySchema createTestSchema() {
        EligibilitySchema eventSchema = new EligibilitySchema();
        eventSchema.applicationId = TEST_APPLICATION_ID;
        eventSchema.eligibility = new EligibilitySchema.Eligibility();
        eventSchema.eligibility.templateCode = 'August2023';
        eventSchema.eligibility.isEligible = 'ELIGIBLE';
        eventSchema.eligibility.submittedOn = Date.newInstance(2023, 8, 8);
        eventSchema.eligibility.summaryText = '<ul><li>Test Summary</li></ul>';

        return eventSchema;
    }
}