salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/AuthorisedOn__c.field-meta.xml
<CustomField>
    <fullName>AuthorisedOn__c</fullName>
    <description>The datetime that the application was moved into Acceptance, used in applicationStageChange event</description>
    <label>AuthorisedOn</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Authoriser__c.field-meta.xml
<CustomField>
    <fullName>Authoriser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the user that approved the application, this is sent to Join in an applicationStageChanged event</description>
    <label>Authoriser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AuthorisedOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact that is used to identify the Line Manager for Application requests</description>
    <label>Line Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Line Manager can&apos;t be a Student Account</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Line Manager)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/ApplicationStageSync.cls
public without sharing class ApplicationStageSync implements Serializer {
    /**
     * The set of Opportunity ids that form part of this event
     */
    private Set<Id> opportunityIds;

    /**
     * List of opportunities related to the opportunity ids
     */
    private List<Opportunity> opportunities;

    public ApplicationStageSync() {
        opportunityIds = new Set<Id>();
        opportunities = new List<Opportunity>();
    }

    /**
     * Adds the given Opportunity to the id list
     * @param record SObject to add to the record
     */
    public void addRecord(SObject record) {
        switch on record.getSObjectType().getDescribe().getName() {
            when 'Opportunity' {
                opportunityIds.add(record.Id);
            }
        }
    }

    /**
     * Creates a list of event payloads
     * @return  Payloads to send to an Emitter
     */
    public List<Map<String, Object>> serialize() {
        List<Map<String, Object>> payloads = new List<Map<String, Object>>();

        // Fetch opportunities
        fetchOpportunities();

        for (Opportunity opp : opportunities) {
            Map<String, Object> payload = new Map<String, Object>{
                'applicationId' => opp.Application_Id__c,
                'currentStage' => opp.StageName.toUpperCase().replace(' ', '_'),
                'currentStageStatus' => opp.BPP_Sub_Status__c.toUpperCase().replace(' ', '_')
            };

            if (opp.StageName == 'Line Manager Review') {
                payload.put(
                    'lineManager',
                    new Map<String, Object>{
                        'firstName' => opp.Line_Manager__r.FirstName,
                        'lastName' => opp.Line_Manager__r.LastName,
                        'email' => opp.Line_Manager__r.Email
                    }
                );
            }

            if (opp.StageName == 'Acceptance') {
                payload.put(
                    'data',
                    new Map<String, Object>{
                        'bppAuthorizerFirstName' => opp.Authoriser__r?.FirstName,
                        'bppAuthorizerLastName' => opp.Authoriser__r?.LastName,
                        'bppAuthorizedOn' => opp.AuthorisedOn__c
                    }
                );
            }

            payloads.add(payload);
        }

        return payloads;
    }

    /**
     * Fetches opportunities from the given ids where the stage is
     * in Line Manager Review
     */
    private void fetchOpportunities() {
        opportunities = [
            SELECT
                Application_Id__c,
                BPP_Sub_Status__c,
                StageName,
                Line_Manager__r.Email,
                Line_Manager__r.FirstName,
                Line_Manager__r.LastName,
                Authoriser__r.FirstName,
                Authoriser__r.LastName,
                AuthorisedOn__c
            FROM Opportunity
            WHERE
                Id IN :opportunityIds
                AND ((StageName = 'Line Manager Review'
                AND BPP_Sub_Status__c = 'In Progress')
                OR (StageName = 'Acceptance'
                AND BPP_Sub_Status__c = 'Completed')
                OR (StageName = 'Unconditional Offer'))
        ];
    }
}