salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cancellation_Reason__c</fullName>
    <description>Cancellation Reason field to be mandatory if Status is set to Cancelled or Declined on Student Application Opportunity</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unable to fund the programme</fullName>
            </value>
            <value>
                <fullName>Change of profession</fullName>
            </value>
            <value>
                <fullName>Taken up a job</fullName>
            </value>
            <value>
                <fullName>Gone to a competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Failed previous qualification</fullName>
            </value>
            <value>
                <fullName>Location/Mode not available</fullName>
            </value>
            <value>
                <fullName>Family Emergency</fullName>
            </value>
            <value>
                <fullName>VISA/CAS/EU Delay</fullName>
            </value>
            <value>
                <fullName>Prefer not to say</fullName>
            </value>
            <value>
                <fullName>VISA Refusal</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>CAS requirement not met</fullName>
            </value>
            <value>
                <fullName>Academic/English entry not met</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Chosen to study at another BPP location</fullName>
            </value>
            <value>
                <fullName>Chosen to study another BPP programme</fullName>
            </value>
            <value>
                <fullName>appMissedDeadline</fullName>
                <label>Failed to submit application before deadline</label>
            </value>
            <value>
                <fullName>appWithdrawApplicant</fullName>
                <label>Learner withdrawn</label>
            </value>
            <value>
                <fullName>appNoResponseApplicant</fullName>
                <label>No response from applicant</label>
            </value>
            <value>
                <fullName>appNoResponseEmployer</fullName>
                <label>No response from employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedEmployer</fullName>
                <label>Cancelled due to change of employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedProgramme</fullName>
                <label>Change of programme</label>
            </value>
            <value>
                <fullName>appRejectIneligibleResidency</fullName>
                <label>Ineligible status (Residency)</label>
            </value>
            <value>
                <fullName>appRejectIneligibleVisa</fullName>
                <label>Ineligible status (VISA)</label>
            </value>
            <value>
                <fullName>appRejectRoleOnboarding</fullName>
                <label>Job role does not match criteria (Onboarding)</label>
            </value>
            <value>
                <fullName>appRejectRoleHop</fullName>
                <label>Job role does not match criteria (Hop)</label>
            </value>
            <value>
                <fullName>appRejectOverqualified</fullName>
                <label>Applicant is not suitable for selected programme</label>
            </value>
            <value>
                <fullName>appRejectFundingIssue</fullName>
                <label>Application has a funding issue</label>
            </value>
            <value>
                <fullName>appNotEligible</fullName>
                <label>Not Eligible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Not eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_JSON__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_JSON__c</fullName>
    <description>Stores the entire Eligibility payload provided in the inbound event for use in rendering the eligibilityData LWC.</description>
    <label>Eligibility JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <description>The current eligibility status of the application</description>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT_CHECKED</fullName>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>ELIGIBLE</fullName>
                <label>Eligible</label>
            </value>
            <value>
                <fullName>NOT_ELIGIBLE</fullName>
                <label>Not Eligible</label>
            </value>
            <value>
                <fullName>Eligibility Incomplete</fullName>
                <default>true</default>
                <label>Eligibility Incomplete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_Text__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Text__c</fullName>
    <description>Stores the Eligibility in a readable way to be displayed in printable view</description>
    <label>Eligibility</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventEligibilityProcessor.cls
/**
 * Processor for the Eligibility events
 */
public class EventEligibilityProcessor extends BaseProcessor {
    private Map<String, EligibilityJobDetails> applicationIdToDetails = new Map<String, EligibilityJobDetails>();

    /**
     * Update a related opp from event.
     * @param  queueJobs queueJobs description
     */
    public void processImpl(List<Queue_Job__c> queueJobs) {
        // deserialize event
        deserializeEvents(queueJobs);

        // find Account
        Map<String, Opportunity> applicationToOpp = new Map<String, Opportunity>();
        for (Opportunity opp : [
            SELECT Id, Application_Id__c
            FROM Opportunity
            WHERE Application_Id__c IN :applicationIdToDetails.keySet()
        ]) {
            // Update opp's addresses
            EligibilitySchema schema = applicationIdToDetails.get(opp.Application_Id__c).schema;

            opp.Eligibility_Status__c = schema.eligibility.isEligible;
            opp.Eligibility_JSON__c = JSON.serialize(schema);

            String eliStatus = schema.eligibility.isEligible != null ? schema.eligibility.isEligible : 'N/A';
            String eliSubmitted = schema.eligibility.submittedOn != null
                ? schema.eligibility.submittedOn.formatGMT('MM/dd/YYYY')
                : 'N/A';
            String eliTemplate = schema.eligibility.templateCode != null ? schema.eligibility.templateCode : 'N/A';

            opp.Eligibility_Text__c =
                'Eligibility Status: ' +
                eliStatus +
                ' | Date Submitted: ' +
                eliSubmitted +
                ' | Template: ' +
                eliTemplate +
                '\n';

            for (EligibilitySchema.Answer answer : schema.eligibility.answers) {
                opp.Eligibility_Text__c +=
                    '\n' +
                    answer.question +
                    (answer.eligible ? ' (Eligible)' : ' (Ineligible)') +
                    '\n' +
                    answer.summaryText +
                    '\n';
            }

            if (!String.isBlank(schema.eligibility.summaryText)) {
                opp.Eligibility_Text__c += '\nSummary\n';

                opp.Eligibility_Text__c += schema.eligibility.summaryText.replaceAll('<(?:/(?:p|li)|(?:p)/)>', '$0~~')
                    .stripHtmlTags()
                    .replaceAll('~~', '\n');
            }

            // If the Application has been marked as illegible, close it
            if (opp.Eligibility_Status__c == 'NOT_ELIGIBLE') {
                opp.StageName = 'Closed Lost';
                opp.BPP_Sub_Status__c = 'Not eligible';
                opp.BPP_Cancellation_Reason__c = 'appNotEligible';
            }

            applicationToOpp.put(opp.Application_Id__c, opp);
        }

        // fail for events we didn't find an opp for
        for (String applicationId : applicationIdToDetails.keySet()) {
            if (!applicationToOpp.containsKey(applicationId)) {
                failedJobs.put(
                    applicationIdToDetails.get(applicationId).queueJob,
                    'No Opp found with matching applicationId'
                );
            }
        }

        processDML(applicationToOpp);
    }

    /**
     * Preforms any DML inserts and updates for the provided records
     * @param  applicationToOpp  A map of Application Ids to Opportunities to update
     */
    private void processDML(Map<String, Opportunity> applicationToOpp) {
        // Update any opps
        List<Database.SaveResult> oppResults = Database.Update(applicationToOpp.values(), false);
        for (Integer i = 0; i < oppResults.size(); i++) {
            Database.SaveResult result = oppResults[i];

            String applicationId = (new List<String>(applicationToOpp.keySet()))[i];
            EligibilityJobDetails jobDetails = applicationIdToDetails.get(applicationId);

            if (result.isSuccess()) {
                successfulJobs.add(jobDetails.queueJob);
                continue;
            }

            processDMLErrors(jobDetails.queueJob, result.getErrors());
        }
    }

    /**
     * Deserializes job content and adds to lists to be processed
     * @param  queueJobs Queue Jobs being processed
     */
    public void deserializeEvents(List<Queue_Job__c> queueJobs) {
        for (Queue_Job__c queueJob : queueJobs) {
            EligibilitySchema event = (EligibilitySchema) JSON.deserialize(
                queueJob.Job_Content__c,
                EligibilitySchema.class
            );

            // If any required values aren't present, skip
            if (String.isBlank(event.applicationId)) {
                failedJobs.put(queueJob, 'Required value null in event payload');
                continue;
            }

            // If we have already mapped an event with a given Application Id, mark whichever is oldest as successful
            if (applicationIdToDetails.containsKey(event.applicationId)) {
                Queue_Job__c duplicateJob = applicationIdToDetails.get(event.applicationId).queueJob;

                if (queueJob.Event_Time__c <= duplicateJob.Event_Time__c) {
                    successfulJobs.add(queueJob);
                    continue;
                }

                successfulJobs.add(duplicateJob);
            }

            EligibilityJobDetails jobDetails = new EligibilityJobDetails();
            jobDetails.schema = event;
            jobDetails.queueJob = queueJob;

            applicationIdToDetails.put(event.applicationId, jobDetails);
        }
    }

    // Class to store details relating to the event
    private class EligibilityJobDetails {
        public EligibilitySchema schema;
        public Queue_Job__c queueJob;
    }
}