salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/RecallApplicationController.cls
/**
 * RecallApplicationController deals with recalling applications
 * from previous status' and sub status', the controller is used
 * along side the recallApplication LWC.
 */
public without sharing class RecallApplicationController {

    /**
     * Provides an opportunity with recall changes applied
     * @param opportunityId The opportunity id
     * @return  Opportunity with changes that would happen during the recall
     * @exception 
     */
    @AuraEnabled(cacheable=true)
    public static Opportunity getPreview(Id opportunityId) {
        try {
            Opportunity opp = convertOpp(opportunityId);

            return opp;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Recalls the opportunity, updates Status and Sub Status and emits
     * an applicationStageChanged event
     * @param opportunityId The oppportunity Id
     */
    @AuraEnabled
    public static void recallOpportunity(Id opportunityId) {
        try {

            Opportunity opp = convertOpp(opportunityId);

            // Update the opportunity
            update opp;

            // Trigger event
            ApplicationRecall recall = new ApplicationRecall();
            recall.addRecord(opp);

            PlatformEventEmitter emitter = new PlatformEventEmitter();
            emitter.send('applicationStageChanged', recall.serialize());
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * Applies changes to status and sub status for recalled opportunities
     * @param opportunityId The opportunity id
     * @return  Opportunity with status and sub status changes applied
     */
    private static Opportunity convertOpp(Id opportunityId) {
        Opportunity opp = [SELECT Id, Application_Id__c, StageName, BPP_Sub_Status__c FROM Opportunity WHERE Id = :opportunityId];

        switch on opp.StageName {
            when 'BPP Review' {
                if (opp.BPP_Sub_Status__c == 'Awaiting Information') {
                    opp.BPP_Sub_Status__c = 'In Progress';
                }
            }
            when 'Line Manager Review' {
                opp.StageName = 'BPP Review';
                opp.BPP_Sub_Status__c = 'In Progress';
            }
            when 'Acceptance' {
                if (opp.BPP_Sub_Status__c == 'Completed') {
                    opp.BPP_Sub_Status__c = 'In Progress';
                }
            }
        }

        return opp;
    }
}