salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Enrolment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Status__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <description>Stages to enrolment once application has been accepted</description>
    <label>Enrolment Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Post-Registration (non-attendees)</fullName>
            </value>
            <value>
                <fullName>First Instalment Paid</fullName>
            </value>
            <value>
                <fullName>Temporarily Registered</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Indicates the location that the student has applied to or expressed interest.</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>London - City</fullName>
            </value>
            <value>
                <fullName>London - Waterloo</fullName>
            </value>
            <value>
                <fullName>London - Holborn</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>Leeds</fullName>
            </value>
            <value>
                <fullName>Croydon</fullName>
            </value>
            <value>
                <fullName>Milton Keynes</fullName>
            </value>
            <value>
                <fullName>eLearning Center</fullName>
            </value>
            <value>
                <fullName>Cambridge</fullName>
            </value>
            <value>
                <fullName>Maidstone</fullName>
            </value>
            <value>
                <fullName>Glasgow</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Nottingham</fullName>
            </value>
            <value>
                <fullName>Cardiff</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Southampton</fullName>
            </value>
            <value>
                <fullName>Manchester</fullName>
            </value>
            <value>
                <fullName>Liverpool</fullName>
            </value>
            <value>
                <fullName>Swindon</fullName>
            </value>
            <value>
                <fullName>Abingdon - McTimoney</fullName>
            </value>
            <value>
                <fullName>London (City)</fullName>
            </value>
            <value>
                <fullName>London (Waterloo)</fullName>
            </value>
            <value>
                <fullName>London (Holborn)</fullName>
            </value>
            <value>
                <fullName>Abingdon (McTimoney)</fullName>
            </value>
            <value>
                <fullName>Doncaster-RDASH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/classes/StudentCoursesOppBatchTest.cls
@isTest
private class StudentCoursesOppBatchTest {
    @TestSetup
    private static void setup() {
        Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get('Student Account')
            .getRecordTypeId();

        Account account = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);
        insert account;

        Programme__c programme = new Programme__c(Name = 'Test programme');
        insert programme;

        Product2 product = new Product2(
            Name = 'Test Course',
            Programme__c = programme.Id,
            BPP_ProductFactoryID__c = 'test-123',
            Instance_Id__c = 'test-1234',
            Location__c = 'London',
            Start_Date__c = Date.today()
        );
        insert product;

        Id applicationRtId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
            .get('Student_Application')
            .getRecordTypeId();

        insert new Opportunity(
            RecordTypeId = applicationRtId,
            AccountId = account.Id,
            Name = 'Test Opportunity',
            StageName = 'Accepted - Pmt Received',
            CloseDate = Date.today() + 30,
            Application_Id__c = 'test-32874',
            Course_Instance__c = product.Id,
            Enrolment_Status__c = 'Acceptance'
        );
    }

    @isTest
    private static void itShouldCreateStudentCourses() {
        // GIVEN an opportunity
        delete [SELECT Id FROM Student_Course__c];
        // WHEN the batch runs
        System.Test.startTest();

        Database.executeBatch(new StudentCoursesOppBatch());

        System.Test.stopTest();

        // THEN I expect it to create a student course
        Account account = [SELECT Id FROM Account LIMIT 1];
        Student_Course__c course = [SELECT Instance_Id__c FROM Student_Course__c WHERE Student__c = :account.Id];

        Assert.areEqual('test-1234', course.Instance_Id__c);
    }

    @isTest
    private static void itShouldNotCreateStudentCourseWhenTheyExist() {
        // GIVEN an opportunity
        // AND a student course already exists - satisfied by trigger
        // WHEN the batch runs
        System.Test.startTest();

        Database.executeBatch(new StudentCoursesOppBatch());

        System.Test.stopTest();

        // THEN I expect it to skip creating a student course
        Account account = [SELECT Id FROM Account LIMIT 1];
        List<Student_Course__c> courses = [SELECT Id FROM Student_Course__c WHERE Student__c = :account.Id];

        Assert.areEqual(1, courses.size());
    }
}