salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Company_City__c.field-meta.xml
<CustomField>
    <fullName>Company_City__c</fullName>
    <description>The city of the company address provided by the student</description>
    <label>Company City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Company_Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Company_Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The country associated with the company address provided by the student</description>
    <label>Company Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The value you have selected is not a valid Country</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Opportunity_Company_Addresses</relationshipLabel>
    <relationshipName>Opportunity_Company_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Company_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Company_Street_1__c</fullName>
    <description>The first line of the company address provided by the student</description>
    <label>Company Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Company_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Company_Street_2__c</fullName>
    <description>The second line of the company address provided by the student</description>
    <label>Company Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Company_Street_3__c.field-meta.xml
<CustomField>
    <fullName>Company_Street_3__c</fullName>
    <description>The third line of the company address provided by the student</description>
    <label>Company Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Company_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Zip_Postal_Code__c</fullName>
    <description>The zip/postal code of the company address provided by the student</description>
    <label>Company Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Job_Description_Apprentice__c.field-meta.xml
<CustomField>
    <fullName>Job_Description_Apprentice__c</fullName>
    <description>A detailed overview of the employee's job responsibilities and duties as provides during the application process.</description>
    <label>Job Description</label>
    <length>800</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Job_Started_On_Apprentice__c.field-meta.xml
<CustomField>
    <fullName>Job_Started_On_Apprentice__c</fullName>
    <description>The date when the employee officially started their current job role.</description>
    <label>Job Started On</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Job_Title_Apprentice__c.field-meta.xml
<CustomField>
    <fullName>Job_Title_Apprentice__c</fullName>
    <description>The title of the job role assigned to the employee as provided during the application process.</description>
    <label>Job Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager_Email__c</fullName>
    <description>Email of Line Manager specified in an Application request</description>
    <label>Line Manager Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager_First_Name__c</fullName>
    <description>The First Name of a Line Manager specified in a Application request</description>
    <label>Line Manager First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager_Job_Title__c</fullName>
    <description>Job Title of Line Manager specified in an Application request</description>
    <label>Line Manager Job Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager_Last_Name__c</fullName>
    <description>Last Name of Line Manager specified in an Application request</description>
    <label>Line Manager Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager_Telephone__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager_Telephone__c</fullName>
    <description>Telephone number of Line Manager specified in an Application request</description>
    <label>Line Manager Telephone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/OOTJTH_Preserved__c.field-meta.xml
<CustomField>
    <fullName>OOTJTH_Preserved__c</fullName>
    <description>Used for preserving the calculation and manual input</description>
    <label>Overall Off The Job Training Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Safety_Knowledge_Apprentice__c.field-meta.xml
<CustomField>
    <fullName>Safety_Knowledge_Apprentice__c</fullName>
    <description>A picklist indicating whether the employee has knowledge of safety queries related to their job role.</description>
    <label>Safety Knowledge</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>NO</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsoring_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sponsoring_Organization__c</fullName>
    <description>Organization that sponsors the student.  Populated by some external sources; can be populated manually as well.  No dynamic link exists; text tracking only.</description>
    <label>Sponsoring Organization</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Weekly_Contracted_Hours_Apprentice__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Contracted_Hours_Apprentice__c</fullName>
    <description>The total number of hours the employee is contracted to work on a weekly basis.</description>
    <label>Weekly Contracted Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/ApplicationUpdated.cls
/**
 * Handles events where a BPP Admin has updated an application during the
 * BPP Review stage
 */
public without sharing class ApplicationUpdated implements Serializer {
    /**
     * Set of opportunity ids given from addRecord when record is Opportunity
     */
    public Set<Id> opportunityIds;

    /**
     * List of Applications to be processed
     */
    private List<Opportunity> opportunities;

    /**
     * Default Construct
     */
    public ApplicationUpdated() {
        opportunityIds = new Set<Id>();
        opportunities = new List<Opportunity>();
    }

    /**
     * Extracts either AccountId or OpportunityId from given records
     * @param record The record to be processed
     */
    public void addRecord(SObject record) {
        switch on record.getSObjectType().getDescribe().getName() {
            when 'Opportunity' {
                opportunityIds.add(record.Id);
            }
        }
    }

    /**
     * Builds the expected payload for the event
     * @return  Payload for the given records
     */
    public List<Map<String, Object>> serialize() {
        List<Map<String, Object>> payloads = new List<Map<String, Object>>();

        fetchOpportunities();

        for (Opportunity opp : opportunities) {
            String productId = opp.Course_Instance__r?.Instance_Id__c;

            if (!String.isBlank(productId)) {
                productId = 'PCV2-' + productId;
            }

            Map<String, Object> payload = new Map<String, Object>{
                'applicationId' => opp.Application_Id__c,
                'productId' => productId,
                'updatedBy' => opp.LastModifiedBy.Name,
                'product' => new Map<String, Object>{ 'startOn' => opp.Start_Date__c, 'endOn' => opp.End_Date__c },
                'employerInformation' => new Map<String, Object>{
                    'lineManagerInformation' => new Map<String, Object>{
                        'firstName' => opp.Line_Manager_First_Name__c,
                        'lastName' => opp.Line_Manager_Last_Name__c,
                        'jobTitle' => opp.Line_Manager_Job_Title__c,
                        'emailAddress' => opp.Line_Manager_Email__c,
                        'mobilePhone' => opp.Line_Manager_Telephone__c
                    },
                    'companyInformation' => new Map<String, Object>{
                        'companyName' => opp.Sponsoring_Organization__c,
                        'line1' => opp.Company_Street_1__c,
                        'line2' => opp.Company_Street_2__c,
                        'line3' => opp.Company_Street_3__c,
                        'city' => opp.Company_City__c,
                        'postalCode' => opp.Company_Zip_Postal_Code__c,
                        'country' => new Map<String, Object>{
                            'code' => opp.Company_Lookup_Country__r?.Country_Code_2__c
                        }
                    },
                    'role' => new Map<String, Object>{
                        'jobTitle' => opp.Job_Title_Apprentice__c,
                        'jobDescription' => opp.Job_Description_Apprentice__c,
                        'safetyQueryKnowledge' => opp.Safety_Knowledge_Apprentice__c,
                        'jobStartDate' => opp.Job_Started_On_Apprentice__c,
                        'weeklyContractedHours' => opp.Weekly_Contracted_Hours_Apprentice__c,
                        'overallOffTheJobTrainingHours' => opp.OOTJTH_Preserved__c
                    }
                }
            };

            payloads.add(payload);
        }

        return payloads;
    }

    /**
     * Uses the extracted identifiers from addRecord to fetch Opportunities
     * related to the changes
     */
    private void fetchOpportunities() {
        for (Opportunity opp : [
            SELECT
                AccountId,
                Application_Id__c,
                Course_Instance__r.Instance_ID__c,
                Job_Started_On_Apprentice__c,
                Weekly_Contracted_Hours_Apprentice__c,
                Sponsoring_Organization__c,
                Company_Street_1__c,
                Company_Street_2__c,
                Company_Street_3__c,
                Company_Zip_Postal_Code__c,
                Company_City__c,
                Line_Manager_Job_Title__c,
                Line_Manager_First_Name__c,
                Line_Manager_Last_Name__c,
                Line_Manager_Email__c,
                Line_Manager_Telephone__c,
                Company_Lookup_Country__r.Country_Code_2__c,
                Start_Date__c,
                End_Date__c,
                LastModifiedBy.Name,
                Safety_Knowledge_Apprentice__c,
                Job_Description_Apprentice__c,
                Job_Title_Apprentice__c,
                OOTJTH_Preserved__c
            FROM Opportunity
            WHERE Id IN :opportunityIds AND (StageName = 'BPP Review' OR StageName = 'Acceptance')
        ]) {
            opportunities.add(opp);
        }
    }
}