salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Recent Activity</fullName>
            </value>
            <value>
                <fullName>Going Stale</fullName>
            </value>
            <value>
                <fullName>Stale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/GoingStaleDate__c.field-meta.xml
<CustomField>
    <fullName>GoingStaleDate__c</fullName>
    <description>The field captures the date/time when the Sub Status is updated to &apos;Going Stale&apos;.</description>
    <label>GoingStaleDate</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity_Age_Threshold__mdt/Opportunity_Age_Threshold__mdt.object-meta.xml
<CustomObject>
    <description>Age of Opportunity Thresholds</description>
    <label>Opportunity Age Threshold</label>
    <pluralLabel>Opportunity Age Thresholds</pluralLabel>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity_Age_Threshold__mdt/fields/Age_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Age_Threshold__c</fullName>
    <label>Age Threshold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/classes/OpportunitySubstatusBatchJob.cls
public class OpportunitySubstatusBatchJob implements Schedulable, Database.Batchable<SObject> {
    private List<Opportunity> opportunitiesList = new List<Opportunity>();
    @testVisible private static Messaging.SingleEmailMessage failedUpdateEmail;
    @testVisible public Map<String, Integer> ageThresholds = new Map<String, Integer>();

    /**
     * Constructor to query out any relevant Opportunities to be processed
     */
    public OpportunitySubstatusBatchJob() {
        populateAgeThresholds();
    }

    private void populateAgeThresholds() {
        // Fetch records from Custom Metadata
        List<Opportunity_Age_Threshold__mdt> metadataRecords = Opportunity_Age_Threshold__mdt.getAll().values();
        for (Opportunity_Age_Threshold__mdt record : metadataRecords) {
            ageThresholds.put(record.MasterLabel, Integer.valueOf(record.Age_Threshold__c));
        }
    }

    //Execute of schedulable interface
    public void execute(SchedulableContext SC) 
    {
        Database.executeBatch(this, 50);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime dateToCalcForFirstStage = DateTime.now().addDays(-ageThresholds.get('Recent Activity'));
        DateTime dateToCalcForSecondStage = DateTime.now().addDays(-ageThresholds.get('Going Stale'));

        return Database.getQueryLocator(
            [
                SELECT Id, BPP_Sub_Status__c, LastModifiedDate, GoingStaleDate__c
                FROM Opportunity
                WHERE
                    RecordType.DeveloperName = 'Student_Interest'
                    AND StageName IN ('Application Started', 'Application in Progress')
                    AND BPP_Sub_Status__c IN ('Recent Activity', 'Going Stale')
                    AND (LastModifiedDate < :dateToCalcForFirstStage OR LastModifiedDate < :dateToCalcForSecondStage)
            ]
        );
    }

    public void execute(Database.BatchableContext bc, List<Opportunity> opportunities) {
        for (Opportunity currentOpportunity : opportunities) {
            processOpportunity(currentOpportunity);
        }

        try {
            Database.upsert(opportunitiesList, false);
        } catch (Exception ex) {
            buildAndSendUnhandledError(ex.getMessage());
        }
    }

    private void processOpportunity(Opportunity currentOpportunity) {
        if (isEligibleForStage(currentOpportunity, 'Recent Activity')) {
            currentOpportunity.BPP_Sub_Status__c = 'Going Stale';
            currentOpportunity.GoingStaleDate__c = Datetime.now();
        } else if (isEligibleForStage(currentOpportunity, 'Going Stale')) {
            currentOpportunity.BPP_Sub_Status__c = 'Stale';
        } else {
            return;
        }
        opportunitiesList.add(currentOpportunity);
    }

    private boolean isEligibleForStage(Opportunity currentOpportunity, String subStatus) {
        Integer daysThreshold = ageThresholds.get(subStatus);
        if (daysThreshold == null) {
            // Handle case where metadata record is not found
            return false;
        }
        Datetime thresholdDate = DateTime.now().addDays(-daysThreshold);
        Datetime goingStaleDate = currentOpportunity.GoingStaleDate__c;
        return currentOpportunity.BPP_Sub_Status__c == subStatus && currentOpportunity.LastModifiedDate < thresholdDate && (goingStaleDate == null || goingStaleDate < thresholdDate);
    }

    public void finish(Database.BatchableContext bc) {
    }

    @testVisible
    private void buildAndSendUnhandledError(String exceptionMessage) {
        String body =
            'Opportunities have failed to update: ' +
            exceptionMessage +
            ' | Opportunities: ' +
            JSON.serialize(opportunitiesList);
        failedUpdateEmail = EmailUtilities.submitSystemAlertEmail('Opportunities Update has failed', body);
    }
}