salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Tier_1__c.field-meta.xml
<CustomField>
    <fullName>Tier_1__c</fullName>
    <label>Tier 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountancy and Tax</fullName>
            </value>
            <value>
                <fullName>Actuarial Education</fullName>
            </value>
            <value>
                <fullName>Banking / Insurance / FS</fullName>
            </value>
            <value>
                <fullName>DTS / MSC in Data Analytics</fullName>
            </value>
            <value>
                <fullName>GDA / wrap</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>HR / Management / Business Admin</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Technology Products</fullName>
            </value>
            <value>
                <fullName>Professional Development</fullName>
            </value>
            <value>
                <fullName>Risk / Compliance / Financial Crime</fullName>
            </value>
            <value>
                <fullName>UG / PG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Tier_2__c.field-meta.xml
<CustomField>
    <fullName>Tier_2__c</fullName>
    <label>Tier 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tier_1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accelerated Training</fullName>
            </value>
            <value>
                <fullName>Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Bespoke</fullName>
            </value>
            <value>
                <fullName>Key Skills Series</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Public Non-Apps</fullName>
            </value>
            <value>
                <fullName>Skills Bootcamps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Tier_3__c.field-meta.xml
<CustomField>
    <fullName>Tier_3__c</fullName>
    <label>Tier 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tier_2__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ActEd</fullName>
            </value>
            <value>
                <fullName>Apprenticeship School (Level 2/3/4/5)</fullName>
            </value>
            <value>
                <fullName>Apprenticeship School (Level 6/7)</fullName>
            </value>
            <value>
                <fullName>Channel Islands</fullName>
            </value>
            <value>
                <fullName>Data Assembly</fullName>
            </value>
            <value>
                <fullName>Estio</fullName>
            </value>
            <value>
                <fullName>Firebrand</fullName>
            </value>
            <value>
                <fullName>Law School</fullName>
            </value>
            <value>
                <fullName>Malaysia BPP</fullName>
            </value>
            <value>
                <fullName>PD</fullName>
            </value>
            <value>
                <fullName>Poland BPP</fullName>
            </value>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>PQ (FS, Level 6/7)</fullName>
            </value>
            <value>
                <fullName>PQ (FS)</fullName>
            </value>
            <value>
                <fullName>Romania BPP</fullName>
            </value>
            <value>
                <fullName>School of Business</fullName>
            </value>
            <value>
                <fullName>School of Business (Level 6/7)</fullName>
            </value>
            <value>
                <fullName>School of FS (Level 2/3/4/5)</fullName>
            </value>
            <value>
                <fullName>School of FS (Level 6/7)</fullName>
            </value>
            <value>
                <fullName>School of Health</fullName>
            </value>
            <value>
                <fullName>School of Nursing</fullName>
            </value>
            <value>
                <fullName>School of Technology</fullName>
            </value>
            <value>
                <fullName>School of Technology (Level 6/7)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Tier_4__c.field-meta.xml
<CustomField>
    <fullName>Tier_4__c</fullName>
    <label>Tier 4</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tier_3__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>Academic and careers skills</fullName>
            </value>
            <value>
                <fullName>Academic LLMs</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>ACCA Professional Level</fullName>
            </value>
            <value>
                <fullName>Accountancy / Taxation Professional - Level 7 (ACCA)</fullName>
            </value>
            <value>
                <fullName>Accountancy / Taxation Professional - Level 7 (ATT/CTA)</fullName>
            </value>
            <value>
                <fullName>Accountancy / Taxation Professional - Level 7 (CIMA)</fullName>
            </value>
            <value>
                <fullName>Accountancy / Taxation Professional - Level 7 (CTA)</fullName>
            </value>
            <value>
                <fullName>Accountancy / Taxation Professional - Level 7 (ICAEW)</fullName>
            </value>
            <value>
                <fullName>Accountancy / Taxation Professional - Level 7 (ICAEW ACA/CTA)</fullName>
            </value>
            <value>
                <fullName>Accountancy (Scotland) – SCQF Level 5</fullName>
            </value>
            <value>
                <fullName>Accountancy (Scotland) – SCQF Level 6</fullName>
            </value>
            <value>
                <fullName>Accountancy (Scotland) – SCQF Level 8</fullName>
            </value>
            <value>
                <fullName>Accountancy &amp; Tax</fullName>
            </value>
            <value>
                <fullName>Actuarial Technician - Level 4</fullName>
            </value>
            <value>
                <fullName>Actuary - Level 7</fullName>
            </value>
            <value>
                <fullName>Acturial Education</fullName>
            </value>
            <value>
                <fullName>Advanced Credit Controller / Debt Collection Specialist - Level 3</fullName>
            </value>
            <value>
                <fullName>Advanced Data and Audit Analytics</fullName>
            </value>
            <value>
                <fullName>Advanced Diploma in Accounting Finance (ACCA Route)</fullName>
            </value>
            <value>
                <fullName>Advanced Diploma in Accounting - Level 3</fullName>
            </value>
            <value>
                <fullName>Agile Thinking in a Changing Business World</fullName>
            </value>
            <value>
                <fullName>Analytical and Critical Thinking</fullName>
            </value>
            <value>
                <fullName>App and Web Development</fullName>
            </value>
            <value>
                <fullName>Application Support Lead - Level 4</fullName>
            </value>
            <value>
                <fullName>Artificial Intelligence - Level 7</fullName>
            </value>
            <value>
                <fullName>Assistant Accountant - Level 3</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager - Level 4</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>Capability Analysis</fullName>
            </value>
            <value>
                <fullName>MSc Management</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Tier_5__c.field-meta.xml
<CustomField>
    <fullName>Tier_5__c</fullName>
    <label>Tier 5</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tier_2__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Existing Staff</fullName>
            </value>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Graduates</fullName>
            </value>
            <value>
                <fullName>Mixed Recruitment Type</fullName>
            </value>
            <value>
                <fullName>Online Classroom Live</fullName>
            </value>
            <value>
                <fullName>Online Demand</fullName>
            </value>
            <value>
                <fullName>School Leavers</fullName>
            </value>
            <value>
                <fullName>Traineeships</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Tier_6__c.field-meta.xml
<CustomField>
    <fullName>Tier_6__c</fullName>
    <label>Tier 6</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tier_2__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Existing Employee</fullName>
            </value>
            <value>
                <fullName>New Recruit (BPP RS)</fullName>
            </value>
            <value>
                <fullName>New Recruit (Estio RS)</fullName>
            </value>
            <value>
                <fullName>New Recruit (in house)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/EditTiersExtTest.cls
@isTest
public class EditTiersExtTest {
    
    @testSetup
    static void testSetup(){
        Account a = new Account();
        a.Name = 'Test Company';
        a.RecordTypeId = Schema.sObjectType.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId();
        insert a;

        Opportunity opp = new Opportunity();
        opp.AccountId = a.Id;
        opp.Name = 'Test Opportunity';
        opp.RecordTypeId = Schema.Sobjecttype.Opportunity.getRecordTypeInfosByName().get('Business Development').getRecordTypeId();
        opp.StageName = 'Quoting';
        opp.BPP_Sub_Status__c = 'Other';
        opp.CloseDate = Date.Today();
        insert opp;
    }
    
    @isTest static void test_SelectOptions(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity'];

        Test.setCurrentPage(Page.EditTiers);
        ApexPages.StandardController opportunityController = new ApexPages.StandardController(opp);
        EditTiersExt editTiersExt = new EditTiersExt(opportunityController);
        
        List<SelectOption> tier2Options = editTiersExt.getNewTier2Options();
        for (SelectOption so2: tier2Options) {
            System.debug(so2);
        }
        
        List<SelectOption> tier3Options = editTiersExt.getNewTier3Options();
        for (SelectOption so3: tier3Options) {
            System.debug(so3);
        }
        
        List<SelectOption> tier4Options = editTiersExt.getNewTier4Options();
        for (SelectOption so4: tier4Options) {
            System.debug(so4);
        }
        
        List<SelectOption> tier5Options = editTiersExt.getNewTier5Options();
        for (SelectOption so5: tier5Options) {
            System.debug(so5);
        }
        List<SelectOption> tier6Options = editTiersExt.getNewTier6Options();
        for (SelectOption so6: tier6Options) {
            System.debug(so6);
        }
    }
    
    @isTest static void verifyEditTiers(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity'];
        Test.setCurrentPage(Page.EditTiers);
        ApexPages.StandardController opportunityController = new ApexPages.StandardController(opp);
        EditTiersExt editTiersExt = new EditTiersExt(opportunityController);
        
        Test.startTest();
            editTiersExt.tier1Options = 'Accountancy and Tax';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'PQ';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'Apprenticeship School (Level 2/3/4/5)';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'PQ';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Actuarial Education';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'ActEd';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'ActEd';
                    editTiersExt.updateTier4Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Banking / Insurance / FS';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Apprenticeship School (Level 2/3/4/5)';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of FS (Level 2/3/4/5)';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of FS (Level 6/7)';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();
        			editTiersExt.tier3Options = 'PQ';
                    editTiersExt.updateTier4Dropdown();
        			editTiersExt.tier3Options = 'PQ (FS)';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'DTS / MSC in Data Analytics';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'School of Technology (Level 6/7)';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of Technology';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'GDA / wrap';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'School of Business';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Health';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'School of Nursing';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of Health';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of Nursing';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'HR / Management / Business Admin';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Apprenticeship School (Level 2/3/4/5)';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'Apprenticeship School (Level 6/7)';
                    editTiersExt.updateTier4Dropdown();
        			editTiersExt.tier3Options = 'School of Business (Level 6/7)';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
        		editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Apprenticeship School (Level 2/3/4/5)';
        			editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'International';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'School of Technology';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'PD';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
        			editTiersExt.tier3Options = 'Apprenticeship School (Level 2/3/4/5)';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'PD';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'Romania BPP';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'Channel Islands';
                    editTiersExt.updateTier4Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Law';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Law School';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Law School';
                    editTiersExt.updateTier4Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Other';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Other';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Other Technology Products';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Accelerated Training';
                editTiersExt.updateTier3Dropdown();
                editTiersExt.tier3Options = 'Firebrand';
                editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                editTiersExt.tier3Options = 'Apprenticeship School (Level 2/3/4/5)';
                editTiersExt.updateTier4Dropdown();
                editTiersExt.tier3Options = 'Estio';
                editTiersExt.updateTier4Dropdown();
                editTiersExt.tier3Options = 'Firebrand';
                editTiersExt.updateTier4Dropdown();
                editTiersExt.tier3Options = 'School of Technology';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Data Assembly';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of Technology';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Key Skills Series';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'School of Technology';
                    editTiersExt.updateTier4Dropdown();
        		editTiersExt.tier2Options = 'Skills Bootcamps';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'Firebrand';
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'Professional Development';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'PD';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                    editTiersExt.updateTier3Dropdown();
        				editTiersExt.tier3Options = 'Malaysia BPP';
                    	editTiersExt.updateTier4Dropdown();
                        editTiersExt.tier3Options = 'PD';
                        editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Key Skills Series';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'PD';
                    editTiersExt.updateTier4Dropdown();
                        editTiersExt.tier4Options = 'Capability Analysis';
                        editTiersExt.updateTier5Dropdown();
                            editTiersExt.tier5Options = 'Online Demand';
                            editTiersExt.updateTier6Dropdown();
                                editTiersExt.tier6Options = '--None--';

            editTiersExt.tier1Options = 'Risk / Compliance / Financial Crime';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Apprenticeship';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.tier3Options = 'PQ (FS, Level 6/7)';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of FS (Level 2/3/4/5)';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of FS (Level 6/7)';
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();

            editTiersExt.tier1Options = 'UG / PG';
            editTiersExt.updateTier2Dropdown();
                editTiersExt.tier2Options = 'Bespoke';
                editTiersExt.updateTier3Dropdown();
                    editTiersExt.updateTier4Dropdown();
                editTiersExt.tier2Options = 'Public Non-Apps';
                editTiersExt.updateTier3Dropdown();
        			editTiersExt.tier3Options = 'Malaysia BPP';
                    editTiersExt.updateTier4Dropdown();
                    editTiersExt.tier3Options = 'School of Business';
                    editTiersExt.updateTier4Dropdown();
                        editTiersExt.tier4Options = 'MSc Management';
                        editTiersExt.updateTier5Dropdown();
                            editTiersExt.tier5Options = 'Mixed Recruitment Type';
                            editTiersExt.updateTier6Dropdown();
        
            PageReference redPage = editTiersExt.save();
        Test.stopTest();

        Opportunity verifyOpportunityUpdate = [SELECT Id, Tier_1__c, Tier_2__c, Tier_3__c, Tier_4__c, Tier_5__c, Tier_6__c FROM Opportunity where Id =: editTiersExt.opp.Id];
        System.assert(verifyOpportunityUpdate.Id != NULL);
        String oppId = (verifyOpportunityUpdate != NULL ? String.valueof(verifyOpportunityUpdate.Id) : NULL);
        String oppId15 = (oppId != NULL ? oppId.left(15) : NULL);
                        
        System.assert(verifyOpportunityUpdate.Tier_1__c == 'UG / PG');
        System.assert(verifyOpportunityUpdate.Tier_2__c == 'Public Non-Apps');
        System.assert(verifyOpportunityUpdate.Tier_3__c == 'School of Business');
        System.assert(verifyOpportunityUpdate.Tier_4__c == 'MSc Management');
        System.assert(verifyOpportunityUpdate.Tier_5__c == 'Mixed Recruitment Type');
        System.assert(verifyOpportunityUpdate.Tier_6__c == NULL);
        
        if (oppId15 != NULL) {   
        	System.assertEquals('/'+oppId15, redPage.getUrl());
        }
    }
}