salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Record_Source__c.field-meta.xml
<CustomField>
    <fullName>Record_Source__c</fullName>
    <description>Source of data to create this particular record (e.g. CAB/UCAS/BPTC).  Record source &apos;Salesforce&apos; indicates a record created by an end user.</description>
    <label>Record Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>UCAS</fullName>
            </value>
            <value>
                <fullName>BPTC</fullName>
            </value>
            <value>
                <fullName>Direct Apps</fullName>
            </value>
            <value>
                <fullName>Administrate</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Join</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/DedupeOpportunity.cls
@RestResource(urlMapping='/v1.0/DedupeOpportunity/*')
global with sharing class DedupeOpportunity {
    global class Response {
        public Response() {}
        public String opportunityId { get; set; }
        
        public Response(String opportunityId) {
            this.opportunityId = opportunityId;
        }
    }

    global class CheckOpportunity {
        public String accountId;
        public String courseInstance;
        public String recordSource;
    }

    @HttpPost
    global static Response doPost(CheckOpportunity opportunity) {
        try {
            String accountId, recordTypeId, courseInstance, recordSource;
            accountId = DedupeHelper.verifyPostInput(opportunity.accountId);
            courseInstance = DedupeHelper.verifyPostInput(opportunity.courseInstance);
            recordSource = DedupeHelper.verifyPostInput(opportunity.recordSource);
            
            Opportunity matchedOpportunity = opportunityCheck(accountId, courseInstance, recordSource);
            if (matchedOpportunity != NULL) {
                return new Response(String.valueOf(matchedOpportunity.Id));
            } else {
                return new Response('null');
            }
        } catch (Exception e) { 
            return new Response('DedupeOpportunity Error: [' + e.getLineNumber() + '] ' + e.getMessage());
        }
    }

    public static Opportunity opportunityCheck(String accountId, String courseInstance, String recordSource) {
        Opportunity oppFound;

        List<Opportunity> opportunityList = [
            SELECT Id FROM Opportunity 
            WHERE AccountId =: accountId AND Course_Instance__c =: courseInstance AND Record_Source__c =: recordSource AND RecordType.Name IN('Application', 'Locked Application')
            ORDER BY CreatedDate DESC
        ];
        
        if (opportunityList.size() > 0 ? true : false) {
            oppFound = opportunityList.get(0);
            System.debug('@DedupeOpportunity opportunityCheck - match found');
        }
        return oppFound;
    }
}