salesforce-main/src/main/default/objects/Authorisation_Token__c/Authorisation_Token__c.object-meta.xml
<CustomObject>
    <label>Authorisation Token</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisation Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Email_Verified__c.field-meta.xml
<CustomField>
    <fullName>Email_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Verified</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Integration_Log__c/fields/Salesforce_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_ID__c</fullName>
    <label>Salesforce ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/HubAccountVerificationEmailTest.cls
@isTest
private class HubAccountVerificationEmailTest {
    @isTest
    static void test_resendVerificationEmail() {
        Authorisation_Token__c authToken = TestDataFactory.createAuthorisationToken(TRUE);

        Hub_Account__c hubAccount = new Hub_Account__c();
        hubAccount.Auth0_Id__c = 'auth0|qwertyuiop';
        hubAccount.Hub_Username__c = 'test1@bpp.com';
        insert hubAccount;

        List<String> inputList = new List<String>{hubAccount.Auth0_Id__c};

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HubAccountCalloutMock());
            List<HubAccountUpdateHelper> response = new List<HubAccountUpdateHelper>();
            response = HubAccountVerificationEmail.getResult(inputList);
            System.assertEquals('Success', response[0].outputString);

            List<Integration_Log__c> integLogList = [SELECT Id FROM Integration_Log__c WHERE Salesforce_ID__c =: hubAccount.Id];
            System.assertEquals(1, integLogList.size());
        Test.stopTest();
    }

    @isTest
    static void test_resendVerificationEmailFailure1() {
        Authorisation_Token__c authToken = TestDataFactory.createAuthorisationToken(TRUE);

        Hub_Account__c hubAccount = new Hub_Account__c();
        hubAccount.Hub_Username__c = 'test1@bpp.com';
        insert hubAccount;

        List<String> inputList = new List<String>{hubAccount.Auth0_Id__c};

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HubAccountCalloutMock());
            List<HubAccountUpdateHelper> response = new List<HubAccountUpdateHelper>();
            response = HubAccountVerificationEmail.getResult(inputList);
            System.assertEquals('\nError: Auth0Id value is blank.', response[0].outputString);

            List<Integration_Log__c> integLogList = [SELECT Id FROM Integration_Log__c WHERE Salesforce_ID__c =: hubAccount.Id];
            System.assertEquals(0, integLogList.size());
        Test.stopTest();
    }

    @isTest
    static void test_resendVerificationEmailFailure2() {
        Authorisation_Token__c authToken = TestDataFactory.createAuthorisationToken(TRUE);

        Hub_Account__c hubAccount = new Hub_Account__c();
        hubAccount.Auth0_Id__c = 'auth0|qwertyuiop';
        hubAccount.Hub_Username__c = 'test1@bpp.com';
        hubAccount.Email_Verified__c = true;
        insert hubAccount;

        List<String> inputList = new List<String>{hubAccount.Auth0_Id__c};

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HubAccountCalloutMock());
            List<HubAccountUpdateHelper> response = new List<HubAccountUpdateHelper>();
            response = HubAccountVerificationEmail.getResult(inputList);
            System.assertEquals('\nError: Hub Account\'s Email address is already verified.', response[0].outputString);

            List<Integration_Log__c> integLogList = [SELECT Id FROM Integration_Log__c WHERE Salesforce_ID__c =: hubAccount.Id];
            System.assertEquals(0, integLogList.size());
        Test.stopTest();
    }
}