salesforce-main/src/main/default/objects/Authorisation_Token__c/Authorisation_Token__c.object-meta.xml
<CustomObject>
    <label>Authorisation Token</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisation Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Requested_Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>BPP_Requested_Hub_Username__c</fullName>
    <label>Requested Hub Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Username_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>BPP_Username_Error_Message__c</fullName>
    <label>Username Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Username_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Username_Update_Status__c</fullName>
    <description>Tracks the progress of the active Hub Username update request.</description>
    <inlineHelpText>Tracks the progress of the active Hub Username update request.</inlineHelpText>
    <label>Username Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/HubUsernameUpdateTest.cls
@isTest
private class HubUsernameUpdateTest {
    @testSetup
    static void testSetup() {
        List<Account> accountList = new List<Account>();
        Account account1 = TestDataFactory.createAccount(false,true,null,1);
        Account account2 = TestDataFactory.createAccount(false,true,null,2);
        account2.PersonEmail = 'john2@john.com';
        accountList.add(account1);
        accountList.add(account2);
        insert accountList;

        List<Hub_Account__c> hubAccountList = new List<Hub_Account__c>();
        Hub_Account__c hubAccount1 = new Hub_Account__c(Student__c = account1.Id, Hub_Username__c = account1.PersonEmail, Auth0_Id__c = 'auth0|1xx23x45xx67x89012x34x05');
        Hub_Account__c hubAccount2 = new Hub_Account__c(Student__c = account2.Id, Hub_Username__c = account2.PersonEmail, Auth0_Id__c = 'auth0|9xx87x65xx43x21098x76x54');
        hubAccountList.add(hubAccount1);
        hubAccountList.add(hubAccount2);
        insert hubAccountList;

        Authorisation_Token__c authToken = TestDataFactory.createAuthorisationToken(TRUE);
    }

    @isTest
    static void test_HubUsernameUpdateCalloutSuccess() {
        Test.startTest();
            Hub_Account__c hubAccountBefore = [SELECT Id, Student__c FROM Hub_Account__c WHERE Hub_Username__c = 'john@john.com' LIMIT 1];
            hubAccountBefore.BPP_Requested_Hub_Username__c = 'newhubusername@test.com';
            update hubAccountBefore;

            Test.setMock(HttpCalloutMock.class, new AWSCalloutMock());
        Test.stopTest();    

        List<Integration_Log__c> integrationLogList = [SELECT Id FROM Integration_Log__c];
        System.assert(integrationLogList.size() > 0);
    }

    @isTest
    static void test_HubUsernameUpdateCalloutFailure() {
        Test.startTest();
        Hub_Account__c hubAccountBefore = [SELECT Id, Student__c FROM Hub_Account__c WHERE Hub_Username__c = 'john2@john.com' LIMIT 1];
            hubAccountBefore.BPP_Requested_Hub_Username__c = 'john@john.com';
            update hubAccountBefore;

            Test.setMock(HttpCalloutMock.class, new AWSCalloutMock());
        Test.stopTest();    

        Hub_Account__c hubAccountAfter = [
            SELECT Hub_Username__c, BPP_Requested_Hub_Username__c, BPP_Username_Update_Status__c, BPP_Username_Error_Message__c FROM Hub_Account__c WHERE Student__c =: hubAccountBefore.Student__c LIMIT 1
        ];
        System.assertEquals('john2@john.com', hubAccountAfter.Hub_Username__c, 'Hub Username value should not have changed');
        System.assertEquals(null, hubAccountAfter.BPP_Requested_Hub_Username__c, 'Requested Hub Username value should still be null');
        System.assertEquals('Error', hubAccountAfter.BPP_Username_Update_Status__c, 'Username Update Status value should equal "Error"');
        System.assert(hubAccountAfter.BPP_Username_Error_Message__c.contains('is present on an existing Hub Account record'));

        List<Integration_Log__c> integrationLogList = [SELECT Id FROM Integration_Log__c];
        System.assert(integrationLogList.size() == 0);
    }
}