salesforce-main/src/main/default/objects/Authorisation_Token__c/Authorisation_Token__c.object-meta.xml
<CustomObject>
    <label>Authorisation Token</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisation Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Authorisation_Token__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Authorisation_Token__c/fields/Authorisation_Type__c.field-meta.xml
<CustomField>
    <fullName>Authorisation_Type__c</fullName>
    <label>Authorisation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BPP API Gateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Authorisation_Token__c/fields/Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Expires_In__c</fullName>
    <label>Expires In</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/objects/Authorisation_Token__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/OAuthTokenRetriever.cls
global with sharing class OAuthTokenRetriever {
    /**
     * The named credential associated with events api
     */
    @TestVisible
    private String endpoint {
        get {
            System.Domain domain = System.DomainParser.parse(URL.getOrgDomainUrl());

            if (!String.isEmpty(domain.getSandboxName())) {
                return 'callout:OAuth_Test';
            } else {
                return 'callout:OAuth';
            }
        }
    }

    public Map<String, Authorisation_Token__c> getNewAccessToken() {
        Map<String, Authorisation_Token__c> accessTokenMap = new Map<String, Authorisation_Token__c>();
        Authorisation_Token__c authToken = new Authorisation_Token__c();
        String response;

        HttpRequest httpRequest = createRequest();
        try {
            Http http = new Http();
            HttpResponse httpResponse = http.send(httpRequest);
            Map<String, Object> respMap = (Map<String, Object>) JSON.deserializeUntyped(httpResponse.getBody());
            if (httpResponse.getStatusCode() == 200) {
                authToken.Access_Token__c = (String) respMap.get('access_token');
                authToken.Expires_In__c = (Integer) respMap.get('expires_in');
                authToken.Scope__c = (String) respMap.get('scope');
                authToken.Authorisation_Type__c = 'BPP API Gateway';
                accessTokenMap.put(httpResponse.getBody(), authToken);
            } else {
                response = 'Error: ' + (String) respMap.get('error') + ' - ' + (String) respMap.get('error_description');
                accessTokenMap.put(response, null);
            }
        } catch (Exception e) {
            response = 'Error: [' + e.getLineNumber() + '] ' + e.getMessage();
            accessTokenMap.put(response, null);
        }

        return accessTokenMap;
    }

    /**
     * Creates an HTTP request with the necessary parameters for client credentials grant type authentication.
     *
     * @return An HTTP request object configured with the endpoint, method, headers and payload.
     */
    private HttpRequest createRequest() {
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setEndpoint(endpoint);
        httpRequest.setMethod('POST');
        httpRequest.setHeader('Content-Type', 'application/x-www-form-urlencoded');

        String payload =
            'grant_type=client_credentials' +
            '&client_id={!$Credential.OAuth.ClientId}' +
            '&client_secret={!$Credential.OAuth.ClientSecret}' +
            '&audience={!$Credential.OAuth.Audience}';
        httpRequest.setBody(payload);

        return httpRequest;
    }
}