salesforce-main/src/main/default/objects/Contact/fields/Other_Email__c.field-meta.xml
<CustomField>
    <fullName>Other_Email__c</fullName>
    <description>Other email address of student.  As preferred email address is required when adding an email address,  this field can be used when  the email address type is unknown.</description>
    <label>Other Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email__c</fullName>
    <description>Personal email address of student.</description>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>Student&apos;s work email address.</description>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Phone__c</fullName>
    <description>Student&apos;s work phone number.</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/recordTypes/BD_Contact.recordType-meta.xml
<RecordType>
    <fullName>BD_Contact</fullName>
    <active>true</active>
    <description>Business development contact for B2B relationships.</description>
    <label>Business Development Contact</label>
</RecordType>

salesforce-main/src/main/default/classes/DedupeContact.cls
/************************************************************************
 Name:  DedupeContact
========================================================================
Purpose: REST call to check if Contact exists using dedupe rules
========================================================================
History                                                                
VERSION    AUTHOR             DATE              DETAIL                              
1.0      David Lovejoy     19/03/2020      INITIAL DEVELOPMENT   
************************************************************************/

@RestResource(urlMapping='/v1.0/DedupeContact/*')
global with sharing class DedupeContact {
    global class Response {
        public Response() {
        }
        public String contactId { get; set; }

        public Response(String contactId) {
            this.contactId = contactId;
        }
    }

    global class CheckContact {
        public String accountName;
        public String recordType;
        public String firstname;
        public String lastname;
        public String email;
        public String phone;
    }

    public static Contact createComparisonContact(CheckContact checkContact) {
        String recordType = DedupeHelper.verifyPostInput(checkContact.recordType);
        String accountName = DedupeHelper.verifyPostInput(checkContact.accountName);
        String firstname = DedupeHelper.verifyPostInput(checkContact.firstname);
        String lastname = DedupeHelper.verifyPostInput(checkContact.lastname);
        String email = DedupeHelper.verifyPostInput(checkContact.email);
        String phone = DedupeHelper.verifyPostInput(checkContact.phone);

        Contact contact = new Contact();
        contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
            .get('BD_Contact')
            .getRecordTypeId();
        contact.FirstName = firstname;
        contact.LastName = lastname;
        contact.Home_Email__c = email;
        contact.Other_Email__c = email;
        contact.Email = email;
        contact.Personal_Email__c = email;
        contact.Work_Email__c = email;
        contact.Phone = phone;
        contact.HomePhone = phone;
        contact.MobilePhone = phone;
        contact.OtherPhone = phone;
        contact.Work_Phone__c = phone;

        return contact;
    }

    @HttpPost
    global static Response doPost(CheckContact checkContact) {
        try {
            Id matchedContactId;

            Contact contact = createComparisonContact(checkContact);
            List<Contact> contactList = new List<Contact>{ contact };

            List<DuplicateHandler.MatchingRecord> matchingRecords = DuplicateFinder.findDuplicateRecords(contactList);
            if (matchingRecords.size() == 0) {
                return new Response('null');
            } else {
                matchedContactId = (matchingRecords.size() == 1
                    ? matchingRecords.get(0).matchingId
                    : DuplicateHandler.handleMatchingRecords(matchingRecords));
                return new Response(String.valueOf(matchedContactId));
            }
        } catch (Exception e) {
            return new Response('DedupeContact Error: [' + e.getLineNumber() + '] ' + e.getMessage());
        }
    }
}