salesforce-main/src/main/default/objects/Contact/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <description>Indicates the preferred email address of the student.  Must be populated if an email address is present on the student record.  Update the email field of the student every time the student record is saved based on the preferred selection.</description>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>BPP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>Student&apos;s work email address.</description>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/AuthorisedOn__c.field-meta.xml
<CustomField>
    <fullName>AuthorisedOn__c</fullName>
    <description>The datetime that the application was moved into Acceptance, used in applicationStageChange event</description>
    <label>AuthorisedOn</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Bypass_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass_Validation_Rule</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact that is used to identify the Line Manager for Application requests</description>
    <label>Line Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Line Manager can&apos;t be a Student Account</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Line Manager)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/ApplicationStageSyncTest.cls
@isTest
private class ApplicationStageSyncTest {
    @TestSetup
    private static void setUp() {
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get('Student Account')
            .getRecordTypeId();
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName()
            .get('Apprentice Application')
            .getRecordTypeId();
        Id trainingManagerRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName()
            .get('Training Manager')
            .getRecordTypeId();
        Id oppApplicationRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
            .get('Student_Application')
            .getRecordTypeId();        

        Account account = new Account(
            RecordTypeId = accRecordTypeId,
            FirstName = 'Test',
            LastName = 'Tester',
            Salutation = 'Mr',
            Personal_Email__pc = 'test@bpp.com',
            Preferred_Email__pc = 'test@bpp.com'
        );

        insert account;

        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = 'Tester',
            Work_Email__c = 'test@bpp.com',
            Preferred_Email__c = 'Work',
            Email = 'test@bpp.com',
            RecordTypeId = trainingManagerRTId
        );

        insert contact;

        Opportunity opp = new Opportunity(
            RecordTypeId = oppRecordTypeId,
            AccountId = account.Id,
            Name = 'Test Opportunity',
            Application_Id__c = 'test-1234',
            Line_Manager__c = contact.Id,
            StageName = 'Application',
            CloseDate = Date.today() + 30
        );

        insert opp;

        Opportunity oppAppl = new Opportunity(
            RecordTypeId = oppApplicationRecordTypeId,
            AccountId = account.Id,
            Name = 'Test Opportunity',
            Application_Id__c = 'test-12345',
            Line_Manager__c = contact.Id,
            StageName = 'Unconditional Offer',
            CloseDate = Date.today() + 30
        );

        insert oppAppl;
    }

    @isTest
    private static void itShouldBuildTheCorrectPayloadAtLineManagerStage() {
        // GIVEN we have an opp at line manager review stage
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-1234'];

        opp.Bypass_Validation_Rule__c = true;
        opp.StageName = 'Line Manager Review';
        opp.BPP_Sub_Status__c = 'In Progress';
        update opp;

        // WHEN this is sent to the serializer
        Serializer serializer = new ApplicationStageSync();
        serializer.addRecord(opp);

        List<Map<String, Object>> payloads = serializer.serialize();
        Map<String, Object> payload = payloads[0];

        Assert.areEqual('LINE_MANAGER_REVIEW', payload.get('currentStage'));
        Assert.areEqual('IN_PROGRESS', payload.get('currentStageStatus'));

        Map<String, Object> lineManager = (Map<String, Object>) payload.get('lineManager');

        // THEN I expect it to build the correct payload
        Assert.areEqual('test-1234', payload.get('applicationId'));
        Assert.areEqual('Tester', lineManager.get('lastName'));
        Assert.areEqual('test@bpp.com', lineManager.get('email'));
    }

    @isTest
    private static void itShouldBuildTheCorrectPayloadAtAcceptance() {
        // GIVEN we have an opp at Acceptance stage
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-1234'];

        opp.Bypass_Validation_Rule__c = true;
        opp.StageName = 'Acceptance';
        opp.BPP_Sub_Status__c = 'Completed';
        opp.AuthorisedOn__c = Datetime.now();
        update opp;

        // WHEN this is sent to the serializer
        Serializer serializer = new ApplicationStageSync();
        serializer.addRecord(opp);

        List<Map<String, Object>> payloads = serializer.serialize();
        Map<String, Object> payload = payloads[0];
        Map<String, Object> data = (Map<String, Object>) payload.get('data');

        System.debug(payload);

        // THEN I expect it to
        Assert.areEqual('ACCEPTANCE', payload.get('currentStage'));
        Assert.areEqual('COMPLETED', payload.get('currentStageStatus'));
        Assert.isNotNull((DateTime) data.get('bppAuthorizedOn'));
    }

    @isTest
    private static void itShouldBuildTheCorrectPayloadAtStatusUnconOffer() {
        // GIVEN we have an opp at Unconditional Offer stage
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-12345'];

        opp.Bypass_Validation_Rule__c = true;
        opp.StageName = 'Unconditional Offer';
        update opp;

        // WHEN this is sent to the serializer
        Serializer serializer = new ApplicationStageSync();
        serializer.addRecord(opp);

        List<Map<String, Object>> payloads = serializer.serialize();
        Map<String, Object> payload = payloads[0];

        // THEN I expect it to
        Assert.areEqual('UNCONDITIONAL_OFFER', payload.get('currentStage'));
        Assert.areEqual('test-12345', payload.get('applicationId'));
    }
}