salesforce-main/src/main/default/objects/Application_Review__c/Application_Review__c.object-meta.xml
<CustomObject>
    <description>This object tracks reviews against Applications(Opportunities) and provides an audit including comments and reviewing users.</description>
    <label>Application Review</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Application Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The Application (Opportunity) that this review is related to</description>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Reviews</relationshipLabel>
    <relationshipName>Application_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Feedback_Required__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Feedback Required</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/ReviewFeedback.cls
public without sharing class ReviewFeedback implements Serializer {
    /**
     * A Set of Application Review ids to process
     */
    private Set<Id> reviewIds;

    /**
     * List of Application Ids related to the set of ids
     */
    private List<Application_Review__c> reviews;

    /**
     * Default Construct
     */
    public ReviewFeedback() {
        reviewIds = new Set<Id>();
        reviews = new List<Application_Review__c>();
    }

    /**
     * Adds the given record to the process list
     * @param record The sObject to add to the process list
     */
    public void addRecord(SObject record) {
        switch on record.getSObjectType().getDescribe().getName() {
            when 'Application_Review__c' {
                reviewIds.add(record.Id);
            }
        }
    }

    /**
     * Serializes the list of objects into events
     */
    public List<Map<String, Object>> serialize() {
        List<Map<String, Object>> payloads = new List<Map<String, Object>>();

        fetchReviews();

        for (Application_Review__c review : reviews) {
            Map<String, Object> payload = new Map<String, Object>{
                'applicationId' => review.Application__r.Application_Id__c,
                'currentStage' => 'BPP_REVIEW',
                'currentStageStatus' => 'AWAITING_INFORMATION',
                'applicantFeedback' => new Map<String, Object>{ 'updateRequiredDescription' => review.Comment__c }
            };

            payloads.add(payload);
        }

        return payloads;
    }

    /**
     * Fetch reviews from the given list where feedback is required
     */
    private void fetchReviews() {
        reviews = [
            SELECT Application__r.Application_ID__c, Comment__c
            FROM Application_Review__c
            WHERE Id IN :reviewIds AND Feedback_Required__c = TRUE
        ];
    }
}