salesforce-main/src/main/default/objects/Account/recordTypes/Business_Development_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Development_Account</fullName>
    <active>true</active>
    <description>Business development account for establishing B2B relationships.</description>
    <label>Business Development Account</label>
</RecordType>

salesforce-main/src/main/default/objects/Contact/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <description>Indicates the preferred email address of the student.  Must be populated if an email address is present on the student record.  Update the email field of the student every time the student record is saved based on the preferred selection.</description>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>BPP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Preferred_Phone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Phone__c</fullName>
    <description>Indicates the preferred phone number of the student.  Must be populated if a phone number is populated.  Preferred number is copied into the phone field every time a student record is updated.</description>
    <label>Preferred Phone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Parents/Guardian/Emergency</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>Student&apos;s work email address.</description>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Phone__c</fullName>
    <description>Student&apos;s work phone number.</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/recordTypes/BD_Contact.recordType-meta.xml
<RecordType>
    <fullName>BD_Contact</fullName>
    <active>true</active>
    <description>Business development contact for B2B relationships.</description>
    <label>Business Development Contact</label>
</RecordType>

salesforce-main/src/main/default/objects/Lead/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Preferred_Phone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Phone__c</fullName>
    <label>Preferred Phone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Parents/Guardian/Emergency</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/recordTypes/Business_Development.recordType-meta.xml
<RecordType>
    <fullName>Business_Development</fullName>
    <active>true</active>
    <businessProcess>Business Development</businessProcess>
    <description>Business_Development Lead</description>
    <label>Business Development</label>
</RecordType>

salesforce-main/src/main/default/objects/Lead/recordTypes/Prospective_Student.recordType-meta.xml
<RecordType>
    <fullName>Prospective_Student</fullName>
    <active>true</active>
    <businessProcess>Prospective Student</businessProcess>
    <description>Prospective Student</description>
    <label>Prospective Student</label>
</RecordType>

salesforce-main/src/main/default/classes/DuplicateHandlerTest.cls
@isTest
public class DuplicateHandlerTest {
    @testSetup
    static void makeData() {
        Account businessAccount = new Account(
            Name = 'Test BDAccount',
            Phone = '1234567890',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get('Business_Development_Account')
                .getRecordTypeId()
        );
        insert businessAccount;

        Contact businessContact = new Contact(
            AccountId = businessAccount.Id,
            FirstName = 'Test',
            LastName = 'BDContact',
            Work_Email__c = 'testbdcontact1@mail.invalid',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
                .get('BD_Contact')
                .getRecordTypeId()
        );
        insert businessContact;

        Lead businessLead = new Lead(
            FirstName = 'Test',
            LastName = 'BDLead',
            Company = 'TestBD',
            Preferred_Email__c = 'Work',
            Work_Email__c = 'testbdlead1@mail.invalid',
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                .get('Business_Development')
                .getRecordTypeId()
        );
        insert businessLead;

        Lead studentLead = new Lead(
            FirstName = 'Test',
            LastName = 'StudentLead',
            Preferred_Email__c = 'Work',
            Work_Email__c = 'testbdlead1@mail.invalid',
            Preferred_Phone__c = 'Work',
            Work_Phone__c = '+447798536743',
            RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                .get('Prospective_Student')
                .getRecordTypeId()
        );
        insert studentLead;

        Account studentAccount = new Account(
            FirstName = 'Test',
            LastName = 'Student',
            Preferred_Email__pc = 'Work',
            Work_Email__pc = 'teststudent1@mail.invalid',
            Preferred_Phone__pc = 'Mobile',
            PersonMobilePhone = '+447716123748',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get('Student_Account')
                .getRecordTypeId()
        );
        insert studentAccount;
    }

    @isTest
    private static void itShouldFindDuplicateLeadAndReturnMatchedId() {
        List<Lead> leadList = new List<Lead>();
        leadList.add(
            new Lead(
                FirstName = 'Test',
                LastName = 'BDLead',
                Company = 'TestBD',
                Preferred_Email__c = 'Work',
                Work_Email__c = 'TestBD',
                RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
                    .get('Business_Development')
                    .getRecordTypeId()
            )
        );
        List<DuplicateHandler.MatchingRecord> matchingRecords = DuplicateFinder.findDuplicateRecords(leadList);
        System.assert(matchingRecords.size() > 0, 'List should contain matching Lead record.');
        System.assertEquals(
            'Lead',
            matchingRecords.get(0).sObjectType,
            'Matched record sObjectType should equal "Lead".'
        );

        Lead existingLead = [SELECT Id FROM Lead LIMIT 1];
        System.assertEquals(
            existingLead.Id,
            matchingRecords.get(0).matchingId,
            'Matched record Id should match previously inserted Lead.'
        );
    }

    @isTest
    private static void itShouldFindDuplicateStudentsAndReturnMatchedId() {
        Account existingAccount = [
            SELECT
                Id,
                FirstName,
                LastName,
                PersonMobilePhone,
                Preferred_Email__pc,
                Preferred_Phone__pc,
                Work_Email__pc,
                RecordTypeId
            FROM Account
            WHERE IsPersonAccount = TRUE
            LIMIT 1
        ];

        Account newAccount = new Account();
        newAccount.FirstName = existingAccount.FirstName;
        newAccount.LastName = existingAccount.LastName;
        newAccount.Preferred_Email__pc = existingAccount.Preferred_Email__pc;
        newAccount.Work_Email__pc = existingAccount.Work_Email__pc;
        newAccount.Preferred_Phone__pc = existingAccount.Preferred_Phone__pc;
        newAccount.PersonMobilePhone = existingAccount.PersonMobilePhone;
        newAccount.RecordTypeId = existingAccount.RecordTypeId;

        Database.DMLOptions dbDML = new Database.DMLOptions();
        dbDML.DuplicateRuleHeader.allowSave = true;
        Database.insert(newAccount, dbDML);

        Account dupeAccount = new Account();
        dupeAccount.FirstName = existingAccount.FirstName;
        dupeAccount.LastName = existingAccount.LastName;
        dupeAccount.Preferred_Email__pc = existingAccount.Preferred_Email__pc;
        dupeAccount.Work_Email__pc = existingAccount.Work_Email__pc;
        dupeAccount.Preferred_Phone__pc = existingAccount.Preferred_Phone__pc;
        dupeAccount.PersonMobilePhone = existingAccount.PersonMobilePhone;
        dupeAccount.RecordTypeId = existingAccount.RecordTypeId;
        List<Account> accountList = new List<Account>();
        accountList.add(dupeAccount);

        List<DuplicateHandler.MatchingRecord> matchingRecords = DuplicateFinder.findDuplicateRecords(accountList);
        System.assert(matchingRecords.size() > 0, 'List should contain matching Student records.');

        Id winningId = DuplicateHandler.handleMatchingRecords(matchingRecords);

        Account lastModifiedAccount = [
            SELECT Id
            FROM Account
            WHERE IsPersonAccount = TRUE
            ORDER BY LastModifiedDate DESC
            LIMIT 1
        ];
        System.assertEquals(
            lastModifiedAccount.Id,
            winningId,
            'Id should have returned existing Student with most recent LastModifiedDate.'
        );
    }

    @isTest
    private static void itShouldFindDuplicateStudentAndReturnMatchedId() {
        List<Account> accountList = new List<Account>();
        accountList.add(
            new Account(
                FirstName = 'Test',
                LastName = 'Student',
                Preferred_Email__pc = 'Work',
                Work_Email__pc = 'teststudent1@mail.invalid',
                Preferred_Phone__pc = 'Mobile',
                PersonMobilePhone = '+447716123748',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                    .get('Student_Account')
                    .getRecordTypeId()
            )
        );
        List<DuplicateHandler.MatchingRecord> matchingRecords = DuplicateFinder.findDuplicateRecords(accountList);
        System.assert(matchingRecords.size() > 0, 'List should contain matching Student record.');
        System.assertEquals(
            'Student',
            matchingRecords.get(0).sObjectType,
            'Matched record sObjectType should equal "Student".'
        );

        Account existingAccount = [SELECT Id FROM Account WHERE IsPersonAccount = TRUE LIMIT 1];
        System.assertEquals(
            existingAccount.Id,
            matchingRecords.get(0).matchingId,
            'Matched record Id should match previously inserted Account.'
        );
    }

    @isTest
    private static void itShouldHandleUpgradeCategoryAndReturnMatchedId() {
        Lead existingLead = [
            SELECT
                Id,
                FirstName,
                LastName,
                Preferred_Email__c,
                Work_Email__c,
                Preferred_Phone__c,
                Work_Phone__c,
                RecordTypeId
            FROM Lead
            WHERE LastName = 'StudentLead'
            LIMIT 1
        ];

        Lead newLead = new Lead();
        newLead.FirstName = existingLead.FirstName;
        newLead.LastName = existingLead.LastName;
        newLead.Preferred_Email__c = existingLead.Preferred_Email__c;
        newLead.Work_Email__c = existingLead.Work_Email__c;
        newLead.Preferred_Phone__c = existingLead.Preferred_Phone__c;
        newLead.Work_Phone__c = existingLead.Work_Phone__c;
        newLead.RecordTypeId = existingLead.RecordTypeId;

        Database.DMLOptions dbDML = new Database.DMLOptions();
        dbDML.DuplicateRuleHeader.allowSave = true;
        Database.insert(newLead, dbDML);

        Lead dupeLead = new Lead();
        dupeLead.FirstName = existingLead.FirstName;
        dupeLead.LastName = existingLead.LastName;
        dupeLead.Preferred_Email__c = existingLead.Preferred_Email__c;
        dupeLead.Work_Email__c = existingLead.Work_Email__c;
        dupeLead.Preferred_Phone__c = existingLead.Preferred_Phone__c;
        dupeLead.Work_Phone__c = existingLead.Work_Phone__c;
        List<Lead> leadList = new List<Lead>();
        leadList.add(dupeLead);

        List<DuplicateHandler.MatchingRecord> matchingRecords = DuplicateFinder.findDuplicateRecords(leadList);
        for (DuplicateHandler.MatchingRecord mr : matchingRecords) {
            mr.category = 'Silver';
        }
        System.assert(matchingRecords.size() > 0, 'List should contain matching Lead records.');

        Id winningId = DuplicateHandler.handleMatchingRecords(matchingRecords);

        Lead lastModifiedLead = [SELECT Id FROM Lead ORDER BY LastModifiedDate DESC LIMIT 1];
        System.assertEquals(
            lastModifiedLead.Id,
            winningId,
            'Id should have returned existing Lead with most recent LastModifiedDate.'
        );
    }
}