salesforce-main/src/main/default/objects/Application_Audit__c/Application_Audit__c.object-meta.xml
<CustomObject>
    <description>An object that keeps track of who updates an application and its surrounding objects and when</description>
    <label>Application Audit</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Application Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Audit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related application</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Audits</relationshipLabel>
    <relationshipName>Application_Audits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Audit__c/fields/Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Updated_By__c</fullName>
    <description>The name of the user who triggered the update ie Student or Line manager&apos;s name</description>
    <label>Updated By</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/Application_Review__c.object-meta.xml
<CustomObject>
    <description>This object tracks reviews against Applications(Opportunities) and provides an audit including comments and reviewing users.</description>
    <label>Application Review</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Application Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The Application (Opportunity) that this review is related to</description>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Reviews</relationshipLabel>
    <relationshipName>Application_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/External_Document__c.object-meta.xml
<CustomObject>
    <label>External Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/External_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Document ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>External Documents</relationshipLabel>
    <relationshipName>External_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>External Documents</relationshipLabel>
    <relationshipName>External_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION_HISTORY</fullName>
                <label>Education History</label>
            </value>
            <value>
                <fullName>GENERAL</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>Name Changed</fullName>
            </value>
            <value>
                <fullName>Application Pack</fullName>
            </value>
            <value>
                <fullName>letter</fullName>
                <label>Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/KSB__c/KSB__c.object-meta.xml
<CustomObject>
    <description>Self Assessment KSBs (Knowledge, Skills, Behaviours)</description>
    <label>KSB</label>
    <nameField>
        <displayFormat>KSB-{0000}</displayFormat>
        <label>KSB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KSBs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/KSB__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>A numeric value based on the users ability corresponding to the question (ranging 1 - 4 - Weakest/Strongest)</description>
    <label>Answer</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/KSB__c/fields/Experience_Information__c.field-meta.xml
<CustomField>
    <fullName>Experience_Information__c</fullName>
    <label>Experience Information</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/KSB__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>The application related to the KSB</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>KSBs</relationshipLabel>
    <relationshipName>KSBs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/KSB__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cancellation_Reason__c</fullName>
    <description>Cancellation Reason field to be mandatory if Status is set to Cancelled or Declined on Student Application Opportunity</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unable to fund the programme</fullName>
            </value>
            <value>
                <fullName>Change of profession</fullName>
            </value>
            <value>
                <fullName>Taken up a job</fullName>
            </value>
            <value>
                <fullName>Gone to a competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Failed previous qualification</fullName>
            </value>
            <value>
                <fullName>Location/Mode not available</fullName>
            </value>
            <value>
                <fullName>Family Emergency</fullName>
            </value>
            <value>
                <fullName>VISA/CAS/EU Delay</fullName>
            </value>
            <value>
                <fullName>Prefer not to say</fullName>
            </value>
            <value>
                <fullName>VISA Refusal</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>CAS requirement not met</fullName>
            </value>
            <value>
                <fullName>Academic/English entry not met</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Chosen to study at another BPP location</fullName>
            </value>
            <value>
                <fullName>Chosen to study another BPP programme</fullName>
            </value>
            <value>
                <fullName>appMissedDeadline</fullName>
                <label>Failed to submit application before deadline</label>
            </value>
            <value>
                <fullName>appWithdrawApplicant</fullName>
                <label>Learner withdrawn</label>
            </value>
            <value>
                <fullName>appNoResponseApplicant</fullName>
                <label>No response from applicant</label>
            </value>
            <value>
                <fullName>appNoResponseEmployer</fullName>
                <label>No response from employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedEmployer</fullName>
                <label>Cancelled due to change of employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedProgramme</fullName>
                <label>Change of programme</label>
            </value>
            <value>
                <fullName>appRejectIneligibleResidency</fullName>
                <label>Ineligible status (Residency)</label>
            </value>
            <value>
                <fullName>appRejectIneligibleVisa</fullName>
                <label>Ineligible status (VISA)</label>
            </value>
            <value>
                <fullName>appRejectRoleOnboarding</fullName>
                <label>Job role does not match criteria (Onboarding)</label>
            </value>
            <value>
                <fullName>appRejectRoleHop</fullName>
                <label>Job role does not match criteria (Hop)</label>
            </value>
            <value>
                <fullName>appRejectOverqualified</fullName>
                <label>Applicant is not suitable for selected programme</label>
            </value>
            <value>
                <fullName>appRejectFundingIssue</fullName>
                <label>Application has a funding issue</label>
            </value>
            <value>
                <fullName>appNotEligible</fullName>
                <label>Not Eligible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventWithdrewProcessorTest.cls
@isTest
public class EventWithdrewProcessorTest {
    private static Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Student_Account')
        .getRecordTypeId();

    private static Id apprenticeRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Apprentice_Application')
        .getRecordTypeId();

    private static Id applicationRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Student_Application')
        .getRecordTypeId();

    private static Id interestRecordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Student_Interest')
        .getRecordTypeId();

    @TestSetup
    private static void setup() {
        Account acc = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);
        insert acc;

        List<Opportunity> opps = new List<Opportunity>{
            new Opportunity(
                RecordTypeId = apprenticeRecordType,
                name = 'Test Apprentice Application',
                Application_Id__c = 'test-1234',
                accountid = acc.Id,
                StageName = 'Application',
                CloseDate = Date.today()
            ),
            new Opportunity(
                RecordTypeId = applicationRecordType,
                name = 'Test Application',
                Application_Id__c = 'test-1235',
                accountid = acc.Id,
                StageName = 'Application',
                CloseDate = Date.today()
            ),
            new Opportunity(
                RecordTypeId = interestRecordType,
                name = 'Test Interest',
                Application_Id__c = 'test-1236',
                accountid = acc.Id,
                StageName = 'Application Started',
                CloseDate = Date.today()
            )
        };

        insert opps;
    }

    @isTest
    private static void itShouldUpdateTheOppToWithdrawn() {
        List<String> appIdsToTest = new List<String>{ 'test-1234', 'test-1235', 'test-1236' };
        List<Queue_Job__c> jobs = new List<Queue_Job__c>();

        for (String applicationId : appIdsToTest) {
            ApplicationWithdrewSchema schema = new ApplicationWithdrewSchema();
            schema.applicationId = applicationId;

            jobs.add(new Queue_Job__c(Job_Content__c = JSON.serialize(schema), Event_Time__c = DateTime.now()));
        }

        //WHEN the event processor is run
        System.Test.startTest();

        EventWithdrewProcessor processor = new EventWithdrewProcessor();
        processor.processImpl(jobs);

        System.Test.stopTest();

        // THEN the queue jobs are successful
        Assert.areEqual(3, processor.successfulJobs.size(), 'Expected 3 successful jobs');
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        Integer updatedOpps = 0;
        // AND the field values have been updated
        for (Opportunity oppAfter : [
            SELECT StageName, BPP_Sub_Status__c, BPP_Cancellation_Reason__c, recordType.DeveloperName
            FROM Opportunity
            WHERE Application_ID__c IN :appIdsToTest
        ]) {
            switch on oppAfter.recordType.DeveloperName {
                when 'Apprentice_Application' {
                    Assert.areEqual('Closed Lost', oppAfter.StageName, 'Stage should be closed lost');
                    Assert.areEqual('Withdrawn', oppAfter.BPP_Sub_Status__c, 'Sub-Stage should be withdrawn');
                    Assert.areEqual(
                        'appWithdrawApplicant',
                        oppAfter.BPP_Cancellation_Reason__c,
                        'Reason should be appWithdrawApplicant'
                    );
                    updatedOpps++;
                }
                when 'Student_Application' {
                    Assert.areEqual('Cancelled', oppAfter.StageName, 'Stage should be Cancelled');
                    Assert.areEqual('Withdrawn', oppAfter.BPP_Sub_Status__c, 'Sub-Stage should be withdrawn');
                    updatedOpps++;
                }
                when 'Student_Interest' {
                    Assert.areEqual('No Longer Interested', oppAfter.StageName, 'Stage should be No Longer Interested');
                    Assert.areEqual('Withdrawn', oppAfter.BPP_Sub_Status__c, 'Sub-Stage should be withdrawn');
                    updatedOpps++;
                }
            }
        }
        Assert.areEqual(3, updatedOpps);
    }

    @isTest
    private static void itShouldFailWithInvalidApp() {
        ApplicationWithdrewSchema schema = new ApplicationWithdrewSchema();
        schema.applicationId = 'test-fail';

        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Content__c = JSON.serialize(schema),
            Event_Time__c = DateTime.now()
        );

        //WHEN the event processor is run
        System.Test.startTest();

        EventWithdrewProcessor processor = new EventWithdrewProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN the queue job is unsuccessful
        Assert.areEqual(0, processor.successfulJobs.size(), 'Expected no successful jobs');
        Assert.areEqual(1, processor.failedJobs.size(), 'Expected one failed job');
    }

    @isTest
    private static void itShouldDeleteLinkedRecords() {
        // GIVEN a schema
        ApplicationWithdrewSchema schema = new ApplicationWithdrewSchema();
        schema.applicationId = 'test-1234';

        Opportunity existingOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // AND and Opportunity with some KSBs
        insert new List<KSB__c>{
            new KSB__c(
                Code__c = 'ksb-1',
                Question__c = 'ksb-1',
                Answer__c = '1',
                Experience_Information__c = 'ksb 1',
                Opportunity__c = existingOpp.Id
            ),
            new KSB__c(
                Code__c = 'ksb-2',
                Question__c = 'ksb-2',
                Answer__c = '2',
                Experience_Information__c = 'ksb 2',
                Opportunity__c = existingOpp.Id
            )
        };

        // AND some external documents
        insert new List<External_Document__c>{
            new External_Document__c(
                Type__c = 'GENERAL',
                Category__c = '1',
                Document_ID__c = '1',
                Opportunity__c = existingOpp.Id
            ),
            new External_Document__c(
                Type__c = 'GENERAL',
                Category__c = '2',
                Document_ID__c = '2',
                Opportunity__c = existingOpp.Id
            )
        };

        // AND some application audits
        insert new List<Application_Audit__c>{
            new Application_Audit__c(
                Updated_By__c = 'Test 1',
                Opportunity__c = existingOpp.Id,
                Event_Date__c = DateTime.Now()
            ),
            new Application_Audit__c(
                Updated_By__c = 'Test 2',
                Opportunity__c = existingOpp.Id,
                Event_Date__c = DateTime.Now()
            )
        };

        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Content__c = JSON.serialize(schema),
            Event_Time__c = DateTime.now()
        );

        //WHEN the event processor is run
        System.Test.startTest();

        EventWithdrewProcessor processor = new EventWithdrewProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        System.Test.stopTest();

        // THEN the queue job is unsuccessful
        Assert.areEqual(1, processor.successfulJobs.size(), 'Expected 1 successful job');

        // AND all of the records should have been deleted
        Opportunity oppResults = [
            SELECT
                (SELECT Id FROM KSBs__r),
                (SELECT Id FROM External_Documents__r),
                (SELECT Id FROM Application_Reviews__r)
            FROM Opportunity
            LIMIT 1
        ];

        Assert.areEqual(0, oppResults.KSBs__r.size(), 'Expected 0 KSBs');
        Assert.areEqual(0, oppResults.External_Documents__r.size(), 'Expected 0 External Docs');
        Assert.areEqual(0, oppResults.Application_Reviews__r.size(), 'Expected 0 Application Reviews');
    }
}