salesforce-main/src/main/default/objects/AssignmentUsers__c/AssignmentUsers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A collection of users that can be referenced for record assignment and triggers</description>
    <label>AssignmentUsers</label>
</CustomObject>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_Admissions_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Admissions_Owner__c</fullName>
    <description>Id of Admissions user records will be assigned to. This will trigger the round robin assignment</description>
    <label>Default Admissions Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_BES_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_BES_Owner__c</fullName>
    <description>Default Business Engagement Specialist owner</description>
    <inlineHelpText>Default Business Engagement Specialist owner user id (15 digit Id)</inlineHelpText>
    <label>Default BES Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Lead_Owner__c</fullName>
    <description>Id of the user leads will be assigned to by default (QC Team). This will trigger the round robin assignment</description>
    <inlineHelpText>Default lead owner user id (15 digit Id)</inlineHelpText>
    <label>Default Lead Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_Sales_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Sales_Owner__c</fullName>
    <description>Id of Sales user records will be assigned to. This will trigger the round robin assignment</description>
    <label>Default Sales Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/UserHelper.cls
public class UserHelper {
    public static Set<Id> createUserExclusionSet() {
        List<String> userIdList = Label.IntegrationUserIds.split(';');
        Set<Id> integrationUserIds = new Set<Id>();
        for (String userId : userIdList) {
            integrationUserIds.add(userId);
        }
        return integrationUserIds;
    }

    public static Set<Id> defaultAccountOpportunityUserIdSet() {
        Set<Id> defaultAccountOpportunityUserIdSet = new Set<Id>{
            AssignmentUsers__c.getInstance().Default_Admissions_Owner__c, 
            AssignmentUsers__c.getInstance().Default_Sales_Owner__c
        };
        return defaultAccountOpportunityUserIdSet;
    }
    
    public static Set<Id> defaultLeadUserIdSet() {
        Set<Id> defaultLeadUserUserIdSet = new Set<Id>{
            AssignmentUsers__c.getInstance().Default_Lead_Owner__c, 
            AssignmentUsers__c.getInstance().Default_BES_Owner__c
        };
        return defaultLeadUserUserIdSet;
    }

    public static String obtainReassignmentSourceRole(Id userId) {
        String sourceRole;
        if (userId == AssignmentUsers__c.getInstance().Default_Admissions_Owner__c) {
            sourceRole = 'Admissions Mgmt';
        } else if (userId == AssignmentUsers__c.getInstance().Default_Sales_Owner__c) {
            sourceRole = 'Sales Mgmt';
        } else if (userId == AssignmentUsers__c.getInstance().Default_Lead_Owner__c) {
            sourceRole = 'Qualifying Centre Mgmt';
        } else if (userId == AssignmentUsers__c.getInstance().Default_BES_Owner__c) {
            sourceRole = 'Business Engagement Specialists';
        }
        return sourceRole;
    }

    /*public static void handleUserRoundRobinReassignment(Map<Id, User> oldMap, Map<Id, User> newMap) {
        Set<Id> userIdsToReassign = new Set<Id>();
        for (User newUser : newMap.values()) {
            User oldUser = oldMap.get(newUser.Id);
            if ((oldUser.IsActive && !newUser.IsActive)) {
                userIdsToReassign.add(newUser.Id);
            }
        }
        System.debug(userIdsToReassign);
        if (userIdsToReassign.size() > 0) {
            RoundRobinHandler.reassignRecords(userIdsToReassign);
        }
    }*/

    public static String getOrgName() {
        String orgId = UserInfo.getOrganizationId();
        String orgName;
        switch on orgId {
            when '00Dg0000006TAA8EAO' {
                orgName = 'DEV: ';
            }
            when '00Dg0000006S5LREA0' {
                orgName = 'QA: ';
            }
            when '00Dg000000066hpEAA' {
                orgName = 'UAT: ';
            }
            when '00Db0000000Z8FREA0' {
                orgName = 'Production: ';
            }
            when else {
                orgName = orgId + ': ';
            }
        }
        return orgName;
    }
}