salesforce-main/src/main/default/objects/AssignmentUsers__c/AssignmentUsers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A collection of users that can be referenced for record assignment and triggers</description>
    <label>AssignmentUsers</label>
</CustomObject>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_Admissions_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Admissions_Owner__c</fullName>
    <description>Id of Admissions user records will be assigned to. This will trigger the round robin assignment</description>
    <label>Default Admissions Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Lead_Owner__c</fullName>
    <description>Id of the user leads will be assigned to by default (QC Team). This will trigger the round robin assignment</description>
    <inlineHelpText>Default lead owner user id (15 digit Id)</inlineHelpText>
    <label>Default Lead Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/RoundRobinHandlerTest.cls
@isTest
public class RoundRobinHandlerTest {
    @testSetup
    static void testSetup() {
        String ownerId = UserInfo.getUserId().left(15);
        AssignmentUsers__c assignmentUser = new AssignmentUsers__c();
        assignmentUser.Default_Lead_Owner__c = ownerId;
        assignmentUser.Default_Admissions_Owner__c = ownerId;
        insert assignmentUser;
        
        Id userId = [SELECT Id FROM User WHERE UserRole.Name = 'BD Sales User' AND IsActive = true ORDER BY Name LIMIT 1].Id;
        Id userId2 = [SELECT Id FROM User WHERE UserRole.Name = 'Domestic Team [+Record Assignment]' AND IsActive = true ORDER BY Name LIMIT 1].Id;
        Id userId3 = [SELECT Id FROM User WHERE UserRole.Name = 'QC' AND IsActive = true ORDER BY Name LIMIT 1].Id;
        
        List<Owner_Assignment__c> ownerAssignmentList = new List<Owner_Assignment__c>();
        ownerAssignmentList.add(new Owner_Assignment__c(Name = 'BD Sales User', Last_Assignee__c = userId));
        ownerAssignmentList.add(new Owner_Assignment__c(Name = 'Domestic Team [+Record Assignment]', Last_Assignee__c = userId2));
        ownerAssignmentList.add(new Owner_Assignment__c(Name = 'QC', Last_Assignee__c = userId3));
        insert ownerAssignmentList;

        Database.DMLOptions dbDML = new Database.DMLOptions(); 
        dbDML.DuplicateRuleHeader.allowSave = true;
        dbDML.DuplicateRuleHeader.runAsCurrentUser = true;

        List<Account> accountList = new List<Account>();
        for (Integer i = 0; i < 2; i++) {
            accountList.add(new Account(Name = 'Account ' + i, OwnerId = userId, RecordTypeId = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId()));
        }
        Database.insert(accountList, dbDML);

        List<Opportunity> opportunityList = new List<Opportunity>();
        for (Integer i = 0; i < 2; i++) {
            opportunityList.add(new Opportunity(AccountId = accountList.get(i).Id, CloseDate = System.today(), Name = 'Opportunity ' + i, OwnerId = userId, RecordTypeId = Schema.Sobjecttype.Opportunity.getRecordTypeInfosByName().get('Business Development').getRecordTypeId(), StageName = 'Quoting', BPP_Sub_Status__c = 'Other'));
        }
        Database.insert(opportunityList, dbDML);

        List<Lead> leadList = new List<Lead>();
        for (Integer i = 0; i < 2; i++) {
            leadList.add(new Lead(Company = 'TestCompany', FirstName = 'Test', LastName = 'Lead ' + i, OwnerId = userId, RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Business Development').getRecordTypeId(), Status = 'New'));
        }
        Database.insert(leadList, dbDML);
    }
    
    @isTest
    static void test_reassignRecords_RecordChange() {
        String defaultLeadOwner = AssignmentUsers__c.getInstance().Default_Lead_Owner__c;
        String defaultOwner = AssignmentUsers__c.getInstance().Default_Admissions_Owner__c;
        
        Account account = [SELECT Id, OwnerId FROM Account LIMIT 1];
        account.OwnerId = defaultOwner;
        update account;
        
        Opportunity opportunity = [SELECT Id, OwnerId FROM Opportunity LIMIT 1];
        opportunity.OwnerId = defaultOwner;
        update opportunity;
        
        Lead lead = [SELECT Id, OwnerId FROM Lead LIMIT 1];
        lead.OwnerId = defaultLeadOwner;
        update lead;
        
        Account accountAfter = [SELECT OwnerId FROM Account WHERE Id =: account.Id LIMIT 1];
        Opportunity opportunityAfter = [SELECT OwnerId FROM Opportunity WHERE Id =: opportunity.Id LIMIT 1];
        Lead leadAfter = [SELECT OwnerId FROM Lead WHERE Id =: lead.Id LIMIT 1];
        System.assert(accountAfter.OwnerId != defaultOwner);
        System.assert(opportunityAfter.OwnerId != defaultOwner);
        System.assert(leadAfter.OwnerId != defaultLeadOwner);
    }
}