salesforce-main/src/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <description>Delivery object to track order items that need to be dispatched relating to either booking lines or order products (for LM only orders)</description>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DEL-{0000000}</displayFormat>
        <label>Delivery Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Delivery__c/fields/Added_To_Shortage__c.field-meta.xml
<CustomField>
    <fullName>Added_To_Shortage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Quantity has been added to stock shortage - used to ensure it is not counted more than once during multiple allocation attempts</description>
    <label>Added To Shortage</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Allocation_Date__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Date__c</fullName>
    <description>Timestamp when stock was allocated to the record</description>
    <label>Allocation Date</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Auto_Allocate__c.field-meta.xml
<CustomField>
    <fullName>Auto_Allocate__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When checked the delivery record will attempt to allocate stock when it is set to &apos;Awaiting Allocation&apos;, otherwise it will await assignment by other means.</description>
    <label>Auto Allocate</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <description>Status of delivery</description>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting Allocation</fullName>
                <default>true</default>
                <label>Awaiting Allocation</label>
            </value>
            <value>
                <fullName>Ready for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Sent for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Stock_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Stock_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows stock has been allocated for this delivery</description>
    <label>Stock Allocated</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Stock_Management__c.field-meta.xml
<CustomField>
    <fullName>Stock_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stock management record controlling the stock allocation for this delivery</description>
    <label>Stock Management</label>
    <referenceTo>Stock_Management__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>StockManagement</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/StockDeallocation.cls
public class StockDeallocation {
    @InvocableMethod(label='Deallocate Stock')
    public static List<StockAllocationHelper> getResult(List<String> idList) {
        List<StockAllocationHelper> resultList = deallocateStock(idList);
        return resultList;
    }
    
    private static List<StockAllocationHelper> deallocateStock(List<String> idList) {
        System.debug(idList);
        StockAllocationHelper response = new StockAllocationHelper();
        List<StockAllocationHelper> responseWrapper = new List<StockAllocationHelper>();
        List<Delivery__c> deliveryListToUpdate = new List<Delivery__c>();
        List<Stock_Management__c> stockManagementToUpdate = new List<Stock_Management__c>();
        Map<Delivery__c, Stock_Management__c> deliveryStockManagementMap = new Map<Delivery__c, Stock_Management__c>();

        try {
            deliveryStockManagementMap = DeliveryUtility.getStockAllocationRecords(idList);

            for (Delivery__c delivery : deliveryStockManagementMap.keyset()) {
                Stock_Management__c stockManagement = deliveryStockManagementMap.get(delivery);
                Decimal allocated = stockManagement.Allocated__c;
                Decimal quantity = delivery.Quantity__c;

                delivery.Added_To_Shortage__c = FALSE;
                delivery.Allocation_Date__c = NULL;
                delivery.Auto_Allocate__c = FALSE;
                delivery.Delivery_Status__c = 'Awaiting Allocation';
                delivery.Stock_Allocated__c = FALSE;
                allocated = allocated - quantity;
                stockManagement.Allocated__c = allocated;
                
                DeliveryUtility.updateDeliveryUpdateList(deliveryListToUpdate, delivery);
                DeliveryUtility.updateStockManagementUpdateList(stockManagementToUpdate, stockManagement);
                deliveryListToUpdate.add(delivery);
                stockManagementToUpdate.add(stockManagement);
                
                response.outputString = 'Success';
                responseWrapper.add(response);
            }

            if (deliveryListToUpdate.size() > 0) {
                update deliveryListToUpdate;
            }

            if (stockManagementToUpdate.size() > 0) {
                update stockManagementToUpdate;
            }
        } catch (Exception e) {
            response.outputString = 'Error: [' + e.getLineNumber() + '] | ' + e.getMessage();
            responseWrapper.add(response);
        }

        System.debug(responseWrapper);
        return responseWrapper;
    }
}