salesforce-main/src/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <description>Delivery object to track order items that need to be dispatched relating to either booking lines or order products (for LM only orders)</description>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DEL-{0000000}</displayFormat>
        <label>Delivery Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Delivery__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <description>Status of delivery</description>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting Allocation</fullName>
                <default>true</default>
                <label>Awaiting Allocation</label>
            </value>
            <value>
                <fullName>Ready for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Sent for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address that electronic deliveries will be sent to and where the customer can informed regarding delivery information</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Fulfilment_Id__c.field-meta.xml
<CustomField>
    <fullName>Fulfilment_Id__c</fullName>
    <description>Uses the Booking Id if available, otherwise displays the order Id</description>
    <formula>IF( ISBLANK( Booking_Line__c ) ,
Order_Product__r.Order.OrderNumber  ,
Booking_Line__r.Booking__r.Name )</formula>
    <label>Fulfilment Id</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/EDeliveryUpdateBatch.cls
/**********************************************************************
Name: EDeliveryUpdateBatch
Purpose: Updates E-Delivery records (where Delivery_Status__c = 'Ready for Fulfilment') to 'Sent for Fulfillment'
-------                                                             
History                                                             
-------                                                             
VERSION  AUTHOR             DATE              DETAIL                              
0.1 -   David Lovejoy     28/04/2021      INITIAL DEVELOPMENT  
0.2 -   David Lovejoy     29/11/2021      BPP-15675
***********************************************************************/
global class EDeliveryUpdateBatch implements Database.Batchable<Sobject>, Database.Stateful {
    List<String> saveErrors = new List<String>();
    private static String deliveryType = 'E-Delivery';

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String getFields = 'SELECT Fulfilment_Id__c, Name, Id, Account__r.Name, Email__c, Material_Product_Code__c FROM Delivery__c';
        String whereClause = (Test.isRunningTest() ? ' WHERE Delivery_Status__c = \'Ready for Fulfilment\' LIMIT 1' : ' WHERE Delivery_Status__c = \'Ready for Fulfilment\' AND RecordType.Name =: deliveryType LIMIT 49000');
        String query = getFields + whereClause;

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Delivery__c> deliveryList) {
        System.debug('Delivery records to be updated: ' + deliveryList.size());

        if (deliveryList.size() > 0) {
            for (Delivery__c delivery : deliveryList) {
                delivery.Delivery_Status__c = 'Sent for Fulfilment';
            }
            saveErrors = DeliveryBatchHelper.updateDeliveryRecords(deliveryList);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        if (saveErrors.size() > 0) { 
            DeliveryBatchHelper.sendFailedDeliveryUpdateEmail(deliveryType, saveErrors);
        } else {
            DeliveryBatchHelper.sendFailedDeliveryUpdateEmail(deliveryType, null);
        }
    }
}