salesforce-main/src/main/default/objects/Case/fields/Query_Id__c.field-meta.xml
<CustomField>
    <fullName>Query_Id__c</fullName>
    <description>The external ID from the website</description>
    <externalId>true</externalId>
    <inlineHelpText>The external ID from the website</inlineHelpText>
    <label>Query Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Query_Subtype__c</fullName>
    <label>Query Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Query_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Authorised Leave</fullName>
            </value>
            <value>
                <fullName>How do I access my EBook?</fullName>
            </value>
            <value>
                <fullName>How do I access my results and feedback</fullName>
            </value>
            <value>
                <fullName>How do I collect my ID card?</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from accessing my e-materials</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from studying</fullName>
            </value>
            <value>
                <fullName>I am in financial difficulty, what are my options?</fullName>
            </value>
            <value>
                <fullName>I am on Interruption of Studies and wish to extend</fullName>
            </value>
            <value>
                <fullName>I am taking an interruption of studies, how does that affect my payment plan and fees?</fullName>
            </value>
            <value>
                <fullName>I can&apos;t access my forum</fullName>
            </value>
            <value>
                <fullName>I can’t see my course within my online learning platform</fullName>
            </value>
            <value>
                <fullName>I have a different problem with my online learning</fullName>
            </value>
            <value>
                <fullName>I have a query about applying for Post Study Work/Graduate Route Visa</fullName>
            </value>
            <value>
                <fullName>I have a query about exemptions</fullName>
            </value>
            <value>
                <fullName>I have a query about inviting visitors to the UK</fullName>
            </value>
            <value>
                <fullName>I have a query about my attendance</fullName>
            </value>
            <value>
                <fullName>I have a query about my balance</fullName>
            </value>
            <value>
                <fullName>I have a query about my End Point Assessment</fullName>
            </value>
            <value>
                <fullName>I have a query about my submission</fullName>
            </value>
            <value>
                <fullName>I have a query about my timetable</fullName>
            </value>
            <value>
                <fullName>I have a question about my assessments feedback</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam arrangements</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam learning support</fullName>
            </value>
            <value>
                <fullName>I have a question about my graduation ceremony</fullName>
            </value>
            <value>
                <fullName>I have a question about my mock/assessment</fullName>
            </value>
            <value>
                <fullName>I have a question about my Oyster card</fullName>
            </value>
            <value>
                <fullName>I have a question about my results</fullName>
            </value>
            <value>
                <fullName>I have a question about my review/gate-way call</fullName>
            </value>
            <value>
                <fullName>I have a question about my student loan</fullName>
            </value>
            <value>
                <fullName>I have a question about my term dates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Type__c.field-meta.xml
<CustomField>
    <fullName>Query_Type__c</fullName>
    <label>Query Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assessments</fullName>
            </value>
            <value>
                <fullName>Attendance</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Changes to personal details</fullName>
            </value>
            <value>
                <fullName>Changes to studies</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Finance and Billing</fullName>
            </value>
            <value>
                <fullName>Graduation and Certificates</fullName>
            </value>
            <value>
                <fullName>IoS (Interruption of Studies)</fullName>
            </value>
            <value>
                <fullName>Letter requests</fullName>
            </value>
            <value>
                <fullName>My Apprenticeship</fullName>
            </value>
            <value>
                <fullName>My Course</fullName>
            </value>
            <value>
                <fullName>My Online Learning and The HUB</fullName>
            </value>
            <value>
                <fullName>My Study Materials</fullName>
            </value>
            <value>
                <fullName>Online learning</fullName>
            </value>
            <value>
                <fullName>Registration and enrolment</fullName>
            </value>
            <value>
                <fullName>Review Meeting</fullName>
            </value>
            <value>
                <fullName>Student Finance</fullName>
            </value>
            <value>
                <fullName>Student Loans</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Undetermined Query</fullName>
            </value>
            <value>
                <fullName>Prior Learning/Exemptions information</fullName>
            </value>
            <value>
                <fullName>Additional Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>School</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>Nursing</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Student)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/recordTypes/Student_Query.recordType-meta.xml
<RecordType>
    <fullName>Student_Query</fullName>
    <active>true</active>
    <businessProcess>Student Queries</businessProcess>
    <description>Case management for queries initiated by students.</description>
    <label>Student Query</label>
</RecordType>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventCaseProcessor.cls
/**
 * Processor for creating a Case data
 */
public class EventCaseProcessor extends BaseProcessor {
    @testVisible
    private static final string AUTH0_ID_ERROR = 'auth0Id does not exist in Salesforce.';

    @testVisible
    private static final string GENERIC_FAILURE = 'One or more jobs failed to process resulting in all jobs in the same batch failing. Please resolve.';

    private Map<Id, Queue_Job__c> queueJobIdToQueueJob = new Map<Id, Queue_Job__c>();
    private Map<String, CaseJobDetails> auth0IdsToJobDetails = new Map<String, CaseJobDetails>();
    private Map<String, Product2> identifierToProduct = new Map<String, Product2>();
    private Set<String> allProductIds = new Set<String>();
    private Set<String> allInstanceIds = new Set<String>();
    private Map<String, Hub_Account__c> auth0IdToHubAccount = new Map<String, Hub_Account__c>();
    private Map<String, Account> accountIdToAccount = new Map<String, Account>();
    private Set<String> allAuth0Ids = new Set<String>();

    // Maps containing records to be inserted or updated
    private Map<Id, Case> queueJobIdToCaseToInsert = new Map<Id, Case>();

    private Integer failedDMLCount = 0;
    private static final Integer RETRY_DML_COUNT_LIMIT = 1;

    /**
     * Update the Accounts linked to the given Queue Jobs with new personal information, including Addresses
     * @param  queueJobs jobs to be processed
     */
    public void processImpl(List<Queue_Job__c> queueJobs) {
        // Allow user case updated events
        StreamingService.allowedEvents.add('queryFormUpdated');

        // Extract data from Event, run initial validation, deduplicate and create more accessible data structures
        deserializeEvents(queueJobs);

        // Using data extracted above, create Account update and Address upsert records
        processSchemas();

        // Attempt to save the DML, removing invalid jobs and attempting to re-run *failedDMLCount* amount of times if there are any failures
        processRecordDML();
    }

    /**
     * Deserialize events on the given Queue Jobs into Schemas, validate for early issues and map into data structures
     * @param  queueJobs Queue Jobs being processed
     */
    void deserializeEvents(List<Queue_Job__c> queueJobs) {
        Map<Queue_Job__c, CaseJobDetails> jobsToSchema = new Map<Queue_Job__c, CaseJobDetails>();

        // Loop over all queue jobs, deserialize them and extract any details that are required for later processing
        for (Queue_Job__c queueJob : queueJobs) {
            CaseSchema event = (CaseSchema) JSON.deserialize(queueJob.Job_Content__c, CaseSchema.class);

            // Identify any required fields which are blank so we can fail the job
            List<String> requiredFieldErrors = new List<String>();
            checkRequiredFieldErrors(event, requiredFieldErrors);

            if (!requiredFieldErrors.isEmpty()) {
                failedJobs.put(
                    queueJob,
                    'Required value(s) ' + String.join(requiredFieldErrors, ', ') + ' are null in event payload'
                );
                continue;
            }

            // remove prefix for PCV2 instances
            if (event.productId != null && event.productId != '') {
                allProductIds.add(event.productId);
            }
            if (event.instanceId != null && event.instanceId != '') {
                String instanceId = event.instanceId?.remove('PCV2-');
                allInstanceIds.add(instanceId);
            }

            CaseJobDetails jobDetails = new CaseJobDetails();
            jobDetails.schema = event;
            jobDetails.queueJob = queueJob;
            jobDetails.auth0Id = event.auth0Id;
            allAuth0Ids.add(event.auth0Id);

            jobsToSchema.put(queueJob, jobDetails);
        }

        if (!allProductIds.isEmpty() || !allInstanceIds.isEmpty()) {
            retrieveProducts();
        }
        retrieveAccounts();

        // Loop over the Queue Jobs again, ensure that User Ids are valid and further process data into a more useful format
        for (Queue_Job__c currentQueueJob : jobsToSchema.keySet()) {
            CaseJobDetails currentJobDetails = jobsToSchema.get(currentQueueJob);

            Hub_Account__c relatedHubAccount = auth0IdToHubAccount.get(currentJobDetails.auth0Id);

            // If we have been given a auth0Id that does not exist in Salesforce
            if (relatedHubAccount == null) {
                failedJobs.put(currentQueueJob, AUTH0_ID_ERROR);
                continue;
            }

            String accountId = auth0IdToHubAccount.get(currentJobDetails.auth0Id).Student__c;

            // Once we are certain that we have the Account Id relating to this Queue Job, retrieve the Account including all details and set it on the class
            currentJobDetails.account = accountIdToAccount.get(accountId);

            // Deduplicate any jobs which have updates for the same Account and add the final job to be processed to a Map for later usage
            Queue_Job__c duplicate = auth0IdsToJobDetails.get(accountId)?.queueJob;
            if (duplicate != null) {
                if (duplicate.Event_Time__c > currentQueueJob.Event_Time__c) {
                    // if job in map is newer, set current job as successful and skip
                    successfulJobs.add(currentQueueJob);
                    continue;
                }
                // if current job is newer, set job in map as successful
                successfulJobs.add(duplicate);
            }
            auth0IdsToJobDetails.put(accountId, currentJobDetails);
            queueJobIdToQueueJob.put(currentQueueJob.Id, currentQueueJob);
        }
    }

    /**
     * Checks for required field errors in a CaseSchema event object and populates the provided requiredFieldErrors list with any errors found.
     * The method creates a map of required field names and their corresponding values from the CaseSchema event object.
     */
    private void checkRequiredFieldErrors(CaseSchema event, List<String> requiredFieldErrors) {
        Map<String, String> requiredFieldMap = new Map<String, String>{
            'Auth0Id' => event?.auth0Id,
            'Query Id' => event?.queryId,
            'Query Type' => event?.queryType,
            'Query Subtype' => event?.subQueryType
        };

        for (String potentialError : requiredFieldMap.keySet()) {
            if (String.isBlank(requiredFieldMap.get(potentialError))) {
                requiredFieldErrors.add(potentialError);
            }
        }
    }

    /**
     * Builds a SOQL query for retrieving Product2 records based on specified criteria.
     *
     * @return The constructed SOQL query as a String, or null if both allInstanceIds and allProductIds are empty.
     */
    private String buildProductQuery() {
        String productQuery = 'SELECT Id, Instance_Id__c, BNR_Program_Code__c FROM Product2';
        String productCondition = '';
        if (!allInstanceIds.isEmpty() || !allProductIds.isEmpty()) {
            productQuery += ' WHERE ';

            if (!allInstanceIds.isEmpty()) {
                productCondition += ' Instance_Id__c IN :allInstanceIds';
            }

            String programCodeClause = 'BNR_Program_Code__c IN :allProductIds';
            if (!allProductIds.isEmpty() && !allInstanceIds.isEmpty()) {
                productCondition += ' AND ' + programCodeClause;
            } else if (!allProductIds.isEmpty()) {
                productCondition += ' ' + programCodeClause;
            }

            return productQuery += productCondition;
        }
        return null;
    }

    /**
     * Retrieves products from the database and populates the identifierToProduct map.
     * The method builds a product query, executes it, and iterates through the resulting list
     */
    private void retrieveProducts() {
        String productQuery = buildProductQuery();
        List<Product2> productList = Database.query(productQuery);
        for (Product2 product : productList) {
            if (product.Instance_Id__c != null) {
                identifierToProduct.put(product.Instance_Id__c, product);
            }

            if (product.BNR_Program_Code__c != null) {
                identifierToProduct.put(product.BNR_Program_Code__c, product);
            }
        }
    }

    /**
     * Retrieves accounts from the database and populates the accountIdToAccount and auth0IdToHubAccount maps.
     * The method queries for accounts that are linked to Hub Accounts, identified by the provided Auth0 IDs.
     */
    private void retrieveAccounts() {
        // Query out any Accounts which are linked to Hub Accounts identified on the Queue Jobs
        for (Account currentAccount : [
            SELECT
                Id,
                PersonContactId,
                (SELECT Id, Student__c, Auth0_Id__c FROM Hub_Accounts__r WHERE Auth0_Id__c IN :allAuth0Ids)
            FROM Account
            WHERE Id IN (SELECT Student__c FROM Hub_Account__c WHERE Auth0_Id__c IN :allAuth0Ids)
        ]) {
            accountIdToAccount.put(currentAccount.Id, currentAccount);

            for (Hub_Account__c currentHubAccount : currentAccount.Hub_Accounts__r) {
                auth0IdToHubAccount.put(currentHubAccount.Auth0_Id__c, currentHubAccount);
            }
        }
    }

    /**
     * Create or Update records using data structures created earlier, run validation and create additional
     * data structures containing only records ready for DML actions
     */
    void processSchemas() {
        // Assign case using active case assignment rule
        AssignmentRule aRule = [
            SELECT id
            FROM AssignmentRule
            WHERE SobjectType = 'Case' AND Active = TRUE
        ];

        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId = aRule.id;

        for (String currentAuth0Id : auth0IdsToJobDetails.keySet()) {
            Boolean jobFailed = false;
            CaseJobDetails currentJobDetails = auth0IdsToJobDetails.get(currentAuth0Id);
            CaseSchema caseSchema = currentJobDetails.schema;

            Queue_Job__c queueJob = currentJobDetails.queueJob;
            String productId = caseSchema.productId;
            String trimmedInstanceId = caseSchema.instanceId?.remove('PCV2-');

            // Insert the Case information
            Case caseToUpdate = new Case(
                Origin = 'Web',
                RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName()
                    .get('Student_Query')
                    .getRecordTypeId(),
                Query_Type__c = caseSchema.queryType,
                Query_Subtype__c = caseSchema.subQueryType,
                Description = caseSchema.queryDescription,
                School__c = caseSchema.school,
                ContactId = currentJobDetails.account.PersonContactId,
                Query_Id__c = caseSchema.queryId
            );

            if (
                (productId != '' && identifierToProduct.containsKey(productId)) ||
                (trimmedInstanceId != '' && identifierToProduct.containsKey(trimmedInstanceId))
            ) {
                Product2 product = productId != '' && identifierToProduct.containsKey(productId)
                    ? identifierToProduct.get(productId)
                    : identifierToProduct.get(trimmedInstanceId);
                caseToUpdate.productId = product.id;
            }

            caseToUpdate.setOptions(dmlOpts);

            // If the job has been marked as failed, continue the loop to the DML maps
            if (jobFailed) {
                continue;
            }

            queueJobIdToCaseToInsert.put(queueJob.Id, caseToUpdate);
        }
    }

    /**
     * Process records created in earlier methods by Inserting or Updated records depending, allowing for X amount of retries, removing
     * any Queue Jobs which were identified as will fail before each retry
     */
    void processRecordDML() {
        Map<Id, List<Database.Error>> jobsToFailToErrors = new Map<Id, List<Database.Error>>();
        Set<Id> successfullyProcessedJobIds = new Set<Id>();
        Savepoint savePoint = Database.setSavepoint();

        List<Database.UpsertResult> caseResults = Database.upsert(
            queueJobIdToCaseToInsert.values(),
            Case.Query_Id__c,
            false
        );
        for (Integer i = 0; i < caseResults.size(); i++) {
            Database.upsertResult result = caseResults[i];
            Id relatedJobId = new List<Id>(queueJobIdToCaseToInsert.keySet())[i];

            if (!result.isSuccess()) {
                jobsToFailToErrors.put(relatedJobId, result.getErrors());
            } else {
                successfullyProcessedJobIds.add(relatedJobId);
            }
        }

        // If there we no failures, succeed the jobs
        if (jobsToFailToErrors.isEmpty()) {
            for (Id queueJobId : successfullyProcessedJobIds) {
                successfulJobs.add(queueJobIdToQueueJob.get(queueJobId));
            }
            return;
        }

        // Otherwise, if there were any failures we must rollback all DML as to not end up with Case Updates persisting.
        // To do so, work out which we know will be successful, and re-processes only those
        Database.rollback(savePoint);

        // Loop over any jobs containing DML that failed, fail the job and remove any records associated with the job from our Insert/Update maps
        // so that they are not re-processed
        for (Id queueJobId : jobsToFailToErrors.keySet()) {
            processDMLErrors(queueJobIdToQueueJob.get(queueJobId), jobsToFailToErrors.get(queueJobId));
            queueJobIdToCaseToInsert.remove(queueJobId);
        }

        // If we have reached or surpassed the threshold to retry the jobs which succeeded on the previous DML run attempt, fail all remaining jobs
        if (RETRY_DML_COUNT_LIMIT <= failedDMLCount) {
            // If the retry also fails, fail all remaining jobs
            for (Id remainingJobId : queueJobIdToCaseToInsert.keySet()) {
                failedJobs.put(queueJobIdToQueueJob.get(remainingJobId), GENERIC_FAILURE);
            }

            return;
        }
        failedDMLCount++;

        // Otherwise if we are still able to retry the DML, do so
        processRecordDML();
    }

    /**
     * Wrapper class to store different data pertaining to a single Queue Job
     */
    private class CaseJobDetails {
        private CaseSchema schema;
        private String auth0Id;
        private Queue_Job__c queueJob;
        private Account account;
    }
}