salesforce-main/src/main/default/objects/Case/fields/Query_Id__c.field-meta.xml
<CustomField>
    <fullName>Query_Id__c</fullName>
    <description>The external ID from the website</description>
    <externalId>true</externalId>
    <inlineHelpText>The external ID from the website</inlineHelpText>
    <label>Query Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Query_Subtype__c</fullName>
    <label>Query Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Query_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Authorised Leave</fullName>
            </value>
            <value>
                <fullName>How do I access my EBook?</fullName>
            </value>
            <value>
                <fullName>How do I access my results and feedback</fullName>
            </value>
            <value>
                <fullName>How do I collect my ID card?</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from accessing my e-materials</fullName>
            </value>
            <value>
                <fullName>I&apos;m having technical issues preventing me from studying</fullName>
            </value>
            <value>
                <fullName>I am in financial difficulty, what are my options?</fullName>
            </value>
            <value>
                <fullName>I am on Interruption of Studies and wish to extend</fullName>
            </value>
            <value>
                <fullName>I am taking an interruption of studies, how does that affect my payment plan and fees?</fullName>
            </value>
            <value>
                <fullName>I can&apos;t access my forum</fullName>
            </value>
            <value>
                <fullName>I can’t see my course within my online learning platform</fullName>
            </value>
            <value>
                <fullName>I have a different problem with my online learning</fullName>
            </value>
            <value>
                <fullName>I have a query about applying for Post Study Work/Graduate Route Visa</fullName>
            </value>
            <value>
                <fullName>I have a query about exemptions</fullName>
            </value>
            <value>
                <fullName>I have a query about inviting visitors to the UK</fullName>
            </value>
            <value>
                <fullName>I have a query about my attendance</fullName>
            </value>
            <value>
                <fullName>I have a query about my balance</fullName>
            </value>
            <value>
                <fullName>I have a query about my End Point Assessment</fullName>
            </value>
            <value>
                <fullName>I have a query about my submission</fullName>
            </value>
            <value>
                <fullName>I have a query about my timetable</fullName>
            </value>
            <value>
                <fullName>I have a question about my assessments feedback</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam arrangements</fullName>
            </value>
            <value>
                <fullName>I have a question about my exam learning support</fullName>
            </value>
            <value>
                <fullName>I have a question about my graduation ceremony</fullName>
            </value>
            <value>
                <fullName>I have a question about my mock/assessment</fullName>
            </value>
            <value>
                <fullName>I have a question about my Oyster card</fullName>
            </value>
            <value>
                <fullName>I have a question about my results</fullName>
            </value>
            <value>
                <fullName>I have a question about my review/gate-way call</fullName>
            </value>
            <value>
                <fullName>I have a question about my student loan</fullName>
            </value>
            <value>
                <fullName>I have a question about my term dates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Query_Type__c.field-meta.xml
<CustomField>
    <fullName>Query_Type__c</fullName>
    <label>Query Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assessments</fullName>
            </value>
            <value>
                <fullName>Attendance</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Changes to personal details</fullName>
            </value>
            <value>
                <fullName>Changes to studies</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Finance and Billing</fullName>
            </value>
            <value>
                <fullName>Graduation and Certificates</fullName>
            </value>
            <value>
                <fullName>IoS (Interruption of Studies)</fullName>
            </value>
            <value>
                <fullName>Letter requests</fullName>
            </value>
            <value>
                <fullName>My Apprenticeship</fullName>
            </value>
            <value>
                <fullName>My Course</fullName>
            </value>
            <value>
                <fullName>My Online Learning and The HUB</fullName>
            </value>
            <value>
                <fullName>My Study Materials</fullName>
            </value>
            <value>
                <fullName>Online learning</fullName>
            </value>
            <value>
                <fullName>Registration and enrolment</fullName>
            </value>
            <value>
                <fullName>Review Meeting</fullName>
            </value>
            <value>
                <fullName>Student Finance</fullName>
            </value>
            <value>
                <fullName>Student Loans</fullName>
            </value>
            <value>
                <fullName>Timetables</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>General Query</fullName>
            </value>
            <value>
                <fullName>Undetermined Query</fullName>
            </value>
            <value>
                <fullName>Prior Learning/Exemptions information</fullName>
            </value>
            <value>
                <fullName>Additional Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Student)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Study_Location__c.field-meta.xml
<CustomField>
    <fullName>Study_Location__c</fullName>
    <label>Study Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Cambridge</fullName>
            </value>
            <value>
                <fullName>Doncaster</fullName>
            </value>
            <value>
                <fullName>Leeds</fullName>
            </value>
            <value>
                <fullName>London (City)</fullName>
            </value>
            <value>
                <fullName>London (Holborn)</fullName>
            </value>
            <value>
                <fullName>London (Kings Cross)</fullName>
            </value>
            <value>
                <fullName>London (Portsoken)</fullName>
            </value>
            <value>
                <fullName>London (Shepherd&apos;s Bush)</fullName>
            </value>
            <value>
                <fullName>London (Waterloo)</fullName>
            </value>
            <value>
                <fullName>Manchester</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/QueryFormSyncTest.cls
@isTest
private class QueryFormSyncTest {

    @TestSetup
    private static void setUp() {
        
        Account account = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get('Student Account')
            .getRecordTypeId(),
            FirstName = 'Test',
            LastName = 'Tester',
            Salutation = 'Mr',
            Personal_Email__pc = 'test@bpp.com',
            Preferred_Email__pc = 'Personal',
            BNR_Banner_ID__pc = 'test-1'
        );
        
        insert account;

        Account acc = [SELECT Id, PersonContactId FROM Account WHERE Id = :account.Id];
        
        Hub_Account__c hubAccount = new Hub_Account__c(
            Student__c = account.Id, 
            Hub_Username__c = 'test@bpp.com', 
            Auth0_Id__c = 'auth|test-123');
        
        insert hubAccount;
        
        insert new Case(
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
            .get('Student Query')
            .getRecordTypeId(),
            AccountId = account.Id,
            ContactId = acc.PersonContactId,
            Status = 'New',
            Origin = 'Web',
            Query_Type__c = 'Assessments',
            Query_Subtype__c = 'How do I access my results and feedback',
            Study_Location__c ='Leeds',
            Query_Id__c = 'test-123'
        );
    }
    
    @isTest
    private static void itShouldBuildTheCorrectPayload() {
        // Given we have a Web case 
        Case cs = [SELECT Id, CaseNumber, Query_Id__c, Status, LastModifiedDate, AccountId, ContactId FROM Case];
        
        // WHEN this is passed to the case query form sync handler
        Serializer serializer = new QueryFormSync();
        serializer.addRecord(cs);
        
        // THEN I expect it to include Auth0 id in the payload
        List<Map<String, Object>> payload = serializer.serialize();
        List<String> authIds = (List<String>) payload.get(0).get('auth0Ids');
        
        Assert.areEqual(1, authIds.size());
        Assert.areEqual('auth|test-123', authIds.get(0));
        
        String status = (String) payload.get(0).get('status');
        Assert.areEqual('New', status);
    }
    
    @isTest
    private static void itShouldSerializeExcludingCasesWithNoHubAccount() {
        // GIVEN we have a case
        Case cs = [SELECT Id, CaseNumber, Query_Id__c, Status, LastModifiedDate, AccountId, ContactId FROM Case];

        // AND there are no Hub Accounts
        delete [SELECT Id FROM Hub_Account__c];

        // WHEN this is passed to the case query form sync handler
        Serializer serializer = new QueryFormSync();
        serializer.addRecord(cs);

        // THEN I expect it to serialize it correctly
        List<Map<String, Object>> payload = serializer.serialize();
        Assert.isTrue(payload.isEmpty(), 'I expect there to be no payloads');
    }
}