salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/HubAccountVerificationEmailCallout.cls
global with sharing class HubAccountVerificationEmailCallout {
    webService static String sendVerificationEmail(Hub_Account__c hubAccount) {
        if (hubAccount == null) {
            return null;
        }

        String response;
        String responseToUser;
        List<Hub_Account__c> hubAccountToUpdate = new List<Hub_Account__c>();

        AWSsampleAPIUtil.AuthToken at = AWSsampleAPIUtil.getAccessToken();

        String body = '{"userId" : "' + hubAccount.Auth0_Id__c + '"}';
        String endpoint = AWSsampleAPIUtil.retrieveAWSEndpoint() + '/user/username/verify';

        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setEndpoint(endpoint);
        httpRequest.setHeader('Authorization', 'Bearer ' + at.token);
        httpRequest.setHeader('Content-Type', 'application/json');
        httpRequest.setBody(body);

        Integration_Log__c integ = new Integration_Log__c();
        try {
            HttpResponse httpResponse = new Http().send(httpRequest);
            response = httpResponse.getStatusCode() + ': ' + httpResponse.getBody();

            if (httpResponse.getStatusCode() == 200) {
                hubAccountToUpdate.add(hubAccount);
                responseToUser = 'Success';
            } else {
                String message;
                if (response.length() > 5) {
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(
                        httpResponse.getBody()
                    );
                    message = (String) responseMap.get('message');
                } else {
                    message = 'Something went wrong. Please contact your Salesforce Administrator.';
                }
                responseToUser = '\nError: ' + message;
            }
        } catch (System.Exception e) {
            responseToUser = '\nError: ' + String.valueOf(e.getMessage());
            response += ' : ' + String.valueOf(e.getMessage());
        } finally {
            integ = AWSsampleAPIUtil.createIntegrationLog('HUB', endpoint, response, hubAccount.Id);
            insert integ;

            if (hubAccountToUpdate.size() > 0) {
                update hubAccountToUpdate;
            }

            if (!at.valid) {
                update at.authToken;
            }
        }

        return responseToUser;
    }
}