salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Last_Password_Reset_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Last_Password_Reset_Email_Sent__c</fullName>
    <description>Shows the date and time that the last password reset email was sent to this Hub Account.</description>
    <inlineHelpText>Shows the date and time that the last password reset email was sent to this Hub Account.</inlineHelpText>
    <label>Last Password Reset Email Sent</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Integration_Log__c/fields/Salesforce_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_ID__c</fullName>
    <label>Salesforce ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/HubAccountPasswordResetTest.cls
@isTest
private class HubAccountPasswordResetTest {

    public static Hub_Account__c createHubAccount(String auth0Id, String hubUserName) {

        Hub_Account__c hubAccount = new Hub_Account__c();
        hubAccount.Auth0_Id__c = auth0Id;
        hubAccount.Hub_Username__c = hubUserName;
        insert hubAccount;

        return hubAccount;
    }

    public static Hub_Account__c retrieveHubAccount(String auth0Id, String hubUserName) {

        return createHubAccount(auth0Id, hubUserName);
    }

    @isTest
    static void test_PasswordReset() {
        
        Hub_Account__c hubAccount = retrieveHubAccount('auth0|qwertyuiop', 'test1@bpp.com');

        List<String> inputList = new List<String>();
		String combinedStrings = hubAccount.Auth0_Id__c;
		inputList.add(combinedStrings);

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HubAccountCalloutMock());
            List<HubAccountUpdateHelper> response = new List<HubAccountUpdateHelper>();
            response = HubAccountPasswordReset.getResult(inputList);

            List<Integration_Log__c> integLogList = [SELECT Id FROM Integration_Log__c WHERE Salesforce_ID__c =: hubAccount.Id];
            System.assertEquals(1, integLogList.size());

            Hub_Account__c hubAccountAfter = [SELECT Last_Password_Reset_Email_Sent__c FROM Hub_Account__c LIMIT 1];
            System.assertEquals(Date.valueOf(System.now()), Date.valueOf(hubAccountAfter.Last_Password_Reset_Email_Sent__c));
        Test.stopTest();
    }

    @isTest
    static void test_PasswordResetFailure1() {
       
        Hub_Account__c hubAccount = retrieveHubAccount('', 'test1@bpp.com');

        List<String> inputList = new List<String>();
		String combinedStrings = hubAccount.Auth0_Id__c;
		inputList.add(combinedStrings);

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HubAccountCalloutMock());
            List<HubAccountUpdateHelper> response = new List<HubAccountUpdateHelper>();
            response = HubAccountPasswordReset.getResult(inputList);

            List<Integration_Log__c> integLogList = [SELECT Id FROM Integration_Log__c WHERE Salesforce_ID__c =: hubAccount.Id];
            System.assertEquals(0, integLogList.size());

            Hub_Account__c hubAccountAfter = [SELECT Last_Password_Reset_Email_Sent__c FROM Hub_Account__c LIMIT 1];
            System.assertEquals(NULL, hubAccountAfter.Last_Password_Reset_Email_Sent__c);
        Test.stopTest();
    }

    @isTest
    static void test_PasswordResetFailure2() {
        
        Hub_Account__c hubAccount = retrieveHubAccount('auth0|qwertyuiop', 'test1@my.bpp.com');

        List<String> inputList = new List<String>();
		String combinedStrings = hubAccount.Auth0_Id__c;
		inputList.add(combinedStrings);

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HubAccountCalloutMock());
            List<HubAccountUpdateHelper> response = new List<HubAccountUpdateHelper>();
            response = HubAccountPasswordReset.getResult(inputList);

            List<Integration_Log__c> integLogList = [SELECT Id FROM Integration_Log__c WHERE Salesforce_ID__c =: hubAccount.Id];
            System.assertEquals(0, integLogList.size());

            Hub_Account__c hubAccountAfter = [SELECT Last_Password_Reset_Email_Sent__c FROM Hub_Account__c LIMIT 1];
            System.assertEquals(NULL, hubAccountAfter.Last_Password_Reset_Email_Sent__c);
        Test.stopTest();
    }
}