salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/Institute_Body__c.object-meta.xml
<CustomObject>
    <description>Institute Bodies that a student is a member of</description>
    <label>Institute Body</label>
    <nameField>
        <displayFormat>IB{00000000}</displayFormat>
        <label>Institute Body ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institute Bodies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Body__c.field-meta.xml
<CustomField>
    <fullName>Institute_Body__c</fullName>
    <description>Institute Body</description>
    <label>Institute Body</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>Apprenticeships</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CBI</fullName>
            </value>
            <value>
                <fullName>CFA</fullName>
            </value>
            <value>
                <fullName>CII</fullName>
            </value>
            <value>
                <fullName>CIMA</fullName>
            </value>
            <value>
                <fullName>CIPD</fullName>
            </value>
            <value>
                <fullName>CISI</fullName>
            </value>
            <value>
                <fullName>CMI</fullName>
            </value>
            <value>
                <fullName>CTA</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>IAD</fullName>
            </value>
            <value>
                <fullName>ICAEW</fullName>
            </value>
            <value>
                <fullName>ICAS</fullName>
            </value>
            <value>
                <fullName>ICSA</fullName>
            </value>
            <value>
                <fullName>IMC</fullName>
            </value>
            <value>
                <fullName>Insolvency</fullName>
            </value>
            <value>
                <fullName>IOC</fullName>
            </value>
            <value>
                <fullName>ITP</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>PMI</fullName>
            </value>
            <value>
                <fullName>Association of Accounting Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Accounting Technicians</label>
            </value>
            <value>
                <fullName>Association of Chartered Certified Accountants</fullName>
                <isActive>false</isActive>
                <label>Association of Chartered Certified Accountants</label>
            </value>
            <value>
                <fullName>Association of Tax Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Tax Technicians</label>
            </value>
            <value>
                <fullName>CII Diploma in Regulated Financial Planning</fullName>
                <isActive>false</isActive>
                <label>CII Diploma in Regulated Financial Planning</label>
            </value>
            <value>
                <fullName>CISI Apprenticeship Programmes</fullName>
                <isActive>false</isActive>
                <label>CISI Apprenticeship Programmes</label>
            </value>
            <value>
                <fullName>CISI Capital Markets</fullName>
                <isActive>false</isActive>
                <label>CISI Capital Markets</label>
            </value>
            <value>
                <fullName>CISI Cert in Private Client Investment Advice&amp;Mgmt</fullName>
                <isActive>false</isActive>
                <label>CISI Cert in Private Client Investment Advice&amp;Mgmt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Number__c.field-meta.xml
<CustomField>
    <fullName>Institute_Number__c</fullName>
    <description>Student&apos;s membership number of the institute body</description>
    <label>Institute Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Student account that is a member of the professional body institution</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Must be a student account</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institute Bodies</relationshipLabel>
    <relationshipName>Institute_Bodies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/classes/InstituteBodyTriggerTest.cls
@isTest
private class InstituteBodyTriggerTest {
    @testSetup
    private static void setUp() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
            .get('Student Account')
            .getRecordTypeId();
        // Account
        Account account = new Account(
            RecordTypeId = recordTypeId,
            FirstName = 'Test',
            LastName = 'Tester',
            Salutation = 'Mr',
            Personal_Email__pc = 'test@bpp.com',
            Preferred_Email__pc = 'test@bpp.com'
        );

        insert account;

        insert new Hub_Account__c(
            Student__c = account.Id,
            Auth0_Id__c = 'sub|12345',
            Hub_Username__c = 'testuser@bpp.com'
        );

        // Institute Body
        insert new Institute_Body__c(
            Institute_Body__c = 'AAT',
            Institute_Number__c = 'ref-1234',
            Student__c = account.Id
        );
    }

    @isTest
    private static void itShouldSendAnEventWhenARecordIsCreated() {
        StreamingService.canFetchStreams = true;

        Account account = [SELECT Id FROM Account WHERE LastName = 'Tester'];
        // GIVEN we create a new Institute Body object
        // WHEN the trigger runs
        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        insert new Institute_Body__c(Institute_Body__c = 'CFA', Institute_Number__c = '1', Student__c = account.Id);

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect an event to be published
        Assert.areEqual(1, mock.processedRequests);
    }

    @isTest
    private static void itShouldSendAnEventWhenARecordIsUpdated() {
        StreamingService.canFetchStreams = true;

        // GIVEN we have an existing institute body object
        Institute_Body__c body = [
            SELECT Id, Institute_Number__c
            FROM Institute_Body__c
            WHERE Institute_Number__c = 'ref-1234'
        ];

        // WHEN the I update the record
        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        body.Institute_Number__c = 'ref-4321';
        update body;

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect an event to be published
        Assert.areEqual(1, mock.processedRequests);
    }

    @isTest
    private static void itShouldSendAnEventWhenARecordIsDeleted() {
        StreamingService.canFetchStreams = true;

        // GIVEN we have an existing institute body object
        Institute_Body__c body = [
            SELECT Id, Institute_Number__c
            FROM Institute_Body__c
            WHERE Institute_Number__c = 'ref-1234'
        ];

        // WHEN the I delete the record
        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        delete body;

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect an event to be published
        Assert.areEqual(1, mock.processedRequests);
    }

    @isTest
    private static void itShouldPreventMultipleInstituteBodiesWithTheSameBodyBeingCreated() {
        // GIVEN we already have an institute body
        Account account = [SELECT Id FROM Account WHERE LastName = 'Tester'];
        // WHEN we attempt to add a new one with the same body
        Boolean exceptionThrown = false;
        System.Test.startTest();

        try {
            insert new Institute_Body__c(Institute_Body__c = 'AAT', Institute_Number__c = '1', Student__c = account.Id);
        } catch (DMLException e) {
            exceptionThrown = true;
        }

        System.Test.stopTest();

        // THEN I expect it to fail
        Assert.isTrue(exceptionThrown);
    }
}