salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Requested_Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>BPP_Requested_Hub_Username__c</fullName>
    <label>Requested Hub Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/HubAccountTriggerHandler.cls
public with sharing class HubAccountTriggerHandler {
    public static void handleAfterUpdate(Map<Id, Hub_Account__c> oldMap, Map<Id, Hub_Account__c> newMap) {
        Set<Id> hubAccountIdsToUpdateInHub = new Set<Id>();
        for (Hub_Account__c newHubAccount : newMap.values()) {
            Hub_Account__c oldHubAccount = oldMap.get(newHubAccount.Id);
            if (
                newHubAccount.BPP_Requested_Hub_Username__c != null &&
                oldHubAccount.BPP_Requested_Hub_Username__c != newHubAccount.BPP_Requested_Hub_Username__c
            ) {
                hubAccountIdsToUpdateInHub.add(newHubAccount.Id);
            }
        }
        if (hubAccountIdsToUpdateInHub.size() > 0) {
            HubUsernameUpdate.hubUsernameUpdateCallout(hubAccountIdsToUpdateInHub);
        }
    }
}