salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Email_Verified__c.field-meta.xml
<CustomField>
    <fullName>Email_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Verified</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Last_Verification_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Last_Verification_Email_Sent__c</fullName>
    <description>Shows the date and time that the last verification email was sent to this Hub Account.</description>
    <inlineHelpText>Shows the date and time that the last verification email was sent to this Hub Account.</inlineHelpText>
    <label>Last Verification Email Sent</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/classes/HubAccountVerificationEmail.cls
public with sharing class HubAccountVerificationEmail {
    @InvocableMethod(label='Send Hub Verification Email')
    public static List<HubAccountUpdateHelper> getResult(List<String> inputList) {
        List<HubAccountUpdateHelper> resultList = sendVerificationEmail(inputList);
        return resultList;
    }

    private static List<HubAccountUpdateHelper> sendVerificationEmail(List<String> inputList) {
        System.debug(inputList);
        HubAccountUpdateHelper response = new HubAccountUpdateHelper();
        List<HubAccountUpdateHelper> responseWrapper = new List<HubAccountUpdateHelper>();

        if (inputList.size() == 1) {
            String auth0Id = inputList[0];

            if (auth0Id != NULL && auth0Id.length() > 0) {
                Hub_Account__c hubAccount = [SELECT Auth0_Id__c, Hub_Username__c, Email_Verified__c FROM Hub_Account__c WHERE Auth0_Id__c =: auth0Id];
                if (!hubAccount.Email_Verified__c) {
                    hubAccount.Last_Verification_Email_Sent__c = System.now();
                    String result = HubAccountVerificationEmailCallout.sendVerificationEmail(hubAccount);
                    response.outputString = result;
                } else {
                    response.outputString = '\nError: Hub Account\'s Email address is already verified.';
                }
            } else {
                if (auth0Id == NULL || auth0Id.length() == 0) {
                    response.outputString = '\nError: Auth0Id value is blank.';
                }
            }
        } else {
            response.outputString = '\nError: Something went wrong!';
        }

        responseWrapper.add(response);
        System.debug(responseWrapper);
        return responseWrapper;
    }
}