salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Requested_Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>BPP_Requested_Hub_Username__c</fullName>
    <label>Requested Hub Username</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Username_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>BPP_Username_Error_Message__c</fullName>
    <label>Username Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/BPP_Username_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Username_Update_Status__c</fullName>
    <description>Tracks the progress of the active Hub Username update request.</description>
    <inlineHelpText>Tracks the progress of the active Hub Username update request.</inlineHelpText>
    <label>Username Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/HubUsernameUpdate.cls
public with sharing class HubUsernameUpdate {
    @future(callout=true)
    public static void hubUsernameUpdateCallout(Set<Id> hubAccountIds) {
        AWSsampleAPIUtil.AuthToken at = AWSsampleAPIUtil.getAccessToken();

        List<Hub_Account__c> hubAccountsToUpdate = new List<Hub_Account__c>();
        List<Integration_Log__c> integrationListToInsert = new List<Integration_Log__c>();
        List<Hub_Account__c> hubAccountList = retrieveHubAccountRecords(hubAccountIds);
        List<Hub_Account__c> existingHubAccountList = retrieveExistingHubAccountList(hubAccountList);

        for (Hub_Account__c hubAccount : hubAccountList) {
            Hub_Account__c hubAccountInProgress = new Hub_Account__c(Id = hubAccount.Id);
            Boolean hubUsernameAlreadyExists = checkHubUsernameExists(
                hubAccount.BPP_Requested_Hub_Username__c,
                existingHubAccountList
            );
            if (hubUsernameAlreadyExists) {
                hubAccountInProgress.BPP_Requested_Hub_Username__c = null;
                hubAccountInProgress.BPP_Username_Update_Status__c = 'Error';
                hubAccountInProgress.BPP_Username_Error_Message__c =
                    'The requested username: "' +
                    hubAccount.BPP_Requested_Hub_Username__c +
                    '" is present on an existing Hub Account record.';
                hubAccountsToUpdate.add(hubAccountInProgress);
            } else {
                String response;
                String message;
                String body =
                    '{"user_id" : "' +
                    hubAccount.Auth0_Id__c +
                    '","email" : "' +
                    hubAccount.BPP_Requested_Hub_Username__c +
                    '"}';
                String endpoint = AWSsampleAPIUtil.retrieveAWSEndpoint() + '/user/username';

                HttpRequest httpRequest = new HttpRequest();
                httpRequest.setMethod('PATCH');
                httpRequest.setEndpoint(endpoint);
                httpRequest.setHeader('Authorization', 'Bearer ' + at.token);
                httpRequest.setHeader('Content-Type', 'application/json');
                httpRequest.setBody(body);

                Integration_Log__c integ = new Integration_Log__c();

                try {
                    HttpResponse httpResponse = new Http().send(httpRequest);
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(
                        httpResponse.getBody()
                    );
                    message = (String) responseMap.get('message');
                    response = httpResponse.getStatusCode() + ': ' + httpResponse.getBody() + ' : ' + message;
                } catch (System.Exception e) {
                    response += ' : ' + String.valueOf(e.getMessage());
                } finally {
                    hubAccountInProgress.BPP_Requested_Hub_Username__c = null;
                    hubAccountsToUpdate.add(hubAccountInProgress);

                    integ = AWSsampleAPIUtil.createIntegrationLog('HUB', endpoint, response, hubAccount.Id);
                    integrationListToInsert.add(integ);
                }
            }
        }
        if (integrationListToInsert.size() > 0) {
            insert integrationListToInsert;
        }
        if (hubAccountsToUpdate.size() > 0) {
            update hubAccountsToUpdate;
        }
        if (!at.valid) {
            update at.authToken;
        }
    }

    private static List<Hub_Account__c> retrieveHubAccountRecords(Set<Id> hubAccountIds) {
        return new List<Hub_Account__c>(
            [
                SELECT Auth0_Id__c, BPP_Requested_Hub_Username__c, Student__c
                FROM Hub_Account__c
                WHERE Id IN :hubAccountIds
            ]
        );
    }

    private static List<Hub_Account__c> retrieveExistingHubAccountList(List<Hub_Account__c> hubAccountList) {
        Set<String> newHubUsernames = new Set<String>();
        for (Hub_Account__c hubAccount : hubAccountList) {
            newHubUsernames.add(hubAccount.BPP_Requested_Hub_Username__c);
        }
        return new List<Hub_Account__c>(
            [SELECT Name, Hub_Username__c FROM Hub_Account__c WHERE Hub_Username__c IN :newHubUsernames]
        );
    }

    private static Boolean checkHubUsernameExists(
        String requestedHubUsername,
        List<Hub_Account__c> existingHubAccountList
    ) {
        Boolean hubUsernameAlreadyExists = false;
        for (Hub_Account__c existingHubAccount : existingHubAccountList) {
            if (requestedHubUsername == existingHubAccount.Hub_Username__c) {
                hubUsernameAlreadyExists = true;
            }
        }
        return hubUsernameAlreadyExists;
    }
}