salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/classes/outboundEvents/serializers/HubAccountSyncTest.cls
@isTest
private with sharing class HubAccountSyncTest {
    @TestSetup
    private static void setUp() {
        insert new Hub_Account__c(Hub_Username__c = 'test@bpp.com', Auth0_Id__c = 'auth|test-123');
    }

    @isTest
    private static void itShouldBuildTheCorrectPayload() {
        // Given we have a hub account
        Hub_Account__c hub = [SELECT Auth0_Id__c FROM Hub_Account__c WHERE Auth0_Id__c = 'auth|test-123'];

        // WHEN this is passed to the hub account sync handler
        Serializer serializer = new HubAccountSync();
        serializer.addRecord(hub);

        // THEN I expect it to include Auth0 id in the payload
        List<Map<String, Object>> payload = serializer.serialize();
        List<String> authIds = (List<String>) payload.get(0).get('userIds');

        Assert.areEqual(1, authIds.size());
        Assert.areEqual('auth|test-123', authIds.get(0));
    }
}