salesforce-main/src/main/default/objects/Institute_Body__c/Institute_Body__c.object-meta.xml
<CustomObject>
    <description>Institute Bodies that a student is a member of</description>
    <label>Institute Body</label>
    <nameField>
        <displayFormat>IB{00000000}</displayFormat>
        <label>Institute Body ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institute Bodies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Institute_Body__c.field-meta.xml
<CustomField>
    <fullName>Institute_Body__c</fullName>
    <description>Institute Body</description>
    <label>Institute Body</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>Apprenticeships</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CBI</fullName>
            </value>
            <value>
                <fullName>CFA</fullName>
            </value>
            <value>
                <fullName>CII</fullName>
            </value>
            <value>
                <fullName>CIMA</fullName>
            </value>
            <value>
                <fullName>CIPD</fullName>
            </value>
            <value>
                <fullName>CISI</fullName>
            </value>
            <value>
                <fullName>CMI</fullName>
            </value>
            <value>
                <fullName>CTA</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
            <value>
                <fullName>IAD</fullName>
            </value>
            <value>
                <fullName>ICAEW</fullName>
            </value>
            <value>
                <fullName>ICAS</fullName>
            </value>
            <value>
                <fullName>ICSA</fullName>
            </value>
            <value>
                <fullName>IMC</fullName>
            </value>
            <value>
                <fullName>Insolvency</fullName>
            </value>
            <value>
                <fullName>IOC</fullName>
            </value>
            <value>
                <fullName>ITP</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>PMI</fullName>
            </value>
            <value>
                <fullName>Association of Accounting Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Accounting Technicians</label>
            </value>
            <value>
                <fullName>Association of Chartered Certified Accountants</fullName>
                <isActive>false</isActive>
                <label>Association of Chartered Certified Accountants</label>
            </value>
            <value>
                <fullName>Association of Tax Technicians</fullName>
                <isActive>false</isActive>
                <label>Association of Tax Technicians</label>
            </value>
            <value>
                <fullName>CII Diploma in Regulated Financial Planning</fullName>
                <isActive>false</isActive>
                <label>CII Diploma in Regulated Financial Planning</label>
            </value>
            <value>
                <fullName>CISI Apprenticeship Programmes</fullName>
                <isActive>false</isActive>
                <label>CISI Apprenticeship Programmes</label>
            </value>
            <value>
                <fullName>CISI Capital Markets</fullName>
                <isActive>false</isActive>
                <label>CISI Capital Markets</label>
            </value>
            <value>
                <fullName>CISI Cert in Private Client Investment Advice&amp;Mgmt</fullName>
                <isActive>false</isActive>
                <label>CISI Cert in Private Client Investment Advice&amp;Mgmt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Institute_Body__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <description>Student account that is a member of the professional body institution</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Must be a student account</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institute Bodies</relationshipLabel>
    <relationshipName>Institute_Bodies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/classes/InstituteBodyTriggerHandler.cls
public without sharing class InstituteBodyTriggerHandler {
    /**
     * Ensures only a unique combination of student and qualification
     * @param bodies List of institute bodies being created/updated
     */
    public static void checkUniqueQualification(List<Institute_Body__c> bodies) {
        Map<Id, Set<String>> studentQualifications = new Map<Id, Set<String>>();
        Set<Id> studentIds = new Set<Id>();
        Set<Id> bodyIds = new Set<Id>();

        for (Institute_Body__c body : bodies) {
            studentIds.add(body.Student__c);
            bodyIds.add(body.Id);
        }

        for (Institute_Body__c body : [
            SELECT Student__c, Institute_Body__c
            FROM Institute_Body__c
            WHERE Student__c IN :studentIds
            AND Id NOT IN :bodyIds
        ]) {
            Set<String> qualifications = new Set<String>();
            if (studentQualifications.containsKey(body.Student__c)) {
                qualifications = studentQualifications.get(body.Student__c);
            }

            qualifications.add(body.Institute_Body__c);
            studentQualifications.put(body.Student__c, qualifications);
        }

        for (Institute_Body__c body : bodies) {
            Set<String> qualifications = studentQualifications.get(body.Student__c);

            if (qualifications == null) {
                continue;
            }

            if (qualifications.contains(body.Institute_Body__c)) {
                body.addError('Institute_Body__c', 'A record already exists for this institute body.');
            }
        }
    }
}