salesforce-main/src/main/default/objects/Account/fields/AA_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>AA_Passport_Number__c</fullName>
    <description>Sourced from Active Apply for SIStoCRM Integration.

Added for International Specific Applications.</description>
    <label>Passport Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizenship</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <description>This object will contain values for Business Units.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Case/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field provides look up to Business Unit from Case.</description>
    <label>Business Unit</label>
    <referenceTo>Business_Unit__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Case_Group__c.field-meta.xml
<CustomField>
    <fullName>Case_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field provides look up to Case Group from Case.</description>
    <label>Case Group</label>
    <referenceTo>Case_Group__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/fields/Issue_Type__c.field-meta.xml
<CustomField>
    <fullName>Issue_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field provides look up to Issue Type from Case.</description>
    <label>Issue Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Issues_Type__c.Case_Group__c</field>
            <operation>equals</operation>
            <valueField>$Source.Case_Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Issues_Type__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Case/recordTypes/Backlog.recordType-meta.xml
<RecordType>
    <fullName>Backlog</fullName>
    <active>false</active>
    <businessProcess>Backlog</businessProcess>
    <description>Used to manage Salesforce team backlog.  Use only for components packaged for release.</description>
    <label>Backlog</label>
</RecordType>

salesforce-main/src/main/default/objects/Case/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>false</active>
    <businessProcess>Standard</businessProcess>
    <description>For all support issues and feature requests initiated by end users.</description>
    <label>Standard</label>
</RecordType>

salesforce-main/src/main/default/objects/Case_Group__c/Case_Group__c.object-meta.xml
<CustomObject>
    <description>This object will contain values for Case Groups.</description>
    <label>Case Group</label>
    <nameField>
        <label>Case Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>All Tenants - Country table for variety of uses</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Country__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Country must be enabled for related lookup relationships to function</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Entitlement/fields/Case_Group__c.field-meta.xml
<CustomField>
    <fullName>Case_Group__c</fullName>
    <label>Case Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Issues_Type__c/Issues_Type__c.object-meta.xml
<CustomObject>
    <description>This object will contain values for Issue Type .</description>
    <label>Issue Type</label>
    <nameField>
        <label>Issues Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issue Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Issues_Type__c/fields/Case_Group__c.field-meta.xml
<CustomField>
    <fullName>Case_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field provides look up to BU from Case.</description>
    <label>Case Group</label>
    <referenceTo>Case_Group__c</referenceTo>
    <relationshipName>Issues_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/Test_CaseHandlerForProcessBuilderUtil.cls
@isTest(seeAllData = false)
public class Test_CaseHandlerForProcessBuilderUtil {
    Public static list<Entitlement> entitlementLst;
    Public static void createEntitlementProcess(){
    Map<String,SlaProcess> slaProcessMap = new map<String,SlaProcess>();
          for(SlaProcess currSlaProcess : [select id,Name from SlaProcess]){
              slaProcessMap.put(currSlaProcess.Name,currSlaProcess);    
          }
        Account testAccount = createAccount(); 
        System.Debug('Value'+slaProcessMap);
        entitlementLst = new list<Entitlement>();   
        for(RecordType currRecordType : [SELECT Id,Name FROM RecordType WHERE SobjectType='Case' and Name != :'SIS Error Escalations' and Name != 'Backlog'
                                        and Name != 'Standard' and Name != 'SyncBatch Escalation' and Name != 'Vanta Cases']){
        System.debug('Record type name'+currRecordType.name);
        System.Debug('slaprocess'+slaProcessMap.get(currRecordType.Name).Id);
            if(slaProcessMap.containsKey(currRecordType.Name))
            entitlementLst.add(New Entitlement(AccountId = testAccount.id,Name = currRecordType.Name,SlaProcessId = slaProcessMap.get(currRecordType.Name).Id,StartDate = System.today() ) );           
        }
     insert  entitlementLst; 
    }
    Public static Account createAccount(){    
        Country__c testCountry = createCountry('India', True, 'IN');
        Id MyRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId();
        Account testAccount = new Account(firstName = 'test', lastName = 'Account', PersonHomePhone = '7777887788',
                                         Personal_Email__pc = 'test@testaccount.com', Gender__pc = 'Male',
                                         PersonBirthdate = Date.parse('02/09/1990'),
                                         recordTypeId = MyRecTypeId, Country__c = testCountry.Id,AA_Passport_Number__c='12345',
                                         Preferred_Email__pc = 'Personal', Preferred_Phone__pc = 'Home');
        insert testAccount;
        return testAccount;
    }
    Public static Country__c createCountry(String name, Boolean active, String countryCode){        
        Country__c testCountry = new Country__c(Name = name, Active__c = active, Country_Code__c = countryCode);
        insert testCountry;        
        return testCountry;
    }
    Public static Business_Unit__c createBusinessUnit(){
        Business_Unit__c businessUnit = new Business_Unit__c(Name='Test Business Unit');
        insert businessUnit;
        return businessUnit;  
    }
    Public static Case_Group__c createCaseGroup(){
        Case_Group__c caseGroup= new Case_Group__c(Name='Test Case Group');
        insert caseGroup;
        return caseGroup;  
    }
    Public static Issues_Type__c  createIssueType(){ 
        Issues_Type__c issueType = new Issues_Type__c(Case_Group__c = createCaseGroup().id,Name = 'Test Issue type');
        insert  issueType;
        return issueType; 
    }
     Public static List<Case> createCasesForNonValidatedUser(String recordTypeName){
        if(entitlementLst == Null){
            createEntitlementProcess();
        } 
        List<Case> listOfTestCases = new List<Case>();
        Id MyRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        Business_Unit__c businessUnit = createBusinessUnit();
        Issues_Type__c issueType = createIssueType();
        for(Integer i = 0; i < 1; i++){
            Case testCase = new Case(Case_Group__c=issueType.Case_Group__c,Issue_Type__c=issueType .id, Status= 'New', Subject= 'Case'+ i,recordTypeId = MyRecTypeId,Business_Unit__c = businessUnit.id);  
            listOfTestCases.add(testCase);            
        }
        insert listOfTestCases;
        return listOfTestCases;
    }
    Public static List<Case> createCasesForValidatedUser(String recordTypeName){
        Account testAccount = createAccount();
        List<Case> listOfTestCases = new List<Case>();
        Id MyRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        Business_Unit__c businessUnit = createBusinessUnit();
        Issues_Type__c issueType = createIssueType();
        for(Integer i = 0; i < 1; i++){
            Case testCase = new Case(Accountid = testAccount.id,Case_Group__c=issueType.Case_Group__c,Issue_Type__c=issueType .id, Status= 'New', Subject= 'Case'+ i,recordTypeId = MyRecTypeId,Business_Unit__c = businessUnit.id);  
            listOfTestCases.add(testCase);            
        }
        insert listOfTestCases;
        return listOfTestCases;
    }
    
    Public static List<Case> createCasesForPortalUser(String recordTypeName, String Source){
        Account testAccount = createAccount();
        List<Case> listOfTestCases = new List<Case>();
        Id MyRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        Business_Unit__c businessUnit = createBusinessUnit();
        Issues_Type__c issueType = createIssueType();
        for(Integer i = 0; i < 1; i++){
            Case testCase = new Case(Accountid = testAccount.id,Case_Group__c=issueType.Case_Group__c,Issue_Type__c=issueType .id,Origin = Source,Status= 'New', Subject= 'Case'+ i,recordTypeId = MyRecTypeId,Business_Unit__c = businessUnit.id);  
            listOfTestCases.add(testCase);            
        }
        return listOfTestCases;
    }
    Public static Case updateCaseRecordType(String recordTypeName,Case currCase){
        Id MyRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        currCase.recordTypeId = MyRecTypeId;
        update currCase;
        return currCase;
    }
    
    
}