salesforce-main/src/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Priority Client</fullName>
            </value>
            <value>
                <fullName>In House Client</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/AR_Account_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Account_Status_Code__c</fullName>
    <label>Account Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Country_of_Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Permanent_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Countries List</description>
    <label>Country of Permanent Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>country_list__c.Valid_Domicile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Please select the country with valid domicile true</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Accounts (Country of Permanent Address)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Legal Entity</label>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Level_Code_Text__c.field-meta.xml
<CustomField>
    <fullName>BNR_Level_Code_Text__c</fullName>
    <label>Level Code Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Application_Number__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Application_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Added for SIS Integration.</description>
    <label>Application Number</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Amount__c</fullName>
    <label>Sponsorship Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Level__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Level__c</fullName>
    <label>Sponsorship Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Percentage__c</fullName>
    <label>Sponsorship Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Stage_Text__c.field-meta.xml
<CustomField>
    <fullName>Stage_Text__c</fullName>
    <formula>TEXT(StageName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage Text</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/submitAppBController.cls
public class submitAppBController {
    @AuraEnabled
    public static string submitApp(Id recordId) { 
        System.debug('@submitAppBController Opportunity Id: ' + recordId);
        String Errormsg = '';
        String finalresult = '';
        Boolean checkerror = false;
        
        List<Address__c> address = new List<Address__c>();
        List<Sponsorship__c> sponsorship = new List<Sponsorship__c>();
        BNR_SubmitApplication.submitCalloutWrapper classTwoWrap;
        
        Opportunity opp = [SELECT Id, Name, AccountId, Account.AR_Account_Status_Code__c, Stage_Text__c, BNR_Level_Code_Text__c, Account.Account_Type__c, Account.VAT_Code__pc, Account.Phone, Account.PersonEmail, Account.PersonBirthdate, Account.Primary_Nationality__pc, Account.Age__pc, Account.Country_of_Permanent_Address__c, Account.Country_of_Permanent_Address__r.country_code_2__c, Account.PS_Profile_Services_ID__pc, Account.Student_Type__pc, Account.Legal_Entity__c, Sponsorship_Level__c, Sponsorship_Percentage__c, Sponsorship_Amount__c FROM Opportunity WHERE Id =: recordId]; 
        if (opp != null) {
            if (opp.Account.AR_Account_Status_Code__c == 'FinancialHoldApplied') {
                checkerror = true;
                Errormsg = 'Student is on Financial Hold. Application cannot be submitted</br>';
            } else if (opp.Stage_Text__c != 'Accepted - Conditional Firm' && opp.Stage_Text__c != 'Accepted - Unconditional Firm' && opp.Stage_Text__c != 'Accepted - Pmt Received' && opp.Stage_Text__c != 'Transferred' && opp.Stage_Text__c != 'Deferred Entry'){
                checkerror = true;
                Errormsg = 'Submit Application Failed because the Status is not valid</br>';
            } else {
                address = [SELECT Id, Active__c, Type__c FROM Address__c WHERE Active__c = TRUE AND Student__c =: opp.AccountId];
                if (address.size() == 0) {
                    checkerror = true;
                    Errormsg = 'At least One Active Address is Required</br>';
                }
                if (opp.Account.PersonBirthdate == null) {
                    checkerror = true;
                    Errormsg = 'Student Date of Birth is Required</br>';
                }
                if (opp.Account.Primary_Nationality__pc == null){
                    checkerror = true;
                    Errormsg = 'Student Primary Nationality is Required</br>';
                }
                if (opp.BNR_Level_Code_Text__c == 'PQ') {
                    if (opp.Account.Account_Type__c == null) {
                        checkerror = true;
                        Errormsg = 'Account Type is Required</br>';
                    }
                    if (opp.Account.VAT_Code__pc == null) {
                        checkerror = true;
                        Errormsg = 'VAT Code is Required</br>';
                    }
                    if (opp.Account.Phone == null) {
                        checkerror = true;
                        Errormsg = 'At least One Phone is Required</br>';
                    }
                    if (opp.Account.PersonEmail == null) {
                        checkerror = true;
                        Errormsg = 'At least One Email is Required</br>';
                    }
                }
            
                if ((opp.Account.PersonBirthdate != null) && (opp.BNR_Level_Code_Text__c != 'PQ')) {
                    if (opp.Account.Age__pc < 17) {
                        checkerror = true;
                        Errormsg = 'Student must be at least 17 years old</br>';
                    }
                }
                if (opp.BNR_Level_Code_Text__c != 'PQ') {
                    if (opp.Account.Country_of_Permanent_Address__c == null) {
                        checkerror = true;
                        Errormsg = 'Country of Permanent Address is Required</br>';
                    }
                }
                if (opp.Account.PS_Profile_Services_ID__pc == null) {
                    checkerror = true;
                    Errormsg = 'The related Account does not have a Profile ID. A Profile ID is required to submit an application</br>';
                }
                if (opp.Account.Student_Type__pc == null) {
                    checkerror = true;
                    system.debug('@@Errormsg@@'+Errormsg);
                    Errormsg = Errormsg+ 'Student Type is Required</br>';
                    system.debug('@@Errormsg@@'+Errormsg);
                }
                if (opp.Account.Legal_Entity__c == null) {
                    checkerror = true;
                    Errormsg = 'Legal Entity is Required</br>';
                }
                
                sponsorship = [SELECT Id, Active__c, Student__c FROM Sponsorship__c WHERE Active__c = TRUE AND Student__c =: opp.AccountId AND Opportunity__c =: opp.Id];
                if (sponsorship.size() == 0 && opp.Sponsorship_Level__c != null && opp.Sponsorship_Percentage__c != null && opp.Sponsorship_Amount__c != null) {
                    checkerror = true;
                    Errormsg = 'An Active Sponsorship record on Account should exist if Sponsorship level is Partial or Full</br>';
                }
            }
            
            if (!checkerror){
                classTwoWrap = BNR_SubmitApplication.Submitnew(opp.Id);
                System.debug('@@classTwoWrap@@'+classTwoWrap);
                System.debug('@@classTwoWrap Result@@'+classTwoWrap.newResult);

                if (classTwoWrap.newResult != 'Application Submitted Successfully') { 
                    System.debug('@submitAppBController Entered BNR');
                    finalresult = classTwoWrap.newResult; 
                    System.debug('@submitAppBController Entered BNR result: ' + finalresult);
                }
                else{
                    System.debug('@submitAppBController Entered else BNR');
                    String result_updatesisperson = UpdateSISPerson.PersonInformationnew(classTwoWrap.acc,classTwoWrap.opp);
                    System.debug('@submitAppBController result_updatesisperson: ' + result_updatesisperson);
                    insert classTwoWrap.newApp;

                    classTwoWrap.opp.SFDC_Application_Number__c = classTwoWrap.newApp.id;
                    update classTwoWrap.opp;
                    update classTwoWrap.prodList;
                    update classTwoWrap.acc;
                    
                    finalresult = result_updatesisperson;
                    System.debug('@submitAppBController Entered else BNR result' + finalresult);
                }
           }
        }

        System.debug('@submitAppBController checkerror: ' + checkerror);
        System.debug('@submitAppBController Errormsg: ' + Errormsg);
        return (!checkerror ? finalresult : Errormsg);         
   }
}