salesforce-main/src/main/default/objects/Account/fields/Account_Category__c.field-meta.xml
<CustomField>
    <fullName>Account_Category__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer - FTSE 350 or Equal</fullName>
            </value>
            <value>
                <fullName>Customer - Middle Market</fullName>
            </value>
            <value>
                <fullName>Customer - Small</fullName>
            </value>
            <value>
                <fullName>Customer - Individual</fullName>
            </value>
            <value>
                <fullName>Prospect - FTSE 350 or Equal</fullName>
            </value>
            <value>
                <fullName>Prospect - Middle Market</fullName>
            </value>
            <value>
                <fullName>Prospect - Small</fullName>
            </value>
            <value>
                <fullName>Prospect - Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Acronym_short_title__c.field-meta.xml
<CustomField>
    <fullName>Acronym_short_title__c</fullName>
    <label>Acronym (short title)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
            <value>
                <fullName>PD Special Account Managers</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <label>Profile Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Sector_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Sector_Level_1__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Tier 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PQ</fullName>
            </value>
            <value>
                <fullName>FINANCIAL SERVICES</fullName>
            </value>
            <value>
                <fullName>PROFESSIONAL DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>BUSINESS SCHOOL</fullName>
            </value>
            <value>
                <fullName>PROFESSIONAL APPS</fullName>
            </value>
            <value>
                <fullName>PATHWAYS</fullName>
            </value>
            <value>
                <fullName>LAW SCHOOL</fullName>
            </value>
            <value>
                <fullName>SCHOOL OF HEALTH</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>CIMA</fullName>
                <isActive>false</isActive>
                <label>CIMA</label>
            </value>
            <value>
                <fullName>Education</fullName>
                <isActive>false</isActive>
                <label>Education</label>
            </value>
            <value>
                <fullName>Industry &amp; Commerce</fullName>
                <isActive>false</isActive>
                <label>Industry &amp; Commerce</label>
            </value>
            <value>
                <fullName>Law</fullName>
                <isActive>false</isActive>
                <label>Law</label>
            </value>
            <value>
                <fullName>Law Firms</fullName>
                <isActive>false</isActive>
                <label>Law Firms</label>
            </value>
            <value>
                <fullName>Private (Individuals)</fullName>
                <isActive>false</isActive>
                <label>Private (Individuals)</label>
            </value>
            <value>
                <fullName>Professional Firms</fullName>
                <isActive>false</isActive>
                <label>Professional Firms</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
                <isActive>false</isActive>
                <label>Unknown</label>
            </value>
            <value>
                <fullName>ee</fullName>
                <isActive>false</isActive>
                <label>ee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Sector_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Sector_Level_2__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Tier 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector_Level_1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>A&amp;T</fullName>
            </value>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>AAT APPS</fullName>
            </value>
            <value>
                <fullName>ACCA FT</fullName>
            </value>
            <value>
                <fullName>ACCA PT</fullName>
            </value>
            <value>
                <fullName>Accountancy</fullName>
            </value>
            <value>
                <fullName>ACTUARIAL EDUCATION</fullName>
            </value>
            <value>
                <fullName>Aerospace &amp; Defence</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>ATT APPS</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>BPTC</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>BUS ADMIN</fullName>
            </value>
            <value>
                <fullName>BUSINESS DEGREES</fullName>
            </value>
            <value>
                <fullName>Central Bank</fullName>
            </value>
            <value>
                <fullName>Central Government</fullName>
            </value>
            <value>
                <fullName>CFA</fullName>
            </value>
            <value>
                <fullName>CFAB</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>CII</fullName>
            </value>
            <value>
                <fullName>CILEX</fullName>
            </value>
            <value>
                <fullName>CIM</fullName>
            </value>
            <value>
                <fullName>CIMA</fullName>
            </value>
            <value>
                <fullName>CIMA APPS</fullName>
            </value>
            <value>
                <fullName>CIMA PD</fullName>
            </value>
            <value>
                <fullName>CIPD</fullName>
            </value>
            <value>
                <fullName>CISI</fullName>
            </value>
            <value>
                <fullName>Commercial Bank</fullName>
            </value>
            <value>
                <fullName>Committee</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/SIS_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>SIS_Company_ID__c</fullName>
    <label>SIS Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <description>Pulls the Profile Company Id value from the related Account. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>Student__r.Profile_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Company ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Locality__c/fields/Banner_Code__c.field-meta.xml
<CustomField>
    <fullName>Banner_Code__c</fullName>
    <label>Banner Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ISO Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/classes/Test_CreateCompanyARAccountService.cls
/**
 * This class contains unit tests for validating the behavior of Apex classe 
 * CreateCompanyARAccountService 
 */
@isTest
private class Test_CreateCompanyARAccountService {

    static testMethod void myUnitTest() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = new State_Province__c(Name = 'Unit Test', ISO_Code__c = '123');
        insert stt;
        Locality__c lct = new Locality__c(Name = 'Unit Test', Banner_Code__c = '123');
        insert lct;
        
        Account a = new Account();
        a.Name='Inftes';
        a.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId();
        a.Phone='8015555556';
        a.Profile_Company_ID__c = '1234f567-bc23-42e8-924c-1234asdf5678';
        a.Customer_Type__c = 'Key Client';       
        a.Account_Category__c = 'Customer - FTSE 350 or Equal';
        a.Sector_Level_1__c = 'Financial Services';
        a.Sector_Level_2__c = 'Broker';
        insert a;
        
        Address__c add1 = new Address__c();
        //StopRecursion.Dorun = true;
        add1.Student__c = a.Id; 
        add1.Type__c = 'Home';
        add1.Street_1__c = '329 S Tonne Dr';
        add1.Street_2__c = '123';
        add1.Street_3__c = '123';
        add1.Street_4__c = '12';
        add1.City__c = 'Chicago';
        add1.Locality__c = lct.Id;
        add1.State_Province__c = stt.Id;
        add1.Zip_Postal_Code__c = '12345';
        add1.Lookup_Country__c = cntry.Id;
        insert add1;
        
        
        string validSIS = CreateCompanyARAccountService.validationRulesForSIS(a.Id);        
        string validAR = CreateCompanyARAccountService.validationRulesForAR(a.Id);
        a.SIS_Company_ID__c = 'Bp343d32';
        a.Legal_Entity__c = 'UC';
        update a;
        CreateCompanyARAccountService.testFail = false;
        CreateCompanyARAccountService.companyARAccInt(a.Id);
        CreateCompanyARAccountService.testFail = true;
        CreateCompanyARAccountService.companyARAccInt(a.Id);
        
        validAR = CreateCompanyARAccountService.validationRulesForAR(a.Id);
        validSIS = CreateCompanyARAccountService.validationRulesForSIS(a.Id);
    }
    
    static testMethod void myUnitTest2() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = new State_Province__c(Name = 'Unit Test', ISO_Code__c = '123');
        insert stt;
        Locality__c lct = new Locality__c(Name = 'Unit Test', Banner_Code__c = '123');
        insert lct;
        
        Account a = new Account();
        a.Name='Inftes';
        a.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId();
        a.Phone='8015555556';
        a.Profile_Company_ID__c = '1234f567-bc23-42e8-924c-1234asdf5678';
        a.Customer_Type__c = 'Key Client';       
        a.Account_Category__c = 'Customer - FTSE 350 or Equal';
        a.Sector_Level_1__c = 'Financial Services';
        a.Sector_Level_2__c = 'Broker';
        insert a;
        
        Address__c add1 = new Address__c();
        //StopRecursion.Dorun = true;
        add1.Student__c = a.Id; 
        add1.Type__c = 'Home';
        add1.Street_1__c = '329 S Tonne Dr';
        add1.Street_2__c = '123';
        add1.Street_3__c = '123';
        add1.Street_4__c = '12';
        add1.City__c = 'Chicago';
        add1.Locality__c = lct.Id;
        add1.State_Province__c = stt.Id;
        add1.Zip_Postal_Code__c = '12345';
        add1.Lookup_Country__c = cntry.Id;
        insert add1;
        
        
        string validSIS = CreateCompanyARAccountService.validationRulesForSIS(a.Id);        
        string validAR = CreateCompanyARAccountService.validationRulesForAR(a.Id);
        a.Legal_Entity__c = 'UC';
        a.Acronym_short_title__c = 'test';
        update a;
        CreateCompanyARAccountService.testFail = false;
        CreateARSISServiceController.ARSISService(a.Id);
    }
    
    static testMethod void myUnitTest3() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = new State_Province__c(Name = 'Unit Test', ISO_Code__c = '123');
        insert stt;
        Locality__c lct = new Locality__c(Name = 'Unit Test', Banner_Code__c = '123');
        insert lct;
        
        Account a = new Account();
        a.Name='Inftes';
        a.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId();
        a.Phone='8015555556';
        a.Customer_Type__c = 'Key Client';       
        a.Account_Category__c = 'Customer - FTSE 350 or Equal';
        a.Sector_Level_1__c = 'Financial Services';
        a.Sector_Level_2__c = 'Broker';
        insert a;
        
        Address__c add1 = new Address__c();
        //StopRecursion.Dorun = true;
        add1.Student__c = a.Id; 
        add1.Type__c = 'Home';
        add1.Street_1__c = '329 S Tonne Dr';
        add1.Street_2__c = '123';
        add1.Street_3__c = '123';
        add1.Street_4__c = '12';
        add1.City__c = 'Chicago';
        add1.Locality__c = lct.Id;
        add1.State_Province__c = stt.Id;
        add1.Zip_Postal_Code__c = '12345';
        add1.Lookup_Country__c = cntry.Id;
        insert add1;
        
        
        string validSIS = CreateCompanyARAccountService.validationRulesForSIS(a.Id);        
        string validAR = CreateCompanyARAccountService.validationRulesForAR(a.Id);
        a.SIS_Company_ID__c = 'Bp343d32';
        a.Legal_Entity__c = 'UC';
        update a;
        CreateCompanyARAccountService.testFail = false;
        CreateARSISServiceController.ARSISService(a.Id);
    }
    
    static testMethod void myUnitTest4() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = new State_Province__c(Name = 'Unit Test', ISO_Code__c = '123');
        insert stt;
        Locality__c lct = new Locality__c(Name = 'Unit Test', Banner_Code__c = '123');
        insert lct;
        
        Account a = new Account();
        a.Name='Inftes';
        a.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId();
        a.Profile_Company_ID__c = '1234f567-bc23-42e8-924c-1234asdf5678';
        a.Phone='8015555556';
        a.Customer_Type__c = 'Key Client';       
        a.Account_Category__c = 'Customer - FTSE 350 or Equal';
        a.Sector_Level_1__c = 'Financial Services';
        a.Sector_Level_2__c = 'Broker';
        insert a;
        
        Address__c add1 = new Address__c();
        //StopRecursion.Dorun = true;
        add1.Student__c = a.Id; 
        add1.Type__c = 'Home';
        add1.Street_1__c = '329 S Tonne Dr';
        add1.Street_2__c = '123';
        add1.Street_3__c = '123';
        add1.Street_4__c = '12';
        add1.City__c = 'Chicago';
        add1.Locality__c = lct.Id;
        add1.State_Province__c = stt.Id;
        add1.Zip_Postal_Code__c = '12345';
        add1.Lookup_Country__c = cntry.Id;
        insert add1;
        
        
        string validSIS = CreateCompanyARAccountService.validationRulesForSIS(a.Id);        
        string validAR = CreateCompanyARAccountService.validationRulesForAR(a.Id);
        a.SIS_Company_ID__c = 'Bp343d32';
        a.Legal_Entity__c = 'UC';
        a.AR_Global_Customer_Number__c = '73910481';
        update a;
        CreateCompanyARAccountService.testFail = false;
        CreateCompanyARAccountService.companyARAccInt(a.Id);
        CreateCompanyARAccountService.testFail = true;
        CreateCompanyARAccountService.companyARAccInt(a.Id);
        
        CreateARSISServiceController.ARSISService(a.Id);
    }
}