salesforce-main/src/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Priority Client</fullName>
            </value>
            <value>
                <fullName>In House Client</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/AR_Account_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>AR_Account_Status_Code__c</fullName>
    <label>Account Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Country_of_Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Permanent_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Countries List</description>
    <label>Country of Permanent Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>country_list__c.Valid_Domicile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Please select the country with valid domicile true</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Accounts (Country of Permanent Address)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Legal Entity</label>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Level_Code_Text__c.field-meta.xml
<CustomField>
    <fullName>BNR_Level_Code_Text__c</fullName>
    <label>Level Code Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Enrolment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Status__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <description>Stages to enrolment once application has been accepted</description>
    <label>Enrolment Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Post-Registration (non-attendees)</fullName>
            </value>
            <value>
                <fullName>First Instalment Paid</fullName>
            </value>
            <value>
                <fullName>Temporarily Registered</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_RESD_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_RESD_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions RESD Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U~ UK National</fullName>
            </value>
            <value>
                <fullName>L~ Indefinite Leave to Remain</fullName>
            </value>
            <value>
                <fullName>R~ Right of Abode</fullName>
            </value>
            <value>
                <fullName>E~ EU National</fullName>
            </value>
            <value>
                <fullName>F~ EU National Family Member</fullName>
            </value>
            <value>
                <fullName>M~ EEA Family Member</fullName>
            </value>
            <value>
                <fullName>R~ Refugee</fullName>
            </value>
            <value>
                <fullName>B~ Refugee Family Member</fullName>
            </value>
            <value>
                <fullName>H~ Humanitarian Protection</fullName>
            </value>
            <value>
                <fullName>P~ Humanitarian Protection Family</fullName>
            </value>
            <value>
                <fullName>T~ Child of a Turkish worker</fullName>
            </value>
            <value>
                <fullName>C~ Child of a Swiss National</fullName>
            </value>
            <value>
                <fullName>A~ EEA</fullName>
            </value>
            <value>
                <fullName>O~ Non-EEA VISA  required</fullName>
            </value>
            <value>
                <fullName>V~ Non-EEA no VISA required</fullName>
            </value>
            <value>
                <fullName>G~ England</fullName>
            </value>
            <value>
                <fullName>S~ Scotland</fullName>
            </value>
            <value>
                <fullName>W~ Wales</fullName>
            </value>
            <value>
                <fullName>N~ Northern Ireland</fullName>
            </value>
            <value>
                <fullName>I~ Islands (Man, Channel)</fullName>
            </value>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_STYPE_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_STYPE_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions STYPE Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
            <value>
                <fullName>N~ New</fullName>
            </value>
            <value>
                <fullName>R~ Returning</fullName>
            </value>
            <value>
                <fullName>C~ Continuing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Cohort_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Cohort_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Cohort Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1~ Cohort January</fullName>
            </value>
            <value>
                <fullName>C2~ Cohort February</fullName>
            </value>
            <value>
                <fullName>C3~ Cohort March</fullName>
            </value>
            <value>
                <fullName>C4~ Cohort April</fullName>
            </value>
            <value>
                <fullName>C5~ Cohort May</fullName>
            </value>
            <value>
                <fullName>C6~ Cohort June</fullName>
            </value>
            <value>
                <fullName>C7~ Cohort July</fullName>
            </value>
            <value>
                <fullName>C8~ Cohort August</fullName>
            </value>
            <value>
                <fullName>C9~ Cohort September</fullName>
            </value>
            <value>
                <fullName>C10~ Cohort October</fullName>
            </value>
            <value>
                <fullName>C11~ Cohort November</fullName>
            </value>
            <value>
                <fullName>C12~ Cohort December</fullName>
            </value>
            <value>
                <fullName>S1~ SLC May</fullName>
            </value>
            <value>
                <fullName>S2~ SLC Sep</fullName>
            </value>
            <value>
                <fullName>S3~ SLC Jan</fullName>
            </value>
            <value>
                <fullName>H1~ HESA 11/12</fullName>
            </value>
            <value>
                <fullName>H2~ HESA 12/13</fullName>
            </value>
            <value>
                <fullName>H3~ HESA 13/14</fullName>
            </value>
            <value>
                <fullName>H4~ HESA 14/15</fullName>
            </value>
            <value>
                <fullName>H5~ HESA 15/16</fullName>
            </value>
            <value>
                <fullName>H6~ HESA 16/17</fullName>
            </value>
            <value>
                <fullName>H7~ HESA 17/18</fullName>
            </value>
            <value>
                <fullName>H8~ HESA 18/19</fullName>
            </value>
            <value>
                <fullName>H9~ HESA 19/20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Amount__c</fullName>
    <label>Sponsorship Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Level__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Level__c</fullName>
    <label>Sponsorship Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Percentage__c</fullName>
    <label>Sponsorship Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

salesforce-main/src/main/default/classes/submitAppBControllerTest.cls
@isTest
public class submitAppBControllerTest {
    @testSetup
	static void testSetup() {
		Database.DMLOptions dbDML = new Database.DMLOptions(); 
		dbDML.DuplicateRuleHeader.allowSave = true;
		dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
        Account studentAccount = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId(),
            FirstName = 'TestAccount',
            LastName = 'Student2',
            PersonBirthdate = Date.newInstance(2002,2,1),
            Preferred_Email__pc = 'Personal',
            Preferred_Phone__pc = 'Mobile',
            PersonEmail = 'john2@john.com',
            Personal_Email__pc = 'john2@john.com',
            PersonMobilePhone ='+447716123222',
            Account_Type__c = 'General', 
            VAT_Code__pc = '123456789',  
            Domicile__pc = 'XF~ England', 
            PS_Profile_Services_ID__pc = 'ba618412-c3d7-4752-67yu-17c52bfc20c8', 
            Student_Type__pc = 'Domestic', 
            AR_Account_Status_Code__c = 'test',
            Legal_Entity__c = 'UC~COL',
            Parent_Guardian_Occupation__pc = '0000~ Not stated',
            SFDC_Disability_Status_Code_Select__pc = '0~ No Known Disability'
            //SFDC_Disability_Type_Code_Select__pc = '0~ No Known Disability'
        );
		Database.insert(studentAccount, dbDML);

        Opportunity opportunity = new Opportunity(
            Name = 'TestOpportunity2', 
            AccountId = studentAccount.Id,
            CloseDate = System.today(),
            Enrolment_Status__c = 'Acceptance',
            StageName = 'Accepted - Conditional Firm', 
            BNR_Level_Code_Text__c = 'Code Text', 
            Sponsorship_Level__c = 'Partial', 
            Sponsorship_Percentage__c = 50,
            SFDC_Admissions_STYPE_Code_Select__c = '0~ Undeclared',
            SFDC_Admissions_RESD_Code_Select__c = '0~ Undeclared',
            SFDC_Cohort_Code_Select__c = 'C7~ Cohort July'
        );
		Database.insert(opportunity, dbDML);

        Address__c address = new Address__c(
            Student__c = studentAccount.Id,
            Type__c = 'Home',
            Street_1__c = '329 S Tonne Dr',
            Street_2__c = '123',
            Street_3__c = '123',
            Street_4__c = '12',
            City__c = 'Chicago',
            Zip_Postal_Code__c = '12345'
        );
		Database.insert(address, dbDML);
    }

    @isTest
    public static void unitTest4() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
            acc.AR_Account_Status_Code__c = 'FinancialHoldApplied';
            Database.update(acc, dbDML);

            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }

    @isTest
    public static void unitTest5() {
        Test.startTest();
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }

    @isTest
    public static void unitTest6() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];

            Address__c address = [SELECT Id FROM Address__c];
            address.Student__c = NULL;
            Database.update(address, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }

    @isTest
    public static void unitTest7() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
            acc.PersonBirthdate = null;
            Database.update(acc, dbDML);
            
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }

    @isTest
    public static void unitTest8() {
        Test.startTest();
            country_list__c cntry = new country_list__c(Name = 'United Kingdom', ISO_Code__c = 'GBR', country_code_2__c = 'GB');
            insert cntry;
			
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;

            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
            acc.Primary_Nationality__pc = cntry.Id;
            acc.Account_Type__c = null;
            acc.VAT_Code__pc = null;
            acc.Phone = null;
            acc.Preferred_Email__pc = null;
            acc.Preferred_Phone__pc = null;
            acc.PersonEmail = null;
            acc.Personal_Email__pc = null;
            acc.PersonMobilePhone = null;
            Database.update(acc, dbDML);
            
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.BNR_Level_Code_Text__c = 'PQ';
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
	
	@isTest
    public static void unitTestNoARStatusCode() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
        	acc.AR_Account_Status_Code__c = 'FinancialHoldApplied';
        	Database.update(acc, dbDML);

            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Confirmed';
            opp.Enrolment_Status__c = null;
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
	
	@isTest
    public static void unitTestWrongStatus() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Closed Won';
            opp.Enrolment_Status__c = null;
        	opp.BNR_Level_Code_Text__c = 'PQ';
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
	
	@isTest
    public static void unitTestNoAddressOrSponsorship() {
        Test.startTest();
			delete [SELECT Id FROM Address__c];
			delete [SELECT Id FROM Sponsorship__c];
        
        	Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
        
        	Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Closed Won';
            opp.Enrolment_Status__c = null;
        	opp.Sponsorship_Amount__c = 50;
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
	
	@isTest
    public static void unitTestNulls() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
        	acc.PersonBirthdate = null;
        	acc.Account_Type__c = null;
        	acc.VAT_Code__pc = null;
        	acc.Phone = null;
        	acc.PersonEmail = null;
        	acc.Domicile__pc = null;
        	acc.PS_Profile_Services_ID__pc = null;
        	acc.Student_Type__pc = null;
        	acc.Legal_Entity__c = null;
        	Database.update(acc, dbDML);
			
			Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Closed Won';
            opp.Enrolment_Status__c = null;
        	opp.BNR_Level_Code_Text__c = 'PQ';
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
	
	@isTest
    public static void unitTestNullsNotPQ() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
        	acc.PersonBirthdate = System.today().addYears(-15);
        	acc.Domicile__pc = null;
        	acc.PS_Profile_Services_ID__pc = null;
        	acc.Student_Type__pc = null;
        	acc.Legal_Entity__c = null;
        	Database.update(acc, dbDML);
			
			Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Accepted - Conditional Firm';
            opp.Enrolment_Status__c = null;
        	opp.BNR_Level_Code_Text__c = null;
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
    
    @isTest
    public static void unitTestNullsPQ1() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
        	acc.PersonBirthdate = System.today().addYears(-15);
        	acc.Domicile__pc = null;
        	acc.PS_Profile_Services_ID__pc = null;
        	acc.Student_Type__pc = null;
        	acc.Legal_Entity__c = null;
        	acc.Account_Type__c = null;
        	Database.update(acc, dbDML);
			
			Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Accepted - Conditional Firm';
            opp.Enrolment_Status__c = null;
        	opp.BNR_Level_Code_Text__c = 'PQ';
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
    
    @isTest
    public static void unitTestNullsPQ2() {
        Test.startTest();
			Database.DMLOptions dbDML = new Database.DMLOptions(); 
			dbDML.DuplicateRuleHeader.allowSave = true;
			dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
		
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
        	acc.PersonBirthdate = System.today().addYears(-15);
        	acc.Domicile__pc = null;
        	acc.PS_Profile_Services_ID__pc = null;
        	acc.Student_Type__pc = null;
        	acc.Legal_Entity__c = null;
        	acc.VAT_Code__pc = null;
        	Database.update(acc, dbDML);
			
			Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
            opp.StageName = 'Accepted - Conditional Firm';
            opp.Enrolment_Status__c = null;
        	opp.BNR_Level_Code_Text__c = 'PQ';
            Database.update(opp, dbDML);

            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
    
    @isTest
    public static void unitTestSuccess() {
        Test.startTest();
            country_list__c cntry = new country_list__c(Name = 'United Kingdom', ISO_Code__c = 'GBR', country_code_2__c = 'GB', Valid_Nationality__c = true, Valid_Domicile__c = true);
            insert cntry;
            
            Database.DMLOptions dbDML = new Database.DMLOptions(); 
        	dbDML.DuplicateRuleHeader.allowSave = true;
        	dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
            
            Account acc = [SELECT Id FROM Account WHERE Name = 'TestAccount Student2'];
            acc.Primary_Nationality__pc = cntry.Id;
        	acc.Country_of_Permanent_Address__c = cntry.Id;
            Database.update(acc, dbDML);
            
            Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'TestOpportunity2'];
    
            String result = submitAppBController.submitApp(opp.Id);
            System.debug(result);
        Test.stopTest();
    }
}