salesforce-main/src/main/default/objects/Account/fields/Acronym_short_title__c.field-meta.xml
<CustomField>
    <fullName>Acronym_short_title__c</fullName>
    <label>Acronym (short title)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Correspondence_Detail__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Detail__c</fullName>
    <label>Correspondence Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
            <value>
                <fullName>PD Special Account Managers</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/EU_Tax_registered__c.field-meta.xml
<CustomField>
    <fullName>EU_Tax_registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EU Tax registered</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Industry_Type_SIC__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type_SIC__c</fullName>
    <label>Industry Type (SIC)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A~ Agriculture, forestry and fishing</fullName>
            </value>
            <value>
                <fullName>B~ Mining and quarrying</fullName>
            </value>
            <value>
                <fullName>C~ Manufacturing</fullName>
            </value>
            <value>
                <fullName>D~ Electricity, gas, steam and air conditioning supply</fullName>
            </value>
            <value>
                <fullName>E~ Water supply; sewerage, waste management and remediation activities</fullName>
            </value>
            <value>
                <fullName>F~ Construction</fullName>
            </value>
            <value>
                <fullName>G~ Wholesale and retail trade; repair of motor vehicles and motor cycles</fullName>
            </value>
            <value>
                <fullName>H~ Transport and storage</fullName>
            </value>
            <value>
                <fullName>I~ Accommodation and food service activities</fullName>
            </value>
            <value>
                <fullName>J~ Information and communication</fullName>
            </value>
            <value>
                <fullName>K~ Financial and insurance activities</fullName>
            </value>
            <value>
                <fullName>L~ Real estate activities</fullName>
            </value>
            <value>
                <fullName>M~ Professional, scientific and technical activities</fullName>
            </value>
            <value>
                <fullName>N~ Administrative and support service activities</fullName>
            </value>
            <value>
                <fullName>O~ Public administration and defense; compulsory social security</fullName>
            </value>
            <value>
                <fullName>P~ Education</fullName>
            </value>
            <value>
                <fullName>Q~ Human health and social work activities</fullName>
            </value>
            <value>
                <fullName>R~ Arts, entertainment and recreation</fullName>
            </value>
            <value>
                <fullName>S~ Other service activities</fullName>
            </value>
            <value>
                <fullName>T~ Activities of households as employers; undifferentiated goods and services-producing activities of households for own use</fullName>
            </value>
            <value>
                <fullName>U~ Activities of extraterritorial organizations and bodies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Invoice_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Email_Address__c</fullName>
    <label>Invoice Email Address</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <label>Profile Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Use_This_One__c.field-meta.xml
<CustomField>
    <fullName>Use_This_One__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked to indicate main account if duplicates are present.

Legacy field for BD to indicate record of use prior to data cleansing.</description>
    <label>Use This One</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/VAT_number__c.field-meta.xml
<CustomField>
    <fullName>VAT_number__c</fullName>
    <label>VAT number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrimary</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <description>Pulls the Profile Company Id value from the related Account. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>Student__r.Profile_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Company ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Integration_Log__c/fields/Salesforce_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_ID__c</fullName>
    <label>Salesforce ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Locality__c/fields/Banner_Code__c.field-meta.xml
<CustomField>
    <fullName>Banner_Code__c</fullName>
    <label>Banner Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ISO Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/classes/CreateCompanyProfile.cls
global with sharing class CreateCompanyProfile{
    //public static string endPoint = '/rest/company/v1/companies/createUpdateCompanyInfo';
    public static string endPoint_findmatch = '/rest/company/v2/companies/findMatchingCompany';
    public static string endPoint_insert = '/rest/company/v1/companies';
    public static string endPoint_update = '/rest/company/v2/companies';
    
    public static Boolean bFailSIS = false;
    
    WebService static String CompanyInformation(String accountId){
        String result;
        Account acc = [Select Id, Acronym_short_title__c, Name, VAT_number__c, EU_Tax_registered__c, Reporting_Required__c, 
                              Correspondence_Detail__c, Customer_Type__c, Profile_Company_ID__c, Industry_Type_SIC__c, Use_This_One__c,
                              Phone, Invoice_Email_Address__c, Fax,
                                  (Select Id, Type__c, Street_1__c, Street_2__c, Street_3__c, Street_4__c, City__c, State_Province__r.ISO_CODE__c, 
                                  Zip_Postal_Code__c, Lookup_Country__r.ISO_CODE__c, Locality__r.Banner_Code__c, Primary__c From Addresses__r Where Active__c = true) 
                                  From Account Where Id = :accountId Limit 1];
        String strRet = sendCompanyInformation(acc);
        
        result = strRet;
        return result;
    }
     
    public class companyTypeInfo{
        public companyType company = new companyType();
    }
    
    public class UpdatecompanyTypeInfo{
        public companyType company = new companyType();
        //public string profileId;
        public DeleteEntityType deleteEntity;
    }
    
    public class companyType {
        public companyInformationType companyInformation = new companyInformationType();
        public CustType customerType = new CustType();
        public AddressDTO addresses = new AddressDTO();
        
        public EmailDTO emails = new EmailDTO();
        public PhoneDTO phones = new PhoneDTO();
        //public Identity identities = new Identity();
    }
    
    public class companyInformationType {
        public string shortName = '';
        public string companyName = '';
        public string taxId = '';
        public string euTaxRegistered = '';
        public boolean poRequired = false;
        public string isoCountryCode = '';
        public string preferredMethodOfCorrespondence = '';
    }
    
    public class CustType {
        public string value = '';
    }
    
    public class AddressDTO {
        List<AddressType> values = new List<AddressType>();
    }
    
    public class AddressType {
        public string type = '';
        public string line1 = '';
        public string line2 = '';
        public string line3 = '';
        public string line4 = '';
        public string city = '';
        public string stateProvince = '';
        public string locality = '';
        public string postalCode = '';
        public string country = '';
        public boolean isPrimary = false;
        public boolean isCertified = false;
    }
    
    public class EmailDTO {
        List<EmailType> values = new List<EmailType>();
    }
    
    public class EmailType {
        public string type = '';
        public string emailAddress = '';
        public boolean isPrimary = false;
    }
    
    public class PhoneDTO {
        List<PhoneType> values = new List<PhoneType>();
    }
    
    public class PhoneType {
        public string type = '';
        public string areaCode = '';
        public string phoneNumber = '';
        public string extension = '';
        public string countryCode = '';
        public boolean isPrimary = false;
    }
    
    /*public class Identity {
        List<IdentityType> values = new List<IdentityType>();
    }
    
    public class IdentityType {
        public string value = '';
        public string type = '';
        public boolean active = false;
    }*/
    
    public class DeleteEntityType {
        public DeleteAddressDTO addresses = new DeleteAddressDTO(); 
        public DeleteEmailDTO emails = new DeleteEmailDTO();   
        public DeletePhoneDTO phones = new DeletePhoneDTO(); 
    }
    
    public class DeleteAddressDTO {
        List<DeleteAddressType> values = new List<DeleteAddressType>();
    }    
    
    public class DeleteAddressType {
        public string type = '';
    }
     
    public class DeleteEmailDTO {
        List<DeleteEmailType> values = new List<DeleteEmailType>();
    }   
    
    public class DeleteEmailType {
        public string type = '';
    }
    
    public class DeletePhoneDTO {
        List<DeletePhoneType> values = new List<DeletePhoneType>();
    }   
    
    public class DeletePhoneType {
        public string type = '';
    }
    
    
    public static String sendCompanyInformation(Account acc){
        string result;
        if (acc != null){
            CompanyTypeInfo cti = new CompanyTypeInfo();
            
            if (acc.Acronym_short_title__c != null && acc.Acronym_short_title__c != ''){
                cti.company.companyInformation.shortName = acc.Acronym_short_title__c;
            }
            if (acc.Name != null && acc.Name != ''){
                cti.company.companyInformation.companyName = acc.Name;
            }
            if (acc.VAT_number__c != null && acc.VAT_number__c != ''){
                cti.company.companyInformation.taxId = acc.VAT_number__c;
            }
            if (acc.EU_Tax_registered__c != null){
                cti.company.companyInformation.euTaxRegistered = acc.EU_Tax_registered__c ? '1' : '0';
            }
            if (acc.Reporting_Required__c != null){
                cti.company.companyInformation.poRequired = acc.Reporting_Required__c;
            }
            if (acc.Correspondence_Detail__c != null && acc.Correspondence_Detail__c != ''){
                cti.company.companyInformation.preferredMethodOfCorrespondence = acc.Correspondence_Detail__c;
            }
            if (acc.Customer_Type__c != null && acc.Customer_Type__c != ''){
                cti.company.customerType.value = acc.Customer_Type__c;
            }
            
            cti.company.addresses.values = new List<AddressType>();
            for (Address__c addr : acc.Addresses__r){
                AddressType adr = new AddressType();
                if (addr.Type__c != null && addr.Type__c != ''){
                    if(addr.Type__c == 'Next of Kin/Emergency/Guardian'){
                        adr.type = 'Parent';
                    }
                    else{
                        adr.type = addr.Type__c;
                    }
                }
                if (addr.Street_1__c != null && addr.Street_1__c != ''){
                    adr.line1 = addr.Street_1__c;
                }
                if (addr.Street_2__c != null && addr.Street_2__c != ''){
                    adr.line2 = addr.Street_2__c;
                }
                if (addr.Street_3__c != null && addr.Street_3__c != ''){
                    adr.line3 = addr.Street_3__c;
                }
                if (addr.Street_4__c != null && addr.Street_4__c != ''){
                    adr.line4 = addr.Street_4__c;
                }
                if (addr.City__c != null && addr.City__c != ''){
                    adr.city = addr.City__c;
                }
                if (addr.State_Province__c != null && addr.State_Province__r.ISO_CODE__c != null && 
                    addr.State_Province__r.ISO_CODE__c != ''){
                    adr.stateProvince = addr.State_Province__r.ISO_CODE__c;
                }
                if (addr.Locality__c != null && addr.Locality__r.Banner_Code__c != null && 
                    addr.Locality__r.Banner_Code__c != ''){
                    adr.locality = addr.Locality__r.Banner_Code__c;
                }
                if (addr.Zip_Postal_Code__c != null && addr.Zip_Postal_Code__c != ''){
                    adr.postalCode = addr.Zip_Postal_Code__c;
                }
                if (addr.Lookup_Country__c != null && addr.Lookup_Country__r.ISO_CODE__c != null && 
                    addr.Lookup_Country__r.ISO_CODE__c != ''){
                    adr.country = addr.Lookup_Country__r.ISO_CODE__c;
                }
                adr.isPrimary = addr.Primary__c;
                adr.isCertified = addr.Primary__c;
                
                cti.company.addresses.values.add(adr);
            }
            
            cti.company.emails.values = new List<EmailType>();
            if(acc.Invoice_Email_Address__c!= null){
                EmailType et = new EmailType();
                et.type = 'Billing';
                et.emailAddress = acc.Invoice_Email_Address__c;
                et.isPrimary = true;
                cti.company.emails.values.add(et);
            }
            cti.company.phones.values = new List<PhoneType>();
            if(acc.Phone != null){
                PhoneType pt = BuildPhone.BuildPhoneTypeDTO(acc.Phone, 'Business', true);
                cti.company.phones.values.add(pt);              
            }
            if(acc.Fax != null){
                PhoneType pt = BuildPhone.BuildPhoneTypeDTO(acc.Fax, 'Fax', false);
                cti.company.phones.values.add(pt);
            }
            
            String jsonRequest = JSON.serialize(cti);
            system.debug(jsonRequest +'Company Profile');
            Http http = new Http();
            //HttpRequest req = BPPIntegrationConfig.callRestService(jsonRequest, 'application/json', endPoint);
            HttpRequest req = BPPIntegrationConfig.callRestService(jsonRequest, 'application/json', endPoint_findmatch);
            
            system.debug('Final JSON: ' + req.getMethod() + ' ' + req.getEndPoint() + 'Accept-Encoding:' + req.getHeader('Accept-Encoding') +'Accept:' + req.getHeader('Accept') + 'Content-Type:' + req.getHeader('Content-Type') + 'tenantId:' + req.getHeader('tenantId') + req.getBody());
            system.debug(req.toString());
            HttpResponse res = null;
            if (Test.isRunningTest()){
                res = new HttpResponse();
                if (bFailSIS){
                    String strResponse = '{"companyId":"1234f567-bc23-42e8-924c-1234asdf5678","operation":"UPDATE"}';
                    res.setStatusCode(200);
                    res.setStatus('OK');
                    res.setBody(strResponse);
                }
                else{
                    String strResponse = '{"self":"null","httpMethod":"DELETE","errorMessage":"Cannot find Company or Profile Record for the specified Id: 1231231231","errorCode":"PLATFORM-801","transactionId":"A563C5CD-4CA9-B1C6-392A-09377720BFAC"}';
                    res.setStatusCode(200);
                    res.setStatus('Internal Error');
                    res.setBody(strResponse);
                }
            }
            else{
                res = http.send(req);
            }
            system.debug(res.getBody());
            system.debug(res.getStatus());
            
            /* Integration Log */
            Integration_Log__c intg = new Integration_Log__c();
            intg.Request__c =  jsonRequest;
            intg.Response__c = res.getBody();
            intg.Salesforce_ID__c = acc.Id;
            intg.Integration_Type__c = 'Find Matching Company';
            
            String companyProfile;
            if (res.getStatus() == 'OK' && res.getStatusCode() == 200){
                //resp is a JSON string
                JSONParser parser = JSON.createParser(res.getBody());
                while (parser.nextToken() != null) {
                    if ((parser.getCurrentToken() == JSONToken.FIELD_NAME)){
                        String fieldName = parser.getText();
                        parser.nextToken();
                        if(fieldName == 'id') {
                            companyProfile = parser.getText();
                            system.debug('CompanyProfile' + companyProfile);
                            result = 'Success';
                            break;
                        }
                    }
                }
                
                list<Account> chkDupe = [Select id,Profile_Company_ID__c,Name from Account where Profile_Company_ID__c =: companyProfile and Profile_Company_ID__c != null];
                if(chkDupe.size()>0)
                    result = 'Potential duplicate company record. Check existing account:\n\n'+ chkDupe[0].Name;
                
                else if (parser.nextToken() == null) {
                    //insert new company account in profile   
                    HttpRequest req_inst = BPPIntegrationConfig.callRestService(jsonRequest, 'application/json', endPoint_insert);
                
                    system.debug('Final JSON: ' + req_inst.getMethod() + ' ' + req_inst.getEndPoint() + 'Accept-Encoding:' + req_inst.getHeader('Accept-Encoding') +'Accept:' + req_inst.getHeader('Accept') + 'Content-Type:' + req_inst.getHeader('Content-Type') + 'tenantId:' + req_inst.getHeader('tenantId') + req_inst.getBody());
                    system.debug(req_inst.toString());
                    HttpResponse res_inst = null;
                    if (Test.isRunningTest()){
                      res_inst = new HttpResponse();
                      if (bFailSIS){
                          String strResponse = '{"companyId":"1234f567-bc23-42e8-924c-1234asdf5678","operation":"UPDATE"}';
                          res_inst.setStatusCode(200);
                          res_inst.setStatus('OK');
                          res_inst.setBody(strResponse);
                      }
                      else{
                        String strResponse = '{"self":"null","httpMethod":"DELETE","errorMessage":"Cannot find Company or Profile Record for the specified Id: 1231231231","errorCode":"PLATFORM-801","transactionId":"A563C5CD-4CA9-B1C6-392A-09377720BFAC"}';
                          res_inst.setStatusCode(200);
                          res_inst.setStatus('OK');
                          res_inst.setBody(strResponse);
                      }
                    }
                    else{
                        res_inst = http.send(req_inst);
                    }
                    system.debug(res_inst.getBody());
                    system.debug(res_inst.getStatus());                   
                    
                    /* Integration Log */
                    Integration_Log__c intg_inst = new Integration_Log__c();
                    intg_inst.Request__c =  jsonRequest;
                    intg_inst.Response__c = res_inst.getBody();
                    intg_inst.Salesforce_ID__c = acc.Id;
                    intg_inst.Integration_Type__c = 'Insert Company';
                    
                    String companyProfile_inst;
                    if (res_inst.getStatus() == 'OK' && res_inst.getStatusCode() == 200){
        
                        JSONParser parser_inst = JSON.createParser(res_inst.getBody());
                        while (parser_inst.nextToken() != null) {
                            if ((parser_inst.getCurrentToken() == JSONToken.FIELD_NAME)){
                                String fieldName = parser_inst.getText();
                                parser_inst.nextToken();
                                if(fieldName == 'companyId') {   
                                companyProfile_inst = parser_inst.getText();
                                    system.debug('CompanyProfileDebug' + companyProfile_inst);
                                    result = 'Success';
                                    break;
                                }
                            }
                        }
                        //update account with profile id
                        acc.Profile_Company_ID__c = companyProfile_inst;
                        update acc;
                
                    }
                    else{
                        //error handling for insert call
                        JSONParser jParser_inst = JSON.createParser(res_inst.getBody());
                        while(jParser_inst.nextToken() != null){
                            if((jParser_inst.getCurrentToken() == JSONToken.FIELD_NAME)){
                                string fieldN = jParser_inst.getText();
                                jParser_inst.nextToken();
                                if(fieldN == 'errorMessage'){
                                    result = jParser_inst.getText();
                                    system.debug('errorMessage' + result);
                                    break;
                                }
                            }
                        }
                    }
                    insert intg_inst;
                }//end insert new company account
                    
            }
            else{ 
                //error handling for find company call
                JSONParser jParser = JSON.createParser(res.getBody());
                while(jParser.nextToken() !=null){
                    if((jParser.getCurrentToken() == JSONToken.FIELD_NAME)){
                        string fieldN = jParser.getText();
                        jParser.nextToken();
                        if(fieldN == 'errorMessage'){
                            result = jParser.getText();
                            system.debug('errorMessage' + result);
                            break;
                        }
                    }
                }
            }
            insert intg;                    
        }
        return result;
    }
    
        
        
    @future(callOut=true)
    public static void UpdateCompanyInformation(String strProfileId, String AccountId, String AddressType, Boolean AddressDeleted){
        Account acc = [Select Id, Acronym_short_title__c, Name, VAT_number__c, EU_Tax_registered__c, Reporting_Required__c, 
                                  Correspondence_Detail__c, Customer_Type__c, Profile_Company_ID__c, Industry_Type_SIC__c, Use_This_One__c,
                                  Phone, Invoice_Email_Address__c, Fax,
                                  (Select Id, Type__c, Street_1__c, Street_2__c, Street_3__c, Street_4__c, City__c, State_Province__r.ISO_CODE__c, 
                                  Zip_Postal_Code__c, Lookup_Country__r.ISO_CODE__c, Locality__r.Banner_Code__c, Primary__c From Addresses__r Where Active__c = true) 
                                  From Account Where Id = :AccountId Limit 1];
        string result;
        if (acc != null){
            UpdatecompanyTypeInfo cti = new UpdatecompanyTypeInfo();
            //cti.profileId = strProfileId;
            
            if (acc.Acronym_short_title__c != null && acc.Acronym_short_title__c != ''){
                cti.company.companyInformation.shortName = acc.Acronym_short_title__c;
            }
            if (acc.Name != null && acc.Name != ''){
                cti.company.companyInformation.companyName = acc.Name;
            }
            if (acc.VAT_number__c != null && acc.VAT_number__c != ''){
                cti.company.companyInformation.taxId = acc.VAT_number__c;
            }
            if (acc.EU_Tax_registered__c != null){
                cti.company.companyInformation.euTaxRegistered = acc.EU_Tax_registered__c ? '1' : '0';
            }
            if (acc.Reporting_Required__c != null){
                cti.company.companyInformation.poRequired = acc.Reporting_Required__c;
            }
            if (acc.Correspondence_Detail__c != null && acc.Correspondence_Detail__c != ''){
                cti.company.companyInformation.preferredMethodOfCorrespondence = acc.Correspondence_Detail__c;
            }
            if (acc.Customer_Type__c != null && acc.Customer_Type__c != ''){
                cti.company.customerType.value = acc.Customer_Type__c;
            }
            
            cti.company.addresses.values = new List<AddressType>();
            for (Address__c addr : acc.Addresses__r){
                AddressType adr = new AddressType();
                if (addr.Type__c != null && addr.Type__c != ''){
                    if(addr.Type__c == 'Next of Kin/Emergency/Guardian'){
                        adr.type = 'Parent';
                    }
                    else{
                        adr.type = addr.Type__c;
                    }
                }
                if (addr.Street_1__c != null && addr.Street_1__c != ''){
                    adr.line1 = addr.Street_1__c;
                }
                if (addr.Street_2__c != null && addr.Street_2__c != ''){
                    adr.line2 = addr.Street_2__c;
                }
                if (addr.Street_3__c != null && addr.Street_3__c != ''){
                    adr.line3 = addr.Street_3__c;
                }
                if (addr.Street_4__c != null && addr.Street_4__c != ''){
                    adr.line4 = addr.Street_4__c;
                }
                if (addr.City__c != null && addr.City__c != ''){
                    adr.city = addr.City__c;
                }
                if (addr.State_Province__c != null && addr.State_Province__r.ISO_CODE__c != null && 
                    addr.State_Province__r.ISO_CODE__c != ''){
                    adr.stateProvince = addr.State_Province__r.ISO_CODE__c;
                }
                if (addr.Locality__c != null && addr.Locality__r.Banner_Code__c != null && 
                    addr.Locality__r.Banner_Code__c != ''){
                    adr.locality = addr.Locality__r.Banner_Code__c;
                }
                if (addr.Zip_Postal_Code__c != null && addr.Zip_Postal_Code__c != ''){
                    adr.postalCode = addr.Zip_Postal_Code__c;
                }
                if (addr.Lookup_Country__c != null && addr.Lookup_Country__r.ISO_CODE__c != null && 
                    addr.Lookup_Country__r.ISO_CODE__c != ''){
                    adr.country = addr.Lookup_Country__r.ISO_CODE__c;
                }
                adr.isPrimary = addr.Primary__c;
                adr.isCertified = addr.Primary__c;
                
                cti.company.addresses.values.add(adr);
            }
            
            cti.company.emails.values = new List<EmailType>();
            if(acc.Invoice_Email_Address__c!= null){
                EmailType et = new EmailType();
                et.type = 'Billing';
                et.emailAddress = acc.Invoice_Email_Address__c;
                et.isPrimary = true;
                cti.company.emails.values.add(et);
            }
            cti.company.phones.values = new List<PhoneType>();
            if(acc.Phone != null){
                PhoneType pt = BuildPhone.BuildPhoneTypeDTO(acc.Phone, 'Business', true);
                cti.company.phones.values.add(pt);              
            }
            if(acc.Fax != null){
                PhoneType pt = BuildPhone.BuildPhoneTypeDTO(acc.Fax, 'Fax', false);
                cti.company.phones.values.add(pt);
            }
            /*cti.company.identities.values = new List<IdentityType>(); 
            IdentityType it = new IdentityType();
            it.value = strProfileId;
            it.type = 'ProfileID';
            if (acc.Use_This_One__c != null){
                it.active = acc.Use_This_One__c;
            }
            cti.company.identities.values.add(it);
            */
            
            //if update is from an address being deleted
            if(AddressDeleted == true){
                cti.deleteEntity = new DeleteEntityType();  
                DeleteAddressType adr = new DeleteAddressType();
                adr.type = AddressType;
                cti.deleteEntity.addresses.values.add(adr);  
            }
                     
            String jsonRequest = JSON.serialize(cti);
            system.debug(jsonRequest);
            Http http = new Http();
            HttpRequest req = BPPIntegrationConfig.callUpdateRestService(jsonRequest, 'application/json', endPoint_update +'/'+ strProfileId);
            
            system.debug('Final JSON: ' + req.getMethod() + ' ' + req.getEndPoint() + 'Accept-Encoding:' + req.getHeader('Accept-Encoding') +'Accept:' + req.getHeader('Accept') + 'Content-Type:' + req.getHeader('Content-Type') + 'tenantId:' + req.getHeader('tenantId') + req.getBody());
            system.debug(req.toString());
            HttpResponse res = null;
            if (Test.isRunningTest()){
                res = new HttpResponse();
                if (bFailSIS){
                    String strResponse = '{"companyId":"bfb463f9-b4c2-4ce4-a429-05818b8cae1f","operation":"UPDATE","identities":{"values":[{"id":"92a41ad1-6c4d-4361-b16f-4b43cdd7af4f","value":"BP0015638","type":"BANNER","active":true}';
                    res.setStatusCode(200);
                    res.setStatus('OK');
                    res.setBody(strResponse);
                }
                else{
                    String strResponse = '{"self":"null","httpMethod":"DELETE","errorMessage":"Cannot find Company or Profile Record for the specified Id: 1231231231","errorCode":"PLATFORM-801","transactionId":"A563C5CD-4CA9-B1C6-392A-09377720BFAC"}';
                    res.setStatusCode(200);
                    res.setStatus('Internal Error');
                    res.setBody(strResponse);
                }
            }
            else{
                res = http.send(req);
            }
            system.debug(res.getBody());
            system.debug(res.getStatus());
            
            /* Integration Log */
            Integration_Log__c intg = new Integration_Log__c();
            intg.Request__c =  jsonRequest;
            intg.Response__c = res.getBody();
            intg.Salesforce_ID__c = acc.Id;
            intg.Integration_Type__c = 'Update Existing Company';
            
            String companyProfile;
            if (res.getStatus() == 'OK' && res.getStatusCode() == 200){
                //resp is a JSON string
                JSONParser parser = JSON.createParser(res.getBody());
                while (parser.nextToken() != null) {
                    if ((parser.getCurrentToken() == JSONToken.FIELD_NAME)){
                        String fieldName = parser.getText();
                        parser.nextToken();
                        if(fieldName == 'companyId') {
                            companyProfile = parser.getText();
                            system.debug('CompanyProfile' + companyProfile);
                            result = 'Success';
                            break;
                        }
                    }
                }
            }
            else{
                JSONParser jParser = JSON.createParser(res.getBody());
                while(jParser.nextToken() !=null){
                    if((jParser.getCurrentToken() == JSONToken.FIELD_NAME)){
                        string fieldN = jParser.getText();
                        jParser.nextToken();
                        if(fieldN == 'errorMessage'){
                            result = jParser.getText();
                            system.debug('errorMessage' + result);
                            break;
                        }
                    }
                }
            }
            insert intg;
        }
        return;
    }
}