salesforce-main/src/main/default/objects/Account/fields/Acronym_short_title__c.field-meta.xml
<CustomField>
    <fullName>Acronym_short_title__c</fullName>
    <label>Acronym (short title)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Booking_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Booking_Requirements__c</fullName>
    <label>Booking Requirements</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Correspondence_Detail__c.field-meta.xml
<CustomField>
    <fullName>Correspondence_Detail__c</fullName>
    <label>Correspondence Detail</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit__c</fullName>
    <defaultValue>7500</defaultValue>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Client Services</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
            <value>
                <fullName>PD Special Account Managers</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/EU_Tax_registered__c.field-meta.xml
<CustomField>
    <fullName>EU_Tax_registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EU Tax registered</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Industry_Type_SIC__c.field-meta.xml
<CustomField>
    <fullName>Industry_Type_SIC__c</fullName>
    <label>Industry Type (SIC)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A~ Agriculture, forestry and fishing</fullName>
            </value>
            <value>
                <fullName>B~ Mining and quarrying</fullName>
            </value>
            <value>
                <fullName>C~ Manufacturing</fullName>
            </value>
            <value>
                <fullName>D~ Electricity, gas, steam and air conditioning supply</fullName>
            </value>
            <value>
                <fullName>E~ Water supply; sewerage, waste management and remediation activities</fullName>
            </value>
            <value>
                <fullName>F~ Construction</fullName>
            </value>
            <value>
                <fullName>G~ Wholesale and retail trade; repair of motor vehicles and motor cycles</fullName>
            </value>
            <value>
                <fullName>H~ Transport and storage</fullName>
            </value>
            <value>
                <fullName>I~ Accommodation and food service activities</fullName>
            </value>
            <value>
                <fullName>J~ Information and communication</fullName>
            </value>
            <value>
                <fullName>K~ Financial and insurance activities</fullName>
            </value>
            <value>
                <fullName>L~ Real estate activities</fullName>
            </value>
            <value>
                <fullName>M~ Professional, scientific and technical activities</fullName>
            </value>
            <value>
                <fullName>N~ Administrative and support service activities</fullName>
            </value>
            <value>
                <fullName>O~ Public administration and defense; compulsory social security</fullName>
            </value>
            <value>
                <fullName>P~ Education</fullName>
            </value>
            <value>
                <fullName>Q~ Human health and social work activities</fullName>
            </value>
            <value>
                <fullName>R~ Arts, entertainment and recreation</fullName>
            </value>
            <value>
                <fullName>S~ Other service activities</fullName>
            </value>
            <value>
                <fullName>T~ Activities of households as employers; undifferentiated goods and services-producing activities of households for own use</fullName>
            </value>
            <value>
                <fullName>U~ Activities of extraterritorial organizations and bodies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Invoice_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Delivery__c</fullName>
    <label>Invoice Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardcopy</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Invoice_Method__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Method__c</fullName>
    <label>Invoice Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediate Invoice</fullName>
            </value>
            <value>
                <fullName>Consolidated Rules</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IP</fullName>
            </value>
            <value>
                <fullName>30 Days</fullName>
            </value>
            <value>
                <fullName>45 Days</fullName>
            </value>
            <value>
                <fullName>60 Days</fullName>
            </value>
            <value>
                <fullName>90 Days</fullName>
            </value>
            <value>
                <fullName>120 Days</fullName>
            </value>
            <value>
                <fullName>180 Days</fullName>
            </value>
            <value>
                <fullName>OnDelivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <label>Profile Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/SIS_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>SIS_Company_ID__c</fullName>
    <label>SIS Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Sponsor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Sponsor_Contact__c</fullName>
    <label>Sponsor Contact</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Use_This_One__c.field-meta.xml
<CustomField>
    <fullName>Use_This_One__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To be checked to indicate main account if duplicates are present.

Legacy field for BD to indicate record of use prior to data cleansing.</description>
    <label>Use This One</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/VAT_number__c.field-meta.xml
<CustomField>
    <fullName>VAT_number__c</fullName>
    <label>VAT number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <description>Pulls the Profile Company Id value from the related Account. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>Student__r.Profile_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Company ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Reporting_Required__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reporting Required</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Locality__c/fields/Banner_Code__c.field-meta.xml
<CustomField>
    <fullName>Banner_Code__c</fullName>
    <label>Banner Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ISO Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/classes/Test_CreateStudentAccount.cls
@isTest
private class Test_CreateStudentAccount {

    static testMethod void myUnitTest() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = new State_Province__c(Name = 'Unit TestState', ISO_Code__c = '1234');
        insert stt;
        Locality__c lct = new Locality__c(Name = 'Unit TestState', Banner_Code__c = '12345');
        insert lct;
        
        Account a = new Account();
        a.Name = 'Test Company';
        a.Acronym_short_title__c = 'Test'; 
        a.VAT_number__c = '1234567890';
        a.EU_Tax_registered__c = true;
        a.Customer_Type__c = 'Key Client';
        a.Industry_Type_SIC__c = 'B~ Mining and quarrying';
        a.Use_This_One__c = true;
        a.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Business Development Account').getRecordTypeId();
        a.Profile_Company_ID__c = '1234f567-bc23-42e8-924c-1234asdf5678';
        a.SIS_Company_ID__c = 'BP0015424';
        a.Sponsor_Contact__c = 'Term';
        a.Invoice_Method__c = 'Email';
        a.Invoice_Delivery__c = 'Email';
        a.Booking_Requirements__c = 'Passport';
        a.Correspondence_Detail__c = 'Email';
        a.Payment_Terms__c = '40 Days';
        a.Credit_Limit__c = 7500;
        a.Website = 'www.test.com';
        a.Discount__c = 25;
        a.Reporting_Required__c = true;
        insert a;
        
        Address__c add = new Address__c();
        StopRecursion.Dorun = true;
        add.Student__c = a.Id;
        add.Type__c = 'Home';
        add.Street_1__c = '329 S Tonne Dr';
        add.Street_2__c = '123';
        add.Street_3__c = '123';
        add.Street_4__c = '12';
        add.City__c = 'Chicago';
        add.Locality__c = lct.Id;
        add.State_Province__c = stt.Id;
        add.Zip_Postal_Code__c = '12345';
        add.Lookup_Country__c = cntry.Id;
        insert add;
        
        Contact c = new Contact();
        c.RecordTypeId = Schema.sObjectType.Contact.getRecordTypeInfosByName().get('Training Manager').getRecordTypeId();
        c.LastName = 'testc';
        c.FirstName = 'testfi';
        c.AccountId = a.Id;
        c.Phone = '3126608787';
        c.Email = 'testc@con.com';
        c.Birthdate = Date.newInstance(1986, 4, 5);
        c.Preferred_Email__c = 'Personal';
        c.Personal_Email__c = 'john@johnzz.com';    
        c.PS_Profile_Services_ID__c = '12300567-bc23-42e8-924c-1234asdf5678';
        c.Active__c = true;
        insert c;
        
        List<CreateStudentAccount.StudentDTO> stdDTO = new List<CreateStudentAccount.StudentDTO>();
        CreateStudentAccount.StudentDTO std = new CreateStudentAccount.StudentDTO();
        
        Account a1 = new Account();
        a1.FirstName='John';
        a1.LastName='Coppedge';
        a1.Salutation = 'Mr';
        a1.Middle_Name__pc = 'Mex';
        a1.Gender__pc = 'Male';
        a1.Preferred_Email__pc = 'Personal';
        a1.Preferred_Phone__pc = 'Mobile';
        a1.Personal_Email__pc ='john@john.com';
        a1.PersonMobilePhone = '8015555556';
        a1.PersonBirthdate = Date.valueOf('1986-02-27');
        a1.PS_Profile_Services_ID__pc = '1234f567-bc23-42e8-924c-asdf12345678';
        a1.Student_Cycle__c = 'Pursue';
        a1.Student_Type__pc = 'Domestic';
        std.student = a1;
        
        List<Address__c> adds = new List<Address__c>();
        Address__c add1 = new Address__c();
        add1.Type__c = 'Billing';
        add1.Street_1__c = '123 S Test Dr';
        add1.Street_2__c = '12345';
        add1.Street_3__c = '1234';
        add1.Street_4__c = '123';
        add1.City__c = 'Test City';
        add1.Text_Locality__c = '12345';
        add1.Text_State__c = '1234';
        add1.Zip_Postal_Code__c = '12345';
        add1.Text_Country__c = '123';
        adds.add(add1);
        std.addresses = adds;
        
        CreateStudentAccount.SponsorshipDTO spn = new CreateStudentAccount.SponsorshipDTO();
        spn.CompanyProfileId = '1234f567-bc23-42e8-924c-1234asdf5678';
        spn.TrainingManagerProfileId = '12300567-bc23-42e8-924c-1234asdf5678';
        std.sponsor = spn;
        
        List<Qualification__c> qlfs = new List<Qualification__c>();
        Qualification__c qlf1 = new Qualification__c();
        qlf1.Examing_Body__c = 'ACCA';
        qlf1.Student_Institute__c = '1234567890';
        qlfs.add(qlf1);
        std.qualifications = qlfs;
        
        stdDTO.add(std);
                //Create REST request and response values and objects.
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/v1.0/CreateStudentAccount';
        req.addHeader('httpMethod', 'POST');
        //req.requestBody = Blob.valueof(JSON);
        RestContext.request = req;
        RestContext.response = res;
        
        CreateStudentAccount.Response res1 = CreateStudentAccount.doPost(stdDTO);
        
    }
}