salesforce-main/src/main/default/objects/Account/fields/AR_Student_Finance_England_SFE__c.field-meta.xml
<CustomField>
    <fullName>AR_Student_Finance_England_SFE__c</fullName>
    <label>Student Finance England # (SFE)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/UpdateQualificationsCtrlTest.cls
@isTest
public class UpdateQualificationsCtrlTest {
    static testmethod void testGetCompanyProfileId_noAddress() {
        Test.startTest();
            country_list__c cntry = CreateTestData.createCountry1();
            State_Province__c stt = CreateTestData.createStateProvince();
            Locality__c lct = CreateTestData.createLocality();
            
            Account a = CreateTestData.createAccount1(cntry);
            a.personHomePhone = '555-777-8888';
            a.Work_Phone__pc = '555-777-8888';
            a.Parents_Guardian_Emergency_Phone__pc = '555-777-8888';
            a.Fax = '555-777-8888';
            a.PersonMobilePhone ='111-222-3333';
            a.Personal_Email__pc = 'ktest@test.com';
            a.Work_Email__pc = 'ktest@test.com';
            a.BPP_Email__pc = 'ktest@test.com';
            a.Other_Email__pc = 'ktest@test.com';
            a.Billing_Email__pc = 'ktest@test.com';
            a.AR_Student_Finance_England_SFE__c = 'AAAA11112222F';
            update a;
                    
            Address__c addr = CreateTestData.createAddress(a, null, null, cntry, stt, lct, true, 'Billing');
            Opportunity o = CreateTestData.createOpportunity(a);
        
        	UpdateQualificationsCtrl.updateQualifications(o.Id);
        Test.stopTest();
    }
}