salesforce-main/src/main/default/objects/Account/fields/AR_Student_Finance_England_SFE__c.field-meta.xml
<CustomField>
    <fullName>AR_Student_Finance_England_SFE__c</fullName>
    <label>Student Finance England # (SFE)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Student_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Student_Cycle__c</fullName>
    <description>Student cycle sets the default mode of contact for the particular student record.  

Pursue (default): Student is a potential purchaser of BPP products near-term.
Maintenance: Student is a potential purchaser of BPP products long-term.
No Further Action: Student is not a potential purchaser of BPP products.</description>
    <label>Student Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pursue</fullName>
                <default>true</default>
                <label>Pursue</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <description>Country of student&apos;s current residence.</description>
    <label>Country of Residence</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Home_Phone__c.field-meta.xml
<CustomField>
    <fullName>Home_Phone__c</fullName>
    <description>DO NOT USE.  This field was originally added to translate home phone from lead, but is no longer in use as the lead object was not implemented.  Validation and page display shows the standard home phone field.  Prior to removal:
1) Validate no data exists in this field.
2) Validate field removal does not have negative impact on data team interfaces.</description>
    <label>[REMOVE] Home Phone</label>
    <type>Phone</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Other_Email__c.field-meta.xml
<CustomField>
    <fullName>Other_Email__c</fullName>
    <description>Other email address of student.  As preferred email address is required when adding an email address,  this field can be used when  the email address type is unknown.</description>
    <label>Other Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email__c</fullName>
    <description>Personal email address of student.</description>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <description>Indicates the preferred email address of the student.  Must be populated if an email address is present on the student record.  Update the email field of the student every time the student record is saved based on the preferred selection.</description>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>BPP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Preferred_Phone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Phone__c</fullName>
    <description>Indicates the preferred phone number of the student.  Must be populated if a phone number is populated.  Preferred number is copied into the phone field every time a student record is updated.</description>
    <label>Preferred Phone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Parents/Guardian/Emergency</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <label>Programme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intensive</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Integrated no gap</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>KGS</fullName>
            </value>
            <value>
                <fullName>School leaver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <description>NOT CURRENTLY IN USE OR DISPLAYED.  Indicates the highest level of qualification the student has achieved.</description>
    <label>[INACTIVE] Qualification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High School</fullName>
            </value>
            <value>
                <fullName>Bachelors Degree</fullName>
            </value>
            <value>
                <fullName>Masers Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>Student&apos;s work email address.</description>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Work_Phone__c.field-meta.xml
<CustomField>
    <fullName>Work_Phone__c</fullName>
    <description>Student&apos;s work phone number.</description>
    <label>Work Phone</label>
    <type>Phone</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Country_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Residence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as per JIRA BPPBAU-2331</description>
    <inlineHelpText>Select the Country of Residence</inlineHelpText>
    <label>Country of Residence</label>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Leads (Country list)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Parents_Guardian_Emergency_Phone__c.field-meta.xml
<CustomField>
    <fullName>Parents_Guardian_Emergency_Phone__c</fullName>
    <label>Parents/Guardian/Emergency Phone</label>
    <type>Phone</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/rfi_Are_you_EU_UK__c.field-meta.xml
<CustomField>
    <fullName>rfi_Are_you_EU_UK__c</fullName>
    <label>Are you EU/UK?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UK Student</fullName>
            </value>
            <value>
                <fullName>EU Student</fullName>
            </value>
            <value>
                <fullName>International Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Locality__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ISO Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity_Product__c/Opportunity_Product__c.object-meta.xml
<CustomObject>
    <label>Product Catalog Item</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PCItem #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalog Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity_Product__c/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <formula>Product__r.Programme__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Programme</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/TEST_ProfileIntegrations.cls
@isTest()
public class TEST_ProfileIntegrations
{
    static testMethod void myUnitTestP1() {
        country_list__c cntry = CreateTestData.createCountry1();
        State_Province__c stt = CreateTestData.createStateProvince();
        Locality__c lct = CreateTestData.createLocality();
        
        Account a = CreateTestData.createAccount1(cntry);
        a.personHomePhone = '444-666-9999';
        a.Work_Phone__pc = '444-666-9999';
        a.Parents_Guardian_Emergency_Phone__pc = '444-666-9999';
        a.Fax = '444-666-9999';
        a.PersonMobilePhone ='111-333-4444';
        a.Personal_Email__pc = 'ptestmeda@test.com';
        a.Work_Email__pc = 'ptestmeda@test.com';
        a.BPP_Email__pc = 'ptestmeda@test.com';
        a.Other_Email__pc = 'ptestmeda@test.com';
        a.Billing_Email__pc = 'ptestmeda@test.com';
        a.AR_Student_Finance_England_SFE__c = 'BBBB22223333F';
        update a;
                
        Address__c addr = CreateTestData.createAddress(a, null, null, cntry, stt, lct, true, 'Billing');
        Opportunity o = CreateTestData.createOpportunity(a);
        Programme__c pgrm = CreateTestData.createProgram();
        Product2 pd = CreateTestData.createProduct(pgrm,'OFFERING');
        
        list<Contact> contacts = [Select Id, AccountId From Contact Where AccountId =: a.id];
        Qualification__c qual = new Qualification__c();
        qual.Student_Institute__c = 'testabcd';
        qual.Examing_Body__c = 'test123';
        qual.Student_Institute__c = 'test';
        qual.Student__c = contacts[0].id;
        insert qual;
        
        Test.startTest();
        Opportunity_Product__c oppPrd = CreateTestData.createOppProduct(o, pd, true);
        String Result = ProfileIntegrations.ProfileInt(a.id);
        Test.stopTest();
    }  
    
    static testMethod void myUnitTest1P2() {
        Account a2 = new Account();
        a2.PS_Profile_Services_ID__pc = '1324f567-bc23-42e8-924c-1324asdf5678';
        a2.firstname='John Smith';
        a2.lastname='Smith';
        a2.Salutation = 'Mr';
        a2.Middle_Name__pc = 'Mex';
        a2.Gender__pc = 'Female';
        a2.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId();
        a2.Student_Cycle__c = 'Pursue';
        a2.Student_Type__pc ='International';
        a2.PersonBirthdate =Date.valueOf('1984-10-11');
        a2.AA_Suffix__pc = 'Jr';
        a2.Preferred_First_Name__pc = 'Smith';
        a2.Previous_First_Name__pc = 'John';
        a2.Previous_Surname__pc = 'Cop';
        a2.Previous_Middle_Name__pc = 'Copp';
        
        a2.personHomePhone = '444-666-9999';
        a2.Work_Phone__pc = '444-666-9999';
        a2.Parents_Guardian_Emergency_Phone__pc = '444-666-9999';
        a2.Fax = '444-666-9999';
        a2.PersonMobilePhone ='111-333-4444';
        a2.Preferred_Phone__pc = 'Mobile';
        a2.Personal_Email__pc = 'ptestmeda@test.com';
        a2.Work_Email__pc = 'ptestmeda@test.com';
        a2.BPP_Email__pc = 'ptestmeda@test.com';
        a2.Other_Email__pc = 'ptestmeda@test.com';
        a2.Billing_Email__pc = 'ptestmeda@test.com';
        a2.Preferred_Email__pc = 'Personal';
               
        insert a2;
        country_list__c cntry1 = new country_list__c(Name = 'Unit Test', ISO_Code__c = '123', country_code_2__c = '12', enabled__c = true, Valid_Nationality__c = true);
        insert cntry1;
        
        State_Province__c stt1 = new State_Province__c(Name = 'Unit Test', ISO_Code__c = '123');
        insert stt1;
        
        Address__c addacc = new Address__c();
        addacc.Student__c = a2.Id;
        addacc.Type__c = 'Next of Kin/Emergency/Guardian';
        addacc.Street_1__c = '329 S Tonne Dr';
        addacc.Street_2__c = '123';
        addacc.Street_3__c = '123';
        addacc.Street_4__c = '12';
        addacc.City__c = 'Chicago';
        addacc.State_Province__c = stt1.Id;
        addacc.Zip_Postal_Code__c = '12345';
        addacc.Lookup_Country__c = cntry1.Id;
        insert addacc;
        ProfileIntegrations.UpdatePersonInfo(a2.PS_Profile_Services_ID__pc, a2.id);
        
    StopRecursion.Dorun = true;   
         
        
        a2.personHomePhone = null;
        a2.Work_Phone__pc = null;
        a2.Parents_Guardian_Emergency_Phone__pc = null;
        a2.Fax = null;
        a2.PersonMobilePhone = null;
        a2.Personal_Email__pc = null;
        a2.Work_Email__pc = null;
        a2.BPP_Email__pc = null;
        a2.Other_Email__pc = null;
        a2.Billing_Email__pc = null;
        a2.Preferred_Email__pc = null;
        a2.Preferred_Phone__pc = null;
        
        update a2;      
    }  
   
    static testMethod void myUnitTest2P3() {
    
    country_list__c clist = new country_list__c(Name = 'Unit Test', ISO_Code__c = 'PM2', country_code_2__c = '00', enabled__c = true, Valid_Nationality__c = true);
        insert clist;
        Lead l1 = New Lead();
        l1.LastName = 'Test';
        l1.Birth_Date__c = Date.today().addYears(-20);
        l1.rfi_Are_you_EU_UK__c = 'UK (EU) Student';
        //l1.Country_of_Residence__c = 'USA';
        l1.Country_of_Residence__c = clist.id;
        l1.Preferred_Email__c = 'Personal';
        l1.Personal_Email__c = 'test@t.com';
        l1.FirstName = 'keith';
        l1.Work_Email__c = 'ptestmeda@test.com';
        l1.Other_Email__c = 'ptestmeda@test.com';
        l1.Billing_Email__c = 'ptestmeda@test.com';
        l1.MobilePhone = '444-666-9999';
        l1.Work_Phone__c = '444-666-9999';
        l1.Parents_Guardian_Emergency_Phone__c = '555-777-8888';
        l1.Home_Phone__c = '444-666-9999';
        l1.Fax = '444-666-9999';
        l1.Preferred_Phone__c = 'Work';
        l1.Gender__c = 'Male';
        l1.Middle_Name__c = 'mid';
        l1.Salutation = 'sal';
        l1.Preferred_First_Name__c ='pref';
        insert l1;
 
        country_list__c cntry = new country_list__c(Name = 'Unit Test', ISO_Code__c = '123', country_code_2__c = '12', enabled__c = true, Valid_Nationality__c = true);
        insert cntry;
           
        State_Province__c stt = new State_Province__c(Name = 'Unit Test', ISO_Code__c = '123');
        insert stt;
              
        Address__c add1 = new Address__c();
        add1.Lead__c = l1.Id;
        add1.Type__c = 'Next of Kin/Emergency/Guardian';
        add1.Street_1__c = '329 S Tonne Dr';
        add1.Street_2__c = '123';
        add1.Street_3__c = '123';
        add1.Street_4__c = '12';
        add1.City__c = 'Chicago';
        add1.State_Province__c = stt.Id;
        add1.Zip_Postal_Code__c = '12345';
        add1.Lookup_Country__c = cntry.Id;
        insert add1;
      
        Test.startTest();
        String Result = ProfileIntegrations.ProfileLeadInt(l1.id);
        Test.stopTest();
    }
}