salesforce-main/src/main/default/objects/Account/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <description>Billing Frequency defined on the Account level. For Accounts of type Customer Group Tier 1 - Key, this Billing Frequency will be interpreted and set correctly for invoicing.</description>
    <inlineHelpText>For Accounts of type Customer Group Tier 1 - Key, this Billing Frequency will be interpreted and set correctly for invoicing.</inlineHelpText>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
                <default>true</default>
                <label>In Advance</label>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Student</relationshipLabel>
    <relationshipName>Student</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</description>
    <inlineHelpText>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <description>The instance name, Used in related lists</description>
    <formula>Instance__r.Instance_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instance Name</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Material_Price__c.field-meta.xml
<CustomField>
    <fullName>Material_Price__c</fullName>
    <description>Roll up of cost of materials for this booking from the booking lines. To be used in reports as backing information for invoices</description>
    <label>Material Price</label>
    <summarizedField>Booking_Line__c.blng_PreratedAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Booking_Line__c.Product_Family__c</field>
        <operation>equals</operation>
        <value>Materials, VLE</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking_Line__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>PO number related to this booking. This field is mandatory if the account requires PO&apos;s</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Tuition_Price__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Price__c</fullName>
    <description>Roll up of tuition cost from the booking lines. To be used in reports</description>
    <label>Tuition Price</label>
    <summarizedField>Booking_Line__c.blng_PreratedAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Booking_Line__c.Product_Family__c</field>
        <operation>contains</operation>
        <value>Session</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking_Line__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(blng_Order__r.Billing_Type__c)</formula>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_MatchingId__c.field-meta.xml
<CustomField>
    <fullName>blng_MatchingId__c</fullName>
    <description>This field will be the matching ID from the related booking summary. This field will be populated by the booking line creation code</description>
    <externalId>true</externalId>
    <label>Matching ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>blng_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order product line this booking line relates to.This field is populated by the booking line creation code</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_StartDateTime__c</fullName>
    <description>The start date of the session if product family is session or the instance start date if product family is materials</description>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Booking this booking line relates to</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking line relates to</description>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <description>The name of the instance to show in related lists</description>
    <formula>Instance__r.Instance_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instance Name</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>The PO number this booking line is associated to</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <description>Longer Name field as requested by BPP</description>
    <label>Instance Name</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of this course</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/recordTypes/Instance.recordType-meta.xml
<RecordType>
    <fullName>Instance</fullName>
    <active>true</active>
    <label>Instance</label>
</RecordType>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/Invoiceheader_details__c.object-meta.xml
<CustomObject>
    <label>Invoice Backing Detail</label>
    <nameField>
        <displayFormat>IBD-{000000}</displayFormat>
        <label>Invoice Backing Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Backing Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Booking that this Invoice Backing Detail is related to.</description>
    <inlineHelpText>The Booking that this Invoice Backing Detail is related to.</inlineHelpText>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Invoice Backing Details</relationshipLabel>
    <relationshipName>Invoice_Backing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Cost_Centre__c.field-meta.xml
<CustomField>
    <fullName>Cost_Centre__c</fullName>
    <label>Cost Centre</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Customer_POnumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_POnumber__c</fullName>
    <label>Customer PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Instance that this Invoice Backing Detail is related to.</description>
    <inlineHelpText>The Instance that this Invoice Backing Detail is related to.</inlineHelpText>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Invoice Backing Details</relationshipLabel>
    <relationshipName>Invoice_Backing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Order/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <description>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</description>
    <inlineHelpText>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</inlineHelpText>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingType</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/InvoiceHeaderDetailsGeneratorTest.cls
/**
 *  @who    Duy Vu <duy.vu@weare4c.com>
 *  @when   02/07/2020
 *  @what   Helper for InvoiceHeaderDetailsGenerator
 */
@isTest
public class InvoiceHeaderDetailsGeneratorTest {
    @TestSetup
    static void makeData(){
        Database.DMLOptions dbDML = new Database.DMLOptions(); 
        dbDML.DuplicateRuleHeader.allowSave = true;
        dbDML.DuplicateRuleHeader.runAsCurrentUser = true;
        
        Account account = TestDataFactory.createAccount(false, false, null, 0);
        account.Billing_Frequency__c = 'Monthly';
        account.Billing_Type__c = 'In Arrears';
        Database.insert(account, dbDML);
        
        Account student = TestDataFactory.createAccount(false, true, account.Id, 1);
        student.Cost_Centre_Number__pc = 'CC# 00000';
        student.Client__c = account.Id;
        Database.insert(student, dbDML);
        
        country_list__c cntry = CreateTestData.createCountry1();
        
        Address__c addressAccount = TestDataFactory.createAddress(false, 0, account, cntry, true, false);
		Database.insert(addressAccount, dbDML);        
        
        Order order = TestDataFactory.createOrder(false, 1, account, null, addressAccount);
        order.SBQQ__PaymentTerm__c = 'Net 30';
        insert order;

        blng__BillingRule__c billingRule = TestDataFactory.createBillingRule(true);
        blng__FinanceBook__c billingFinanceBook = TestDataFactory.createBillingFinanceBook(true);
        blng__BillingTreatment__c billingTreatment = TestDataFactory.createBillingTreatment(true, billingRule, billingFinanceBook);
        blng__RevenueRecognitionRule__c revenueRecognitionRule = TestDataFactory.createRevenueRecognitionRule(true);
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule(true);
        
        Product2 product = TestDataFactory.createProduct(true,1,billingRule,revenueRecognitionRule,taxRule);
        PricebookEntry pricebookEntry = TestDataFactory.createPricebookEntry(true, product, null);

        OrderItem parentOrderLine = TestDataFactory.createOrderLine(true,order,product,null,priceBookEntry,billingRule,revenueRecognitionRule, taxRule,'');

        List<OrderItem> orderLines = new List<OrderItem>();
        orderLines.add(TestDataFactory.createOrderLine(false, order, product, parentOrderLine, priceBookEntry, billingRule, revenueRecognitionRule, taxRule, 'Materials'));
        orderLines.add(TestDataFactory.createOrderLine(false, order, product, parentOrderLine, priceBookEntry, billingRule, revenueRecognitionRule, taxRule, 'Session'));
        orderLines.add(TestDataFactory.createOrderLine(false, order, product, parentOrderLine, priceBookEntry, billingRule, revenueRecognitionRule, taxRule, 'Online Session'));
        insert orderLines;

        List<blng__UsageSummary__c> bookingSummaries = new List<blng__UsageSummary__c>();
        for(Integer i=0;i<orderLines.size();i++){
            blng__UsageSummary__c bookingSummary = TestDataFactory.createBookingSummary(false,orderLines.get(i));
            bookingSummary.blng__Order__c = order.Id;
            bookingSummaries.add(bookingSummary);
        }
        insert bookingSummaries;
        
        // create instance 
        Instance__c instance = TestDataFactory.createInstance(false, 1, product);
        instance.Instance_Name__c = 'TEST Instance';
        instance.Start_Date__c = Date.today();
        insert instance;

        order.Status = 'Activated';
        update order;
        
        Booking__c booking = TestDataFactory.createBooking(false, instance, order, student);
        booking.PO_Number__c = 'PO# 999';
        try {
            insert booking;
        } catch (DmlException e) {
            System.debug('error is ' + e.getMessage() + e.getCause());
        }

        List<Booking_Line__c> bookingLines = [SELECT Id, Batch_Processed__c FROM Booking_Line__c];
        for(Integer i = 0; i < bookingLines.size(); i++) {
            bookingLines.get(i).blng_OrderProduct__c = null;
            bookingLines.get(i).blng_MatchingId__c = String.valueOf(Math.random());
        }
        update bookingLines;

        BookingLineBatch testBatch = new BookingLineBatch('blng_StartDateTime__c','Batch_Processed__c', 'On_Hold__c', 'Cancelled');
        Database.executeBatch(testBatch);

        // Insert a Legal Entity
        insert TestDataFactory.buildDefaultLegalEntity();

        blng__Invoice__c invoice = new blng__Invoice__c();
        invoice.SFBD__HoldCollections__c = false;
        invoice.blng__Account__c = account.Id;
        invoice.blng__InvoiceDate__c = System.today();
        insert invoice;
    }

    @isTest
    static void createInvoiceHeaderDetails() {
        Test.startTest();
			blng__Invoice__c invoice = [SELECT Id, Name FROM blng__Invoice__c];
			List<blng__UsageSummary__c> bookingSummaries = [SELECT Id FROM blng__UsageSummary__c];
			List<blng__Usage__c> usageLines = [SELECT Id FROM blng__Usage__c];
			for(Integer i = 0; i < usageLines.size(); i++) {
				usageLines.get(i).blng__UsageSummary__c = bookingSummaries.get(i).Id;
			}
			update usageLines;
			System.debug('This is modified usageLines ' + usageLines);
			
			List<blng__InvoiceLine__c> invoiceLines = new List<blng__InvoiceLine__c>();
			for (blng__UsageSummary__c bookingSummary : bookingSummaries) {
				blng__InvoiceLine__c invoiceLine = new blng__InvoiceLine__c();
				invoiceLine.blng__Invoice__c = invoice.Id;
				invoiceLine.blng__UsageSummary__c = bookingSummary.Id;
                invoiceLine.PaymentTerm__c = 'Net 30';
				invoiceLines.add(invoiceLine);
			}
			// Test for One-time charged product (eg.Postage)
			blng__InvoiceLine__c invoiceLine = new blng__InvoiceLine__c();
			invoiceLine.blng__Invoice__c = invoice.Id;
			invoiceLines.add(invoiceLine);
			insert invoiceLines;
			
			List<Invoiceheader_details__c> invoiceHeaderDetails = [SELECT Id, Customer_POnumber__c, Material_Price__c,Tuition_Price__c, Cost_Centre__c, Student_Name__c, Course_Name__c FROM Invoiceheader_details__c];
			// System.debug('Invoiceheader Details' + invoiceHeaderDetails);
			
			System.assertEquals(1, invoiceHeaderDetails.size(), 'There should be 1 InvoiceheaderDetail object created');
			Invoiceheader_details__c invoiceHeaderDetail = invoiceHeaderDetails.get(0);
			System.assertEquals('PO# 999', invoiceHeaderDetail.Customer_POnumber__c, 'Customer PO number should be populated');
			System.assertEquals(10, invoiceHeaderDetail.Material_Price__c, 'Material Price should be populated');
			// System.assertEquals(20, invoiceHeaderDetail.Tuition_Price__c, 'Tuition Price should be populated');
			System.assertEquals('CC# 00000', invoiceHeaderDetail.Cost_Centre__c, 'Customer PO number should be populated');
			System.assertEquals('Test account 1 Student', invoiceHeaderDetail.Student_Name__c, 'Student Name should be populated');
			System.assertEquals('TEST Instance', invoiceHeaderDetail.Course_Name__c, 'Course name should be populated');
        Test.stopTest();
    }
}