salesforce-main/src/main/default/objects/Account/fields/Billing_Cycle_Start_Month__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle_Start_Month__c</fullName>
    <description>Used for alignment of the Order Start Dates.</description>
    <inlineHelpText>Mandatory for Billing Type In Arrears and Billing Frequency &gt; Monthly. Sets the cycle start month for alignment of charges on various orders.</inlineHelpText>
    <label>Billing Cycle Start Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <description>Billing Frequency defined on the Account level. For Accounts of type Customer Group Tier 1 - Key, this Billing Frequency will be interpreted and set correctly for invoicing.</description>
    <inlineHelpText>For Accounts of type Customer Group Tier 1 - Key, this Billing Frequency will be interpreted and set correctly for invoicing.</inlineHelpText>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
                <default>true</default>
                <label>In Advance</label>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Order/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <description>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</description>
    <inlineHelpText>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</inlineHelpText>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingType</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/OrderManipulatorTest.cls
/*
* Who Patrick Duncan <patrick.duncan@weare4c.com> 
* What Test class for OrderManipulator
* When 10/8/20
*/
@isTest
public class OrderManipulatorTest {
	
    /*@testSetup
    static void setup(){
        Account monthlyAccount = TestDataFactory.createAccount(false, false, 1);
        monthlyAccount.Billing_Frequency__c = 'Monthly';
        monthlyAccount.Billing_Type__c = 'In Arrears';
        Account quaterlyAccount = TestDataFactory.createAccount(false, false, 2);
        quaterlyAccount.Billing_Frequency__c = 'Quarterly';
        quaterlyAccount.Billing_Cycle_Start_Month__c = '6';
        quaterlyAccount.Billing_Type__c = 'In Arrears';
        Account semiAnnualAccount = TestDataFactory.createAccount(false, false, 3);
        semiAnnualAccount.Billing_Frequency__c = 'Semiannual';
        semiAnnualAccount.Billing_Cycle_Start_Month__c = '6';
        semiAnnualAccount.Billing_Type__c = 'In Arrears';
        Account annualAccount = TestDataFactory.createAccount(false, false, 4);
        annualAccount.Billing_Frequency__c = 'Annual';
        annualAccount.Billing_Cycle_Start_Month__c = '6';
        annualAccount.Billing_Type__c = 'In Arrears';
        insert new List<Account>{monthlyAccount, quaterlyAccount, semiAnnualAccount, annualAccount};
    }

    
    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is before its parent account's billing cycle start that also has a monthly billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the created month
    *
    @isTest
    static void createdAfterMonthlyCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%1'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2020, 11, 7);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2020, 11, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is after its parent account's billing cycle start that also has a monthly billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the created month
    *
    @isTest
    static void createdBeforeMonthlyCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%1'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2021, 1, 7);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2021, 1, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is before its parent account's billing cycle start that also has a quaterly billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the quaterly period
    *
    @isTest
    static void createdBeforeQuaterlyCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%2'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2021, 3, 1);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2021, 3, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is after its parent account's billing cycle start that also has a quaterly billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the current quaterly period
    *
    @isTest
    static void createdAfterQuaterlyCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%2'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2020, 8, 1);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2020, 6, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is after its parent account's billing cycle start that also has a semi-annual billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the current quaterly period
    *
    @isTest
    static void createdBeforeSemiAnnualCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%3'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2021, 4, 18);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2020, 12, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is after its parent account's billing cycle start that also has a semi-annual billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the current quaterly period
    *
    @isTest
    static void createdAfterSemiAnnualCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%3'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2020, 8, 1);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2020, 6, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is after its parent account's billing cycle start that also has a annual billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the current quaterly period
    *
    @isTest
    static void createdBeforeAnnualCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%4'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2020, 5, 17);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2019, 6, 1), updatedOrder.EffectiveDate);

    }

    *
    * Method backDateOrders
    * Case When inserting an order with a created date that is after its parent account's billing cycle start that also has a annual billing frequency
    * Result Expect the Order's EffectiveDate to be the start of the current quaterly period
    *
    @isTest
    static void createdAfterAnnualCycle(){
        Account quaterlyAccount = [SELECT Id FROM Account WHERE Name LIKE '%4'];
        Order order = new Order(AccountId=quaterlyAccount.Id);
        order.EffectiveDate = Date.today();
        order.Status = 'Draft';
        OrderCreatedDateMock.mockCreationDate = Date.newInstance(2020, 12, 21);

        Test.startTest();
            insert order;
        Test.stopTest();

        Order updatedOrder = [SELECT EffectiveDate FROM Order WHERE Id = :order.Id];

        System.assertEquals(Date.newInstance(2020, 6, 1), updatedOrder.EffectiveDate);

    }*/

   
}