salesforce-main/src/main/default/objects/Account/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
                <default>true</default>
                <label>In Advance</label>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/BPP_Deliver_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>BPP_Deliver_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Default contact for deliveries for this account</description>
    <label>Deliver To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Deliver To Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Student</relationshipLabel>
    <relationshipName>Student</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</description>
    <inlineHelpText>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/BPP_Student_Name__c.field-meta.xml
<CustomField>
    <fullName>BPP_Student_Name__c</fullName>
    <formula>Student__r.FirstName + &apos; &apos; + Student__r.LastName</formula>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>PO number related to this booking. This field is mandatory if the account requires PO&apos;s</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student that will be attending this booking</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(blng_Order__r.Billing_Type__c)</formula>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Account__c.field-meta.xml
<CustomField>
    <fullName>blng_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that will be invoiced for the booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines (Account)</relationshipLabel>
    <relationshipName>Booking_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_EndDateTime__c</fullName>
    <description>End date of the booking line. If session this will be session date, if material this will be the instance start date. This field will be populated by the booking line code</description>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_MatchingId__c.field-meta.xml
<CustomField>
    <fullName>blng_MatchingId__c</fullName>
    <description>This field will be the matching ID from the related booking summary. This field will be populated by the booking line creation code</description>
    <externalId>true</externalId>
    <label>Matching ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Order__c.field-meta.xml
<CustomField>
    <fullName>blng_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order this booking relates to</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>blng_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order product line this booking line relates to.This field is populated by the booking line creation code</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_StartDateTime__c</fullName>
    <description>The start date of the session if product family is session or the instance start date if product family is materials</description>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Booking this booking line relates to</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/BPP_Instance_Product__c.field-meta.xml
<CustomField>
    <fullName>BPP_Instance_Product__c</fullName>
    <formula>Instance__r.Product__r.Id</formula>
    <label>Instance Product</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <formula>TEXT(blng_OrderProduct__r.SBQQ__ChargeType__c)</formula>
    <label>Charge Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking line relates to</description>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>The PO number this booking line is associated to</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <description>This field will hold the date used for revenue recognition for billing. For a session line the date will be the date of the session, for a material line the date will show the instance start date</description>
    <inlineHelpText>This field will hold the date used for revenue recognition for billing. For a session line the date will show the date of the actual session, for a material line the date will show the instance start date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The session record related to this booking line</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Booking Lines (Old)</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student attending this session or receiving these materials</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/BookingLineTriggerHandler.cls
/*
* @who   Patrick Duncan <patrick.duncan@weare4c.com>
* @what  Handler class for BookingLineTrigger
* @when  14/1/2020
*/
public with sharing class BookingLineTriggerHandler {

    public static void handleAfterInsert(Map<Id,Booking_Line__c> newMap){
        List<Booking_Line__c> nonCancelledBookingLines = BookingUtility.getNonCancelledBookingLines(newMap.values());
        OrderLineBookedCalculator.calculateOrderProductsBooked(new List<Booking_Line__c>(),nonCancelledBookingLines);

        Map<Id, Booking_Line__c> bookingLinesReadyForUsageGeneration = getBookingLinesReadyForUsageGeneration(newMap.keyset());
        if (!bookingLinesReadyForUsageGeneration.isEmpty()) {
            BookingUsageGenerator.GenerationResult results = BookingUsageGenerator.generateUsages(bookingLinesReadyForUsageGeneration.values());
        }

        Set<Id> bookingLineIds = new Set<Id>();
        for (Booking_Line__c bookingLine : newMap.values()) {
            bookingLineIds.add(bookingLine.Id);
        }
        List<Booking_Line__c> bookingLineList = [
            SELECT Id, Instance__c, blng_Order__c, Student__c, Student__r.Name, Student__r.BPP_Deliver_To_Contact__r.Name, blng_Account__c,
            Student__r.RecordTypeId, BPP_Instance_Product__c, blng_OrderProduct__c, On_Hold__c, Booking__r.BPP_Student_Name__c 
            FROM Booking_Line__c WHERE Id IN: bookingLineIds
        ];
        DeliveryUtility.createDeliveryRecords(bookingLineList);
    }

    public static void handleBeforeUpdate(Map<Id,Booking_Line__c> oldMap, Map<Id,Booking_Line__c> newMap){
        Id recordTypeIdMB = Schema.SObjectType.Booking__c.getRecordTypeInfosByName().get('Material or Fee Booking').getRecordTypeId();
        Map<Id, Booking_Line__c> oldBookingLineMapToProcess = new Map<Id, Booking_Line__c>();
        Map<Id, Booking_Line__c> newBookingLineMapToProcess = new Map<Id, Booking_Line__c>();
        for (Booking_Line__c bookingLine : newMap.values()) {
            if (bookingLine.RecordTypeId != recordTypeIdMB) {
                Booking_Line__c oldBookingLine = oldMap.get(bookingLine.Id);
                oldBookingLineMapToProcess.put(oldBookingLine.Id, oldBookingLine);
                newBookingLineMapToProcess.put(bookingLine.Id, bookingLine);
            }
        }

        Set<Id> bookingLineIdsWithUpdatedInstanceLookup = SObjectUtil.filterSObjectsOnUpdatedField(oldBookingLineMapToProcess, newBookingLineMapToProcess,'Instance__c');
        Map<Id,SObject> bookingsWithUpdatedInstanceLookup = SObjectUtil.getUnionOfSObjectMapAndSet(newBookingLineMapToProcess, bookingLineIdsWithUpdatedInstanceLookup);

        InstanceAssignmentValidityChecker.checkBookingLineInstanceAssignmentValidity(bookingsWithUpdatedInstanceLookup.values());
        SessionAvailabilityChecker.filterBookingLinesAndCheckSessionAvailability(oldBookingLineMapToProcess, newBookingLineMapToProcess);
    }

    public static void handleAfterUpdate(Map<Id,Booking_Line__c> oldMap, Map<Id,Booking_Line__c> newMap){
        SessionAvailabilityChecker.updateBookingLinesWithInstanceChange(oldMap,newMap);

        Set<Id> bookingLinesWithUpdatedOrderLineLookup = SObjectUtil.filterSObjectsOnUpdatedField(oldMap,newMap,'blng_OrderProduct__c');
        Set<Id> uncancelledBookingLineIds = SObjectUtil.getUncancelledSObjectIds(oldMap,newMap,'On_Hold__c');
        Set<Id> cancelledBookingLineIds = SObjectUtil.getCancelledSObjectIds(oldMap,newMap,'On_Hold__c');
        bookingLinesWithUpdatedOrderLineLookup.removeAll(uncancelledBookingLineIds);
        bookingLinesWithUpdatedOrderLineLookup.removeAll(cancelledBookingLineIds);

        if(!bookingLinesWithUpdatedOrderLineLookup.isEmpty()){
            Map<Id,SObject> oldMapFiltered = SObjectUtil.getUnionOfSObjectMapAndSet(oldMap,bookingLinesWithUpdatedOrderLineLookup);
            Map<Id,SObject> newMapFiltered = SObjectUtil.getUnionOfSObjectMapAndSet(newMap,bookingLinesWithUpdatedOrderLineLookup);
            OrderLineBookedCalculator.calculateOrderProductsBooked(oldMapFiltered.values(),newMapFiltered.values());
        }
        if(!uncancelledBookingLineIds.isEmpty()){
            Map<Id,SObject> newMapFiltered = SObjectUtil.getUnionOfSObjectMapAndSet(newMap,uncancelledBookingLineIds);
            OrderLineBookedCalculator.calculateOrderProductsBooked(new List<Booking_Line__c>(),newMapFiltered.values());
        }
        if(!cancelledBookingLineIds.isEmpty()){
            Map<Id,SObject> oldMapFiltered = SObjectUtil.getUnionOfSObjectMapAndSet(oldMap,cancelledBookingLineIds);
            OrderLineBookedCalculator.calculateOrderProductsBooked(oldMapFiltered.values(),new List<Booking_Line__c>());
        }

        Map<Id, Booking_Line__c> bookingLinesReadyForUsageGeneration = getBookingLinesReadyForUsageGeneration(newMap.keyset());
        if (!bookingLinesReadyForUsageGeneration.isEmpty()) {
            BookingUsageGenerator.GenerationResult results = BookingUsageGenerator.generateUsages(bookingLinesReadyForUsageGeneration.values());
        }
    }
    
    private static Map<Id, Booking_Line__c> getBookingLinesReadyForUsageGeneration(Set<Id> bookingLineIds) {
        return new Map<Id, Booking_Line__c>([SELECT Id, blng_Account__c, blng_Order__c, blng_OrderProduct__c, blng_MatchingId__c, blng_StartDateTime__c, 
        	blng_EndDateTime__c, Booking__c, Student__c, Instance__c, Session__c, Rev_Rec_Date__c, PO_Number__c, Booking__r.OwnerId FROM Booking_Line__c 
        	WHERE Id IN: bookingLineIds AND On_Hold__c = 'Confirmed' AND Batch_Processed__c = FALSE AND Billing_Type__c = 'In Advance' AND Charge_Type__c = 'Usage']);
    }
}