salesforce-main/src/main/default/objects/Account/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
                <default>true</default>
                <label>In Advance</label>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</description>
    <inlineHelpText>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/Booking_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Booking_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Booking Cancelled</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(blng_Order__r.Billing_Type__c)</formula>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Account__c.field-meta.xml
<CustomField>
    <fullName>blng_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that will be invoiced for the booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines (Account)</relationshipLabel>
    <relationshipName>Booking_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Order__c.field-meta.xml
<CustomField>
    <fullName>blng_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order this booking relates to</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>blng_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order product line this booking line relates to.This field is populated by the booking line creation code</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Booking this booking line relates to</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <formula>TEXT(blng_OrderProduct__r.SBQQ__ChargeType__c)</formula>
    <label>Charge Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Material_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Product_Code__c</fullName>
    <label>Material Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>The product family from the quote line. Populated by a flow</description>
    <label>Product Family</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Order/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <description>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</description>
    <inlineHelpText>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</inlineHelpText>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingType</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/BookingLineUtility.cls
/*
* @who   Patrick Duncan <patrick.duncan@weare4c.com>
* @what  Utility class for booking lines
* @when  29/1/2020
*/
public with sharing class BookingLineUtility {

	/*
	*  @description    Method for filtering a list of booking lines that down to those which arent cancelled 
   	*  @param  bookingLineIds  			List of booking lines to filter
   	*  @return    						Filtered list of booking lines
	*/
	public static List<Booking_Line__c> getNonCancelledBookingLines(List<Booking_Line__c> bookingLines){
		List<Booking_Line__c> nonCancelledBookingLines = new List<Booking_Line__c>();
		for(Booking_Line__c bookingLine:bookingLines){
			if(bookingLine.On_Hold__c != 'Cancelled'){
				nonCancelledBookingLines.add(bookingLine);
			}
		}
		return nonCancelledBookingLines;
	}

	/*
	*  @description    Method for building a map of booking line id -> booking line
   	*  @param  bookingLineIds  			Set of booking line ids
   	*  @return    						Map of booking line id -> booking line 
	*/
	public static Map<Id,Booking_Line__c> getBookingLineMap(Set<Id> bookingLineIds){
		return new Map<Id,Booking_Line__c>([SELECT Id, Product_Family__c FROM Booking_Line__c WHERE Id IN :bookingLineIds]);
	}

	/*
	*  @description Method for filtering a set of booking lines down to those whose bookings arent cancelled
   	*  @param  oldMap   		Old bookings lines before update
   	*  @return   				Set of filtered booking lines ids
	*/
	public static Set<Id> getBookingLineIdsWithoutCancelledBookings(Map<Id,Booking_Line__c> oldMap){
		return new Map<Id,Booking_Line__c>([SELECT Id FROM Booking_Line__c WHERE Id IN :oldMap.keySet() AND Booking__r.Booking_Cancelled__c = FALSE]).keySet();
	}

	/* START OF - Changes made by 4c - 20/01/2021 - Usages */
	/*
	*  @description Method for filtering a set of booking lines down to those confirmed and not processed
   	*  @param  bookingLineIds   		Set of booking line ids
   	*  @return   				Set of filtered booking lines ids
	*/
	public static Map<Id,Booking_Line__c> getBookingLineIdsConfirmedNotProcessed(Map<Id,Booking_Line__c> bookingLines){
		Map<Id,Booking_Line__c> bookingLinesConfirmedNotProcessed = new Map<Id,Booking_Line__c>();

		String fieldsInput = String.join(new List<String>(BookingUsageBatch.fieldMapping.keySet()), ',');

		Set<String> bkgLineIds = new Set<String>();
        for(Id key : bookingLines.keySet()) {
			bkgLineIds.add('\''+key+'\'');
        }
        
        String bkgLineIdsString = String.join(new List<String>(bkgLineIds), ',');
		String customerBillingType = '\''+'In Advance'+'\'';
        String chargeType = '\''+'Usage'+'\'';

        String query = String.format('SELECT {0} FROM Booking_Line__c WHERE On_Hold__c = {1} AND Batch_Processed__c = FALSE AND Id IN ({2}) AND blng_Account__r.Billing_Type__c = {3} AND Charge_Type__c = {4}',
		new List<String>{fieldsInput, '\''+'Confirmed'+'\'', bkgLineIdsString, customerBillingType, chargeType});

		System.debug('@BookingLineUtility: getBookingLineIdsConfirmedNotProcessed: query: ' + query);

		bookingLinesConfirmedNotProcessed = new Map<Id,Booking_Line__c>((List<Booking_Line__c>)Database.query(query));
		
		return bookingLinesConfirmedNotProcessed;
	}
	/* END OF - Changes made by 4c - Usages */

    /* START OF - Changes made by David Lovejoy - 01/11/2020 - BPP-7144/8234/8651/10399 */
	public static List<Booking_Line__c> getMaterialBookingLines(List<Booking_Line__c> bookingLines){
		List<Booking_Line__c> materialBookingLines = new List<Booking_Line__c>();
		for(Booking_Line__c bookingLine:bookingLines){
			if(bookingLine.Product_Family__c == 'Materials' || bookingLine.Product_Family__c.contains('Fee')){
				materialBookingLines.add(bookingLine);
			}
		}
		return materialBookingLines;
	}
	/* END OF - Changes made by David Lovejoy */

	/* START OF - Changes made by David Lovejoy - 07/01/2021 - BPP-11870 */
	public static void addStockMaterialDetails(List<Booking_Line__c> bookingLineList) {
		Set<Id> productIds = new Set<Id>();
		Set<Id> orderIds = new Set<Id>();
		List<OrderItem> orderItemList = new List<OrderItem>();
		List<Order> orderList = new List<Order>();
		List<SBQQ__ProductOption__c> productOptionList = new List<SBQQ__ProductOption__c>();
		Map<OrderItem, SBQQ__ProductOption__c> orderItemProdOptionMap = new Map<OrderItem, SBQQ__ProductOption__c>();
														 
		for (Booking_Line__c bookingLine : bookingLineList) {
			orderIds.add(bookingLine.blng_Order__c);
		}

		if (orderIds.size() > 0) {
			orderList = DeliveryUtility.getOrderList(orderIds);
		}

		if(orderList.size() > 0) {
			productIds = DeliveryUtility.getProductIds(orderList);
			orderItemList = DeliveryUtility.getOrderItemList(orderList);
		}

		if (productIds.size() > 0) {
			productOptionList = DeliveryUtility.getProductOptionList(productIds);
		}

		if (orderItemList.size() > 0) {
			orderItemProdOptionMap = DeliveryUtility.getOrderItemProdOptionMap(orderItemList, productOptionList, bookingLineList);
		}

		if (orderItemProdOptionMap.size() > 0) {
			for (Booking_Line__c bookingLine : bookingLineList) {
				for (Order order : orderList) {
					if (bookingLine.blng_Order__c == order.Id) {
						for (OrderItem orderItem : orderItemProdOptionMap.keyset()) {
							if (bookingLine.blng_OrderProduct__c == orderItem.Id) {
								bookingLine.Available_Stock__c = orderItem.Product2.Available_Stock__c;
                        		bookingLine.Material_Product_Code__c = orderItem.Product2.ProductCode;
								bookingLine.Quantity__c = (orderItemProdOptionMap.get(orderItem).Delivery_Default__c == 'Deliver to BPP Location' ? 1 : orderItem.SBQQ__QuotedQuantity__c);
								bookingLine.Weight__c = orderItem.Product2.Weight__c;
							}
						}
					}
				}
			}
		}
	}
    /* END OF - Changes made by David Lovejoy */
    
}