salesforce-main/src/main/default/objects/Account/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <description>Billing Frequency defined on the Account level. For Accounts of type Customer Group Tier 1 - Key, this Billing Frequency will be interpreted and set correctly for invoicing.</description>
    <inlineHelpText>For Accounts of type Customer Group Tier 1 - Key, this Billing Frequency will be interpreted and set correctly for invoicing.</inlineHelpText>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
                <default>true</default>
                <label>In Advance</label>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</description>
    <inlineHelpText>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(blng_Order__r.Billing_Type__c)</formula>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Booking this booking line relates to</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking line relates to</description>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The session record related to this booking line</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Booking Lines (Old)</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Order/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <description>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</description>
    <inlineHelpText>Billing Type. This value is inherited from the Quote. For any in advance billing, the order will be excluded to a separate batch to avoid it from being picked up on by any invoice run. Billing in advance requires the &apos;Bill Now&apos; to be used in the Order.</inlineHelpText>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingType</valueSetName>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/BookingUtilityTest.cls
@isTest
private class BookingUtilityTest {
    
    /* START OF - Changes made by David Lovejoy - 16/12/2020 - commented out test class as main class does not appear to be in use */
    @testSetup
    static void testSetup(){
        blng__BillingRule__c billingRule = TestDataFactory.createBillingRule(true);
        blng__FinanceBook__c billingFinanceBook = TestDataFactory.createBillingFinanceBook(true);
        blng__RevenueRecognitionRule__c revenueRecognitionRule = TestDataFactory.createRevenueRecognitionRule(true);
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule(true);
        
        
        List<Product2> products = new List<Product2>();
        for(Integer i=0;i<5;i++){
            products.add(TestDataFactory.createProduct(false,i,billingRule,revenueRecognitionRule,taxRule));
        }
        insert products;
        
        List<Instance__c> instances = new List<Instance__c>();
        for(Integer i=0;i<5;i++){
            instances.add(TestDataFactory.createInstance(false,i,products.get(i)));
        }
        insert instances;
        
        List<Session__c> sessions = new List<Session__c>();
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<5;j++){
                sessions.add(TestDataFactory.createSession(false,(i*10)+j,instances.get(i),products.get(j),0,5));
            }
        }
        insert sessions;
        
        List<Account> accounts = new List<Account>();
        for (Integer i=0; i < 5; i++) {
            Account a = TestDataFactory.createAccount(false, false, null, i);
            a.Billing_Frequency__c = 'Monthly';
            a.Billing_Type__c = 'In Arrears';
            accounts.add(a);
        }
        insert accounts;
        
        //Create student account
        List<Account> studentAccounts = new List<Account>();
        for (Integer i=0; i < 5; i++) {
            Account a = TestDataFactory.createAccount(false, true, accounts.get(i).Id, i);
            studentAccounts.add(a);
        }
        insert studentAccounts;
        
        List<Order> orders = new List<Order>();
        for(Integer i=0;i<5;i++){
            orders.add(TestDataFactory.createOrder(false,i,accounts.get(i),null));
        }
        insert orders;
        
        List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
        for(Integer i=0;i<5;i++){
            priceBookEntries.add(TestDataFactory.createPricebookEntry(false,products.get(i),null));
        }
        insert priceBookEntries;
        
        List<OrderItem> parentOrderLines = new List<OrderItem>();
        for(Integer i=0;i<5;i++){
            parentOrderLines.add(TestDataFactory.createOrderLine(false,orders.get(i),products.get(i),null,priceBookEntries.get(i),billingRule,revenueRecognitionRule,
                                                                 taxRule,''));
        }
        insert parentOrderLines;
        
        List<OrderItem> orderLines = new List<OrderItem>();
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<5;j++){
                orderLines.add(TestDataFactory.createOrderLine(false,orders.get(i),products.get(j),parentOrderLines.get(i),
                                                               priceBookEntries.get(j),billingRule,revenueRecognitionRule,taxRule,'Session'));
            }
            
        }
        insert orderLines;
        
        List<blng__UsageSummary__c> usageSummaries = new List<blng__UsageSummary__c>();
        for (Integer i = 0; i < orderLines.size(); i++) {
            usageSummaries.add(TestDataFactory.createBookingSummary(false, orderLines.get(i)));
        }
        insert usageSummaries;
        
        for (Order order : orders) {
            order.Status = 'Activated';
        }
        update orders;
        
        List<Booking__c> bookings = new List<Booking__c>();
        for(Integer i=0;i<5;i++){
            for(Integer j=0;j<3;j++){
                bookings.add(TestDataFactory.createBooking(false,instances.get(i),orders.get(i),studentAccounts.get(i)));
            }
        }
        insert bookings;
    }
    
    @isTest
    static void test_getNonCancelledBookingLines() {
        List<Booking_Line__c> bookingLineList = [SELECT Id, On_Hold__c FROM Booking_Line__c];
        List<Booking_Line__c> nonCancelledBookingLines = BookingUtility.getNonCancelledBookingLines(bookingLineList);
        System.assert(nonCancelledBookingLines.size() > 0);
    }
}