salesforce-main/src/main/default/objects/Account/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <label>Billing Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Advance</fullName>
                <default>true</default>
                <label>In Advance</label>
            </value>
            <value>
                <fullName>In Arrears</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Charge_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Charge_Trigger__c</fullName>
    <description>Instructs the booking engine to either create the charge for an instance on the Start Date or the End Date of that instance. The charge will then be processed by an Invoice Scheduler.</description>
    <inlineHelpText>For customers that are invoiced in arrears, this defines the moment when the customer is charged for a course. As soon as the charge is created, it will be processed during the next eligible invoice run (defined by frequency and cycle start).</inlineHelpText>
    <label>Charge Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Billing_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instance Start Date</fullName>
                <default>true</default>
                <label>Instance Start Date</label>
            </value>
            <value>
                <fullName>Booking Confirmed Date</fullName>
            </value>
            <value>
                <fullName>Instance End Date</fullName>
                <isActive>false</isActive>
                <label>Instance End Date</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</description>
    <inlineHelpText>Indicates that the Account is on hold. Will prevent the creation of bookings related to orders of this account.</inlineHelpText>
    <label>On Hold</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/Booking_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Confirmed_Date__c</fullName>
    <description>Timestamped when the status of the booking is changed to &quot;Confirmed&quot;</description>
    <label>Booking Confirmed Date</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Instance_Start_Date__c</fullName>
    <description>The start date of the instance for a booking</description>
    <formula>Instance__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instance Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>PO number related to this booking. This field is mandatory if the account requires PO&apos;s</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student that will be attending this booking</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_failed__c.field-meta.xml
<CustomField>
    <fullName>Batch_failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch failed</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_failure_date__c.field-meta.xml
<CustomField>
    <fullName>Batch_failure_date__c</fullName>
    <label>Batch failure date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>Billing_Type__c</fullName>
    <formula>TEXT(blng_Order__r.Billing_Type__c)</formula>
    <label>Billing Type</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Account__c.field-meta.xml
<CustomField>
    <fullName>blng_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that will be invoiced for the booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines (Account)</relationshipLabel>
    <relationshipName>Booking_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_EndDateTime__c</fullName>
    <description>End date of the booking line. If session this will be session date, if material this will be the instance start date. This field will be populated by the booking line code</description>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_MatchingId__c.field-meta.xml
<CustomField>
    <fullName>blng_MatchingId__c</fullName>
    <description>This field will be the matching ID from the related booking summary. This field will be populated by the booking line creation code</description>
    <externalId>true</externalId>
    <label>Matching ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Order__c.field-meta.xml
<CustomField>
    <fullName>blng_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order this booking relates to</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>blng_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order product line this booking line relates to.This field is populated by the booking line creation code</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_StartDateTime__c</fullName>
    <description>The start date of the session if product family is session or the instance start date if product family is materials</description>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Booking this booking line relates to</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/BPP_Is_Material_Booking__c.field-meta.xml
<CustomField>
    <fullName>BPP_Is_Material_Booking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Material Booking</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Charge_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Charge_Trigger__c</fullName>
    <label>Charge Trigger</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking line relates to</description>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Instance_Start_Date__c</fullName>
    <description>Formula field used to pull the instance start date onto the booking line</description>
    <formula>Instance__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instance Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>The PO number this booking line is associated to</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <description>This field will hold the date used for revenue recognition for billing. For a session line the date will be the date of the session, for a material line the date will show the instance start date</description>
    <inlineHelpText>This field will hold the date used for revenue recognition for billing. For a session line the date will show the date of the actual session, for a material line the date will show the instance start date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The session record related to this booking line</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Booking Lines (Old)</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student attending this session or receiving these materials</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/BookingUsageBatch_Input__c/BookingUsageBatch_Input__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting for inputs of BookingUsageBatch</description>
    <label>BookingUsageBatch Input</label>
</CustomObject>

salesforce-main/src/main/default/objects/BookingUsageBatch_Input__c/fields/Last_run__c.field-meta.xml
<CustomField>
    <fullName>Last_run__c</fullName>
    <label>Last run</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/recordTypes/Instance.recordType-meta.xml
<RecordType>
    <fullName>Instance</fullName>
    <active>true</active>
    <label>Instance</label>
</RecordType>

salesforce-main/src/main/default/classes/BookingUsageBatch.cls
public without sharing class BookingUsageBatch implements Schedulable, Database.Batchable<sObject>, Database.Stateful 
{
    
    public Map<Id, List<String>> userIdToErrors;
    public BookingUsageBatch_Input__c input;
    public String query;
    public BookingUsageGenerator.GenerationResult results;
	List<BookingUsageGenerator.GenerationResult> allResultList = new List<BookingUsageGenerator.GenerationResult>();
    public static Map<String, String> fieldMapping = new Map<String, String>{ 
        'Id'                        => 'Booking_Line__c',
        'blng_Account__c'           => 'blng__Account__c',
        'blng_Order__c'             => 'blng__Order__c',
        'blng_OrderProduct__c'      => 'blng__OrderProduct__c',
        'blng_MatchingId__c'        => 'blng__MatchingId__c',
        'blng_StartDateTime__c'     => 'blng__StartDateTime__c',
        'blng_EndDateTime__c'       => 'blng__EndDateTime__c',
        'Booking__c'                => 'Booking__c',
        'Student__c'                => 'Student__c',
        'Instance__c'               => 'Instance__c',
        'Session__c'                => 'Session__c',
        'Rev_Rec_Date__c'           => 'Rev_Rec_Date__c',
        'PO_Number__c'              => 'PO_Number__c',
        'Booking__r.OwnerId'        => 'OwnerId'
    };
    
    public BookingUsageBatch() {
        System.debug('CONSTRUCTOR 1');
        input = BookingUsageBatch_Input__c.getOrgDefaults();
        this.userIdToErrors = new Map<Id, List<String>>();
        
        query = 'SELECT Id, blng_Account__c, blng_Order__c, blng_OrderProduct__c, blng_MatchingId__c, blng_StartDateTime__c, blng_EndDateTime__c, Booking__c, Student__c, Instance__c, Session__c, Rev_Rec_Date__c, PO_Number__c, Booking__r.OwnerId FROM Booking_Line__c WHERE On_Hold__c = \'Confirmed\' AND blng_OrderProduct__r.Product2.SBQQ__ChargeType__c = \'Usage\' AND Batch_Processed__c = FALSE AND Batch_failed__c = FALSE AND blng_Account__r.Billing_Type__c = \'In Arrears\' AND ((blng_Account__r.Charge_Trigger__c = \'Instance Start Date\' AND Instance_Start_Date__c <= TODAY) OR (blng_StartDateTime__c <= TODAY AND BPP_Is_Material_Booking__c = true) OR (blng_Account__r.Charge_Trigger__c = \'Booking Confirmed Date\' AND Booking__r.Booking_Confirmed_Date__c = TODAY))';
        System.debug('query : ' + query);
    }
    
    public BookingUsageBatch(date startedDate, date endedDate){
        
        System.debug('CONSTRUCTOR 2');
        Datetime endedDateTime = endedDate;
        String endedDateFormated = endedDateTime.format('YYYY-MM-dd');
        
        Datetime startedDateTime = startedDate;
        String startedDateFormated = startedDateTime.format('YYYY-MM-dd');
        
        input = BookingUsageBatch_Input__c.getOrgDefaults();
        String fieldsInput = String.join(new List<String>(fieldMapping.keySet()), ',');
        String statusInput = '\''+'Confirmed'+'\'';
        String customerBillingType = '\''+'In Arrears'+'\'';
        String chargeType = '\''+'Usage'+'\'';

        this.userIdToErrors = new Map<Id, List<String>>();
        query = String.format('SELECT {0} FROM Booking_Line__c WHERE On_Hold__c = {1} AND Batch_failed__c = TRUE AND Batch_failure_date__c >= {2} AND Batch_failure_date__c <= {3} AND blng_Account__r.Billing_Type__c = {4} AND blng_OrderProduct__r.Product2.SBQQ__ChargeType__c = {5}',
                                new List<String>{fieldsInput, statusInput,startedDateFormated,endedDateFormated, customerBillingType, chargeType}); 
        System.debug('query : ' + query);
    }
    
    public BookingUsageBatch(date selectedDate){
        
        System.debug('CONSTRUCTOR 3');
        Datetime selectedDateTime = selectedDate;
        String selectedDateFormated = selectedDateTime.format('YYYY-MM-dd');

        input = BookingUsageBatch_Input__c.getOrgDefaults();
        String fieldsInput = String.join(new List<String>(fieldMapping.keySet()), ',');
        String statusInput = '\''+'Confirmed'+'\'';
        String customerBillingType = '\''+'In Arrears'+'\'';
        String chargeType = '\''+'Usage'+'\'';

        this.userIdToErrors = new Map<Id, List<String>>();
        query = String.format('SELECT {0} FROM Booking_Line__c WHERE On_Hold__c = {1} AND Batch_failed__c = TRUE AND Batch_failure_date__c = {2} AND blng_Account__r.Billing_Type__c = {3} AND blng_OrderProduct__r.Product2.SBQQ__ChargeType__c = {5}',
                                new List<String>{fieldsInput, statusInput,selectedDateFormated, customerBillingType, chargeType}); 
        system.debug(query);
    }

    //Execute of schedulable interface
    public void execute(SchedulableContext SC) 
    {
        Database.executeBatch(this, 1);
    }

    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        Database.QueryLocator QL = Database.getQueryLocator(query);
        System.debug('QL : ' + QL);
        return QL;
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        System.debug('scope : ' + json.serialize(scope));
        results = BookingUsageGenerator.generateUsages(scope);
        System.debug('execute finish !!! ' + results);
        allResultList.add(results);
    }
    
    public void finish(Database.BatchableContext BC)
    {
		
        System.debug('get all results !!! ' +allResultList);        
        System.debug('input finish : ' + JSON.serialize(input));
        
        input.Last_run__c = Datetime.now();
        try{
            
            update input;
            
        }catch(DMLException e){
            system.debug('error msg : ' + e.getMessage());
        }
        
        //Send Email with CSV File
        Integer nbrUsageSuccess = 0;
        Integer nbrUsageFailed = 0;
        String headerCsv = 'Booking Line Id, isSuccess, Errors, Booking Usage Id \n';
        String finalCsv = headerCsv;
        String corpsCsv;
        
        if(allResultList != null)
        for(BookingUsageGenerator.GenerationResult result : allResultList) {    
            for(Integer i=0;i < result.bookingUsageSaveResults.size();i++){
                
                if(result.bookingUsageSaveResults[i].isSuccess()){
                    nbrUsageSuccess++;
                    corpsCsv = result.bookingUsageGenerated[i].get('Booking_Line__c')+','+'TRUE'+','+'No Errors'+','+result.bookingUsageSaveResults[i].getId()+'\n';  
                }else{
                    nbrUsageFailed++;
                    String errors = generateStringErrors(result.bookingUsageSaveResults[i].getErrors());
                    corpsCsv = result.bookingUsageGenerated[i].get('Booking_Line__c')+','+'FALSE'+','+errors+','+'NULL'+'\n';
                }
                finalCsv = finalCsv + corpsCsv;
            }
        }
        
        Messaging.SendEmailResult[] sendEmailResults = sendEmailWithCsv(finalCsv,  nbrUsageSuccess,  nbrUsageFailed);
        
        system.debug('Emails sent : '  +  sendEmailResults);
           
    }
    
    private static String generateStringErrors(List<Database.Error> saveResultErrors){
        
        String errors = '';
        String error;
        Integer j = 1;
        for(Database.Error err : saveResultErrors){
            error = 'Error ' +j+ ' : '+err.getMessage()+' || ';
            errors = errors+error;
            j++;
        }
        
        return errors.substringBeforeLast(' || ');
    }
    
    private static Messaging.SendEmailResult[] sendEmailWithCsv(String finalCsv, Integer nbrUsageSuccess, Integer nbrUsageFailed){
        
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(finalCsv);
        string csvname= 'BookingUsageResults.csv';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        String toAddressesLabel = Label.toAddresses_UsageGeneration;
        String[] toAddresses = toAddressesLabel.split(';');
        //String[] toAddresses = new List<String>{'chakib.lemkhantar@nbs-consulting.net'};
        String subject ='Booking Usage Report - '+date.today().format();
        email.setSubject(subject);
        email.setToAddresses( toAddresses );
        String body = '1-Booking usage record success : '+nbrUsageSuccess+'\n'+'2-Booking usage record failed : '+nbrUsageFailed;
        email.setPlainTextBody(body);
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        Messaging.SendEmailResult [] r;
        if (!Test.isRunningTest()) {
            r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }
        return r;
    }
}