salesforce-main/src/main/default/objects/Account/fields/BPP_Reason_SELT_Not_Required__c.field-meta.xml
<CustomField>
    <fullName>BPP_Reason_SELT_Not_Required__c</fullName>
    <description>This field reduces risk for UKVI audits. Also improves visibility of processes being followed and managed effectively.</description>
    <label>Reason SELT Not Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Higher Education Institute (HEI) has made assessment</fullName>
            </value>
            <value>
                <fullName>Migrant from majority English speaking country</fullName>
            </value>
            <value>
                <fullName>Migrant has met required English level in a previous successful visa application</fullName>
            </value>
            <value>
                <fullName>Migrant holds degree from majority English speaking country</fullName>
            </value>
            <value>
                <fullName>Migrant holds GSCE, A Levels or Scottish Higher qualification in English studied in the UK whilst under 18</fullName>
            </value>
            <value>
                <fullName>Migrant to apply as Gifted student</fullName>
            </value>
            <value>
                <fullName>Study abroad programme as part of USA HEI degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Currently_in_UK_with_a_Visa__c.field-meta.xml
<CustomField>
    <fullName>Currently_in_UK_with_a_Visa__c</fullName>
    <label>Applying in the UK</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Ever_Studied_in_UK_Before__c.field-meta.xml
<CustomField>
    <fullName>Ever_Studied_in_UK_Before__c</fullName>
    <label>Ever Studied in UK Before</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Preferred_Study_Location__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Study_Location__c</fullName>
    <description>List of BPP centres, student can choose a preferred option. 
This will aid with course planning analysis + potentially automation when booking.</description>
    <label>Preferred Study Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BPP Birmingham</fullName>
            </value>
            <value>
                <fullName>BPP Bristol</fullName>
            </value>
            <value>
                <fullName>BPP Cambridge</fullName>
            </value>
            <value>
                <fullName>BPP Croydon</fullName>
            </value>
            <value>
                <fullName>BPP Glasgow</fullName>
            </value>
            <value>
                <fullName>BPP Leeds - Whitehall Quay</fullName>
            </value>
            <value>
                <fullName>BPP London - Kings Cross</fullName>
            </value>
            <value>
                <fullName>BPP London - Liverpool Street</fullName>
            </value>
            <value>
                <fullName>BPP London - London City</fullName>
            </value>
            <value>
                <fullName>BPP London - Red Lion Street</fullName>
            </value>
            <value>
                <fullName>BPP London - Shepherds Bush</fullName>
            </value>
            <value>
                <fullName>BPP London - Waterloo</fullName>
            </value>
            <value>
                <fullName>BPP Manchester - St James</fullName>
            </value>
            <value>
                <fullName>BPP Milton Keynes</fullName>
            </value>
            <value>
                <fullName>BPP Newcastle</fullName>
            </value>
            <value>
                <fullName>BPP Nottingham</fullName>
            </value>
            <value>
                <fullName>BPP Reading</fullName>
            </value>
            <value>
                <fullName>BPP Southampton</fullName>
            </value>
            <value>
                <fullName>BPP Guernsey</fullName>
            </value>
            <value>
                <fullName>BPP Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_CAS_Number__c.field-meta.xml
<CustomField>
    <fullName>BPP_CAS_Number__c</fullName>
    <label>CAS Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_CAS_Officer__c.field-meta.xml
<CustomField>
    <fullName>BPP_CAS_Officer__c</fullName>
    <description>Field to identify responsible owner of CAS Issuing decision</description>
    <label>CAS Officer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Course_Level__c.field-meta.xml
<CustomField>
    <fullName>BPP_Course_Level__c</fullName>
    <description>Course Level pick list for &apos;CAS VISA Compliance&apos; section located on the &apos;Application&apos; Opportunity Record Type</description>
    <label>Course Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RQF Level 5</fullName>
            </value>
            <value>
                <fullName>RQF Level 6</fullName>
            </value>
            <value>
                <fullName>RQF Level 7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Date_CAS_Issued__c.field-meta.xml
<CustomField>
    <fullName>BPP_Date_CAS_Issued__c</fullName>
    <label>Date CAS Issued</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Last_Enrolment_Date__c.field-meta.xml
<CustomField>
    <fullName>BPP_Last_Enrolment_Date__c</fullName>
    <description>Last Enrolment Date field for &apos;CAS VISA Compliance&apos; section located on the &apos;Application&apos; Opportunity Record Type</description>
    <label>Last Enrolment Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Previous_Course_Level__c.field-meta.xml
<CustomField>
    <fullName>BPP_Previous_Course_Level__c</fullName>
    <description>Previous Course Level pick list for &apos;CAS VISA Compliance&apos; section located on the &apos;Application&apos; Opportunity Record Type</description>
    <label>Previous Course Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RQF Level 2</fullName>
            </value>
            <value>
                <fullName>RQF Level 3</fullName>
            </value>
            <value>
                <fullName>RQF Level 4</fullName>
            </value>
            <value>
                <fullName>RQF Level 5</fullName>
            </value>
            <value>
                <fullName>RQF Level 6</fullName>
            </value>
            <value>
                <fullName>RQF Level 7</fullName>
            </value>
            <value>
                <fullName>RQF Level 8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/CAS_Progression_Justification__c.field-meta.xml
<CustomField>
    <fullName>CAS_Progression_Justification__c</fullName>
    <description>The field should be able to be viewed for the Visa Compliance profile.</description>
    <label>CAS Progression Justification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <description>Value of discount that is applied to the opportunity</description>
    <label>Discount Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Indicates the location that the student has applied to or expressed interest.</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>London - City</fullName>
            </value>
            <value>
                <fullName>London - Waterloo</fullName>
            </value>
            <value>
                <fullName>London - Holborn</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>Leeds</fullName>
            </value>
            <value>
                <fullName>Croydon</fullName>
            </value>
            <value>
                <fullName>Milton Keynes</fullName>
            </value>
            <value>
                <fullName>eLearning Center</fullName>
            </value>
            <value>
                <fullName>Cambridge</fullName>
            </value>
            <value>
                <fullName>Maidstone</fullName>
            </value>
            <value>
                <fullName>Glasgow</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Nottingham</fullName>
            </value>
            <value>
                <fullName>Cardiff</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Southampton</fullName>
            </value>
            <value>
                <fullName>Manchester</fullName>
            </value>
            <value>
                <fullName>Liverpool</fullName>
            </value>
            <value>
                <fullName>Swindon</fullName>
            </value>
            <value>
                <fullName>Abingdon - McTimoney</fullName>
            </value>
            <value>
                <fullName>London (City)</fullName>
            </value>
            <value>
                <fullName>London (Waterloo)</fullName>
            </value>
            <value>
                <fullName>London (Holborn)</fullName>
            </value>
            <value>
                <fullName>Abingdon (McTimoney)</fullName>
            </value>
            <value>
                <fullName>Doncaster-RDASH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Programme_Application__c.field-meta.xml
<CustomField>
    <fullName>Programme_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Programme of interest or application.</description>
    <label>Programme</label>
    <referenceTo>Programme__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Total_Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Sale_Price__c</fullName>
    <description>Total sale price that the customer will pay BPP.
Opportunity value - discount amount</description>
    <formula>Course_Instance__r.BNR_Price__c - Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/classes/CASLetterPDFCtrl.cls
/**********************************************************************
Name: CASLetterPDFCtrl
Purpose: CASLetterPDFCtrl apex controller class is for CAS issued letter with PDF attachment for BPP-24827/BPP-24590                 
-------                                                             
History                                                             
-------                                                             
VERSION  AUTHOR             DATE              DETAIL                              
0.1 -   Swayanprava Sahoo     06/02/2023      INITIAL DEVELOPMENT  
***********************************************************************/
public class CASLetterPDFCtrl {
    public static CASLetterPDFData getCASLetterPDFData(){
        
        CASLetterPDFData casLetterPDFData = new CASLetterPDFData();
        Id oppId = apexpages.Currentpage().getparameters().get('Id');
        Set<Id> accountIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();
        System.debug('@OpportunityId@@'+oppId);
        
        casLetterPDFData.opportunityRecord = [
            SELECT Id, AccountId, BPP_Last_Enrolment_Date__c, Course_Instance__r.Name,  Course_Instance__r.Location__c, Course_Instance__r.Start_Date__c, 
            Course_Instance__r.End_Date__c, Course_Instance__r.Level_PQ__c, Total_Sale_Price__c, Discount_Amount__c, CAS_Progression_Justification__c, 
            BPP_CAS_Officer__c, BPP_Course_Level__c, BPP_Previous_Course_Level__c, BPP_Date_CAS_Issued__c, BPP_CAS_Number__c,Programme_Application__r.Name,
            Account.PersonContactId, Account.LastName, Account.FirstName, Account.BNR_Banner_ID__pc, Account.Primary_Nationality__pr.ISO_CODE__c, 
            Account.Gender__pc, Account.SFDC_Country_of_Birth__pr.ISO_CODE__c, Account.Passport_Number__pc, Account.PersonBirthdate,  
            Account.BPP_Reason_SELT_Not_Required__c, Account.Overall_Language_Score__pc, Account.Speaking_Language_Score__pc, Account.Listening_Language_Score__pc, 
            Account.Reading_Language_Score__pc, Account.Writing_Language_Score__pc, Account.Ever_Studied_in_UK_Before__c, Account.Language_Test_Type__pc
            FROM Opportunity WHERE Id =:oppId
        ];
        
        if(casLetterPDFData.opportunityRecord != null && casLetterPDFData.opportunityRecord.AccountId != null){
            casLetterPDFData.accountRecord = [Select id, name, firstname, lastname, BNR_Banner_ID__pc,PersonBirthdate, Primary_Nationality__pr.name, Gender__pc, Passport_Number__pc, SFDC_Country_of_Birth__pr.name, Currently_in_UK_with_a_Visa__c, Preferred_Study_Location__c from Account where id =:casLetterPDFData.opportunityRecord.AccountId];
            if(casLetterPDFData.accountRecord.Id != null){
                System.debug(casLetterPDFData.opportunityRecord);
                System.debug(casLetterPDFData.accountRecord);
                
                casLetterPDFData.dateOfBirth = (casLetterPDFData.accountRecord.PersonBirthdate != null ? casLetterPDFData.accountRecord.PersonBirthdate.format() : null);
                casLetterPDFData.casIssuedDate = (casLetterPDFData.opportunityRecord.BPP_Date_CAS_Issued__c != null ? casLetterPDFData.opportunityRecord.BPP_Date_CAS_Issued__c.format() : null);
                casLetterPDFData.courseStartDate = (casLetterPDFData.opportunityRecord.Course_Instance__r.Start_Date__c != null ? casLetterPDFData.opportunityRecord.Course_Instance__r.Start_Date__c.format() : null);
                casLetterPDFData.courseEndDate = (casLetterPDFData.opportunityRecord.Course_Instance__r.End_Date__c != null ? casLetterPDFData.opportunityRecord.Course_Instance__r.End_Date__c.format() : null);
                casLetterPDFData.lastEnrolmentDate = (casLetterPDFData.opportunityRecord.BPP_Last_Enrolment_Date__c != null ? casLetterPDFData.opportunityRecord.BPP_Last_Enrolment_Date__c.format() : null);
                
                // Main study address
                System.debug('@StudyLocation@@'+casLetterPDFData.opportunityRecord.Course_Instance__r.Location__c);
                if(casLetterPDFData.opportunityRecord.Course_Instance__r.Location__c != null){
                    casLetterPDFData.mainSiteOfStudy = CasData.setMainSiteOfStudy(casLetterPDFData.opportunityRecord.Course_Instance__r.Location__c);
                }
                
                // Course fees for only first year
                casLetterPDFData.courseFeesForFirstYearOnly = CasData.setCourseFeesForFirstYearOnly(casLetterPDFData.opportunityRecord.Total_Sale_Price__c, casLetterPDFData.opportunityRecord.Discount_Amount__c, casLetterPDFData.opportunityRecord.Course_Instance__r.Start_Date__c, casLetterPDFData.opportunityRecord.Course_Instance__r.End_Date__c);
				
                // Total Course Fees Paid to date
                accountIds.add(casLetterPDFData.opportunityRecord.AccountId);
                casLetterPDFData.paymentAmountMap = CasData.createPaymentAmountMap(accountIds);
                system.debug(casLetterPDFData.paymentAmountMap.get(casLetterPDFData.accountRecord.Id));
                casLetterPDFData.paymentAmount = casLetterPDFData.paymentAmountMap.get(casLetterPDFData.accountRecord.Id);

                // Qualification details and English document used for offer
                contactIds.add(casLetterPDFData.opportunityRecord.Account.PersonContactId);
                casLetterPDFData.qualificationMap = CasData.createQualificationMap(contactIds);
                system.debug(casLetterPDFData.qualificationMap);
                System.debug('English Test Type :'+casLetterPDFData.opportunityRecord.Account.Language_Test_Type__pc);
                if(casLetterPDFData.qualificationMap != null){
                    casLetterPDFData.qualificationList = casLetterPDFData.qualificationMap.get(casLetterPDFData.opportunityRecord.Account.PersonContactId);
                	system.debug(casLetterPDFData.qualificationList);
                }
                if (casLetterPDFData.qualificationList != null && casLetterPDFData.qualificationList.size() > 0) {
                    casLetterPDFData.englishDocumentUsedForOffer = CasData.setEnglishDocumentUsedForOffer(casLetterPDFData.opportunityRecord.Account.Language_Test_Type__pc);
                    casLetterPDFData.qualificationDetails = CasData.concatenateQualificationDetails(casLetterPDFData.qualificationList, casLetterPDFData.englishDocumentUsedForOffer);
                    system.debug(casLetterPDFData.qualificationDetails);
                    system.debug(casLetterPDFData.englishDocumentUsedForOffer);
                }
                
                //CAS Progression Justification field value only if the student studied in the UK before 
                casLetterPDFData.casProgressionJustification = null;
                casLetterPDFData.everStudiedInUKBefore = false;
                if(casLetterPDFData.opportunityRecord.Account.Ever_Studied_in_UK_Before__c=='Yes'){
                    casLetterPDFData.everStudiedInUKBefore = true;
                    casLetterPDFData.casProgressionJustification = casLetterPDFData.opportunityRecord.CAS_Progression_Justification__c;
                }
            }
        }
        return casLetterPDFData;
    }
    
    public class CASLetterPDFData {
        public Opportunity opportunityRecord{get;set;}
        public Account accountRecord{get;set;}
        public String dateOfBirth{get;set;}
        public String casIssuedDate{get;set;}
        public String courseStartDate{get;set;}
        public String courseEndDate{get;set;}
        public String lastEnrolmentDate{get;set;}
        public Decimal courseFeesForFirstYearOnly{get;set;}
        public CasData.MainSiteOfStudy mainSiteOfStudy{get;set;}
        public Map<Id, List<Qualification__c>> qualificationMap{get;set;}
        public Map<Id, Decimal> paymentAmountMap{get;set;}
        public Decimal paymentAmount{get;set;}
        public String qualificationDetails{get;set;}
        public String englishDocumentUsedForOffer{get;set;}
        public List<Qualification__c> qualificationList{get;set;}
        public String casProgressionJustification{get;set;}
        public boolean everStudiedInUKBefore{get;set;}
        
    }
}