salesforce-main/src/main/default/objects/Account/fields/BPP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>BPP_Account_Number__c</fullName>
    <description>Salesforce unique identifier for both Student and Business Accounts</description>
    <displayFormat>{0000000}</displayFormat>
    <label>Account Number</label>
    <type>AutoNumber</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Formula to display student&apos;s progress in buying cycle.  Influenced by opportunities associated with student record.

Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</description>
    <formula>IF( Opportunity_Applications_Accepted__c &gt; 0, &quot;Student&quot;,
  IF( Opportunity_Applications_in_Progress__c &gt; 0, &quot;Applicant&quot;,
    IF( Opportunity_Interests_Declines__c &gt; 0, &quot;Prospect&quot;, &quot;Undeclared&quot;)))</formula>
    <inlineHelpText>Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/CBA__c.field-meta.xml
<CustomField>
    <fullName>CBA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If booking a CBA then this should contain a valid instance for the product</description>
    <label>CBA</label>
    <referenceTo>CBA__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Exam_Price__c.field-meta.xml
<CustomField>
    <fullName>Exam_Price__c</fullName>
    <description>Roll up of cost of exams for this booking from the booking lines. To be used in reports as backing information for invoices</description>
    <label>Exam Price</label>
    <summarizedField>Booking_Line__c.blng_PreratedAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Booking_Line__c.Product_Family__c</field>
        <operation>equals</operation>
        <value>Exam</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking_Line__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <description>The instance name, Used in related lists</description>
    <formula>Instance__r.Instance_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Instance Name</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Material_Price__c.field-meta.xml
<CustomField>
    <fullName>Material_Price__c</fullName>
    <description>Roll up of cost of materials for this booking from the booking lines. To be used in reports as backing information for invoices</description>
    <label>Material Price</label>
    <summarizedField>Booking_Line__c.blng_PreratedAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Booking_Line__c.Product_Family__c</field>
        <operation>equals</operation>
        <value>Materials, VLE</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking_Line__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>PO number related to this booking. This field is mandatory if the account requires PO&apos;s</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this booking.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student that will be attending this booking</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Tuition_Price__c.field-meta.xml
<CustomField>
    <fullName>Tuition_Price__c</fullName>
    <description>Roll up of tuition cost from the booking lines. To be used in reports</description>
    <label>Tuition Price</label>
    <summarizedField>Booking_Line__c.blng_PreratedAmount__c</summarizedField>
    <summaryFilterItems>
        <field>Booking_Line__c.Product_Family__c</field>
        <operation>contains</operation>
        <value>Session</value>
    </summaryFilterItems>
    <summaryForeignKey>Booking_Line__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <description>This object will contain values for Business Units.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/CBA__c/CBA__c.object-meta.xml
<CustomObject>
    <description>CBA (Computer Based Assessment) junction object between Product and Instance</description>
    <label>CBA</label>
    <nameField>
        <displayFormat>CBA-{0000000}</displayFormat>
        <label>CBA Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/CBA__c/fields/CBA_Name__c.field-meta.xml
<CustomField>
    <fullName>CBA_Name__c</fullName>
    <description>Key product / instance info for the CBA</description>
    <formula>Text( Product__r.Qualification__c ) &amp; &quot; - &quot; &amp; TEXT( Product__r.Level_PQ__c ) &amp; &quot; - &quot; &amp; Text( Product__r.Paper__c ) &amp; &quot; - &quot; &amp; Product__r.Course_Type__c &amp; &quot; - &quot; &amp;
Instance__r.Study_Location__r.Name &amp; &quot; - &quot; &amp; Text( Instance__r.Start_Date__c ) &amp; &quot; - &quot; &amp; Text( Instance__r.Session_Duration__c )</formula>
    <label>CBA Name</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/CBA__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <description>Instance the CBA is representing</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This record must be associated with a CBA Instance record</errorMessage>
        <filterItems>
            <field>Instance__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CBA Instance</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>CBA Products</relationshipLabel>
    <relationshipName>CBAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

salesforce-main/src/main/default/objects/CBA__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product the CBA is representing</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>CBA Products</relationshipLabel>
    <relationshipName>CBAs</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/fields/Instance_Name__c.field-meta.xml
<CustomField>
    <fullName>Instance_Name__c</fullName>
    <description>Longer Name field as requested by BPP</description>
    <label>Instance Name</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product related to this Instance</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Instances</relationshipLabel>
    <relationshipName>Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/recordTypes/Instance.recordType-meta.xml
<RecordType>
    <fullName>Instance</fullName>
    <active>true</active>
    <label>Instance</label>
</RecordType>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/Invoiceheader_details__c.object-meta.xml
<CustomObject>
    <label>Invoice Backing Detail</label>
    <nameField>
        <displayFormat>IBD-{000000}</displayFormat>
        <label>Invoice Backing Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Backing Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Booking that this Invoice Backing Detail is related to.</description>
    <inlineHelpText>The Booking that this Invoice Backing Detail is related to.</inlineHelpText>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Invoice Backing Details</relationshipLabel>
    <relationshipName>Invoice_Backing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/BPP_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>BPP_Account_Number__c</fullName>
    <label>Account Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Cost_Centre__c.field-meta.xml
<CustomField>
    <fullName>Cost_Centre__c</fullName>
    <label>Cost Centre</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Customer_POnumber__c.field-meta.xml
<CustomField>
    <fullName>Customer_POnumber__c</fullName>
    <label>Customer PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Exam_Price__c.field-meta.xml
<CustomField>
    <fullName>Exam_Price__c</fullName>
    <label>Exam Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Function__c.field-meta.xml
<CustomField>
    <fullName>Function__c</fullName>
    <label>Function</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Instance that this Invoice Backing Detail is related to.</description>
    <inlineHelpText>The Instance that this Invoice Backing Detail is related to.</inlineHelpText>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Invoice Backing Details</relationshipLabel>
    <relationshipName>Invoice_Backing_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Backing Details</relationshipLabel>
    <relationshipName>Invoiceheader_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Invoiceheader_details__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/InvoiceHeaderDetailsGenerator.cls
/**
 *  @who    Duy Vu <duy.vu@weare4c.com>
 *  @when   02/07/2020
 *  @what   Generate Invoiceheader Details records from invoiceLines
 */
public with sharing class InvoiceHeaderDetailsGenerator {
    private static Map<Id, List<blng__Usage__c>> usageSummaryIdToUsageLines;
    private static Map<Id, Instance__c> instances;
    private static Map<Id, Booking__c> bookings;
    private static Map<Id, Account> students;
    private static List<CBA__c> cbaList = new List<CBA__c>();

    public static void createInvoiceHeaderDetails(List<blng__InvoiceLine__c> invoiceLines) {
        setUpObjectMappings(invoiceLines);
        // Iterating through Invoice Lines to create Invoiceheader Details
        Set<Id> processedBookings = new Set<Id>();
        List<Invoiceheader_details__c> headerDetails = new List<Invoiceheader_details__c>();
        for (blng__InvoiceLine__c invoiceLine : invoiceLines) {
            if (usageSummaryIdToUsageLines.containsKey(invoiceLine.blng__UsageSummary__c)) {
                List<blng__Usage__c> usageLines = usageSummaryIdToUsageLines.get(invoiceLine.blng__UsageSummary__c);
                for (blng__Usage__c usageLine : usageLines) {
                    if (processedBookings.contains(usageLine.Booking__c)) {
                        continue;   
                    }
                    Invoiceheader_details__c headerDetail = createInvoiceHeaderDetailsObject(usageLine);
                    headerDetail.Invoice__c = invoiceLine.blng__Invoice__c;
                    if (invoiceLine.Product_Family_fx__c == 'Exam') {
                        populateCBAName(invoiceLine, headerDetail);
                    }
                    headerDetails.add(headerDetail);
                    processedBookings.add(usageLine.Booking__c);
                }
            }
        }
        if (headerDetails.size() != 0) {
            try { 
                insert headerDetails;
            } catch (DmlException e) {
                System.debug('Error Message: ' + e.getMessage());
                invoiceLines[0].addError(e);
            }
        }
    }

    // This method will setup all static Map variables used for Invoiceheader Detail creation
    private static void setUpObjectMappings(List<blng__InvoiceLine__c> invoiceLines) {
        List<Id> usageSummaryIds = new List<Id>();
        List<Id> bookingIds = new List<Id>();
        List<Id> studentIds = new List<Id>();
        List<Id> instanceIds = new List<Id>();
        List<Id> productIds = new List<Id>();

        for (blng__InvoiceLine__c invoiceLine : invoiceLines) {
            if (invoiceLine.blng__UsageSummary__c != null) {
                usageSummaryIds.add(invoiceLine.blng__UsageSummary__c);
            }
            if (invoiceLine.Product_Family_fx__c == 'Exam') {
                productIds.add(invoiceLine.blng__Product__c);
            }
        }

        usageSummaryIdToUsageLines = new Map<Id, List<blng__Usage__c>>();
        String status = (Test.isRunningTest() ? 'On Hold' : 'Confirmed');
        String query = 'SELECT Id, Booking__c, Instance__c, blng__UsageSummary__c FROM blng__Usage__c WHERE blng__UsageSummary__c IN :usageSummaryIds AND Booking__r.Status__c =: status';
        for (blng__Usage__c usageLine : Database.query(query)) {
            // Create Map from Usage Summary Ids to their Usage Lines
            List<blng__Usage__c> usageLinesWithUsageSummaryId = usageSummaryIdToUsageLines.get(usageLine.blng__UsageSummary__c);
            if (usageLinesWithUsageSummaryId == null) {
                usageLinesWithUsageSummaryId = new List<blng__Usage__c>();
                usageSummaryIdToUsageLines.put(usageLine.blng__UsageSummary__c, usageLinesWithUsageSummaryId);
            }
            usageLinesWithUsageSummaryId.add(usageLine);
            // Getting Booking Id and Instance Id to later query for these objects
            bookingIds.add(usageLine.Booking__c);
            instanceIds.add(usageLine.Instance__c);
        }

        instances = new Map<Id, Instance__c>([SELECT Id, Instance_Name__c FROM Instance__c WHERE Id IN :instanceIds]);
        bookings = new Map<Id, Booking__c>([SELECT Id, PO_Number__c, Tuition_Price__c, Material_Price__c, Exam_Price__c, Student__c FROM Booking__c WHERE Id IN :bookingIds]);
        
        for (Booking__c booking : bookings.values()) {
            studentIds.add(booking.Student__c);
        }
        students = new Map<Id, Account>([SELECT Id, Name, BPP_Account_Number__c, Cost_Centre_Number__pc, Business_Unit__pc, Function__c FROM Account WHERE Id IN :studentIds]);

        if (productIds.size() > 0) {
            cbaList = [SELECT Id, CBA_Name__c, Product__c FROM CBA__c WHERE Product__c IN: productIds AND Instance__c IN: instanceIds];
            System.debug(cbaList.size());
        }
    }

    // Create InvoiceheaderDetail object from required objects' fields
    private static Invoiceheader_details__c createInvoiceHeaderDetailsObject(blng__Usage__c usageLine) {
        Invoiceheader_details__c invoiceBackingDetail = new Invoiceheader_details__c();
        if (bookings.containsKey(usageLine.Booking__c)) {
            Booking__c booking = bookings.get(usageLine.Booking__c);
            invoiceBackingDetail.Booking__c = booking.Id;
            invoiceBackingDetail.Customer_POnumber__c = booking.PO_Number__c;
            invoiceBackingDetail.Material_Price__c = booking.Material_Price__c;
            invoiceBackingDetail.Tuition_Price__c = booking.Tuition_Price__c;
            invoiceBackingDetail.Exam_Price__c = booking.Exam_Price__c;
            if(students.containsKey(booking.Student__c)) {
                Account student = students.get(booking.Student__c);
                invoiceBackingDetail.Cost_Centre__c = student.Cost_Centre_Number__pc;
                invoiceBackingDetail.Student_Name__c = student.Name;
                invoiceBackingDetail.Business_Unit__c = student.Business_Unit__pc;
                invoiceBackingDetail.BPP_Account_Number__c = student.BPP_Account_Number__c;
                invoiceBackingDetail.Function__c = student.Function__c;
            }
        }
        if(instances.containsKey(usageLine.Instance__c)) {
            Instance__c instance = instances.get(usageLine.Instance__c);
            invoiceBackingDetail.Instance__c = instance.Id;
            invoiceBackingDetail.Course_Name__c = instance.Instance_Name__c;
        }
        return invoiceBackingDetail;
    }

    private static void populateCBAName(blng__InvoiceLine__c invoiceLine, Invoiceheader_details__c headerDetail) {
        for (CBA__c cba : cbaList) {
            if (invoiceLine.blng__Product__c == cba.Product__c) {
                System.debug('@InvoiceHeaderDetailsGenerator CBA: ' + cba);
                headerDetail.Course_Name__c = cba.CBA_Name__c;
            }
        }
    }
}