salesforce-main/src/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Student</relationshipLabel>
    <relationshipName>Student</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Formula to display student&apos;s progress in buying cycle.  Influenced by opportunities associated with student record.

Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</description>
    <formula>IF( Opportunity_Applications_Accepted__c &gt; 0, &quot;Student&quot;,
  IF( Opportunity_Applications_in_Progress__c &gt; 0, &quot;Applicant&quot;,
    IF( Opportunity_Interests_Declines__c &gt; 0, &quot;Prospect&quot;, &quot;Undeclared&quot;)))</formula>
    <inlineHelpText>Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Authorisation_Token__c/Authorisation_Token__c.object-meta.xml
<CustomObject>
    <label>Authorisation Token</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisation Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/BPP_Cancellation_Action__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cancellation_Action__c</fullName>
    <description>The purpose of this field is to determine whether or not the Booking&apos;s related dispatched materials should have a negative Revenue Schedule created for them when the Booking is cancelled.</description>
    <label>Cancellation Action</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Fulfilled Materials</fullName>
            </value>
            <value>
                <fullName>Don&apos;t Credit Fulfilled Materials</fullName>
            </value>
            <value>
                <fullName>Credit Dispatched Materials</fullName>
                <isActive>false</isActive>
                <label>Credit Dispatched Materials</label>
            </value>
            <value>
                <fullName>Don&apos;t Credit Dispatched Materials</fullName>
                <isActive>false</isActive>
                <label>Don&apos;t Credit Dispatched Materials</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/BPP_Cancellation_Terms__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cancellation_Terms__c</fullName>
    <description>To determine whether a Booking falls inside or outside of our cancellation terms.</description>
    <label>Cancellation Terms</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside</fullName>
            </value>
            <value>
                <fullName>Outside</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Hub_Account__c.field-meta.xml
<CustomField>
    <fullName>Hub_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student&apos;s Hub account that will be provisioned against this booking</description>
    <label>Hub Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account is not associated with the student on the booking</errorMessage>
        <filterItems>
            <field>Hub_Account__c.Student__c</field>
            <operation>equals</operation>
            <valueField>$Source.Student__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hub_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this booking.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>Dependant field to Status - reason should be given if the status cannot be progressed to &apos;Confirmed&apos;</description>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed Paper</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Changed Mind</fullName>
            </value>
            <value>
                <fullName>Extenuating Circumstances</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Internal Error</fullName>
            </value>
            <value>
                <fullName>Apprenticeships - Break in Learning</fullName>
            </value>
            <value>
                <fullName>Apprenticeships – Leaver Not Achiever</fullName>
            </value>
            <value>
                <fullName>Complaint - HUB</fullName>
            </value>
            <value>
                <fullName>Complaint - Tutor</fullName>
            </value>
            <value>
                <fullName>Complaint - Materials</fullName>
            </value>
            <value>
                <fullName>Complaint - Marking</fullName>
            </value>
            <value>
                <fullName>Complaint - Student Experience</fullName>
            </value>
            <value>
                <fullName>Access – (Internal Fix)</fullName>
            </value>
            <value>
                <fullName>Exemption</fullName>
            </value>
            <value>
                <fullName>Client lead change</fullName>
            </value>
            <value>
                <fullName>IT fix</fullName>
            </value>
            <value>
                <fullName>Scheduling change</fullName>
            </value>
            <value>
                <fullName>Admin error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student that will be attending this booking</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/fields/Instance_ID__c.field-meta.xml
<CustomField>
    <fullName>Instance_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Product Factory ID for this course</description>
    <externalId>true</externalId>
    <label>Product Factory Instance ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/recordTypes/Instance.recordType-meta.xml
<RecordType>
    <fullName>Instance</fullName>
    <active>true</active>
    <label>Instance</label>
</RecordType>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/AWSsampleAPIcallCancellationTest.cls
@isTest
private class AWSsampleAPIcallCancellationTest {
    @testSetup
    static void testSetup() {
        Database.DMLOptions dbDML = new Database.DMLOptions();
        dbDML.DuplicateRuleHeader.allowSave = true;
        dbDML.DuplicateRuleHeader.runAsCurrentUser = true;

        Account clientAccount = TestDataFactory.createAccount(false, false, null, 0);
        Database.insert(clientAccount, dbDML);

        Account studentAccount = TestDataFactory.createAccount(false, true, clientAccount.Id, 1);
        Database.insert(studentAccount, dbDML);
        
        Hub_Account__c hubAccount = new Hub_Account__c(
            Hub_Username__c = studentAccount.PersonEmail, 
            Student__c = studentAccount.Id
        );
        insert hubAccount;

        country_list__c cntry = new country_list__c(
            Name = 'United Kingdom',
            ISO_Code__c = 'GBR',
            country_code_2__c = 'GB'
        );
        insert cntry;

        Address__c address = TestDataFactory.createAddress(false, 0, clientAccount, cntry, true, false);
        Database.insert(address, dbDML);

        Order order = TestDataFactory.createOrder(true, 0, clientAccount, null, address);
        blng__BillingRule__c billingRule = TestDataFactory.createBillingRule(true);
        blng__FinanceBook__c billingFinanceBook = TestDataFactory.createBillingFinanceBook(true);
        blng__BillingTreatment__c billingTreatment = TestDataFactory.createBillingTreatment(
            true,
            billingRule,
            billingFinanceBook
        );
        blng__RevenueRecognitionRule__c revenueRecognitionRule = TestDataFactory.createRevenueRecognitionRule(true);
        blng__TaxRule__c taxRule = TestDataFactory.createTaxRule(true);
        Product2 product = TestDataFactory.createProduct(true, 0, billingRule, revenueRecognitionRule, taxRule);
        Instance__c instance = TestDataFactory.createInstance(true, 0, product);
        PricebookEntry priceBookEntry = (TestDataFactory.createPricebookEntry(true, product, null));
        OrderItem orderLine = TestDataFactory.createOrderLine(
            true,
            order,
            product,
            null,
            priceBookEntry,
            billingRule,
            revenueRecognitionRule,
            taxRule,
            'Materials'
        );
        Authorisation_Token__c authToken = TestDataFactory.createAuthorisationToken(true);
    }

    @isTest
    static void itShouldInitiateBookingCancelledCalloutAndCreateIntegrationLog() {
        Account studentAccount = [SELECT Id, Client__c FROM Account WHERE IsPersonAccount = TRUE];
        Hub_Account__c hubAccount = [SELECT Id FROM Hub_Account__c];

        Order order = [SELECT Id FROM Order];
        order.Status = 'Activated';
        update order;

        Instance__c instance = [SELECT Id, Instance_ID__c FROM Instance__c];

        Test.startTest();
        Booking__c booking = TestDataFactory.createBooking(false, instance, order, studentAccount);
        booking.Hub_Account__c = hubAccount.Id;
        booking.Status__c = 'Cancelled';
        booking.Status_Reason__c = 'Deferral';
        booking.BPP_Cancellation_Action__c = 'Don\'t Credit Fulfilled Materials';
        booking.BPP_Cancellation_Terms__c = 'Outside';
        insert booking;

        Test.setMock(HttpCalloutMock.class, new AWSCalloutMock());
        Test.stopTest();

        List<Integration_Log__c> integrationLogList = [SELECT Id FROM Integration_Log__c];
        Assert.isTrue(
            integrationLogList.size() > 0,
            'Integration Logs for Booking cancellation should have been created.'
        );
    }
}