salesforce-main/src/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Student</relationshipLabel>
    <relationshipName>Student</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Used for SIS Integrations.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appilcations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Review__c/Application_Review__c.object-meta.xml
<CustomObject>
    <description>This object tracks reviews against Applications(Opportunities) and provides an audit including comments and reviewing users.</description>
    <label>Application Review</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Application Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>The Application (Opportunity) that this review is related to</description>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Reviews</relationshipLabel>
    <relationshipName>Application_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

salesforce-main/src/main/default/objects/Application_Review__c/fields/Feedback_Required__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Feedback Required</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/AuthorisedOn__c.field-meta.xml
<CustomField>
    <fullName>AuthorisedOn__c</fullName>
    <description>The datetime that the application was moved into Acceptance, used in applicationStageChange event</description>
    <label>AuthorisedOn</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Authoriser__c.field-meta.xml
<CustomField>
    <fullName>Authoriser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the user that approved the application, this is sent to Join in an applicationStageChanged event</description>
    <label>Authoriser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AuthorisedOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Bypass_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass_Validation_Rule</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company account that is associated to the student (Client field) at the time the opportunity is processed. Primarily developed for Application opportunities</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Select the business account related to the student</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Client)</relationshipLabel>
    <relationshipName>StudentOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Line_Manager__c.field-meta.xml
<CustomField>
    <fullName>Line_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Contact that is used to identify the Line Manager for Application requests</description>
    <label>Line Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Line Manager can&apos;t be a Student Account</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Line Manager)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/classes/ApplicationReviewControllerTest.cls
@isTest
private class ApplicationReviewControllerTest {
    private static Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Student_Account')
        .getRecordTypeId();

    private static Id opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
        .get('Apprentice_Application')
        .getRecordTypeId();

    @TestSetup
    static void setup() {
        Account acc = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);
        insert acc;

        Account client = new Account(Name = 'Acme Inc');
        insert client;

        Country_List__c country = new country_list__c(
            Name = 'United Kingdom',
            country_code_2__c = 'GB',
            Valid_Nationality__c = true
        );
        insert country;

        Address__c address = new Address__c(
            Street_1__c = 'Street0',
            Student__c = acc.Id,
            Lookup_Country__c = country.Id,
            Type__c = 'Home'
        );

        insert address;

        Opportunity opp = new Opportunity(
            RecordTypeId = opportunityRecordTypeId,
            name = 'Test',
            Application_Id__c = 'test-1234',
            accountid = acc.Id,
            StageName = 'Application',
            CloseDate = Date.today(),
            Client__c = client.Id
        );

        insert opp;

        opp.Bypass_Validation_Rule__c = true;
        opp.StageName = 'BPP Review';
        update opp;
    }

    @isTest
    private static void itShouldBeAbleToStartAFinalReview() {
        // GIVEN we have an opportunity in the acceptance stage
        Opportunity opp = [SELECT StageName, BPP_Sub_Status__c FROM Opportunity WHERE Application_ID__c = 'test-1234'];

        opp.StageName = 'Acceptance';
        opp.StageName = 'New';

        update opp;

        // WHEN we call the startFinalReview method
        ApplicationReviewController.startFinalReview(opp.Id);

        // THEN I expect the sub status to be updated
        Opportunity out = [SELECT BPP_Sub_Status__c FROM Opportunity WHERE Id = :opp.Id];

        Assert.areEqual('In Progress', out.BPP_Sub_Status__c);
    }

    @isTest
    private static void itShouldBeAbleToStartAReview() {
        // GIVEN we have an opportunity that is at BPP Review
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-1234'];
        // WHEN we call the start review method
        ApplicationReviewController.startReview(opp.Id);
        // THEN I expect the sub status to update
        Opportunity out = [SELECT BPP_Sub_Status__c FROM Opportunity WHERE Id = :opp.Id];

        Assert.areEqual('In Progress', out.BPP_Sub_Status__c);
    }

    @isTest
    private static void itShouldReturnHomeAddress() {
        // GIVEN we have an account with a home address
        Account account = [SELECT Id FROM Account WHERE LastName = 'Test'];
        Address__c address = [SELECT Id FROM Address__c WHERE Student__c = :account.Id AND Type__c = 'Home'];
        // WHEN we call the getHomeAddress method
        Id addressId = ApplicationReviewController.getHomeAddress(account.Id);
        // THEN I expect it to return an address id
        Assert.areEqual(address.Id, addressId);
    }

    @isTest
    private static void itShouldBeAbleToSubmitAReview() {
        // GIVEN we have an application ready for review
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-1234'];
        // WHEN we call the submit review method
        System.Test.startTest();

        ApplicationReviewController.submitReview(opp.Id, 'Test Comment', true);

        System.Test.stopTest();
        // THEN I expect it to create an Application Review
        Application_Review__c review = [SELECT Comment__c FROM Application_Review__c WHERE Application__c = :opp.Id];

        Assert.areEqual('Test Comment', review.Comment__c);
        // AND I expect it to update the application
        Opportunity out = [SELECT BPP_Sub_Status__c FROM Opportunity WHERE Id = :opp.Id];

        Assert.areEqual('Awaiting Information', out.BPP_Sub_Status__c);
    }

    @isTest
    private static void itShouldThrowAnExceptionWhenLineManagerIsMissing() {
        // GIVEN we have an application ready for review
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Application_Id__c = 'test-1234'];
        // AND the Application is missing Line Manager
        opp.Line_Manager__c = null;
        update opp;

        // WHEN we call the submit review method
        Boolean exceptionThrown = false;

        System.Test.startTest();

        try {
            ApplicationReviewController.submitReview(opp.Id, 'Test Comment', false);
        } catch (AuraHandledException e) {
            exceptionThrown = true;
        }

        System.Test.stopTest();

        // THEN i expect it to throw an exception
        Assert.isTrue(exceptionThrown);
    }

    @isTest
    private static void itShouldBeAbleToSubmitAFinalReview() {
        // GIVEN we have an application ready for a final review
        Opportunity opp = [
            SELECT Id, StageName, BPP_Sub_Status__c
            FROM Opportunity
            WHERE Application_Id__c = 'test-1234'
        ];
        opp.StageName = 'Acceptance';
        opp.BPP_Sub_Status__c = 'New';
        update opp;

        // WHEN we call the submit review method
        System.Test.startTest();

        ApplicationReviewController.submitFinalReview(opp.Id, 'Test Comment', false);

        System.Test.stopTest();

        // THEN I expect it to create an Application Review
        Application_Review__c review = [
            SELECT Feedback_Required__c, Comment__c
            FROM Application_Review__c
            WHERE Application__c = :opp.Id
        ];

        Assert.isFalse(review.Feedback_Required__c);
        Assert.areEqual('Test Comment', review.Comment__c);

        // AND I expect it to update the application
        Opportunity out = [
            SELECT BPP_Sub_Status__c, Authoriser__c, AuthorisedOn__c
            FROM Opportunity
            WHERE Id = :opp.Id
        ];

        Assert.areEqual('Completed', out.BPP_Sub_Status__c);
        Assert.isNotNull(out.Authoriser__c);
        Assert.isNotNull(out.AuthorisedOn__c);
    }

    @isTest
    private static void itShouldBeAbleToPauseAFinalReview() {
        // GIVEN we have an application ready for a final review
        Opportunity opp = [
            SELECT Id, StageName, BPP_Sub_Status__c
            FROM Opportunity
            WHERE Application_Id__c = 'test-1234'
        ];

        opp.StageName = 'Acceptance';
        opp.BPP_Sub_Status__c = 'In Progress';
        update opp;

        // WHEN we call the submit review method
        System.Test.startTest();

        ApplicationReviewController.submitFinalReview(opp.Id, 'This Application Is On Hold', true);

        System.Test.stopTest();

        // THEN I expect it to create an Application Review
        Application_Review__c review = [
            SELECT Feedback_Required__c, Comment__c
            FROM Application_Review__c
            WHERE Application__c = :opp.Id
        ];

        Assert.isFalse(review.Feedback_Required__c);
        Assert.areEqual('This Application Is On Hold', review.Comment__c);

        // AND I expect it to update the application's status to On Hold
        Opportunity out = [
            SELECT BPP_Sub_Status__c
            FROM Opportunity
            WHERE Id = :opp.Id
        ];

        Assert.areEqual('On Hold', out.BPP_Sub_Status__c);
    }

    @isTest
    private static void itShouldBeAbleToAutoPopulateAReview() {
        // GIVEN we have an open review
        String priorLearning = 'none';

        // WHEN we call the auto populate review method
        String content = ApplicationReviewController.autoPopulateReview();

        // THEN I expect it to fetch the default template for reviews
        Assert.isNotNull(content);
    }

    @isTest
    private static void itShouldUpdateOpportunityDateFields() {
        // GIVEN we have an application
        Opportunity opp = [
            SELECT Id
            FROM Opportunity
            WHERE Application_Id__c = 'test-1234'
        ];

        // AND it is linked to a Product with a different Start and End Date
        Programme__c programme = new Programme__c(Name = 'Test1Programme', Programme_Id__c = 'test-123');
        insert programme;

        Product2 product = new Product2(
            Name = 'TestCourse',
            BPP_ProductFactoryID__c = 'test-123',
            Qualification__c = 'Test Qualification',
            Programme__c = programme.Id,
            Start_Date__c = Date.today().addDays(3),
            End_Date__c = Date.today().addDays(4)
        );
        insert product;

        TriggerHandler.bypass('AddressTriggerHandler');
        opp.StageName = 'Acceptance';
        opp.BPP_Sub_Status__c = 'In Progress';
        opp.Course_Instance__c = product.Id;
        opp.Start_Date__c = Date.today().addDays(1);
        opp.End_Date__c = Date.today().addDays(2);
        update opp;

        Opportunity oppResultsBeforeTest = [
            SELECT Id, Start_Date__c, End_Date__c
            FROM Opportunity
            WHERE Id = :opp.Id
        ];

        Assert.areNotEqual(product.Start_Date__c, oppResultsBeforeTest.Start_Date__c);
        Assert.areNotEqual(product.End_Date__c, oppResultsBeforeTest.End_Date__c);

        // WHEN we call the Opportunity update method
        System.Test.startTest();

        ApplicationReviewController.updateOpportunityProductDates(opp.Id);

        System.Test.stopTest();

        // THEN I expect the Opportunity to have had its Start and End Dates updated
        Opportunity oppResultsAfterTest = [
            SELECT Id, Start_Date__c, End_Date__c
            FROM Opportunity
            WHERE Id = :opp.Id
        ];

        Assert.areEqual(product.Start_Date__c, oppResultsAfterTest.Start_Date__c);
        Assert.areEqual(product.End_Date__c, oppResultsAfterTest.End_Date__c);
    }
}