salesforce-main/src/main/default/objects/Account/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Student</relationshipLabel>
    <relationshipName>Student</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>Date student applied for this particular application.  Automatically populated through Salesforce via workflow rule.  Should not be populated through external systems.</description>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_Reference__c.field-meta.xml
<CustomField>
    <fullName>Application_Reference__c</fullName>
    <description>Application Reference created and provided by the 2023 Application Service</description>
    <label>Application Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <defaultValue>CASE( $RecordType.Name, 
&quot;Interest&quot;, &quot;University&quot;, 
&quot;Application&quot;, &quot;University&quot;, 
&quot;PE Booking&quot;, &quot;Professional Qualification&quot;, 
&quot;&quot;)</defaultValue>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>University Application</fullName>
            </value>
            <value>
                <fullName>Degree Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Professional Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Professional Qualification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BD_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>BD_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Represents the Business Development opportunity agreed with the Client which covers the Apprenticeship application it is related to</description>
    <label>BD Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Development</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (BD Opportunity)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cancellation_Reason__c</fullName>
    <description>Cancellation Reason field to be mandatory if Status is set to Cancelled or Declined on Student Application Opportunity</description>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unable to fund the programme</fullName>
            </value>
            <value>
                <fullName>Change of profession</fullName>
            </value>
            <value>
                <fullName>Taken up a job</fullName>
            </value>
            <value>
                <fullName>Gone to a competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Failed previous qualification</fullName>
            </value>
            <value>
                <fullName>Location/Mode not available</fullName>
            </value>
            <value>
                <fullName>Family Emergency</fullName>
            </value>
            <value>
                <fullName>VISA/CAS/EU Delay</fullName>
            </value>
            <value>
                <fullName>Prefer not to say</fullName>
            </value>
            <value>
                <fullName>VISA Refusal</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>CAS requirement not met</fullName>
            </value>
            <value>
                <fullName>Academic/English entry not met</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Chosen to study at another BPP location</fullName>
            </value>
            <value>
                <fullName>Chosen to study another BPP programme</fullName>
            </value>
            <value>
                <fullName>appMissedDeadline</fullName>
                <label>Failed to submit application before deadline</label>
            </value>
            <value>
                <fullName>appWithdrawApplicant</fullName>
                <label>Learner withdrawn</label>
            </value>
            <value>
                <fullName>appNoResponseApplicant</fullName>
                <label>No response from applicant</label>
            </value>
            <value>
                <fullName>appNoResponseEmployer</fullName>
                <label>No response from employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedEmployer</fullName>
                <label>Cancelled due to change of employer</label>
            </value>
            <value>
                <fullName>appCloneCancelChangedProgramme</fullName>
                <label>Change of programme</label>
            </value>
            <value>
                <fullName>appRejectIneligibleResidency</fullName>
                <label>Ineligible status (Residency)</label>
            </value>
            <value>
                <fullName>appRejectIneligibleVisa</fullName>
                <label>Ineligible status (VISA)</label>
            </value>
            <value>
                <fullName>appRejectRoleOnboarding</fullName>
                <label>Job role does not match criteria (Onboarding)</label>
            </value>
            <value>
                <fullName>appRejectRoleHop</fullName>
                <label>Job role does not match criteria (Hop)</label>
            </value>
            <value>
                <fullName>appRejectOverqualified</fullName>
                <label>Applicant is not suitable for selected programme</label>
            </value>
            <value>
                <fullName>appRejectFundingIssue</fullName>
                <label>Application has a funding issue</label>
            </value>
            <value>
                <fullName>appNotEligible</fullName>
                <label>Not Eligible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BPP_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>BPP_Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Developer lead - written</fullName>
            </value>
            <value>
                <fullName>Apprentices</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Applicant Signoff</fullName>
            </value>
            <value>
                <fullName>Awaiting Information</fullName>
            </value>
            <value>
                <fullName>Bid Team lead - written</fullName>
            </value>
            <value>
                <fullName>Chose Competitor</fullName>
            </value>
            <value>
                <fullName>Commercials</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Contracting</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Final Check In Progress</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Internal (numbers, study method)</fullName>
            </value>
            <value>
                <fullName>Lack of BPP time and resources</fullName>
            </value>
            <value>
                <fullName>Lack of expertise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Client</fullName>
            </value>
            <value>
                <fullName>No Budget</fullName>
            </value>
            <value>
                <fullName>Non-apprentices</fullName>
            </value>
            <value>
                <fullName>Non responsive</fullName>
            </value>
            <value>
                <fullName>No training needs</fullName>
            </value>
            <value>
                <fullName>Not required now - future potential</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Organisational Capability Review</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Presentation pitch /demo</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company account that is associated to the student (Client field) at the time the opportunity is processed. Primarily developed for Application opportunities</description>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Select the business account related to the student</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Client)</relationshipLabel>
    <relationshipName>StudentOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Days_In_Current_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Days_In_Current_Sub_Status__c</fullName>
    <description>The number of days since either the status or sub-status was changed</description>
    <formula>TODAY() - BLANKVALUE(Last_Status_Change_Date__c, TODAY())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The number of days since either the status or sub-status was changed</inlineHelpText>
    <label>Days In Current Sub-Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>A list of divisions for NatWest Group PCDP England</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chief Audit Office</fullName>
            </value>
            <value>
                <fullName>Commercial &amp; Institutional Non Ring Fenced Bank</fullName>
            </value>
            <value>
                <fullName>Commercial &amp; Institutional Ring Fenced Bank</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Group Chief of Staff Office</fullName>
            </value>
            <value>
                <fullName>Leadership Hub</fullName>
            </value>
            <value>
                <fullName>Legal, Governance &amp; Regulatory Affairs</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>NatWest Digital X</fullName>
            </value>
            <value>
                <fullName>People and Transformation</fullName>
            </value>
            <value>
                <fullName>Private Banking</fullName>
            </value>
            <value>
                <fullName>Retail Banking</fullName>
            </value>
            <value>
                <fullName>Risk</fullName>
            </value>
            <value>
                <fullName>Strategy, Corporate Development and Sustainability</fullName>
            </value>
            <value>
                <fullName>Ulster Bank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <description>The current eligibility status of the application</description>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT_CHECKED</fullName>
                <label>Not Checked</label>
            </value>
            <value>
                <fullName>ELIGIBLE</fullName>
                <label>Eligible</label>
            </value>
            <value>
                <fullName>NOT_ELIGIBLE</fullName>
                <label>Not Eligible</label>
            </value>
            <value>
                <fullName>Eligibility Incomplete</fullName>
                <default>true</default>
                <label>Eligibility Incomplete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Resubmission_Date__c.field-meta.xml
<CustomField>
    <fullName>Resubmission_Date__c</fullName>
    <label>Resubmission Date</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/classes/EnhancedLayoutController.cls
/**
 * Controller class for the EnhancedLayout LWC
 */
public with sharing class EnhancedLayoutController {
    @TestVisible
    private static Map<String, List<LayoutField>> fieldConfig = new Map<String, List<LayoutField>>{
        // Apprentice Application Details
        'Opp_Appr_Details' => new List<LayoutField>{
            new LayoutField('Opportunity', 'Name'),
            new LayoutField('Opportunity', 'StageName'),
            new LayoutField('Opportunity', 'Application_Reference__c'),
            new LayoutField('Opportunity', 'BPP_Sub_Status__c'),
            new LayoutField('Opportunity', 'Application_Date__c'),
            new LayoutField('Opportunity', 'BPP_Cancellation_Reason__c'),
            new LayoutField('Opportunity', 'Resubmission_Date__c'),
            new LayoutField('Opportunity', 'AccountId'),
            new LayoutField('Opportunity', 'Days_In_Current_Sub_Status__c'),
            new LayoutField('Account', 'Account.ULN__pc'),
            new LayoutField('Opportunity', 'Eligibility_Status__c'),
            new LayoutField('Opportunity', 'BD_Opportunity__c'),
            new LayoutField('Opportunity', 'Category__c'),
            new LayoutField('Opportunity', 'Division__c'),
            new LayoutField('Opportunity', 'Application_Type__c')
        },
        // Learner Personal Details
        'Opp_Appr_PDetail' => new List<LayoutField>{
            new LayoutField('Opportunity', 'AccountId'),
            new LayoutField('Account', 'Account.Personal_Email__pc'),
            new LayoutField('Account', 'Account.Salutation'),
            new LayoutField('Account', 'Account.PersonMobilePhone'),
            new LayoutField('Account', 'Account.FirstName'),
            new LayoutField('Account', 'Account.PersonBirthdate'),
            new LayoutField('Account', 'Account.LastName'),
            new LayoutField('Account', 'Account.Age__pc'),
            new LayoutField('Account', 'Account.NI_Number__pc'),
            new LayoutField('Account', 'Account.Middle_Name__pc')
        },
        // Client Details
        'Opp_Appr_ClientDetails' => new List<LayoutField>{
            new LayoutField('Account', 'Client__r.Name'),
            new LayoutField('Account', 'Client__r.BPP_Account_Number__c'),
            new LayoutField('Account', 'Client__r.Account_Managed__c'),
            new LayoutField('Account', 'Client__r.Client_Category__c'),
            new LayoutField('Account', 'Client__r.Account_Tax_Category__c'),
            new LayoutField('Account', 'Client__r.Addressable_Levy_pot__c'),
            new LayoutField('Account', 'Client__r.AnnualRevenue'),
            new LayoutField('Account', 'Client__r.Apprenticeship_Service_Account_Owner__c'),
            new LayoutField('Account', 'Client__r.Bodies_With_Levy_Permissions__c'),
            new LayoutField('Account', 'Client__r.Levy_pot__c'),
            new LayoutField('Account', 'Client__r.NumberOfEmployees'),
            new LayoutField('Account', 'Client__r.Pays_Into_Apprenticeship_Levy__c')
        },
        // Line Manager Details
        'Opp_Appr_LMDetails' => new List<LayoutField>{
            new LayoutField('Contact', 'Line_Manager__r.Name'),
            new LayoutField('Contact', 'Line_Manager__r.Title'),
            new LayoutField('Contact', 'Line_Manager__r.Email'),
            new LayoutField('Contact', 'Line_Manager__r.Phone'),
            new LayoutField('Contact', 'Line_Manager__r.MobilePhone')
        }
    };

    @TestVisible
    private class LayoutField {
        private String parentObject;
        private String fieldName;

        @TestVisible
        private LayoutField(String parentObject, String fieldName) {
            this.parentObject = parentObject;
            this.fieldName = fieldName;
        }
    }

    /**
     * Queries out all Fields to render for the given Section, extracts any field details and finally enriches with data for these fields on the given record
     * @return  List of all Fields to render and their details
     */
    @AuraEnabled(cacheable=true)
    public static EnhancedLayoutDetails retrieveFieldDetails(String sectionAPIName, String recordId) {
        List<LayoutField> layoutFields = fieldConfig.get(sectionAPIName);

        if (layoutFields == null || layoutFields.isEmpty()) {
            return null;
        }

        EnhancedLayoutDetails detailsToReturn = new EnhancedLayoutDetails();
        Set<String> fieldsToQuery = new Set<String>();
        Map<String, DescribeSObjectResult> objectToSObjectResult = new Map<String, DescribeSObjectResult>();

        for (LayoutField fieldSetting : layoutFields) {
            EnhancedLayoutField fieldDetails = new EnhancedLayoutField();
            detailsToReturn.fields.add(fieldDetails);

            // Retrieve the SObject Describe for the given field
            DescribeSObjectResult currentObjectDescribe = objectToSObjectResult.get(fieldSetting.parentObject);

            // Cache the SObject Results
            if (currentObjectDescribe == null) {
                currentObjectDescribe = Schema.getGlobalDescribe().get(fieldSetting.parentObject)?.getDescribe();

                if (currentObjectDescribe == null) {
                    fieldDetails.errorMessage = 'SObject Provided does not exist.';
                    continue;
                }

                objectToSObjectResult.put(fieldSetting.parentObject, currentObjectDescribe);
            }

            // Split the field up into its individual segments
            fieldDetails.fieldSegments = fieldSetting.fieldName.split('\\.');
            fieldDetails.fullPath = fieldSetting.fieldName;

            // Extract the details of the current field
            DescribeFieldResult currentFieldDescribe = currentObjectDescribe.fields.getMap()
                .get(fieldDetails.fieldSegments[fieldDetails.fieldSegments.size() - 1])
                ?.getDescribe();

            // If the field could not be found, return with an error
            if (currentFieldDescribe == null) {
                fieldDetails.errorMessage = 'Field does not exist.';
                continue;
            }

            // If the field could be found but is not readable by the user, return with a missing permissions flag
            if (!currentFieldDescribe.isAccessible()) {
                fieldDetails.missingPermissions = true;
                continue;
            }

            // If all prior checks pass, allow the field to be queried and extract any details of the field ready to return
            fieldsToQuery.add(fieldSetting.fieldName);

            fieldDetails.label = currentFieldDescribe.getLabel();
            fieldDetails.type = String.valueOf(currentFieldDescribe.getType());

            // If the field is a picklist we also need to return any picklist values and their API names
            if (fieldDetails.type == 'PICKLIST' || fieldDetails.type == 'MULTIPICKLIST') {
                for (Schema.PicklistEntry picklistEntry : currentFieldDescribe.getPicklistValues()) {
                    fieldDetails.picklistValuesToLabels.put(picklistEntry.getValue(), picklistEntry.getLabel());
                }
            }

            // If the field is a reference we also need to return the Name value of the linked record as to not display the records Id
            if (fieldDetails.type == 'REFERENCE') {
                // To achieve this, clone the current records segment
                fieldDetails.lookupFieldSegments = fieldDetails.fieldSegments.clone();

                // Replace the lookup (Id) field with its equivalent relationship field and also the records "Name"
                fieldDetails.lookupFieldSegments.remove(fieldDetails.fieldSegments.size() - 1);
                fieldDetails.lookupFieldSegments.add(currentFieldDescribe.getRelationshipName());
                fieldDetails.lookupFieldSegments.add('Name');

                fieldsToQuery.add(String.join(fieldDetails.lookupFieldSegments, '.'));
            }
        }

        if (fieldsToQuery.isEmpty()) {
            return detailsToReturn;
        }

        // Query out the record and all fields that were identified and return as a string to return the data identically to how it was queried out
        detailsToReturn.queryResultsString = JSON.serialize(
            Database.query(
                string.format(
                    'SELECT Id, {0} FROM {1} WHERE Id = \'\'{2}\'\' LIMIT 1',
                    new List<string>{
                        String.join(new List<String>(fieldsToQuery), ', '),
                        ((Id) recordId).getSObjectType().getDescribe().getName(),
                        recordId
                    }
                )
            )
        );

        return detailsToReturn;
    }

    public class EnhancedLayoutDetails {
        @auraEnabled
        public String queryResultsString;

        @auraEnabled
        public List<EnhancedLayoutField> fields = new List<EnhancedLayoutField>();
    }

    public class EnhancedLayoutField {
        @auraEnabled
        public String label;

        @auraEnabled
        public String type;

        @auraEnabled
        public String fullPath;

        @auraEnabled
        public String errorMessage;

        @auraEnabled
        public Boolean missingPermissions = false;

        @auraEnabled
        public Map<String, String> picklistValuesToLabels = new Map<String, String>();

        @auraEnabled
        public List<String> fieldSegments = new List<String>();

        @auraEnabled
        public List<String> lookupFieldSegments;
    }
}