salesforce-main/src/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Citizenship</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/EORI_Number__c.field-meta.xml
<CustomField>
    <fullName>EORI_Number__c</fullName>
    <description>EORI Number for European companies, required for international shipping</description>
    <label>EORI Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>All Tenants - Country table for variety of uses</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <description>Delivery object to track order items that need to be dispatched relating to either booking lines or order products (for LM only orders)</description>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DEL-{0000000}</displayFormat>
        <label>Delivery Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Delivery__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>BPP_Cost_Center__c</fullName>
    <label>Cost Center</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Delivery_Line_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>BPP_Delivery_Line_Total_Price__c</fullName>
    <description>Related Order Product List Price, minus the Discount Amount. Then multiplied by Delivery Quantity</description>
    <formula>(Order_Product__r.ListPrice - Order_Product__r.BPP_Discount_Amount__c) * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Line Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Division__c.field-meta.xml
<CustomField>
    <fullName>BPP_Division__c</fullName>
    <label>Division</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Product__c.field-meta.xml
<CustomField>
    <fullName>BPP_Product__c</fullName>
    <label>Product</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Project__c.field-meta.xml
<CustomField>
    <fullName>BPP_Project__c</fullName>
    <label>Project</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>BPP_Shipping_Method__c</fullName>
    <description>Populated using related Courier&apos;s Export Code</description>
    <formula>IF( NOT( ISBLANK( Courier__c ) ) ,  Courier__r.Export_Code__c , NULL)</formula>
    <label>Shipping Method</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Consolidated_Address__c.field-meta.xml
<CustomField>
    <fullName>Consolidated_Address__c</fullName>
    <description>Concatenates recipient + address lines</description>
    <formula>IF(Delivered_to_Customer_Address__r.Student__r.IsPersonAccount = False,  Delivered_to_Customer_Address__r.Student__r.Name &amp; &quot;|&quot;, &quot;&quot;) &amp;
IF(LEN(Address_Line_1__c)&gt;0, Address_Line_1__c, &quot;&quot;)&amp;
IF(LEN(Address_Line_2__c)&gt;0, &quot;|&quot; &amp; Address_Line_2__c, &quot;&quot;)&amp;
IF(LEN(Address_Line_3__c)&gt;0, &quot;|&quot; &amp; Address_Line_3__c,&quot;&quot;)</formula>
    <label>Consolidated Address</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <formula>Country__r.country_code_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <description>Status of delivery</description>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting Allocation</fullName>
                <default>true</default>
                <label>Awaiting Allocation</label>
            </value>
            <value>
                <fullName>Ready for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Sent for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address that electronic deliveries will be sent to and where the customer can informed regarding delivery information</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/EORI_Number__c.field-meta.xml
<CustomField>
    <fullName>EORI_Number__c</fullName>
    <description>EORI Number for the company making the order. This is required for shipments going through customs. Acquired from the related order account.</description>
    <formula>Order_Product__r.Order.Account.EORI_Number__c</formula>
    <label>EORI Number</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Fulfilment_Id__c.field-meta.xml
<CustomField>
    <fullName>Fulfilment_Id__c</fullName>
    <description>Uses the Booking Id if available, otherwise displays the order Id</description>
    <formula>IF( ISBLANK( Booking_Line__c ) ,
Order_Product__r.Order.OrderNumber  ,
Booking_Line__r.Booking__r.Name )</formula>
    <label>Fulfilment Id</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Order Product that delivery is for - LM orders</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Phone number customer can be contacted on to receive delivery</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Recipient_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Name__c</fullName>
    <description>Recipient of the delivery</description>
    <label>Recipient Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <description>Delivery date - used to determine when items should be dispatched</description>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Stock_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Stock_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows stock has been allocated for this delivery</description>
    <label>Stock Allocated</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Stock_Site__c.field-meta.xml
<CustomField>
    <fullName>Stock_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Stock site where delivery will be dispatched from</description>
    <label>Stock Site</label>
    <referenceTo>Stock_Site__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/DeliveryUpdateBatch.cls
/**********************************************************************
Name: DeliveryUpdateBatch
Purpose: Updates Delivery records (where Delivery_Status__c = 'Ready for Fulfilment') to 'Sent for Fulfillment'
-------                                                             
History                                                             
-------                                                             
VERSION  AUTHOR             DATE              DETAIL                              
0.1 -   David Lovejoy     19/01/2021      INITIAL DEVELOPMENT  
0.2 -   David Lovejoy     29/11/2021      BPP-15675
***********************************************************************/
global class DeliveryUpdateBatch implements Database.Batchable<Sobject>, Database.Stateful {
    List<String> saveErrors = new List<String>();
    private static String deliveryType = 'Physical Delivery';

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String getFields = 'SELECT Fulfilment_Id__c, Name, Account__r.Name, Email__c, Phone__c, Recipient_Name__c, Consolidated_Address__c, City__c, Postal_Code__c, Country__c, Country__r.Name, Country_Code__c, Requested_Delivery_Date__c, BPP_Shipping_Method__c, Material_Product_Code__c, Quantity__c, EORI_Number__c, Stock_Site__r.Name, Id, BPP_Delivery_Line_Total_Price__c, Order_Product__r.ListPrice, Order_Product__r.BPP_Discount_Amount__c, Order_Product__r.BPP_Discount_Percent__c, BPP_Division__c, BPP_Cost_Center__c, BPP_Project__c, BPP_Product__c FROM Delivery__c';
        String whereClause = (Test.isRunningTest() ? ' WHERE Delivery_Status__c = \'Ready for Fulfilment\' LIMIT 1' : ' WHERE Delivery_Status__c = \'Ready for Fulfilment\' AND Stock_Allocated__c = TRUE AND RecordType.Name =: deliveryType LIMIT 49000');
        String query = getFields + whereClause;
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Delivery__c> deliveryList) {
        System.debug('Delivery records to be updated: ' + deliveryList.size());

        if (deliveryList.size() > 0) {
			for (Delivery__c delivery : deliveryList) {
                delivery.Delivery_Status__c = 'Sent for Fulfilment';
            }
            saveErrors = DeliveryBatchHelper.updateDeliveryRecords(deliveryList);
        }
    }

    global void finish(Database.BatchableContext BC) {
        if (saveErrors.size() > 0) { 
            DeliveryBatchHelper.sendFailedDeliveryUpdateEmail(deliveryType, saveErrors);
        } else {
            DeliveryBatchHelper.sendFailedDeliveryUpdateEmail(deliveryType, null);
        }
    }
}