salesforce-main/src/main/default/objects/Account/fields/Country_of_Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Permanent_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Countries List</description>
    <label>Country of Permanent Address</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>country_list__c.Valid_Domicile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Please select the country with valid domicile true</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Accounts (Country of Permanent Address)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Tier 1 - Key Clients</fullName>
            </value>
            <value>
                <fullName>Tier 2 - Large Clients</fullName>
            </value>
            <value>
                <fullName>Tier 3 - Normal</fullName>
            </value>
            <value>
                <fullName>Direct Debit Students</fullName>
            </value>
            <value>
                <fullName>Export (LM only)</fullName>
            </value>
            <value>
                <fullName>Book Shop/colleges (LM Only)</fullName>
            </value>
            <value>
                <fullName>Legal - Once account has been pass over to out solicitors for collection</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Collection Agent</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Legal Entity</label>
</CustomObject>

salesforce-main/src/main/default/objects/Legal_Entity__c/fields/AR_Integration__c.field-meta.xml
<CustomField>
    <fullName>AR_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AR Integration</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_FieldOfStudy_Code__c.field-meta.xml
<CustomField>
    <fullName>BNR_FieldOfStudy_Code__c</fullName>
    <label>FieldOfStudy Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SLC</fullName>
            </value>
            <value>
                <fullName>SELFFUND</fullName>
            </value>
            <value>
                <fullName>ONLINE</fullName>
            </value>
            <value>
                <fullName>INTSTUDENT</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Expected final day of apprenticeship.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <description>Mode that student has applied or expressed interest in studying.</description>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Full Time - Accelerated</fullName>
            </value>
            <value>
                <fullName>Full Time - Fast Track</fullName>
            </value>
            <value>
                <fullName>Part Time Day</fullName>
            </value>
            <value>
                <fullName>Part Time Weekend</fullName>
            </value>
            <value>
                <fullName>Part Time 1 Evening</fullName>
            </value>
            <value>
                <fullName>Part Time 2 Evening</fullName>
            </value>
            <value>
                <fullName>Part Time Saturday</fullName>
            </value>
            <value>
                <fullName>Part Time Distance Learning</fullName>
            </value>
            <value>
                <fullName>Full Time Distance Learning</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Full Time Accelerated</fullName>
            </value>
            <value>
                <fullName>On-Line</fullName>
            </value>
            <value>
                <fullName>Part Time 2 Evenings</fullName>
            </value>
            <value>
                <fullName>Short Course</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/PC_Attribute_Code_2__c.field-meta.xml
<CustomField>
    <fullName>PC_Attribute_Code_2__c</fullName>
    <label>PC Attribute Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/PC_Attribute_Code_3__c.field-meta.xml
<CustomField>
    <fullName>PC_Attribute_Code_3__c</fullName>
    <label>PC Attribute Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/PC_Attribute_Code__c.field-meta.xml
<CustomField>
    <fullName>PC_Attribute_Code__c</fullName>
    <label>PC Attribute Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Number__c</fullName>
    <label>PO#</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Attribute_Code_Select_v2__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Attribute_Code_Select_v2__c</fullName>
    <label>Attribute Code Select</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FL~ Flex</fullName>
            </value>
            <value>
                <fullName>S1~ Year 1 / Stage 1</fullName>
            </value>
            <value>
                <fullName>S2~ Year 2 / Stage 2</fullName>
            </value>
            <value>
                <fullName>S3~ Year 3 / Stage 3</fullName>
            </value>
            <value>
                <fullName>SP~ Sponsor</fullName>
            </value>
            <value>
                <fullName>BLEN~ Blended</fullName>
            </value>
            <value>
                <fullName>FTF~ Face to Face</fullName>
            </value>
            <value>
                <fullName>DLA~ Distance Learning Mode A</fullName>
            </value>
            <value>
                <fullName>SUN~ Sunday</fullName>
            </value>
            <value>
                <fullName>KC~ Key Client</fullName>
            </value>
            <value>
                <fullName>IH~ In House client</fullName>
            </value>
            <value>
                <fullName>EXAM~ Store Exam Results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Amount__c</fullName>
    <label>Sponsorship Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Sponsorship_Level__c.field-meta.xml
<CustomField>
    <fullName>Sponsorship_Level__c</fullName>
    <label>Sponsorship Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Anticipated or actual start date of the programme.</description>
    <label>Programme Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/classes/SubmitApplicationHandlerTest.cls
@isTest
public class SubmitApplicationHandlerTest {
    @TestSetup
    static void setup() {
        Id opportunityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName()
            .get('Apprentice_Application')
            .getRecordTypeId();

        Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Student_Account')
            .getRecordTypeId();

        Legal_Entity__c setting = new Legal_Entity__c();
        setting.Name = 'UC~COL';
        setting.Entity__c = 'COL';
        setting.AR_Integration__c = true;
        insert setting;

        Country_List__c country = new Country_List__c(
            Name = 'United Kingdom',
            Valid_Domicile__c = true,
            Valid_Nationality__c = true,
            country_code_2__c = 'GB',
            ISO_CODE__c = 'GB',
            enabled__c = true
        );
        insert country;

        Programme__c programme = new Programme__c(
            Name = 'Test programme',
            Programme_Id__c = 'P-123',
            BNR_FieldOfStudy_Code__c = '123',
            BNR_College_Code__c = '123'
        );
        insert programme;

        Product2 product = new Product2(
            Name = 'Test Course',
            BPP_ProductFactoryID__c = 'test-123',
            Instance_Id__c = 'test-1234',
            Programme__c = programme.Id,
            Mode__c = 'Full',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today() + 365,
            BNR_FieldOfStudy_Start_Date__c = Date.today(),
            Product_Type__c = SubmitApplicationHandler.OFFERING_PRDTYPE,
            BNR_Degree_Code__c = '123',
            BNR_Campus_Code__c = '123',
            BNR_Level_Code__c = '123',
            BNR_Term_Code__c = '123'
        );
        insert product;

        Account acc = new Account(
            FirstName = 'Test',
            LastName = 'Test',
            RecordTypeId = accountRecordTypeId,
            PS_Profile_Services_ID__pc = 'ID-123',
            PersonBirthdate = Date.newInstance(2002, 2, 1),
            Primary_Nationality__pc = country.Id,
            Student_Type__pc = 'Domestic',
            Legal_Entity__c = 'UC~COL',
            Country_of_Permanent_Address__c = country.Id
        );
        insert acc;

        insert new Address__c(Type__c = 'Home', Street_1__c = '1', Student__c = acc.Id);

        Opportunity opp = new Opportunity(
            RecordTypeId = opportunityRecordTypeId,
            AccountId = acc.Id,
            Name = 'Test Opportunity',
            StageName = 'Application',
            CloseDate = Date.today() + 30,
            Application_Id__c = 'test-1234',
            Pricebook2Id = Test.getStandardPricebookId(),
            Course_Instance__c = product.Id,
            Purchase_Order_Number__c = '123',
            Sponsorship_Level__c = 'Partial',
            Sponsorship_Amount__c = 10.0,
            Customer_Group__c = 'group',
            SFDC_Attribute_Code_Select_v2__c = 'UC~COL',
            PC_Attribute_Code__c = '123',
            PC_Attribute_Code_2__c = '123',
            PC_Attribute_Code_3__c = '123'
        );
        insert opp;

        opp.StageName = 'Acceptance';
        opp.BPP_Sub_Status__c = 'Completed';
        update opp;
    }

    @isTest
    private static void itShouldSubmitApplicationSuccessfully() {
        // Mock respose from submitApplication
        SubmitApplicationHandler.applicationResult = new HttpResponse();
        SubmitApplicationHandler.applicationResult.setStatus('OK');
        SubmitApplicationHandler.applicationResult.setStatusCode(200);
        SubmitApplicationHandler.applicationResult.setBody(
            '<?xml version="1.0" encoding="utf-8"?>\n<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:platform="http://platform.apollogrp.edu/gateway" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:per="http://platform.apollogrp.edu/services/apolloglobal/person/PersonService"><soapenv:Header><gateway:transactionId xmlns:gateway="http://platform.apollogrp.edu/gateway">4C7D57D0-35AE-3034-1A99-30F1672ED186</gateway:transactionId></soapenv:Header><soapenv:Body><per:getStudentIDByProfileIDResponse><per:studentID>BP0015527</per:studentID></per:getStudentIDByProfileIDResponse></soapenv:Body></soapenv:Envelope>'
        );
        // ARStudentAccountService and BNR_SubmitApplication mock result for tests within the class
        UpdateSISPerson.mockResponse = '{"companyId":"1234f567-bc23-42e8-924c-1234asdf5678","operation":"UPDATE", "success":true}';

        // GIVEN an Opp
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity'];

        // WHEN checkApplication is called
        System.Test.startTest();
        String returnedMessage = SubmitApplicationHandler.checkApplication(opp.Id);
        System.Test.stopTest();

        // THEN a message is returned
        Assert.areEqual('Application Submitted', returnedMessage);
    }

    @isTest
    private static void itShouldShowErrorForFailedSubmitApplication() {
        // Mock respose from submitApplication
        SubmitApplicationHandler.applicationResult = new HttpResponse();
        SubmitApplicationHandler.applicationResult.setStatus('Internal Error');
        SubmitApplicationHandler.applicationResult.setStatusCode(500);
        SubmitApplicationHandler.applicationResult.setBody(
            '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<soapenv:Header><gateway:' +
                'transactionId xmlns:gateway="http://platform.apollogrp.edu/gateway">' +
                'A4A3BF60-2BB1-2EFA-E334-8B03BE650CD0</gateway:transactionId>' +
                '</soapenv:Header>' +
                '<soapenv:Body>' +
                '<soapenv:Fault>' +
                '<faultcode>SOAP-ENV:Server</faultcode>' +
                '<faultstring>Error occurred invoking underlying service implementation' +
                '</faultstring>' +
                '<detail xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">' +
                '<ns2:serviceFault ' +
                'xmlns:ns2="http://platform.apollogrp.edu/schemas/2010/05/28/ServiceFault">' +
                '<ns2:componentCode>15</ns2:componentCode><ns2:transactionId>' +
                'A4A3BF60-2BB1- 2EFA-E334-8B03BE650CD0</ns2:transactionId><ns2:errorCode> ' +
                'PLATFORM-999</ns2:errorCode><ns2:errorDescription> ' +
                'ORA-06512: at line 1' +
                '</ns2:errorDescription></ns2:serviceFault></detail></soapenv:Fault>' +
                '</soapenv:Body>' +
                '</soapenv:Envelope>'
        );

        // GIVEN an Opp
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity'];

        // WHEN checkApplication is called
        System.Test.startTest();
        String returnedMessage = SubmitApplicationHandler.checkApplication(opp.Id);
        System.Test.stopTest();

        // THEN a message is returned
        Assert.isTrue(
            returnedMessage.contains('Submit Application Service Error'),
            'Expected: Submit Application Service Error, Actual: ' + returnedMessage
        );
    }

    @isTest
    private static void itShouldHandleARStudentAccountServiceError() {
        UpdateSISPerson.mockResponse = '{"companyId":"1234f567-bc23-42e8-924c-1234asdf5678","operation":"UPDATE", "success":true}';
        ARStudentAccountService.bFailARStudent = true;

        // GIVEN an Opp
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity'];

        // WHEN checkApplication is called
        System.Test.startTest();
        String returnedMessage = SubmitApplicationHandler.checkApplication(opp.Id);
        System.Test.stopTest();

        // THEN a message is returned
        Assert.isTrue(
            returnedMessage.contains('ARStudentAccountService Error'),
            'Expect \'ARStudentAccountService Error\''
        );
    }

    @isTest
    private static void itShouldHandleStudentIDServiceError() {
        UpdateSISPerson.mockResponse = '{"companyId":"1234f567-bc23-42e8-924c-1234asdf5678","operation":"UPDATE", "success":true}';
        BNR_SubmitApplication.bFailStudentId = true;

        // GIVEN an Opp
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity'];

        // WHEN checkApplication is called
        System.Test.startTest();
        String returnedMessage = SubmitApplicationHandler.checkApplication(opp.Id);
        System.Test.stopTest();

        // THEN a message is returned
        Assert.isTrue(returnedMessage.contains('StudentIDService Error'), 'Expect \'StudentIDService Error\'');
    }
}