salesforce-main/src/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Tier 1 - Key Clients</fullName>
            </value>
            <value>
                <fullName>Tier 2 - Large Clients</fullName>
            </value>
            <value>
                <fullName>Tier 3 - Normal</fullName>
            </value>
            <value>
                <fullName>Direct Debit Students</fullName>
            </value>
            <value>
                <fullName>Export (LM only)</fullName>
            </value>
            <value>
                <fullName>Book Shop/colleges (LM Only)</fullName>
            </value>
            <value>
                <fullName>Legal - Once account has been pass over to out solicitors for collection</fullName>
            </value>
            <value>
                <fullName>Intercompany</fullName>
            </value>
            <value>
                <fullName>Collection Agent</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/AssignmentUsers__c/AssignmentUsers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A collection of users that can be referenced for record assignment and triggers</description>
    <label>AssignmentUsers</label>
</CustomObject>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_Admissions_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Admissions_Owner__c</fullName>
    <description>Id of Admissions user records will be assigned to. This will trigger the round robin assignment</description>
    <label>Default Admissions Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/AssignmentUsers__c/fields/Default_International_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_International_Owner__c</fullName>
    <description>Id of International user records will be assigned to.</description>
    <label>Default International Owner</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>Date student applied for this particular application.  Automatically populated through Salesforce via workflow rule.  Should not be populated through external systems.</description>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Course_Instance__c.field-meta.xml
<CustomField>
    <fullName>Course_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates which course instance this student has an interest or application regarding.  Required for application.  Will override Start Date, Mode, Location, and Programme on opportunity when populated.</description>
    <inlineHelpText>Will override Start Date, Mode, Location, and Programme on opportunity with those on course instance when populated.</inlineHelpText>
    <label>Course Instance</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SLC</fullName>
            </value>
            <value>
                <fullName>SELFFUND</fullName>
            </value>
            <value>
                <fullName>ONLINE</fullName>
            </value>
            <value>
                <fullName>INTSTUDENT</fullName>
            </value>
            <value>
                <fullName>FF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Offer_Type__c</fullName>
    <description>Tracks the type of offer that was offered during the offered phase. Allows visibility of offer type once stage moves to acceptance.</description>
    <label>Offer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conditional</fullName>
            </value>
            <value>
                <fullName>Unconditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Record_Source__c.field-meta.xml
<CustomField>
    <fullName>Record_Source__c</fullName>
    <description>Source of data to create this particular record (e.g. CAB/UCAS/BPTC).  Record source &apos;Salesforce&apos; indicates a record created by an end user.</description>
    <label>Record Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>UCAS</fullName>
            </value>
            <value>
                <fullName>BPTC</fullName>
            </value>
            <value>
                <fullName>Direct Apps</fullName>
            </value>
            <value>
                <fullName>Administrate</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Join</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Referee_Email__c.field-meta.xml
<CustomField>
    <fullName>Referee_Email__c</fullName>
    <description>Email address of referee of this application.</description>
    <label>Referee Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Referee_Name__c.field-meta.xml
<CustomField>
    <fullName>Referee_Name__c</fullName>
    <description>Name of referee of this application.</description>
    <label>Referee Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SOC2020__c.field-meta.xml
<CustomField>
    <fullName>SOC2020__c</fullName>
    <description>SOC2020 category entered in UCAS application.</description>
    <label>SOC2020</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Socio_economic_classification__c.field-meta.xml
<CustomField>
    <fullName>Socio_economic_classification__c</fullName>
    <description>Supplied by UCAS only and only applicable to UK residents applying for undergraduate credit-bearing courses. Stores the socio-economic classification (SEC) of student if 21 or over at the start of their Engagement or parental classification if under 21. Required at entry to a student&apos;s Engagement and is not required to be maintained throughout the Engagement.</description>
    <inlineHelpText>Supplied by UCAS only and only applicable to UK residents applying for undergraduate credit-bearing courses. Stores the socio-economic classification (SEC) of student if 21 or over at the start of their Engagement or parental classification if under 21. Required at entry to a student&apos;s Engagement and is not required to be maintained throughout the Engagement.</inlineHelpText>
    <label>Socio-economic classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01~ Higher managerial &amp; professional occupations</fullName>
            </value>
            <value>
                <fullName>02~ Lower managerial &amp; professional occupations</fullName>
            </value>
            <value>
                <fullName>03~ Intermediate occupation</fullName>
            </value>
            <value>
                <fullName>04~ Small employers &amp; own account workers</fullName>
            </value>
            <value>
                <fullName>05~ Lower supervisory &amp; technical occupations</fullName>
            </value>
            <value>
                <fullName>06~ Semi-routine occupations</fullName>
            </value>
            <value>
                <fullName>07~ Routine occupations</fullName>
            </value>
            <value>
                <fullName>08~ Never worked &amp; long-term unemployed</fullName>
            </value>
            <value>
                <fullName>09~ Not classified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Complete</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer Rejected</fullName>
            </value>
            <value>
                <fullName>CAS Requested</fullName>
            </value>
            <value>
                <fullName>CAS Draft Approved</fullName>
            </value>
            <value>
                <fullName>Visa Obtained</fullName>
            </value>
            <value>
                <fullName>Visa Refused</fullName>
            </value>
            <value>
                <fullName>Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Refund Requested</fullName>
            </value>
            <value>
                <fullName>Deferral Requested</fullName>
            </value>
            <value>
                <fullName>Transfer Requested</fullName>
            </value>
            <value>
                <fullName>Late Registration Requested</fullName>
            </value>
            <value>
                <fullName>Not Able To Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/UCAS_Application_Scheme_Code__c.field-meta.xml
<CustomField>
    <fullName>UCAS_Application_Scheme_Code__c</fullName>
    <description>UCAS identification number specific to the application.  Updated via data team processes.  Should not be modified by end users.</description>
    <inlineHelpText>This field records the 4-character scheme code issued by UCAS and is used in the HESA return</inlineHelpText>
    <label>UCAS Scheme Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/UCAS_Choice_Number__c.field-meta.xml
<CustomField>
    <fullName>UCAS_Choice_Number__c</fullName>
    <description>UCAS identification number specific to the application.  Updated via data team processes.  Should not be modified by end users.</description>
    <label>UCAS Choice Number</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce-main/src/main/default/classes/LearnerApplicationService.cls
@RestResource(urlMapping='/learners/*')
global with sharing class LearnerApplicationService {
    global class Response {
        public Response() {
        }
        global String response { get; set; }
        global String opportunityId { get; set; }

        public Response(String response, String opportunityId) {
            this.response = response;
            this.opportunityId = opportunityId;
        }
    }

    public class RequestWrapper {
        public String applicationDate;
        public String closeDate;
        public String offeringId;
        public String offerType;
        public String source;
        public String refereeEmail;
        public String refereeName;
        public String soc2020;
        public String socioEconomicClassification;
        public String ucasSchemeCode;
        public String ucasChoiceNumber;
    }

    @HttpPost
    global static Response doPost() {
        try {
            Blob body = RestContext.request.requestBody;
            RequestWrapper rw = (RequestWrapper) JSON.deserialize(body.toString(), RequestWrapper.class);
            System.debug(rw);
            cleanUp(rw);

            String result;
            String accountId = RestContext.request.requestURI.substringAfter('/learners/').left(18);
            String opportunityId = lookForOpportunityId(rw, accountId);
            if (opportunityId != null) {
                result = updateOpportunity(opportunityId, rw);
                if (result != null && result.startsWith('006')) {
                    return new Response(
                        'LearnerApplicationService Success: Opportunity - ' + result + ' updated',
                        result
                    );
                } else {
                    return new Response('LearnerApplicationService Opportunity Update Error: ' + result, null);
                }
            }

            result = createOpportunity(accountId, rw);
            if (result != null && result.startsWith('006')) {
                return new Response('LearnerApplicationService Success: Opportunity - ' + result + ' created', result);
            } else {
                return new Response('LearnerApplicationService Opportunity Create Error: ' + result, null);
            }
        } catch (Exception e) {
            return new Response('LearnerApplicationService Error: [' + e.getLineNumber() + '] ' + e.getMessage(), null);
        }
    }

    private static void cleanUp(RequestWrapper rw) {
        rw.applicationDate = DedupeHelper.verifyPostInput(rw.applicationDate);
        rw.closeDate = DedupeHelper.verifyPostInput(rw.closeDate);
        rw.offeringId = DedupeHelper.verifyPostInput(rw.offeringId);
        rw.offerType = DedupeHelper.verifyPostInput(rw.offerType);
        rw.source = DedupeHelper.verifyPostInput(rw.source);
        rw.refereeName = DedupeHelper.verifyPostInput(rw.refereeName);
        rw.soc2020 = DedupeHelper.verifyPostInput(rw.soc2020);
        rw.socioEconomicClassification = DedupeHelper.verifyPostInput(rw.socioEconomicClassification);
        rw.ucasChoiceNumber = DedupeHelper.verifyPostInput(rw.ucasChoiceNumber);
        rw.ucasSchemeCode = DedupeHelper.verifyPostInput(rw.ucasSchemeCode);

        rw.socioEconomicClassification = (rw.socioEconomicClassification != null
            ? LearnerService.setDropdownValueFromCode(
                  rw.socioEconomicClassification,
                  'Socio_economic_classification__c',
                  'Opportunity'
              )
            : null);
    }

    private static String lookForOpportunityId(RequestWrapper rw, String accountId) {
        DedupeOpportunity.CheckOpportunity opportunity = new DedupeOpportunity.CheckOpportunity();
        opportunity.accountId = accountId;
        opportunity.courseInstance = rw.offeringId;
        opportunity.recordSource = rw.source;
        DedupeOpportunity.Response checkOpportunityExists = DedupeOpportunity.doPost(opportunity);

        if (String.valueOf(checkOpportunityExists).contains('006')) {
            return DedupeHelper.formatResponseId(String.valueOf(checkOpportunityExists));
        }
        return null;
    }

    private static String updateOpportunity(Id id, RequestWrapper rw) {
        String result;
        String fields = 'Application_Date__c, CloseDate, Course_Instance__c, Offer_Type__c, Record_Source__c, Referee_Email__c, Referee_Name__c, SOC2020__c, Socio_economic_classification__c, Student_Status__c, UCAS_Application_Scheme_Code__c, UCAS_Choice_Number__c';
        String query = 'SELECT ' + fields + ' FROM Opportunity WHERE Id =: id';

        Opportunity opportunity = Database.query(String.escapeSingleQuotes(query));
        if (opportunity != null) {
            if (DedupeHelper.updateFieldDecision(String.valueOf(opportunity.Application_Date__c), rw.applicationDate)) {
                opportunity.Application_Date__c = Date.valueOf(rw.applicationDate);
            }
            if (DedupeHelper.updateFieldDecision(String.valueOf(opportunity.CloseDate), rw.closeDate)) {
                opportunity.CloseDate = Date.valueOf(rw.closeDate);
            }
            if (DedupeHelper.updateFieldDecision(opportunity.Course_Instance__c, rw.offeringId)) {
                opportunity.Course_Instance__c = rw.offeringId;
            }
            if (DedupeHelper.updateFieldDecision(opportunity.Offer_Type__c, rw.offerType)) {
                opportunity.Offer_Type__c = rw.offerType;
            }
            if (DedupeHelper.updateFieldDecision(opportunity.Record_Source__c, rw.source)) {
                opportunity.Record_Source__c = rw.source;
            }
            if (DedupeHelper.updateFieldDecision(opportunity.Referee_Email__c, rw.refereeEmail)) {
                opportunity.Referee_Email__c = rw.refereeEmail;
                if (DedupeHelper.updateFieldDecision(opportunity.Referee_Name__c, rw.refereeName)) {
                    opportunity.Referee_Name__c = rw.refereeName;
                }
            }
            if (DedupeHelper.updateFieldDecision(String.valueOf(opportunity.SOC2020__c), rw.soc2020)) {
                opportunity.SOC2020__c = Decimal.valueOf(rw.soc2020);
            }
            if (
                DedupeHelper.updateFieldDecision(
                    opportunity.Socio_economic_classification__c,
                    rw.socioEconomicClassification
                )
            ) {
                opportunity.Socio_economic_classification__c = rw.socioEconomicClassification;
            }
            if (DedupeHelper.updateFieldDecision(opportunity.UCAS_Application_Scheme_Code__c, rw.ucasSchemeCode)) {
                opportunity.UCAS_Application_Scheme_Code__c = rw.ucasSchemeCode;
            }
            if (
                DedupeHelper.updateFieldDecision(String.valueOf(opportunity.UCAS_Choice_Number__c), rw.ucasChoiceNumber)
            ) {
                opportunity.UCAS_Choice_Number__c = Decimal.valueOf(rw.ucasChoiceNumber);
            }

            try {
                update opportunity;
                result = opportunity.Id;
            } catch (Exception e) {
                result = 'LearnerService - Opportunity Update Error: [' + e.getLineNumber() + '] ' + e.getMessage();
            }
        }
        return result;
    }

    private static String createOpportunity(String accountId, RequestWrapper rw) {
        String result;
        Opportunity opportunity = new Opportunity();
        if (accountId != null && accountId.startsWith('001') && rw.closeDate != null) {
            Account account = [SELECT OwnerId, Student_Type__pc FROM Account WHERE Id = :accountId];
            opportunity.OwnerId = (account.Student_Type__pc == 'International'
                ? AssignmentUsers__c.getInstance().Default_International_Owner__c
                : AssignmentUsers__c.getInstance().Default_Admissions_Owner__c);
            //opportunity.OwnerId = account.OwnerId;
            opportunity.RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName()
                .get('Application')
                .getRecordTypeId();
            opportunity.AccountId = accountId;
            opportunity.Application_Date__c = (rw.applicationDate != null ? Date.valueOf(rw.applicationDate) : null);
            opportunity.CloseDate = Date.valueOf(rw.closeDate);
            opportunity.Course_Instance__c = rw.offeringId;
            opportunity.Customer_Group__c = 'SELFFUND';
            opportunity.Name = 'Test_' + DedupeHelper.generateRandomString(10);
            opportunity.Offer_Type__c = rw.offerType;
            opportunity.Record_Source__c = rw.source;
            opportunity.Referee_Email__c = rw.refereeEmail;
            opportunity.Referee_Name__c = rw.refereeName;
            opportunity.SOC2020__c = (rw.soc2020 != null ? Integer.valueOf(rw.soc2020) : null);
            opportunity.Socio_economic_classification__c = rw.socioEconomicClassification;
            opportunity.StageName = 'Application';
            opportunity.UCAS_Application_Scheme_Code__c = rw.ucasSchemeCode;
            opportunity.UCAS_Choice_Number__c = (rw.ucasChoiceNumber != null
                ? Decimal.valueOf(rw.ucasChoiceNumber)
                : null);

            try {
                insert opportunity;
                result = opportunity.Id;
            } catch (Exception e) {
                result = 'LearnerApplicationService Error: [' + e.getLineNumber() + '] ' + e.getMessage();
            }
        }
        return result;
    }
}