salesforce-main/src/main/default/objects/Account/fields/GDPR_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GDPR Opt In field in line with GDPR compliance. Linked to Marketing Cloud and student preference centre. Used as initial data point for passive opt in/outs (Marketing Cloud, Direct Apps etc.) &amp; triggers workflow marketing preference actions</description>
    <inlineHelpText>Account field</inlineHelpText>
    <label>GDPR Opt In</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/GDPR_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GDPR Opt In field in line with GDPR compliance. Linked to Marketing Cloud and student preference centre. Used as initial data point for passive opt in/outs (Marketing Cloud, Direct Apps etc.) &amp; triggers workflow marketing preference actions</description>
    <inlineHelpText>Contact Field</inlineHelpText>
    <label>GDPR Opt In</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Hashed_Email__c.field-meta.xml
<CustomField>
    <fullName>Hashed_Email__c</fullName>
    <description>Identifier for interactions across Marketing Cloud systems</description>
    <label>Hashed Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email__c</fullName>
    <description>Personal email address of student.</description>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/recordTypes/BD_Contact.recordType-meta.xml
<RecordType>
    <fullName>BD_Contact</fullName>
    <active>true</active>
    <description>Business development contact for B2B relationships.</description>
    <label>Business Development Contact</label>
</RecordType>

salesforce-main/src/main/default/objects/Lead/fields/GA_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>GA_Client_ID__c</fullName>
    <description>Google Analytics field used for tracking individuals</description>
    <label>GA Client ID</label>
    <length>350</length>
    <type>LongTextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/GClid_Information__c.field-meta.xml
<CustomField>
    <fullName>GClid_Information__c</fullName>
    <description>Google Analytics field used for tracking individuals</description>
    <label>GClid Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/GDPR_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>GDPR Opt In field in line with GDPR compliance. Linked to Marketing Cloud and student preference centre. Used as initial data point for passive opt in/outs (Marketing Cloud, Direct Apps etc.) &amp; triggers workflow marketing preference actions</description>
    <label>GDPR Opt In</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Source_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Recent__c</fullName>
    <label>Lead Source - Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>RFI</fullName>
            </value>
            <value>
                <fullName>Walk-Ins</fullName>
            </value>
            <value>
                <fullName>Campaign Landing Page</fullName>
            </value>
            <value>
                <fullName>Direct Input</fullName>
            </value>
            <value>
                <fullName>3rd Party Website Traffic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Source_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Timestamp__c</fullName>
    <description>Unbounce web page submission time</description>
    <label>Lead Source Timestamp</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Source_Timestamp_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Timestamp_Recent__c</fullName>
    <description>This field has been introduced due to the integration with Eloqua. This has prompted a change in business process for Leads - only 1 unique (email) Lead is allowed. This field has been added to compliment the Lead Source Timestamp - containing the original lead source timestamp value, this field will be updated with the most recent lead source timestamp information.</description>
    <inlineHelpText>Enter the most recent lead source date and time from when the lead was submitted or when the event took place</inlineHelpText>
    <label>Lead Source Timestamp - Recent</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Source_Title__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Title__c</fullName>
    <description>Unbounce web page title field</description>
    <label>Lead Source Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Source_Title_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Title_Recent__c</fullName>
    <description>This field has been introduced due to the integration with Eloqua. This has prompted a change in business process for Leads - only 1 unique (email) Lead is allowed. This field has been added to compliment the Lead Source Title - containing the original lead source title value, this field will be updated with the most recent lead source title information.</description>
    <inlineHelpText>Select the most recent lead source title such as the webpage or event</inlineHelpText>
    <label>Lead Source Title - Recent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Subsource__c.field-meta.xml
<CustomField>
    <fullName>Lead_Subsource__c</fullName>
    <label>Lead Subsource</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Youtube</fullName>
            </value>
            <value>
                <fullName>Linkedin</fullName>
            </value>
            <value>
                <fullName>bpp.com</fullName>
            </value>
            <value>
                <fullName>bpplawschool.com</fullName>
            </value>
            <value>
                <fullName>bppbusiness.com</fullName>
            </value>
            <value>
                <fullName>careerbuilder.com</fullName>
            </value>
            <value>
                <fullName>independent.co.uk</fullName>
            </value>
            <value>
                <fullName>notgoingtouni.com</fullName>
            </value>
            <value>
                <fullName>studentroom.co.uk</fullName>
            </value>
            <value>
                <fullName>ucas.co.uk</fullName>
            </value>
            <value>
                <fullName>The Sunday Times</fullName>
            </value>
            <value>
                <fullName>The Independent</fullName>
            </value>
            <value>
                <fullName>The Times</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Evening Standard</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>UCAS fairs</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Press articles</fullName>
            </value>
            <value>
                <fullName>Unbounce</fullName>
            </value>
            <value>
                <fullName>Fair</fullName>
            </value>
            <value>
                <fullName>Education Liaison</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Incoming Call</fullName>
            </value>
            <value>
                <fullName>Incoming Email</fullName>
            </value>
            <value>
                <fullName>Incoming Mail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Lead_Subsource_Recent__c.field-meta.xml
<CustomField>
    <fullName>Lead_Subsource_Recent__c</fullName>
    <description>This field has been introduced due to the integration with Eloqua. This has prompted a change in business process for Leads - only 1 unique (email) Lead is allowed. This field has been added to compliment the Lead Subource - containing the original lead subsource value, this field will be updated with the most recent lead subsource information.</description>
    <inlineHelpText>Select the most recent lead subsource</inlineHelpText>
    <label>Lead Subsource - Recent</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition Callback</fullName>
            </value>
            <value>
                <fullName>Education Liason</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Fair</fullName>
            </value>
            <value>
                <fullName>Incoming Call</fullName>
            </value>
            <value>
                <fullName>Incoming Email</fullName>
            </value>
            <value>
                <fullName>Incoming Mail</fullName>
            </value>
            <value>
                <fullName>International Agents</fullName>
            </value>
            <value>
                <fullName>Lead Forensics</fullName>
            </value>
            <value>
                <fullName>Live Chat</fullName>
            </value>
            <value>
                <fullName>Open Day</fullName>
            </value>
            <value>
                <fullName>Other Events</fullName>
            </value>
            <value>
                <fullName>Other Salesforce Lead</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Round Table</fullName>
            </value>
            <value>
                <fullName>Unbounce</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Marketing_Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign_ID__c</fullName>
    <label>Marketing Campaign ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Marketing_Media_Source__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Media_Source__c</fullName>
    <label>Marketing Media Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Marketing_Medium__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Medium__c</fullName>
    <label>Marketing Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/rfi_Course_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>rfi_Course_of_Interest__c</fullName>
    <label>Course of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>ACA</fullName>
            </value>
            <value>
                <fullName>Academic English</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>ACCA Professional Level Papers</fullName>
            </value>
            <value>
                <fullName>Accountancy/Taxation Professional Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Actuarial Technician Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Actuary Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Advanced Diploma in Accounting and Finance [ACCA Route]</fullName>
            </value>
            <value>
                <fullName>Agile Thinking in a Changing Business World</fullName>
            </value>
            <value>
                <fullName>Analytical and Critical Thinking</fullName>
            </value>
            <value>
                <fullName>Application Support Lead - Level 4</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Accounting</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Business and Administration</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Customer Service</fullName>
            </value>
            <value>
                <fullName>Apprenticeship General</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Law</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Professional Services</fullName>
            </value>
            <value>
                <fullName>Assistant Accountant Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager Apprenticeship</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>Barrister Training Course (BTC)</fullName>
            </value>
            <value>
                <fullName>Bar Transfer Test (BTT)</fullName>
            </value>
            <value>
                <fullName>BSc Accounting and Finance</fullName>
            </value>
            <value>
                <fullName>BSc Nursing (Adult)</fullName>
            </value>
            <value>
                <fullName>BSc Nursing (Child)</fullName>
            </value>
            <value>
                <fullName>BSc Nursing (Mental Health)</fullName>
            </value>
            <value>
                <fullName>BTC Part 1</fullName>
            </value>
            <value>
                <fullName>BTC Part 2</fullName>
            </value>
            <value>
                <fullName>Building Effective Coaching Skills</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/recordTypes/Prospective_Student.recordType-meta.xml
<RecordType>
    <fullName>Prospective_Student</fullName>
    <active>true</active>
    <businessProcess>Prospective Student</businessProcess>
    <description>Prospective Student</description>
    <label>Prospective Student</label>
</RecordType>

salesforce-main/src/main/default/classes/queueJobs/processors/EventRequestForInformationProcessorTest.cls
@isTest
private class EventRequestForInformationProcessorTest {
    @isTest
    private static void itShouldCreateLeadOnNoMatch() {
        // GIVEN a queue job
        RequestForInformationSchema eventSchema = createTestSchema();

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the processor is called
        EventRequestForInformationProcessor processor = new EventRequestForInformationProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        // THEN theres one successfull job
        Assert.areEqual(1, processor.successfulJobs.size(), 'Job is processed successfully');
        Assert.areEqual(0, processor.failedJobs.size(), 'No failed jobs');

        // AND a Lead has been created
        List<Lead> createdLeads = [
            SELECT
                Id,
                Description,
                GA_Client_ID__c,
                GClid_Information__c,
                Hashed_Email__c,
                LeadSource,
                Lead_Source_Recent__c,
                Lead_Source_Title__c,
                Lead_Subsource__c,
                Lead_Source_Timestamp__c,
                Lead_Source_Timestamp_Recent__c,
                Marketing_Campaign_ID__c,
                FirstName,
                LastName,
                Marketing_Medium__c,
                Marketing_Media_Source__c,
                Lead_Source_Title_Recent__c,
                Lead_Subsource_Recent__c,
                rfi_Course_of_Interest__c,
                GDPR_Opt_In__c,
                Personal_Email__c,
                Preferred_Email__c,
                Home_Phone__c,
                Preferred_Phone__c
            FROM Lead
        ];
        Assert.areEqual(1, createdLeads.size());

        Lead createdLead = createdLeads[0];
        Assert.areEqual(eventSchema.comments, createdLead.Description);
        Assert.areEqual(eventSchema.gaClientId, createdLead.GA_Client_ID__c);
        Assert.areEqual(eventSchema.gaGclId, createdLead.GClid_Information__c);
        Assert.areEqual(eventSchema.hashedEmail, createdLead.Hashed_Email__c);
        Assert.areEqual(eventSchema.leadSource, createdLead.LeadSource);
        Assert.areEqual(eventSchema.leadSource, createdLead.Lead_Source_Recent__c);
        Assert.areEqual(eventSchema.sourceTitle, createdLead.Lead_Source_Title__c);
        Assert.areEqual(eventSchema.subSource, createdLead.Lead_Subsource__c);
        Assert.isNotNull(createdLead.Lead_Source_Timestamp__c);
        Assert.isNotNull(createdLead.Lead_Source_Timestamp_Recent__c);
        Assert.areEqual(eventSchema.analytics_campaign, createdLead.Marketing_Campaign_ID__c);
        Assert.areEqual(eventSchema.firstName, createdLead.FirstName);
        Assert.areEqual(eventSchema.lastName, createdLead.LastName);
        Assert.areEqual(eventSchema.analytics_medium, createdLead.Marketing_Medium__c);
        Assert.areEqual(eventSchema.analytics_source, createdLead.Marketing_Media_Source__c);
        Assert.areEqual(eventSchema.sourceTitle, createdLead.Lead_Source_Title_Recent__c);
        Assert.areEqual(eventSchema.subSource, createdLead.Lead_Subsource_Recent__c);
        Assert.areEqual(eventSchema.programmeOfInterest, createdLead.rfi_Course_of_Interest__c);
        Assert.areEqual(!eventSchema.optOut, createdLead.GDPR_Opt_In__c);
        Assert.areEqual(eventSchema.email.toLowerCase(), createdLead.Personal_Email__c);
        Assert.areEqual('Personal', createdLead.Preferred_Email__c);
        Assert.areEqual(eventSchema.phone, createdLead.Home_Phone__c);
        Assert.areEqual('Home', createdLead.Preferred_Phone__c);
    }

    @isTest
    private static void itShouldUpdateLeadOnMatch() {
        // GIVEN a Lead and a queue job
        RequestForInformationSchema eventSchema = createTestSchema();

        Id leadProspectRtId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
            .get('Prospective_Student')
            .getRecordTypeId();

        insert new Lead(
            RecordTypeId = leadProspectRtId,
            FirstName = eventSchema.firstName,
            LastName = eventSchema.lastName,
            Personal_Email__c = eventSchema.email,
            Preferred_Email__c = 'Personal'
        );

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the processor is called
        EventRequestForInformationProcessor processor = new EventRequestForInformationProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        // THEN theres one successfull job
        Assert.areEqual(1, processor.successfulJobs.size(), 'Job is processed successfully');
        Assert.areEqual(0, processor.failedJobs.size(), 'No failed jobs');

        // AND a Lead has been updated
        List<Lead> updatedLeads = [
            SELECT
                Id,
                Description,
                GA_Client_ID__c,
                GClid_Information__c,
                Hashed_Email__c,
                LeadSource,
                Lead_Source_Recent__c,
                Lead_Source_Title__c,
                Lead_Subsource__c,
                Lead_Source_Timestamp__c,
                Lead_Source_Timestamp_Recent__c,
                Marketing_Campaign_ID__c,
                FirstName,
                LastName,
                Marketing_Medium__c,
                Marketing_Media_Source__c,
                Lead_Source_Title_Recent__c,
                Lead_Subsource_Recent__c,
                rfi_Course_of_Interest__c,
                GDPR_Opt_In__c,
                Personal_Email__c,
                Preferred_Email__c,
                Home_Phone__c,
                Preferred_Phone__c
            FROM Lead
        ];
        Assert.areEqual(1, updatedLeads.size());

        Lead createdLead = updatedLeads[0];
        Assert.areEqual(eventSchema.comments, createdLead.Description);
        Assert.areEqual(eventSchema.gaClientId, createdLead.GA_Client_ID__c);
        Assert.areEqual(eventSchema.gaGclId, createdLead.GClid_Information__c);
        Assert.areEqual(eventSchema.hashedEmail, createdLead.Hashed_Email__c);
        Assert.areEqual(eventSchema.leadSource, createdLead.LeadSource);
        Assert.areEqual(eventSchema.leadSource, createdLead.Lead_Source_Recent__c);
        Assert.isNotNull(createdLead.Lead_Source_Timestamp_Recent__c);
        Assert.areEqual(eventSchema.analytics_campaign, createdLead.Marketing_Campaign_ID__c);
        Assert.areEqual(eventSchema.firstName, createdLead.FirstName);
        Assert.areEqual(eventSchema.lastName, createdLead.LastName);
        Assert.areEqual(eventSchema.analytics_medium, createdLead.Marketing_Medium__c);
        Assert.areEqual(eventSchema.analytics_source, createdLead.Marketing_Media_Source__c);
        Assert.areEqual(eventSchema.sourceTitle, createdLead.Lead_Source_Title_Recent__c);
        Assert.areEqual(eventSchema.subSource, createdLead.Lead_Subsource_Recent__c);
        Assert.areEqual(eventSchema.programmeOfInterest, createdLead.rfi_Course_of_Interest__c);
        Assert.areEqual(!eventSchema.optOut, createdLead.GDPR_Opt_In__c);
        Assert.areEqual(eventSchema.email.toLowerCase(), createdLead.Personal_Email__c);
        Assert.areEqual('Personal', createdLead.Preferred_Email__c);
        Assert.areEqual(eventSchema.phone, createdLead.Home_Phone__c);
        Assert.areEqual('Home', createdLead.Preferred_Phone__c);
    }

    @isTest
    private static void itShouldUpdateAccountOnMatch() {
        // GIVEN a Lead and a queue job
        RequestForInformationSchema eventSchema = createTestSchema();

        Id studentAccountRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Student_Account')
            .getRecordTypeId();

        insert new Account(
            RecordTypeId = studentAccountRT,
            FirstName = eventSchema.firstName,
            LastName = eventSchema.lastName,
            Personal_Email__pc = eventSchema.email,
            Preferred_Email__pc = 'Personal',
            PersonHomePhone = eventSchema.phone,
            Preferred_Phone__pc = 'Home'
        );

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the processor is called
        EventRequestForInformationProcessor processor = new EventRequestForInformationProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        // THEN theres one successfull job
        Assert.areEqual(1, processor.successfulJobs.size(), 'Job is processed successfully');
        Assert.areEqual(0, processor.failedJobs.size(), 'No failed jobs');

        // AND a Lead has been updated
        List<Account> updatedAccounts = [
            SELECT
                Id,
                FirstName,
                GA_Client_ID__pc,
                Hashed_Email__pc,
                LastName,
                PersonHomePhone,
                Personal_Email__pc,
                Preferred_Email__pc,
                Preferred_Phone__pc,
                GDPR_Opt_In__c,
                PersonTitle
            FROM Account
        ];
        Assert.areEqual(1, updatedAccounts.size());

        Account updatedAccount = updatedAccounts[0];
        Assert.areEqual(eventSchema.firstname, updatedAccount.FirstName);
        Assert.areEqual(eventSchema.gaClientId, updatedAccount.GA_Client_ID__pc);
        Assert.areEqual(eventSchema.hashedEmail, updatedAccount.Hashed_Email__pc);
        Assert.areEqual(eventSchema.lastname, updatedAccount.LastName);
        Assert.areEqual(eventSchema.phone, updatedAccount.PersonHomePhone);
        Assert.areEqual(eventSchema.email.toLowerCase(), updatedAccount.Personal_Email__pc);
        Assert.areEqual('Personal', updatedAccount.Preferred_Email__pc);
        Assert.areEqual('Home', updatedAccount.Preferred_Phone__pc);
        Assert.areEqual(!eventSchema.optOut, updatedAccount.GDPR_Opt_In__c);
        Assert.areEqual(eventSchema.jobTitle, updatedAccount.PersonTitle);
    }
    /* Will pass once SF-1316 is merged
    @isTest
    private static void itShouldUpdateContactOnMatch() {
        // GIVEN a Lead and a queue job
        RequestForInformationSchema eventSchema = createTestSchema();
        eventSchema.recordType = 'Business Development';

        Id bdContactRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
            .get('BD_Contact')
            .getRecordTypeId();

        Account account = new Account(Name = eventSchema.company);
        insert account;

        insert new Contact(
            accountId = account.Id,
            RecordTypeId = bdContactRT,
            FirstName = eventSchema.firstName,
            LastName = eventSchema.lastName,
            Personal_Email__c = eventSchema.email,
            Preferred_Email__c = 'Work',
            HomePhone = eventSchema.phone,
            Preferred_Phone__c = 'Work'
        );

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        // WHEN the processor is called
        EventRequestForInformationProcessor processor = new EventRequestForInformationProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        // THEN theres one successfull job
        Assert.areEqual(1, processor.successfulJobs.size(), 'Job is processed successfully');
        Assert.areEqual(0, processor.failedJobs.size(), 'No failed jobs');

        // AND a Lead has been updated
        List<Contact> updatedContacts = [
            SELECT
                Id,
                FirstName,
                GA_Client_ID__c,
                LastName,
                Preferred_Email__c,
                Preferred_Phone__c,
                HomePhone,
                Personal_Email__c,
                GDPR_Opt_In__c,
                Title
            FROM Contact
        ];
        Assert.areEqual(1, updatedContacts.size());

        Contact updatedContact = updatedContacts[0];
        Assert.areEqual(eventSchema.firstname, updatedContact.FirstName);
        Assert.areEqual(eventSchema.gaClientId, updatedContact.GA_Client_ID__c);
        Assert.areEqual(eventSchema.lastname, updatedContact.LastName);
        Assert.areEqual('Work', updatedContact.Preferred_Email__c);
        Assert.areEqual('Work', updatedContact.Preferred_Phone__c);
        Assert.areEqual(eventSchema.phone, updatedContact.HomePhone);
        Assert.areEqual(eventSchema.email, updatedContact.Personal_Email__c);
        Assert.areEqual(!eventSchema.optOut, updatedContact.GDPR_Opt_In__c);
        Assert.areEqual(eventSchema.jobTitle, updatedContact.Title);
    }*/

    @isTest
    private static void itShouldFailOnRequiredFieldsForProspectiveStudent() {
        RequestForInformationSchema eventSchema = createTestSchema();
        eventSchema.lastName = '';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        EventRequestForInformationProcessor processor = new EventRequestForInformationProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        Assert.areEqual(1, processor.failedJobs.size(), 'I expect the job to fail due to missing required fields');
    }

    @isTest
    private static void itShouldFailOnRequiredFieldsForBusinessDevelopment() {
        RequestForInformationSchema eventSchema = createTestSchema();
        eventSchema.lastName = '';
        eventSchema.company = '';
        eventSchema.recordType = 'Business Development';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(eventSchema));

        EventRequestForInformationProcessor processor = new EventRequestForInformationProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        Assert.areEqual(1, processor.failedJobs.size(), 'I expect the job to fail due to missing required fields');
    }

    static RequestForInformationSchema createTestSchema() {
        RequestForInformationSchema eventSchema = new RequestForInformationSchema();
        eventSchema.analytics_campaign = 'test-campaign';
        eventSchema.analytics_source = 'test-campaign';
        eventSchema.analytics_medium = 'test-campaign';
        eventSchema.email = 'rfi@test.com';
        eventSchema.phone = '+441132021111';
        eventSchema.jobTitle = 'test-jobTitle';
        eventSchema.lastName = 'test-lastName';
        eventSchema.gaGclId = 'test-gclId';
        eventSchema.gaClientId = 'test-clientId';
        eventSchema.currentBppStudent = 'test-bppstudent';
        eventSchema.programmeOfInterest = 'test-page';
        eventSchema.optOut = false;
        eventSchema.firstName = 'test-firstName';
        eventSchema.sourceTitle = 'test-title';
        eventSchema.subSource = 'test-subSource';
        eventSchema.leadSource = 'test-leadSource';
        eventSchema.ukEuStudent = 'test-student';
        eventSchema.comments = 'test-comments';
        eventSchema.recordType = 'Prospective Student';
        eventSchema.formName = 'test-formName';
        eventSchema.company = 'test-company';
        eventSchema.hashedEmail = 'test-hashedEmail';
        eventSchema.levyPayer = false;

        return eventSchema;
    }
}