salesforce-main/src/main/default/objects/Account/fields/HUB_Student__c.field-meta.xml
<CustomField>
    <fullName>HUB_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HUB Student</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Authorisation_Token__c/Authorisation_Token__c.object-meta.xml
<CustomObject>
    <label>Authorisation Token</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authorisation Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Legal Entity</label>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity/fields/Enrolment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Status__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <description>Stages to enrolment once application has been accepted</description>
    <label>Enrolment Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Post-Registration (non-attendees)</fullName>
            </value>
            <value>
                <fullName>First Instalment Paid</fullName>
            </value>
            <value>
                <fullName>Temporarily Registered</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Programme_Application__c.field-meta.xml
<CustomField>
    <fullName>Programme_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Programme of interest or application.</description>
    <label>Programme</label>
    <referenceTo>Programme__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/ManualProvisioningControllerTest.cls
@isTest
public class ManualProvisioningControllerTest {
    @testSetup
    static void testSetup() {
        Authorisation_Token__c authToken = TestDataFactory.createAuthorisationToken(true);
        Country_List__c country = CreateTestData.createCountry1();
        Programme__c programme = CreateTestData.createProgram();

        Account account = new Account(
            FirstName = 'Test',
            LastName = 'ManualProvisioning',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                .get('Student_Account')
                .getRecordTypeId(),
            Student_Type__pc = 'Domestic',
            Preferred_Email__pc = 'Personal',
            Personal_Email__pc = 'test@manprovision.com',
            Preferred_Phone__pc = 'Mobile',
            PersonMobilePhone = '8015555556',
            PersonBirthdate = Date.valueOf('1986-12-07'),
            Country_of_Birth__pc = country.Id,
            Legal_Entity__c = 'UC~COL',
            Email_Address__pc = 'testmanualprov@my.bpp.com',
            BNR_Banner_ID__pc = '123456789',
            HUB_Student__c = true
        );
        insert account;

        Opportunity opportunity = new Opportunity(
            AccountId = account.Id,
            Name = 'Test ManualProvisioning',
            StageName = 'Accepted - Conditional Firm',
            Enrolment_Status__c = 'Acceptance',
            CloseDate = Date.valueOf('2015-02-27'),
            Programme_Application__c = programme.Id
        );
        insert opportunity;
    }

    @isTest
    static void itShouldSuccessfullyProvisionOpportunity() {
        Test.startTest();
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];

        Test.setMock(HttpCalloutMock.class, new AWSCalloutMock());
        String response = ManualProvisioningController.manualProvision(opportunity.Id);
        Assert.areEqual('Success', response, 'Manual Provisioning should be successful.');
        Test.stopTest();
    }

    @isTest
    static void itShouldFailProvisioningOpportunityDueToIncorrectStatus() {
        Test.startTest();
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        opportunity.StageName = 'Complete';
        opportunity.Enrolment_Status__c = 'N/A';
        update opportunity;

        String response = ManualProvisioningController.manualProvision(opportunity.Id);
        Assert.areEqual(
            'The Opportunity Status must be one of the following:</br>* Accepted - Conditional Firm</br>* Accepted - Unconditional Firm</br>* Accepted - Pmt Received</br>',
            response,
            'Manual Provisioning should fail due to incorrect Status.'
        );
        Test.stopTest();
    }

    @isTest
    static void itShouldFailProvisioningOpportunityDueToBlankProgramme() {
        Test.startTest();
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        opportunity.Programme_Application__c = null;
        update opportunity;

        String response = ManualProvisioningController.manualProvision(opportunity.Id);
        Assert.areEqual(
            'The Opportunity must have a value in the "Programme" field.</br>',
            response,
            'Manual Provisioning should fail due to blank Programme.'
        );
        Test.stopTest();
    }

    @isTest
    static void itShouldFailProvisioningOpportunityDueToBlankBannerId() {
        Test.startTest();
        Account account = [SELECT Id FROM Account LIMIT 1];
        account.BNR_Banner_ID__pc = null;
        update account;

        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];

        String response = ManualProvisioningController.manualProvision(opportunity.Id);
        Assert.areEqual(
            'The related Account must have a value in the "Banner ID" field.</br>',
            response,
            'Manual Provisioning should fail due to blank Banner Id.'
        );
        Test.stopTest();
    }

    @isTest
    static void itShouldFailProvisioningOpportunityDueToIncorrectEmailType() {
        Test.startTest();
        Account account = [SELECT Id FROM Account LIMIT 1];
        account.Email_Address__pc = null;
        update account;

        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];

        String response = ManualProvisioningController.manualProvision(opportunity.Id);
        Assert.areEqual(
            'The related Account Email Address must contain "my.bpp.com".</br>',
            response,
            'Manual Provisioning should fail due to incorrect Email type (must contain "@my.bpp.com").'
        );
        Test.stopTest();
    }

    @isTest
    static void itShouldFailProvisioningOpportunityDueToAccountHubStudentFalse() {
        Test.startTest();
        Account account = [SELECT Id FROM Account LIMIT 1];
        account.HUB_Student__c = false;
        update account;

        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];

        String response = ManualProvisioningController.manualProvision(opportunity.Id);
        Assert.areEqual(
            'The related Account must have the "HUB Student" checkbox checked.</br>',
            response,
            'Manual Provisioning should fail due to related Account\'s Hub Student field being unchecked.'
        );
        Test.stopTest();
    }
}