salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <label>Profile Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Training_Manager__c.field-meta.xml
<CustomField>
    <fullName>Training_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Training Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrimary</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <description>Pulls the Profile Company Id value from the related Account. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>Student__r.Profile_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Company ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Text_Country__c.field-meta.xml
<CustomField>
    <fullName>Text_Country__c</fullName>
    <label>Text Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Text_Locality__c.field-meta.xml
<CustomField>
    <fullName>Text_Locality__c</fullName>
    <label>Text Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Text_State__c.field-meta.xml
<CustomField>
    <fullName>Text_State__c</fullName>
    <label>Text State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Training_Manager__c.field-meta.xml
<CustomField>
    <fullName>Training_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Training Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/PS_Profile_Services_ID__c.field-meta.xml
<CustomField>
    <fullName>PS_Profile_Services_ID__c</fullName>
    <description>Sourced from Profile Services for SIStoCRM Integration.</description>
    <externalId>true</externalId>
    <label>Profile Services ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <description>NOT CURRENTLY IN USE OR DISPLAYED.  Indicates the highest level of qualification the student has achieved.</description>
    <label>[INACTIVE] Qualification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High School</fullName>
            </value>
            <value>
                <fullName>Bachelors Degree</fullName>
            </value>
            <value>
                <fullName>Masers Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <displayFormat>F-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Faculty__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Faculties</relationshipLabel>
    <relationshipName>Faculties</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Faculty__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Faculties</relationshipLabel>
    <relationshipName>Faculties</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Faculty__c/fields/Text_Country__c.field-meta.xml
<CustomField>
    <fullName>Text_Country__c</fullName>
    <label>Text Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Faculty__c/fields/Text_Locality__c.field-meta.xml
<CustomField>
    <fullName>Text_Locality__c</fullName>
    <label>Text Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Faculty__c/fields/Text_State__c.field-meta.xml
<CustomField>
    <fullName>Text_State__c</fullName>
    <label>Text State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log_Incoming__c/Integration_Log_Incoming__c.object-meta.xml
<CustomObject>
    <label>Integration Log Incoming</label>
    <nameField>
        <displayFormat>LOG#{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incoming Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Integration_Log_Incoming__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <label>Service Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Legal Entity</label>
</CustomObject>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Locality__c/fields/Banner_Code__c.field-meta.xml
<CustomField>
    <fullName>Banner_Code__c</fullName>
    <label>Banner Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ISO Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/classes/CreateStudentAccount.cls
@RestResource(urlMapping='/v1.0/CreateStudentAccount/*')

/*
{
    "stdDTO": [
        {
            "coachProfileId": "fbb4f6be-0d0a-4a3c-8136-c61322ec4c2b",
            "student": {
                "attributes": {
                    "type": "Account"
                },
                "FirstName": "Joey",
                "LastName": "JoBomber",
                "Middle_Name__pc": "James",
                "Preferred_First_Name__pc": "Joe",
                "Salutation": "Mr.",
                "AA_Suffix__pc": "III",
                "PersonTitle": "",
                "PersonBirthdate": "1979-03-23",
                "Intake__pc": "2014-03-23",
                "Business_Unit__pc": "",
                "Cost_Centre_Number__pc": "",
                "Student_Type__pc": "Domestic",
                "Gender__pc": "Male",
                "Legal_Entity__c": "",
                "VAT_Code__pc": "",
                "Work_Phone__pc": "",
                "PersonMobilePhone": "",
                "PersonOtherPhone": "",
                "PersonHomePhone": "",
                "Preferred_Phone__pc": "",
                "Home_Phone__pc": "555-555-5555",
                "Preferred_Phone__pc": "555-555-5555",
                "PS_Profile_Services_ID__pc": "fbb4f6be-0d0a-4a3c-8136-c61322ec4c2b",
                "Other_Email__pc": "JJJ@gmail.com",
                "BNR_Banner_ID__pc": "BP0038331",
                "Personal_Email__pc": "",
                "Work_Email__pc": "",
                "BPP_Email__pc": "",
                "Billing_Email__pc": "",
                "Preferred_email__pc": "JJJ@gmail.com"
            },
            "addresses": [
                {
                    "attributes": {
                        "type": "Address__c"
                    },
                    "Zip_Postal_Code__c": "",
                    "Primary__c": "",
                    "City__c": "PHOENIX",
                    "Zip_Postal_Code__c": "1714452",
                    "Text_Country__c": "USA",
                    "Text_State__c": "US-MS",
                    "Text_Locality__c": "",
                    "Type__c": "Mailing",
                    "Street_1__c": "ChangedAgn",
                    "Street_2__c": "Prt323r",
                    "Street_3__c": "Prnt333r",
                    "Street_4__c": "Homme3me3enex2 4ur STREET"
                },
                {
                    "attributes": {
                        "type": "Address__c"
                    },
                    "Primary__c": "",
                    "City__c": "PHOENIX",
                    "Zip_Postal_Code__c": "1714462",
                    "Text_Country__c": "USA",
                    "Text_State__c": "US-MS",
                    "Text_Locality__c": "",
                    "Type__c": "Billing",
                    "Street_1__c": "123",
                    "Street_2__c": "1233 ",
                    "Street_3__c": "111222",
                    "Street_4__c": "123 2 STREET"
                }
            ]
        }
    ]
}

*/

global with sharing class CreateStudentAccount {
    
    global class Response 
    {
        global String status { get; set; }
        global String code { get; set; }
        global String result { get; set; }
        global String id { get; set; }
        
        public Response(String status, String code, String result, String accountId) 
        {
            this.status = status;
            this.code = code;
            this.result=result;
            this.id=accountId;
        }
    }
    
    global class StudentDTO {
        public String coachProfileId;
        public Account student;
        public list<Address__c> addresses;
        public SponsorshipDTO sponsor;
        public list<Qualification__c> qualifications;      
    }
    
    global class SponsorshipDTO {
        public string CompanyProfileId;
        public string TrainingManagerProfileId;
    }
    
    @HttpPost
    global static Response doPost(List<StudentDTO> stdDTO) {
        return ProcessStudentAccount(stdDTO);
    }
    
    global static Response ProcessStudentAccount(List<StudentDTO> stdDTO) {
        String status = 'Success';
        String LogStatus;
        String Fresponse;
        String accountId = '0';
        String code = '201';
        String result = 'TRUE';
        RestResponse res = RestContext.response;
        res.statusCode = 200;
        
        
        try {
            Set<String> uniqueprofileIds = new Set<String>();
            for(StudentDTO stDTO: stdDTO){
                if(stDTO.student != null){
                    uniqueprofileIds.add(stDTO.student.PS_Profile_Services_ID__pc);
                }
            }
            list<Account> uniqueaccountList = [Select Id, PS_Profile_Services_ID__pc, Profile_Company_ID__c From Account Where (PS_Profile_Services_ID__pc IN :uniqueprofileIds) OR (Profile_Company_ID__c IN :uniqueprofileIds)];
            
            if(uniqueaccountList.size()>=1){
                status = 'Failure 1 : Account already exists';
                LogStatus = 'Failure 1 ' + ':\n' + status;
                result = 'False';
                code = '300';
                res.statusCode = 300;

            }
            else{
                list<Account> insertAcc = new list<Account>();
                list<Address__c> insertAdd = new list<Address__c>();
                list<Qualification__c> insertQlf = new list<Qualification__c>();
                list<Sponsorship__c> insertSpn = new list<Sponsorship__c>();
                list<Address__c> incomingAdd = new list<Address__c>();
                list<Qualification__c> incomingQlf = new list<Qualification__c>();
                
                Set<String> stdprofileIds = new Set<String>();
                Set<String> cmpprofileIds = new Set<String>();
                Set<String> TMprofileIds = new Set<String>();
                
                map<String, Id> stdaccounts = new map<String, Id>();
                map<String, Id> compaccounts = new map<String, Id>();
                map<String, Id> TManagers = new map<String, Id>();
                map<String, Id> Qualifications = new map<String, Id>();
                map<String, Id> countryCode = new map<String, Id>();
                map<String, Id> stateCode = new map<String, Id>();
                map<String, Id> localityCode = new map<String, Id>();
                
                list<Account> accountList;
                list<Contact> contactList;
                list<String> addFields;
                list<country_list__c> countries;
                list<State_Province__c> states;
                list<Locality__c> localities;
                
                
                
                list<RecordType> recordtype = [Select Id, DeveloperName From RecordType Where SobjectType = 'Account' AND DeveloperName =: 'Student_Account'];   
                
                for(StudentDTO stDTO: stdDTO){
                    if(stDTO.student != null){
                        Account acc = new Account();
                        acc = stDTO.student;
                        
                        // WEC 10/15/2014 CRM-3546 Lookup the Coach ID and assign it to the Student Account if coachProfileId is sent into the service.
                        if(stDTO.coachProfileId != null && stDTO.coachProfileId != '')
                        {
                            Faculty__c tempCoach = Util.findCoachFacultyByProfile(stDTO.coachProfileId);
                            acc.Coach__pc = tempCoach.Id;
                        }
                        
                        acc.RecordTypeId = recordtype[0].Id;
                        insertAcc.add(acc);
                        stdprofileIds.add(acc.PS_Profile_Services_ID__pc);
                    }
                    else{
                        status = 'Failure 2 : No Student information found in Request';
                        LogStatus = 'Failure 2 ' + ':\n' + status;
                    }
                    if(stDTO.sponsor != null){
                        if(stDTO.sponsor.CompanyProfileId != null){
                            cmpprofileIds.add(stDTO.sponsor.CompanyProfileId);
                        }
                        if(stDTO.sponsor.TrainingManagerProfileId != null){
                            TMprofileIds.add(stDTO.sponsor.TrainingManagerProfileId);
                        }
                    }
                    if(stDTO.addresses != null){
                        incomingAdd.addAll(stDTO.addresses);
                    }
                    if(stDTO.qualifications != null){
                        incomingQlf.addAll(stDTO.qualifications);
                    }
                }
                insert insertAcc;
                
                //Set the SFDC Account ID for the REST Response
                accountId = insertAcc[0].Id;
                
                system.debug('Incoming Student Accounts' + stdprofileIds.size());
                system.debug('Incoming Addresses' + incomingAdd.size());
                system.debug('Incoming Companies' + cmpprofileIds.size());
                system.debug('Incoming TManagers' + TMprofileIds.size());
                system.debug('Incoming Qualifications' + incomingQlf.size());
                
                if((incomingAdd.size() > 0) || (TMprofileIds.size() > 0) || (cmpprofileIds.size() > 0) || (incomingQlf.size() > 0)){
                    accountList = [Select Id, PS_Profile_Services_ID__pc, Profile_Company_ID__c From Account Where (PS_Profile_Services_ID__pc IN :stdprofileIds) OR (Profile_Company_ID__c IN :cmpprofileIds)];
                    accountList = [Select Id, PS_Profile_Services_ID__pc, Profile_Company_ID__c From Account Where (PS_Profile_Services_ID__pc IN :stdprofileIds) OR (Profile_Company_ID__c IN :cmpprofileIds)];
                    
                    for (Account accnt : accountList){
                        stdaccounts.put(accnt.PS_Profile_Services_ID__pc, accnt.Id);
                        if(accnt.Profile_Company_ID__c != null || accnt.Profile_Company_ID__c != ''){
                            compaccounts.put(accnt.Profile_Company_ID__c, accnt.Id);
                        }
                    }
                }
                if((TMprofileIds.size() > 0) || (incomingQlf.size() > 0)){
                    contactList = [Select Id, PS_Profile_Services_ID__c From Contact Where (PS_Profile_Services_ID__c IN :TMprofileIds) OR (PS_Profile_Services_ID__c IN :stdprofileIds)];
                    for (Contact cnt : contactList){
                        TManagers.put(cnt.PS_Profile_Services_ID__c, cnt.Id);
                        Qualifications.put(cnt.PS_Profile_Services_ID__c, cnt.Id);
                    }
                }
                if(incomingAdd.size() > 0){ 
                    countries = [Select Id, ISO_CODE__c From country_list__c Where ISO_CODE__c != '' AND 
                                 ISO_CODE__c != null];
                    for (country_list__c cntry : countries){
                        countryCode.put(cntry.ISO_CODE__c.toUpperCase(), cntry.Id);
                    }
                    states = [Select Id, ISO_Code__c From State_Province__c Where ISO_Code__c != '' AND 
                              ISO_Code__c != null];
                    for (State_Province__c stt : states){
                        stateCode.put(stt.ISO_Code__c.toUpperCase(), stt.Id);
                    }
                    localities = [Select Id, Banner_Code__c From Locality__c Where Banner_Code__c != '' AND 
                                  Banner_Code__c != null];
                    for (Locality__c lcty : localities){
                        localityCode.put(lcty.Banner_Code__c.toUpperCase(), lcty.Id);
                    }
                }
                for(StudentDTO stDTO: stdDTO){
                    if(stdaccounts.containsKey(stDTO.student.PS_Profile_Services_ID__pc)){
                        if(stDTO.addresses != null){
                            for(Address__c adds: stDTO.addresses){
                                Address__c add = new Address__c();
                                add = adds; 
                                add.Student__c = stdaccounts.get(stDTO.student.PS_Profile_Services_ID__pc);
                                if(add.Text_Country__c != null && add.Text_Country__c != ''){
                                    if (countryCode.containsKey(add.Text_Country__c.toUpperCase())){
                                        add.Lookup_Country__c = countryCode.get(add.Text_Country__c.toUpperCase());
                                    }
                                }
                                if(add.Text_State__c != null && add.Text_State__c != ''){
                                    if (stateCode.containsKey(add.Text_State__c.toUpperCase())){
                                        add.State_Province__c = stateCode.get(add.Text_State__c.toUpperCase());
                                    }
                                }
                                if(add.Text_Locality__c != null && add.Text_Locality__c != ''){
                                    if (localityCode.containsKey(add.Text_Locality__c.toUpperCase())){
                                        add.Locality__c = localityCode.get(add.Text_Locality__c.toUpperCase());
                                    }
                                }
                                insertAdd.add(add);
                            }
                        }
                        if(stDTO.sponsor != null){
                            Sponsorship__c spn = new Sponsorship__c();
                            spn.Active__c = true;
                            spn.Student__c = stdaccounts.get(stDTO.student.PS_Profile_Services_ID__pc);
                            spn.Company__c = compaccounts.get(stDTO.sponsor.CompanyProfileId);
                            spn.Training_Manager__c = TManagers.get(stDTO.sponsor.TrainingManagerProfileId);
                            insertSpn.add(spn);
                        }
                        if(stDTO.qualifications != null){
                            for(Qualification__c qlfs: stDTO.qualifications){
                                Qualification__c qlf = new Qualification__c();
                                qlf = qlfs;
                                qlf.Subject__c = 'TBD'; 
                                qlf.Student__c = Qualifications.get(stDTO.student.PS_Profile_Services_ID__pc);
                                insertQlf.add(qlf);
                            }
                        }
                    }
                }                
                insert insertAdd;
                insert insertSpn;
                insert insertQlf;
            }
            writeLog(stdDTO, LogStatus);
            return new Response(status,
                                code,
                                result,
                                accountId); 
        }
        catch (Exception e) {
            Fresponse =  'Failure' + ':\n' + e.getTypeName() + ' - ' + e.getMessage();
            writeLog(stdDTO, 'Failure' + ':\n' + e.getLineNumber() + ': ' + e.getTypeName() + ' - ' + e.getMessage() + '\n' + e.getStackTraceString());
            res.statusCode = 500;
            return new Response(Fresponse,
                                '500',
                                'FALSE',
                                accountId);
        }
    }
    
    
    private static void writeLog(List<StudentDTO> stdDTO, String Status){
        Integration_Log_Incoming__c log = new Integration_Log_Incoming__c();
        log.Request_Body__c = JSON.serialize(stdDTO);
        log.Request_Date__c = Datetime.now();
        log.Service_Name__c = 'CreateStudentAccount';
        log.Details__c = Status;
        insert log;
    }
}