salesforce-main/src/main/default/objects/Account/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UC~COL</fullName>
            </value>
            <value>
                <fullName>UC~WEB</fullName>
            </value>
            <value>
                <fullName>LEGAL~CEU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Student_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Student_Cycle__c</fullName>
    <description>Student cycle sets the default mode of contact for the particular student record.  

Pursue (default): Student is a potential purchaser of BPP products near-term.
Maintenance: Student is a potential purchaser of BPP products long-term.
No Further Action: Student is not a potential purchaser of BPP products.</description>
    <label>Student Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pursue</fullName>
                <default>true</default>
                <label>Pursue</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Legal Entity</label>
</CustomObject>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Application_Decision_Comment__c.field-meta.xml
<CustomField>
    <fullName>BNR_Application_Decision_Comment__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Application Decision Comment</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Cycle_Override__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Override__c</fullName>
    <description>Cycle override is used to set the cycle for the opportunity if it differs from the student.  By default it will select &quot;Use Student Cycle&quot;.</description>
    <label>Cycle Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Use Student Cycle</fullName>
                <default>true</default>
                <label>Use Student Cycle</label>
            </value>
            <value>
                <fullName>Pursue</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Enrolment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrolment_Status__c</fullName>
    <defaultValue>&quot;N/A&quot;</defaultValue>
    <description>Stages to enrolment once application has been accepted</description>
    <label>Enrolment Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Acceptance</fullName>
            </value>
            <value>
                <fullName>Welcome</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Post-Registration (non-attendees)</fullName>
            </value>
            <value>
                <fullName>First Instalment Paid</fullName>
            </value>
            <value>
                <fullName>Temporarily Registered</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_ADMT_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_ADMT_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions ADMT Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>9~ UCAS</fullName>
            </value>
            <value>
                <fullName>AG~ Agent</fullName>
            </value>
            <value>
                <fullName>DI~ Direct</fullName>
            </value>
            <value>
                <fullName>LC~ Law CABs</fullName>
            </value>
            <value>
                <fullName>MI~ Milkround</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_RESD_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_RESD_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions RESD Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U~ UK National</fullName>
            </value>
            <value>
                <fullName>L~ Indefinite Leave to Remain</fullName>
            </value>
            <value>
                <fullName>R~ Right of Abode</fullName>
            </value>
            <value>
                <fullName>E~ EU National</fullName>
            </value>
            <value>
                <fullName>F~ EU National Family Member</fullName>
            </value>
            <value>
                <fullName>M~ EEA Family Member</fullName>
            </value>
            <value>
                <fullName>R~ Refugee</fullName>
            </value>
            <value>
                <fullName>B~ Refugee Family Member</fullName>
            </value>
            <value>
                <fullName>H~ Humanitarian Protection</fullName>
            </value>
            <value>
                <fullName>P~ Humanitarian Protection Family</fullName>
            </value>
            <value>
                <fullName>T~ Child of a Turkish worker</fullName>
            </value>
            <value>
                <fullName>C~ Child of a Swiss National</fullName>
            </value>
            <value>
                <fullName>A~ EEA</fullName>
            </value>
            <value>
                <fullName>O~ Non-EEA VISA  required</fullName>
            </value>
            <value>
                <fullName>V~ Non-EEA no VISA required</fullName>
            </value>
            <value>
                <fullName>G~ England</fullName>
            </value>
            <value>
                <fullName>S~ Scotland</fullName>
            </value>
            <value>
                <fullName>W~ Wales</fullName>
            </value>
            <value>
                <fullName>N~ Northern Ireland</fullName>
            </value>
            <value>
                <fullName>I~ Islands (Man, Channel)</fullName>
            </value>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Admissions_STYPE_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admissions_STYPE_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Admissions STYPE Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0~ Undeclared</fullName>
            </value>
            <value>
                <fullName>N~ New</fullName>
            </value>
            <value>
                <fullName>R~ Returning</fullName>
            </value>
            <value>
                <fullName>C~ Continuing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Attribute_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Attribute_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Attribute Code Select - Reference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FT~ Full Time Student</fullName>
            </value>
            <value>
                <fullName>PT~ Part Time Student</fullName>
            </value>
            <value>
                <fullName>FL~ Flex</fullName>
            </value>
            <value>
                <fullName>T4~ Tier 4 International Student</fullName>
            </value>
            <value>
                <fullName>S1~ Year 1 / Stage 1</fullName>
            </value>
            <value>
                <fullName>S2~ Year 2 / Stage 2</fullName>
            </value>
            <value>
                <fullName>S3~ Year 3 / Stage 3</fullName>
            </value>
            <value>
                <fullName>SP~ Sponsor</fullName>
            </value>
            <value>
                <fullName>ACCE~ Accelerated</fullName>
            </value>
            <value>
                <fullName>ONLN~ Online</fullName>
            </value>
            <value>
                <fullName>BLEN~ Blended</fullName>
            </value>
            <value>
                <fullName>FTF~ Face to Face</fullName>
            </value>
            <value>
                <fullName>DLA~ Distance Learning Mode A</fullName>
            </value>
            <value>
                <fullName>EVE~ Evening</fullName>
            </value>
            <value>
                <fullName>SATU~ Saturday</fullName>
            </value>
            <value>
                <fullName>SUN~ Sunday</fullName>
            </value>
            <value>
                <fullName>WEK~ Weekend</fullName>
            </value>
            <value>
                <fullName>KC~ Key Client</fullName>
            </value>
            <value>
                <fullName>IH~ In House client</fullName>
            </value>
            <value>
                <fullName>EXAM~ Store Exam Results</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/SFDC_Cohort_Code_Select__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Cohort_Code_Select__c</fullName>
    <description>Added for SIS Integrations.</description>
    <label>Cohort Code Select</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C1~ Cohort January</fullName>
            </value>
            <value>
                <fullName>C2~ Cohort February</fullName>
            </value>
            <value>
                <fullName>C3~ Cohort March</fullName>
            </value>
            <value>
                <fullName>C4~ Cohort April</fullName>
            </value>
            <value>
                <fullName>C5~ Cohort May</fullName>
            </value>
            <value>
                <fullName>C6~ Cohort June</fullName>
            </value>
            <value>
                <fullName>C7~ Cohort July</fullName>
            </value>
            <value>
                <fullName>C8~ Cohort August</fullName>
            </value>
            <value>
                <fullName>C9~ Cohort September</fullName>
            </value>
            <value>
                <fullName>C10~ Cohort October</fullName>
            </value>
            <value>
                <fullName>C11~ Cohort November</fullName>
            </value>
            <value>
                <fullName>C12~ Cohort December</fullName>
            </value>
            <value>
                <fullName>S1~ SLC May</fullName>
            </value>
            <value>
                <fullName>S2~ SLC Sep</fullName>
            </value>
            <value>
                <fullName>S3~ SLC Jan</fullName>
            </value>
            <value>
                <fullName>H1~ HESA 11/12</fullName>
            </value>
            <value>
                <fullName>H2~ HESA 12/13</fullName>
            </value>
            <value>
                <fullName>H3~ HESA 13/14</fullName>
            </value>
            <value>
                <fullName>H4~ HESA 14/15</fullName>
            </value>
            <value>
                <fullName>H5~ HESA 15/16</fullName>
            </value>
            <value>
                <fullName>H6~ HESA 16/17</fullName>
            </value>
            <value>
                <fullName>H7~ HESA 17/18</fullName>
            </value>
            <value>
                <fullName>H8~ HESA 18/19</fullName>
            </value>
            <value>
                <fullName>H9~ HESA 19/20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/ShareAccountTest.cls
@isTest
private class ShareAccountTest 
{
    static testMethod void shareAccTest() 
    {
        User u = [select id, name from User where userrole.name = 'Customer Service' and isActive = true limit 1];
        system.debug('User details'+u.Name);
        
        Account a1 = new Account();
        a1.firstname='John';
        a1.lastname='Coppedge';
        a1.Salutation = 'Mr';
        a1.Middle_Name__pc = 'Mex';
        a1.Gender__pc = 'Male';
        a1.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId();
        a1.Student_Cycle__c = 'Pursue';
        a1.Student_Type__pc ='Domestic';
        a1.Preferred_Email__pc = 'Personal';
        a1.PersonEmail = 'john@john.com';
        a1.Personal_Email__pc ='john@john.com';
        a1.Work_Email__pc = 'john1@john.com';
        a1.BPP_Email__pc = 'john2@john.com';
        a1.Other_Email__pc = 'john3@john.com';
        a1.Billing_Email__pc = 'john4@john.com';
        a1.Preferred_Phone__pc = 'Mobile';
        a1.Phone = '8015555556';
        a1.PersonMobilePhone='8015555556';
        a1.PersonBirthdate =Date.valueOf('1986-12-07');
        a1.AA_Suffix__pc = 'Jr';
        a1.Preferred_First_Name__pc = 'Coppege';
        a1.Previous_First_Name__pc = 'John';
        a1.Previous_Surname__pc = 'Cop';
        a1.Previous_Middle_Name__pc = 'Copp';
        a1.Legal_Entity__c = 'UC~COL';
        a1.PS_Profile_Services_ID__pc = '1234f567-bc23-42e8-924c-1234asdf5678';
        a1.SFDC_Ethnic_Code_Select__pc = '10~ White';
        a1.SFDC_Disability_Status_Code_Select__pc = '0~ No Known DisabilityUndo';
        //a1.SFDC_Disability_Type_Code_Select__pc = '0~ No Known DisabilityUndo';
        a1.Country_of_Birth__pc = 'Unit Test';
        insert a1;
        
        Opportunity opp1 = new Opportunity();
        opp1.AccountId = a1.id;
        opp1.Name = 'test';
        opp1.StageName = 'Accepted - Conditional Firm';
        opp1.Enrolment_Status__c = 'Acceptance';
        opp1.Cycle_Override__c = 'Use Student Cycle';
        opp1.CloseDate = Date.valueOf('2015-02-27'); 
        opp1.BNR_Application_Decision_Comment__c = 'ABCD';
        opp1.SFDC_Attribute_Code_Select__c = 'FT~ Full Time Student';
        opp1.SFDC_Admissions_ADMT_Code_Select__c = 'DI~ Direct';
        opp1.SFDC_Admissions_STYPE_Code_Select__c = 'R~ Returning';
        opp1.SFDC_Admissions_RESD_Code_Select__c = 'E~ EU National';
        opp1.SFDC_Cohort_Code_Select__c = 'C6~ Cohort June';
        insert opp1;
        
        Task taskvar = new Task();
        taskvar.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Admissions Task').getRecordTypeId();
        taskvar.Ownerid=u.id;
        taskvar.Status = 'In Progress';
        taskvar.Priority = 'Normal';
        //taskvar.AccountId = a1.id;
        taskvar.WhatId = a1.id;
        insert taskvar;
        
        taskvar.Status = 'Completed';
        update taskvar;
    
    }
}