salesforce-main/src/main/default/objects/Account/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <label>Profile Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Training_Manager__c.field-meta.xml
<CustomField>
    <fullName>Training_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Training Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/recordTypes/Business_Development_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Development_Account</fullName>
    <active>true</active>
    <description>Business development account for establishing B2B relationships.</description>
    <label>Business Development Account</label>
</RecordType>

salesforce-main/src/main/default/objects/Contact/fields/Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Personal_Email__c</fullName>
    <description>Personal email address of student.</description>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <description>Indicates the preferred email address of the student.  Must be populated if an email address is present on the student record.  Update the email field of the student every time the student record is saved based on the preferred selection.</description>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>BPP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/fields/PS_Profile_Services_ID__c.field-meta.xml
<CustomField>
    <fullName>PS_Profile_Services_ID__c</fullName>
    <description>Sourced from Profile Services for SIStoCRM Integration.</description>
    <externalId>true</externalId>
    <label>Profile Services ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Contact/recordTypes/Training_Manager.recordType-meta.xml
<RecordType>
    <fullName>Training_Manager</fullName>
    <active>true</active>
    <label>Training Manager</label>
</RecordType>

salesforce-main/src/main/default/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {
    @testSetup
    static void makeData() {
        Map<String, Object> accountFieldMap = new Map<String, Object>{ 'Profile_Company_ID__c' => '123456789' };

        List<Account> accountList = TestDataFactory.createAccounts(
            1,
            'Business_Development_Account',
            false,
            accountFieldMap
        );
        Database.insert(accountList);

        Map<String, Object> contactFieldMap = new Map<String, Object>{ 'AccountId' => accountList[0].Id };
        List<Contact> contactList = TestDataFactory.createContacts(2, 'Billing_Contact', false, contactFieldMap);
        contactList[0].Primary_Billing_Contact__c = true;
        Database.insert(contactList);

        Map<String, Object> trainingManagerFieldMap = new Map<String, Object>{
            'Active__c' => true,
            'PS_Profile_Services_ID__c' => '123456789',
            'Preferred_Email__c' => 'Personal',
            'Personal_Email__c' => 'test-Training_Manager@mail.com',
            'AccountId' => accountList[0].Id
        };
        List<Contact> trainingManagerContactList = TestDataFactory.createContacts(
            1,
            'Training_Manager',
            true,
            trainingManagerFieldMap
        );

        Account studentAccount = TestDataFactory.createAccount(false, true, null, 0);
        studentAccount.PS_Profile_Services_ID__pc = '1234xxx5-xxx1-1x2x-xxx1-12345x678x9';
        Database.insert(studentAccount);

        Map<String, Object> sponsorshipFieldMap = new Map<String, Object>{
            'Student__c' => studentAccount.Id,
            'Training_Manager__c' => trainingManagerContactList[0].Id
        };
        List<Sponsorship__c> sponsorshipList = TestDataFactory.createSponsorships(1, true, sponsorshipFieldMap);
    }

    @isTest
    static void test_unableToSaveMultiplePrimaryBillingContacts_beforeInsert() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        Map<String, Object> contactFieldMap = new Map<String, Object>{
            'AccountId' => account.Id,
            'Primary_Billing_Contact__c' => true
        };
        List<Contact> contactsToTest = TestDataFactory.createContacts(1, 'Billing_Contact', false, contactFieldMap);
        try {
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            dml.DuplicateRuleHeader.runAsCurrentUser = true;
            Database.insert(contactsToTest, dml);
        } catch (Exception e) {
            System.debug('test_unableToSaveMultiplePrimaryBillingContacts_beforeInsert error = ' + e.getMessage());
            System.assertEquals(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'), true);
        }
    }

    @isTest
    static void test_unableToSaveMultiplePrimaryBillingContacts_beforeUpdate() {
        Contact contact = [
            SELECT Id
            FROM Contact
            WHERE Primary_Billing_Contact__c = FALSE AND RecordType.DeveloperName = 'Billing_Contact'
            LIMIT 1
        ];
        contact.Primary_Billing_Contact__c = true;
        try {
            update contact;
        } catch (Exception e) {
            System.debug('test_unableToSaveMultiplePrimaryBillingContacts_beforeUpdate error = ' + e.getMessage());
            System.assertEquals(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'), true);
        }
    }

    @isTest
    static void test_unableToDeactivateTrainingManagersWithSponsorships_beforeUpdate() {
        Contact contact = [
            SELECT Id
            FROM Contact
            WHERE RecordType.DeveloperName = 'Training_Manager'
            LIMIT 1
        ];
        contact.Active__c = false;
        try {
            update contact;
        } catch (Exception e) {
            System.debug(
                'test_unableToDeactivateTrainingManagersWithSponsorships_beforeUpdate error = ' + e.getMessage()
            );
            System.assertEquals(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'), true);
        }
    }
}