salesforce-main/src/main/default/objects/Account/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <label>Profile Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Account/fields/Training_Manager__c.field-meta.xml
<CustomField>
    <fullName>Training_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Client__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Training Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Used to store all address records related to a Student</description>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Address__c/fields/Accommodation_Type__c.field-meta.xml
<CustomField>
    <fullName>Accommodation_Type__c</fullName>
    <description>What type of accommodation is the address</description>
    <label>Accommodation Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Term_Time__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01~Provider maintained property</fullName>
            </value>
            <value>
                <fullName>02~Parental/guardian home</fullName>
            </value>
            <value>
                <fullName>04~Own residence</fullName>
            </value>
            <value>
                <fullName>05~Other rented accommodation</fullName>
            </value>
            <value>
                <fullName>06~Private-sector halls</fullName>
            </value>
            <value>
                <fullName>07~Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/County_State__c.field-meta.xml
<CustomField>
    <fullName>County_State__c</fullName>
    <label>County/State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Delivery_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Instructions__c</fullName>
    <description>Instructions to delivery service e.g. how to gain entry to property / where to leave item</description>
    <label>Delivery Instructions</label>
    <type>TextArea</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Locality__c.field-meta.xml
<CustomField>
    <fullName>Locality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locality</label>
    <referenceTo>Locality__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Lookup_Country__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Country value you have selected is not a valid Nationality.</errorMessage>
        <filterItems>
            <field>country_list__c.Valid_Nationality__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>country_list__c</referenceTo>
    <relationshipLabel>Student_Addresses</relationshipLabel>
    <relationshipName>Student_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Permanent_Home__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Home__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This denotes if the address is the student&apos;s designated permanent home address</description>
    <label>Permanent Home?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isPrimary</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary_Billing__c.field-meta.xml
<CustomField>
    <fullName>Primary_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Billing?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Primary_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Delivery?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Profile_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Company_ID__c</fullName>
    <description>Pulls the Profile Company Id value from the related Account. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>Student__r.Profile_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Company ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Profile_Services_ID__c.field-meta.xml
<CustomField>
    <fullName>Profile_Services_ID__c</fullName>
    <description>Pulls the Profile Id value from either the related Account or Contact. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>IF(
				NOT(ISBLANK(Student__r.PS_Profile_Services_ID__pc)),
				Student__r.PS_Profile_Services_ID__pc,
				IF(
								NOT(ISBLANK(Training_Manager__r.PS_Profile_Services_ID__c)),
								Training_Manager__r.PS_Profile_Services_ID__c,
								NULL
				)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Services ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Record_Source__c.field-meta.xml
<CustomField>
    <fullName>Record_Source__c</fullName>
    <description>Indicates from what data source the record was created. &quot;Salesforce&quot; indicates a record that was manually entered.</description>
    <inlineHelpText>Indicates from what data source the record was created. &quot;Salesforce&quot; indicates a record that was manually entered.</inlineHelpText>
    <label>Record Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
                <default>true</default>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Direct Apps</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>UCAS</fullName>
            </value>
            <value>
                <fullName>BARSAS</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Hub</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Related_Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Type_ID__c</fullName>
    <description>Pulls the Record Type Id value from either the related Account or Contact. Useful for avoiding multiple unnecessary SOQL calls in the AddressTrigger.</description>
    <formula>IF(
	NOT(ISBLANK(Student__c)),
	CASESAFEID(Student__r.RecordTypeId),
	IF(
		NOT(ISBLANK(Training_Manager__c)),
		CASESAFEID(Training_Manager__r.RecordTypeId),
		NULL
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Record Type ID</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State/Province</label>
    <referenceTo>State_Province__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_2__c.field-meta.xml
<CustomField>
    <fullName>Street_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_3__c.field-meta.xml
<CustomField>
    <fullName>Street_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Street_4__c.field-meta.xml
<CustomField>
    <fullName>Street_4__c</fullName>
    <label>Address Line 4</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Term_Time__c.field-meta.xml
<CustomField>
    <fullName>Term_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This denotes if the address is the students designated term time address</description>
    <label>Term Time?</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Text_Country__c.field-meta.xml
<CustomField>
    <fullName>Text_Country__c</fullName>
    <label>Text Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Text_Locality__c.field-meta.xml
<CustomField>
    <fullName>Text_Locality__c</fullName>
    <label>Text Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Text_State__c.field-meta.xml
<CustomField>
    <fullName>Text_State__c</fullName>
    <label>Text State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Training_Manager__c.field-meta.xml
<CustomField>
    <fullName>Training_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Training Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Statement</fullName>
            </value>
            <value>
                <fullName>Next of Kin/Emergency/Guardian</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Term time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Locality__c/Locality__c.object-meta.xml
<CustomObject>
    <label>Locality</label>
    <nameField>
        <label>Locality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/AddressAlign.cls
/**
 * Flattens Addresses with multiple checkboxes into individual records
 */
public class AddressAlign {
    /**
     * Queries addresses. Creates one address record per type. Updates type checkboxes
     * @param accountIds List of account ids
     */
    public static List<Address__c> queryAndAlignAddresses(List<Id> accountIds) {
        List<Account> accountsToCheck = [
            SELECT
                Id,
                name,
                (
                    SELECT
                        Id,
                        Type__c,
                        Primary_Billing__c,
                        Primary_Delivery__c,
                        Permanent_Home__c,
                        Term_Time__c,
                        lastModifiedDate,
                        Accommodation_Type__c,
                        Active__c,
                        City__c,
                        County_State__c,
                        Delivery_Instructions__c,
                        Lead__c,
                        Locality__c,
                        Lookup_Country__c,
                        Primary__c,
                        Profile_Company_ID__c,
                        Profile_Services_ID__c,
                        Record_Source__c,
                        Related_Record_Type_ID__c,
                        State_Province__c,
                        Street_1__c,
                        Street_2__c,
                        Street_3__c,
                        Street_4__c,
                        Student__c,
                        Text_Country__c,
                        Text_Locality__c,
                        Text_State__c,
                        Training_Manager__c,
                        Zip_Postal_Code__c
                    FROM Addresses__r
                    WHERE Active__c = TRUE AND Type__c IN ('Home', 'Mailing', 'Billing', 'Term Time')
                )
            FROM Account
            WHERE Id IN :accountIds AND IsPersonAccount = TRUE
        ];

        return alignAddresses(accountsToCheck);
    }

    /**
     * Creates one address record per type. Updates type checkboxes
     * @param accounts List of Accounts
     */
    @TestVisible
    private static List<Address__c> alignAddresses(List<Account> accounts) {
        List<Address__c> addressesToUpsert = new List<Address__c>();

        for (Account account : accounts) {
            Map<String, AddressDetails> addressesByType = new Map<String, AddressDetails>();

            // Loop over each Address and flatten their checkboxes into individual addresses for each checkbox being evaluated which is true
            for (Address__c address : account.Addresses__r) {
                if (address.Permanent_Home__c) {
                    createAddress(addressesByType, address, 'Home');
                }

                if (address.Primary_Billing__c) {
                    createAddress(addressesByType, address, 'Billing');
                }

                if (address.Primary_Delivery__c) {
                    createAddress(addressesByType, address, 'Mailing');
                }

                if (address.Term_Time__c) {
                    createAddress(addressesByType, address, 'Term time');
                }
            }

            Map<String, Address__c> alreadyProcessedPicklistTypes = new Map<String, Address__c>();

            // Re-loop over the Addresses and enrich/inject the existing map with that address data
            for (Address__c address : account.Addresses__r) {
                // If we've already processed a record of the given Type, identify which is newer and update the Id to the most recently updated one, deactivating any others as they are duplicate records
                if (alreadyProcessedPicklistTypes.containsKey(address.Type__c)) {
                    Address__c duplicateAddress = alreadyProcessedPicklistTypes.get(address.Type__c);

                    if (address.lastModifiedDate <= duplicateAddress.lastModifiedDate) {
                        address.Permanent_Home__c = false;
                        address.Primary_Billing__c = false;
                        address.Primary_Delivery__c = false;
                        address.Term_Time__c = false;
                        address.Active__c = false;
                        addressesToUpsert.add(address);
                        continue;
                    } else {
                        duplicateAddress.Permanent_Home__c = false;
                        duplicateAddress.Primary_Billing__c = false;
                        duplicateAddress.Primary_Delivery__c = false;
                        duplicateAddress.Term_Time__c = false;
                        duplicateAddress.Active__c = false;
                        addressesToUpsert.add(duplicateAddress);
                    }
                }

                // If we've not created any Addresses with the current Type using checkboxes, calculate which Checkbox should be selected based on the type and insert the record as it will now have the correct data
                if (!addressesByType.containsKey(address.Type__c)) {
                    address.Permanent_Home__c = address.Type__c == 'Home';
                    address.Primary_Billing__c = address.Type__c == 'Billing';
                    address.Primary_Delivery__c = address.Type__c == 'Mailing';
                    address.Term_Time__c = address.Type__c == 'Term time';

                    AddressDetails newAddressDetails = new AddressDetails();
                    newAddressDetails.newAddress = address;

                    addressesByType.put(address.Type__c, newAddressDetails);
                }
                // Otherwise if we've already created an Address record for the current Type picklist value we can simply inject the Id of the record onto it to make it an update
                else {
                    Address__c AddressToUpdate = addressesByType.get(address.Type__c).newAddress;
                    AddressToUpdate.Id = address.Id;
                }

                // Once we've finished processing the current Type picklist value, flag it as already have been processed for de-duplication later on
                alreadyProcessedPicklistTypes.put(address.Type__c, address);
            }

            // Finally extract the final address records that we must upsert
            for (AddressDetails addressDetails : addressesByType.values()) {
                addressesToUpsert.add(addressDetails.newAddress);
            }
        }
        return addressesToUpsert;
    }

    /**
     * Creates unique Address records
     * @param  addressesByType     All Addresses which have already been created
     * @param  address             The current Address being processed
     * @param  identifier          The current Checkbox being processed
     */
    public static void createAddress(
        Map<String, AddressDetails> addressesByType,
        Address__c address,
        String identifier
    ) {
        if (
            addressesByType.containsKey(identifier) &&
            addressesByType.get(identifier).existingAddress.lastModifiedDate > address.lastModifiedDate
        ) {
            return;
        }

        Address__c newAddress = address.clone(false, true, false, false);
        newAddress.Type__c = identifier;
        newAddress.Permanent_Home__c = identifier == 'Home';
        newAddress.Primary_Billing__c = identifier == 'Billing';
        newAddress.Primary_Delivery__c = identifier == 'Mailing';
        newAddress.Term_Time__c = identifier == 'Term time';

        AddressDetails addressDetails = new AddressDetails();
        addressDetails.existingAddress = address;
        addressDetails.newAddress = newAddress;

        addressesByType.put(identifier, addressDetails);
    }

    // Class to store details relating to the Address
    @TestVisible
    private class AddressDetails {
        public Address__c existingAddress;
        public Address__c newAddress;
    }
}