salesforce-main/src/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Formula to display student&apos;s progress in buying cycle.  Influenced by opportunities associated with student record.

Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</description>
    <formula>IF( Opportunity_Applications_Accepted__c &gt; 0, &quot;Student&quot;,
  IF( Opportunity_Applications_in_Progress__c &gt; 0, &quot;Applicant&quot;,
    IF( Opportunity_Interests_Declines__c &gt; 0, &quot;Prospect&quot;, &quot;Undeclared&quot;)))</formula>
    <inlineHelpText>Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/External_Document__c.object-meta.xml
<CustomObject>
    <label>External Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/External_Document__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>doc</fullName>
                <label>Document</label>
            </value>
            <value>
                <fullName>excel</fullName>
                <label>Excel</label>
            </value>
            <value>
                <fullName>image</fullName>
                <label>Image</label>
            </value>
            <value>
                <fullName>pdf</fullName>
                <label>PDF</label>
            </value>
            <value>
                <fullName>powerpoint</fullName>
                <label>Powerpoint</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Document ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>External Documents</relationshipLabel>
    <relationshipName>External_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventDocumentUploadedProcessorTest.cls
@isTest
public class EventDocumentUploadedProcessorTest {
    private static final String TEST_USER_ID = 'ID_123';

    @TestSetup
    static void setup() {
        Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Student_Account')
            .getRecordTypeId();

        Account account = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);
        insert account;

        insert new Hub_Account__c(
            Student__c = account.Id,
            Auth0_Id__c = TEST_USER_ID,
            Hub_Username__c = 'testuser1@bpp.com'
        );
    }

    @isTest
    static void itShouldCreateDocuments() {
        // GIVEN a queue job
        DocumentSchema eventSchema = createTestSchema();
        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Type__c = 'documentUploaded',
            Job_Content__c = JSON.serialize(eventSchema)
        );

        // WHEN the processor is run
        Test.startTest();
        EventDocumentUploadedProcessor processor = new EventDocumentUploadedProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN theres no failed jobs
        Assert.areEqual(0, processor.failedJobs.size());

        // AND the document was created
        List<External_Document__c> documents = [
            SELECT Id, Name, Document_ID__c, Content_Type__c, Version__c, Status__c, Student__c
            FROM External_Document__c
        ];
        Assert.areEqual(1, documents.size());
        Assert.areEqual(eventSchema.documentId, documents[0].Document_ID__c);
        Assert.areEqual(eventSchema.version, documents[0].Version__c);
        Assert.areEqual(eventSchema.contentType, documents[0].Content_Type__c);
        Assert.areEqual(eventSchema.documentName, documents[0].Name);
        Assert.areEqual('Uploaded', documents[0].Status__c);

        Hub_Account__c hubAccount = [SELECT Student__c FROM Hub_Account__c WHERE auth0_Id__c = :TEST_USER_ID];
        Assert.areEqual(hubAccount.Student__c, documents[0].Student__c);
    }

    @isTest
    static void itShouldUpdateDocuments() {
        // GIVEN a queue job
        DocumentSchema eventSchema = createTestSchema();
        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Type__c = 'documentUploaded',
            Job_Content__c = JSON.serialize(eventSchema)
        );

        // AND a document
        insert new External_Document__c(Document_ID__c = eventSchema.documentId);
        External_Document__c documentBefore = [
            SELECT Status__c
            FROM External_Document__c
            WHERE Document_ID__c = :eventSchema.documentId
        ];
        Assert.areNotEqual('Uploaded', documentBefore.Status__c);

        // WHEN the processor is run
        Test.startTest();
        EventDocumentUploadedProcessor processor = new EventDocumentUploadedProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN theres no failed jobs
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        // AND the document was updated
        External_Document__c documentAfter = [
            SELECT Id, Document_ID__c, Status__c
            FROM External_Document__c
            WHERE Id = :documentBefore.Id
        ];
        Assert.areEqual(eventSchema.documentId, documentAfter.Document_ID__c);
        Assert.areEqual('Uploaded', documentAfter.Status__c);
    }

    @isTest
    static void itShouldDeleteDocuments() {
        // GIVEN a queue job with a type of Deleted
        DocumentSchema eventSchema = createTestSchema();
        Queue_Job__c queueJob = new Queue_Job__c(
            Job_Type__c = 'documentDeleted',
            Job_Content__c = JSON.serialize(eventSchema)
        );

        // AND a document
        insert new External_Document__c(Document_ID__c = eventSchema.documentId);
        External_Document__c documentBefore = [
            SELECT Status__c
            FROM External_Document__c
            WHERE Document_ID__c = :eventSchema.documentId
        ];
        Assert.areNotEqual('Uploaded', documentBefore.Status__c);

        // WHEN the processor is run
        Test.startTest();
        EventDocumentUploadedProcessor processor = new EventDocumentUploadedProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });
        Test.stopTest();

        // THEN there's no failed jobs
        Assert.areEqual(0, processor.failedJobs.size(), 'Expected no failed jobs');

        // AND the document was updated to deleted
        External_Document__c documentAfter = [
            SELECT Id, Document_ID__c, Status__c
            FROM External_Document__c
            WHERE Id = :documentBefore.Id
        ];
        Assert.areEqual(eventSchema.documentId, documentAfter.Document_ID__c);
        Assert.areEqual('Deleted', documentAfter.Status__c);
    }

    private static DocumentSchema createTestSchema() {
        DocumentSchema schema = new DocumentSchema();
        schema.documentName = 'example.txt';
        schema.documentId = 'D123';
        schema.contentType = 'Document';
        schema.documentType = 'General';
        schema.authUserId = TEST_USER_ID;
        schema.version = '1';
        schema.status = 'completed';

        return schema;
    }
}