salesforce-main/src/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Formula to display student&apos;s progress in buying cycle.  Influenced by opportunities associated with student record.

Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</description>
    <formula>IF( Opportunity_Applications_Accepted__c &gt; 0, &quot;Student&quot;,
  IF( Opportunity_Applications_in_Progress__c &gt; 0, &quot;Applicant&quot;,
    IF( Opportunity_Interests_Declines__c &gt; 0, &quot;Prospect&quot;, &quot;Undeclared&quot;)))</formula>
    <inlineHelpText>Undeclared- No Opportunities
Prospect- 1+ Interests
Applicant- 1+ Applications
Student- 1+ Accepted Applications</inlineHelpText>
    <label>Status</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Detail__c/Booking_Detail__c.object-meta.xml
<CustomObject>
    <label>Booking Detail</label>
    <nameField>
        <displayFormat>BK-{0}</displayFormat>
        <label>BK#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Detail__c/fields/Legacy_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Product_Name__c</fullName>
    <description>Legacy product name from outside the CRM and product catalog.</description>
    <inlineHelpText>Legacy product name from outside the CRM and product catalog.</inlineHelpText>
    <label>Legacy Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Substituted</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/Booking_BookingServiceImpl.cls
public class Booking_BookingServiceImpl implements Booking_BookingService {
    
    public class BookingDetailException extends Exception{}
    
    private Booking_SponsorshipService sponsorshipService;
    
    private Booking_OpportunityService opportunityService;
    
    private Booking_BookingDetailService bookingDetailService;
    
    private static Integer QUANTITY = 1;
    
    public Booking_BookingServiceImpl() {
        sponsorshipService = new Booking_SponsorshipService(new Booking_AccountService());
        opportunityService = new Booking_OpportunityService(new Booking_AccountService());    
        bookingDetailService = new Booking_BookingDetailService();
    }
    
    public Opportunity createUpdateBooking(Booking_Rest_Controller.BookingDTO bookingDto) {
        Opportunity corpOpp;
        
        if((bookingDto.companyProfileId != '' && bookingDto.companyProfileId != null) && (bookingDto.orderNumber != '' && bookingDto.orderNumber != null))
        {
            Account oppAccount = Util.findCompanyAccountByProfile(bookingDto.companyProfileId);
            Opportunity tempOpp = Util.findOppByOrderNumber(oppAccount.Id,bookingDto.orderNumber);
            if(tempOpp == null)
            {
                corpOpp = opportunityService.createCorporateOpportunity(bookingDto.orderNumber, bookingDto.trainingMangerProfileId, bookingDto.companyProfileId,oppAccount.Name + '- Opp');
            }
            else 
            {  
                //SA - else corporate booking opportunity already exists
                corpOpp = tempOpp; 
            }
        }
        
        Opportunity opportunity = opportunityService.findOpportunityByOrderNumber(bookingDto.orderNumber, bookingDto.studentAccountProfileId);
        if(opportunity == null)
            opportunity = opportunityService.createOpportunity(bookingDto.orderNumber, bookingDto.studentAccountProfileId,corpOpp);
        

    // WEC: Commmented out due to Plan B effort
/*        
        if(bookingDto.companyProfileId != null) {
            sponsorshipService.createActiveSponsorship(bookingDto.studentAccountProfileId, opportunity.Id, bookingDto.companyProfileId, bookingDto.trainingMangerProfileId);
        }
 */       
        //WEC Added if no product id to support plan b. This will skip Booking Detail if there is no product ID.
        if(bookingDto.productInstanceId != '' && bookingDto.productInstanceId != null)
        {
            Booking_Detail__c bookingDetail = bookingDetailService.findBookingDetailByProductInstanceId(bookingDto.productInstanceId, opportunity.Id);
            if(bookingDetail == null)
                bookingDetail = bookingDetailService.createBookingDetail(opportunity.Id, bookingDto.productInstanceId, bookingDto.detailLineItems, Quantity, bookingDto.cost,bookingDto.legacyProductInstanceId, bookingDto.legacyProductInstanceDesc,bookingDto.bookingStatus);
        }else if (bookingDto.legacyProductInstanceId != '' && bookingDto.legacyProductInstanceId != null)
        {
            Booking_Detail__c bookingDetail = bookingDetailService.findBookingDetailByLegacyProductID(bookingDto.legacyProductInstanceId, opportunity.Id);
            if(bookingDetail == null)
                bookingDetail = bookingDetailService.createBookingDetail(opportunity.Id, bookingDto.productInstanceId, bookingDto.detailLineItems, Quantity, bookingDto.cost,bookingDto.legacyProductInstanceId, bookingDto.legacyProductInstanceDesc,bookingDto.bookingStatus);
            else
            {
                // Update booking detail status
                list<String> statusOptions = Util.getPicklistValues('Booking_Detail__c', 'Status__c');

                if(!Util.setContains(statusOptions,bookingDto.bookingStatus) && bookingDto.bookingStatus!='' && bookingDto.bookingStatus!=null)
                {
                    throw new BookingDetailException('Booking Status not a valid option. Status sent: ' + bookingDto.bookingStatus);
                        
                }else
                    bookingDetail.Status__c = bookingDto.bookingStatus;
                
                //Update Booking Detail Legacy Product Description
                bookingDetail.Legacy_Product_Name__c = bookingDto.legacyProductInstanceDesc;
                
                update bookingDetail;
            
            }
            
        }
        return opportunity;
        
    }
    
}