salesforce-main/src/main/default/objects/Account/fields/Student_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Student_Cycle__c</fullName>
    <description>Student cycle sets the default mode of contact for the particular student record.  

Pursue (default): Student is a potential purchaser of BPP products near-term.
Maintenance: Student is a potential purchaser of BPP products long-term.
No Further Action: Student is not a potential purchaser of BPP products.</description>
    <label>Student Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pursue</fullName>
                <default>true</default>
                <label>Pursue</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/BNR_Application_Decision_Code__c.field-meta.xml
<CustomField>
    <fullName>BNR_Application_Decision_Code__c</fullName>
    <label>Application Decision Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Cycle_Override__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Override__c</fullName>
    <description>Cycle override is used to set the cycle for the opportunity if it differs from the student.  By default it will select &quot;Use Student Cycle&quot;.</description>
    <label>Cycle Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Use Student Cycle</fullName>
                <default>true</default>
                <label>Use Student Cycle</label>
            </value>
            <value>
                <fullName>Pursue</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>No Further Action</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/UpdateOpportunity.cls
@RestResource(urlMapping='/v1.0/UpdateApplication/*')
global with sharing class UpdateOpportunity {
    
    global class Response {
        global String status { get; set; }
        
        public Response(String status) {
            this.status = status;
        }
    }
    
    @HttpPost
    global static Response doPost(List<Opportunity> opportunityList) {
        try {           
            update opportunityList;  
            return new Response('Success');
        } catch (Exception e) { 
            return new Response('Failure');
        }
    }
    
    @isTest
    private static void unitTest1(){
        list<Opportunity> opptyLists = new list<Opportunity>();
        Opportunity Oppty = new Opportunity();
        Oppty.StageName = 'Application Submitted';
        opptyLists.add(Oppty);
        UpdateOpportunity.Response res = UpdateOpportunity.doPost(opptyLists);  
    }
    @isTest
    private static void unitTest2(){    
        list<Opportunity> opptyLists = new list<Opportunity>();
        Account a = new Account();
        a.firstname='John';
        a.lastname='Coppedge';
        a.Salutation = 'Mr';
        a.Middle_Name__pc = 'Mex';
        a.Gender__pc = 'Male';
        a.RecordTypeId=Schema.sObjectType.Account.getRecordTypeInfosByName().get('Student Account').getRecordTypeId();
        a.Preferred_Email__pc = 'Personal';
        a.Preferred_Phone__pc = 'Mobile';
        a.Personal_Email__pc ='john@john.com';
        a.PersonMobilePhone='8015555556';
        a.PersonBirthdate=Date.valueOf('1986-02-27');
        a.PS_Profile_Services_ID__pc = '1234f567-bc23-42e8-924c-1234asdf5678';
        a.Student_Cycle__c = 'Pursue';
        a.Student_Type__pc = 'Domestic';
        insert a;
        
        Opportunity Oppty = new Opportunity();
        oppty.AccountId = a.id;
        oppty.Name = 'test';
        oppty.Cycle_Override__c = 'Use Student Cycle';
        oppty.CloseDate = Date.valueOf('2015-02-27');      
        oppty.StageName = 'Review';
        oppty.BNR_Application_Decision_Code__c = 'test';
        insert oppty;
        opptyLists.add(Oppty);
        UpdateOpportunity.Response res = UpdateOpportunity.doPost(opptyLists);   
    }     
}