salesforce-main/src/main/default/objects/External_Document__c/External_Document__c.object-meta.xml
<CustomObject>
    <label>External Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/External_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Document ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>External Documents</relationshipLabel>
    <relationshipName>External_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION_HISTORY</fullName>
                <label>Education History</label>
            </value>
            <value>
                <fullName>GENERAL</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>Name Changed</fullName>
            </value>
            <value>
                <fullName>Application Pack</fullName>
            </value>
            <value>
                <fullName>letter</fullName>
                <label>Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventAppPackProcessor.cls
/**
 * Processor for the app pack generation event
 */
public without sharing class EventAppPackProcessor extends BaseProcessor {
    /**
     * Map of applicationId to queue job
     */
    private Map<String, Queue_Job__c> applicationToQueue = new Map<String, Queue_Job__c>();

    /**
     * List of documents that need to be upserted
     */
    private List<External_Document__c> documentsToUpsert = new List<External_Document__c>();

    /**
     * List of events that need to be processed
     */
    private List<AppPackSchema> events = new List<AppPackSchema>();

    /**
     * Processes the given queue jobs and creates documents
     * @param queueJobs Queue jobs to process
     */
    public void processImpl(List<Queue_Job__c> queueJobs) {
        deserializeEvents(queueJobs);

        for (AppPackSchema event : events) {
            External_Document__c appPackDocument = new External_Document__c(
                Document_ID__c = event.appPackDocumentId,
                Type__c = 'Application Pack',
                Opportunity__r = new Opportunity(Application_Id__c = event.applicationId)
            );

            documentsToUpsert.add(appPackDocument);
        }

        processDML();
    }

    /**
     * Deserializes the event content and checks required fields
     * @param queueJobs List of queue jobs
     */
    private void deserializeEvents(List<Queue_Job__c> queueJobs) {
        for (Queue_Job__c job : queueJobs) {
            AppPackSchema event = (AppPackSchema) JSON.deserialize(job.Job_Content__c, AppPackSchema.class);

            Map<String, String> requiredFields = new Map<String, String>{
                'Application Id' => event?.applicationId,
                'App pack document Id' => event?.appPackDocumentId
            };

            List<String> requiredFieldErrors = new List<String>();
            for (String potentialError : requiredFields.keySet()) {
                if (String.isBlank(requiredFields.get(potentialError))) {
                    requiredFieldErrors.add(potentialError);
                }
            }

            if (!requiredFieldErrors.isEmpty()) {
                failedJobs.put(
                    job,
                    'Required value(s) ' + String.join(requiredFieldErrors, ', ') + ' are null in event payload'
                );
                continue;
            }

            applicationToQueue.put(event.applicationId, job);
            events.add(event);
        }
    }

    /**
     * Processes the DML
     */
    private void processDML() {
        List<Database.UpsertResult> docResults = Database.Upsert(
            documentsToUpsert,
            External_Document__c.Document_ID__c.getDescribe().getSObjectField(),
            false
        );
        for (Integer i = 0; i < docResults.size(); i++) {
            Database.UpsertResult result = docResults[i];
            if (!result.isSuccess()) {
                String applicationId = documentsToUpsert[i].Opportunity__r.Application_Id__c;
                processDMLErrors(applicationToQueue.get(applicationId), result.getErrors());
                applicationToQueue.remove(applicationId);
            }
        }

        for (String applicationId : applicationToQueue.keySet()) {
            successfulJobs.add(applicationToQueue.get(applicationId));
        }
    }
}