salesforce-main/src/main/default/objects/External_Document__c/External_Document__c.object-meta.xml
<CustomObject>
    <label>External Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/External_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Document ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/DocumentServiceDownloadCalloutTest.cls
@isTest
public class DocumentServiceDownloadCalloutTest {
    private static List<DocumentServiceDownloadCallout.FlowOutput> callGetDocumentUrl(External_Document__c document) {
        List<List<External_Document__c>> documents = new List<List<External_Document__c>>{
            new List<External_Document__c>{ document }
        };
        List<DocumentServiceDownloadCallout.FlowOutput> flowResults = DocumentServiceDownloadCallout.getDocumentUrl(
            documents
        );
        return flowResults;
    }

    private static List<DocumentServiceCalloutResult> assertCheck(
        List<DocumentServiceDownloadCallout.FlowOutput> flowResults,
        External_Document__c document
    ) {
        // THEN there should be a single option returned
        Assert.areEqual(1, flowResults.size(), 'Single option returned.');

        // AND there should have been a single document processed
        List<DocumentServiceCalloutResult> documentResults = flowResults[0].documentResults;
        Assert.areEqual(1, documentResults.size(), 'Single document processed.');

        // AND the document Id and URL should be what we expect
        Assert.areEqual(
            document.Id,
            documentResults[0].documentId,
            'documentId should match created External Document Id.'
        );
        return documentResults;
    }

    @isTest
    private static void itShouldReturnAUrl() {
        TestUtilities.mockKillswitch(Killswitch.DOCUMENT_SERVICE_KILLSWITCH, false);

        // GIVEN a document
        External_Document__c document = new External_Document__c(
            Document_ID__c = 'D-123',
            User_ID__c = 'auth|123',
            Status__c = 'Uploaded'
        );
        insert document;

        String preSignedUrl = 'salesforce.test.com';

        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200, '{"data":{"getPresignedDownloadUrl":{"preSignedUrl":"' + preSignedUrl + '"}}}');

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        // WHEN getDocumentUrl is called
        List<DocumentServiceDownloadCallout.FlowOutput> flowResults = callGetDocumentUrl(document);
        Test.stopTest();

        List<DocumentServiceCalloutResult> documentResults = assertCheck(flowResults, document);
        Assert.areEqual(preSignedUrl, documentResults[0].responseURL, 'responseURL should match preSignedURL.');
    }

    @isTest
    private static void itShouldHandleErrorResponse() {
        TestUtilities.mockKillswitch(Killswitch.DOCUMENT_SERVICE_KILLSWITCH, false);

        // GIVEN a document
        External_Document__c document = new External_Document__c(
            Document_ID__c = 'D-123',
            User_ID__c = 'auth|123',
            Status__c = 'Uploaded'
        );
        insert document;

        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 500);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mock);
        // WHEN getDocumentUrl is called
        List<DocumentServiceDownloadCallout.FlowOutput> flowResults = callGetDocumentUrl(document);
        Test.stopTest();

        List<DocumentServiceCalloutResult> documentResults = assertCheck(flowResults, document);
        Assert.isNull(documentResults[0].responseURL, 'responseURL should be null.');
    }
}