salesforce-main/src/main/default/objects/External_Document__c/External_Document__c.object-meta.xml
<CustomObject>
    <label>External Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/External_Document__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>doc</fullName>
                <label>Document</label>
            </value>
            <value>
                <fullName>excel</fullName>
                <label>Excel</label>
            </value>
            <value>
                <fullName>image</fullName>
                <label>Image</label>
            </value>
            <value>
                <fullName>pdf</fullName>
                <label>PDF</label>
            </value>
            <value>
                <fullName>powerpoint</fullName>
                <label>Powerpoint</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Document ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>External Documents</relationshipLabel>
    <relationshipName>External_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION_HISTORY</fullName>
                <label>Education History</label>
            </value>
            <value>
                <fullName>GENERAL</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>Name Changed</fullName>
            </value>
            <value>
                <fullName>Application Pack</fullName>
            </value>
            <value>
                <fullName>letter</fullName>
                <label>Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Auth0_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_Id__c</fullName>
    <externalId>true</externalId>
    <label>Auth0 Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Student Account associated with the Hub Account</description>
    <label>Student</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account record has not been associated with a student</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hub Accounts</relationshipLabel>
    <relationshipName>Hub_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventDocumentUploadedProcessor.cls
public class EventDocumentUploadedProcessor extends BaseProcessor {
    private static final Map<String, String> STATUS_MAPPING = new Map<String, String>{
        'pendingUpload' => 'Pending',
        'uploaded' => 'Pending',
        'pendingScan' => 'Pending',
        'completed' => 'Uploaded',
        'failed' => 'Failed',
        'documentDeleted' => 'Deleted'
    };

    /**
     * deserialize event payload and upsert records
     * @param  queueJobs queueJobs to process
     */
    public void processImpl(List<Queue_Job__c> queueJobs) {
        Map<String, JobDetails> documentIdToDetails = new Map<String, JobDetails>();
        List<String> userIds = new List<String>();

        for (Queue_Job__c queueJob : queueJobs) {
            DocumentSchema event = (DocumentSchema) JSON.deserialize(queueJob.Job_Content__c, DocumentSchema.class);

            if (event.documentId == null) {
                failedJobs.put(queueJob, 'Required value(s) Document ID are null in event payload');
                continue;
            }

            String calculatedStatus = queueJob.Job_Type__c == 'documentDeleted' ? queueJob.Job_Type__c : event.status;

            if (!STATUS_MAPPING.containsKey(calculatedStatus)) {
                failedJobs.put(queueJob, 'Invalid status provided.');
                continue;
            }

            userIds.add(event.authUserId);

            // de-dupe
            if (documentIdToDetails.containsKey(event.documentId)) {
                JobDetails jobDetails = documentIdToDetails.get(event.documentId);
                successfulJobs.add(jobDetails.queueJob);
            }

            documentIdToDetails.put(event.documentId, new JobDetails(queueJob, event, calculatedStatus));
        }

        Map<String, Id> authIdToHubAccount = new Map<String, Id>();
        for (Hub_Account__c hubAccount : [
            SELECT Id, Auth0_Id__c, Student__c
            FROM Hub_Account__c
            WHERE Auth0_Id__c IN :userIds
        ]) {
            authIdToHubAccount.put(hubAccount.Auth0_Id__c, hubAccount.Student__c);
        }

        Map<String, External_Document__c> documentsToUpdate = new Map<String, External_Document__c>();
        for (JobDetails jobDetail : documentIdToDetails.values()) {
            External_Document__c docToUpdate = new External_Document__c(
                Name = jobDetail.event.documentName,
                Status__c = jobDetail.status,
                Content_Type__c = jobDetail.event.contentType,
                Document_ID__c = jobDetail.event.documentId,
                Version__c = jobDetail.event.version,
                User_ID__c = jobDetail.event.authUserId
            );

            if (authIdToHubAccount.containsKey(jobDetail.event.authUserId)) {
                docToUpdate.Student__c = authIdToHubAccount.get(jobDetail.event.authUserId);
            }

            if (!Killswitch.isEnabled(Killswitch.JOIN2_DOC_KILLSWITCH)) {
                docToUpdate.Type__c = jobDetail.event.documentType;
                docToUpdate.Category__c = jobDetail.event.documentCategory;
            }

            documentsToUpdate.put(jobDetail.event.documentId, docToUpdate);
        }

        List<Database.UpsertResult> upsertResult = Database.Upsert(
            documentsToUpdate.values(),
            External_Document__c.Document_ID__c.getDescribe().getSObjectField(),
            false
        );

        for (Integer i = 0; i < upsertResult.size(); i++) {
            Database.UpsertResult result = upsertResult[i];

            String documentId = documentsToUpdate.values()[i].Document_ID__c;
            Queue_Job__c queueJob = documentIdToDetails.get(documentId).queueJob;

            if (!result.isSuccess()) {
                processDMLErrors(queueJob, result.getErrors());
                continue;
            }

            successfulJobs.add(queueJob);
        }
    }

    private class JobDetails {
        public Queue_Job__c queueJob;
        public DocumentSchema event;
        public String status;

        public JobDetails(Queue_Job__c queueJob, DocumentSchema event, String status) {
            this.queueJob = queueJob;
            this.event = event;
            this.status = STATUS_MAPPING.get(status);
        }
    }
}