salesforce-main/src/main/default/objects/External_Document__c/External_Document__c.object-meta.xml
<CustomObject>
    <label>External Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/External_Document__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <externalId>true</externalId>
    <label>Document ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>External Documents</relationshipLabel>
    <relationshipName>External_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/External_Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EDUCATION_HISTORY</fullName>
                <label>Education History</label>
            </value>
            <value>
                <fullName>GENERAL</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>Name Changed</fullName>
            </value>
            <value>
                <fullName>Application Pack</fullName>
            </value>
            <value>
                <fullName>letter</fullName>
                <label>Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Application_ID__c</fullName>
    <description>Application ID from event</description>
    <externalId>true</externalId>
    <label>Application ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Related Opportunities</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/queueJobs/processors/EventAppPackProcessorTest.cls
@isTest
private class EventAppPackProcessorTest {
    static Id accountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Student_Account')
        .getRecordTypeId();

    @TestSetup
    private static void setUp() {
        Account acc = new Account(FirstName = 'Test', LastName = 'Test', RecordTypeId = accountRecordTypeId);

        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Test-Opp',
            Application_Id__c = 'test-123',
            AccountId = acc.Id,
            StageName = 'Application',
            CloseDate = Date.today()
        );

        insert opp;

        External_Document__c existingDoc = new External_Document__c(
            Document_ID__c = 'test-existing-doc',
            Type__c = 'Application Pack',
            Opportunity__c = opp.Id
        );

        insert existingDoc;
    }

    @isTest
    private static void itShouldCreateAnAppPackDocument() {
        AppPackSchema schema = new AppPackSchema();
        schema.applicationId = 'test-123';
        schema.appPackDocumentId = 'new-id-doc';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(schema));

        EventAppPackProcessor processor = new EventAppPackProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        List<External_Document__c> docsOut = [
            SELECT Opportunity__r.Application_Id__c
            FROM External_Document__c
            WHERE Document_ID__c = 'new-id-doc'
        ];

        Assert.areEqual(1, docsOut.size(), 'I expect one document to be created');
        Assert.areEqual(
            'test-123',
            docsOut[0].Opportunity__r.Application_Id__c,
            'I expect the document to be attached to opp'
        );
    }

    @isTest
    private static void itShouldNotCreateDuplicates() {
        AppPackSchema schema = new AppPackSchema();
        schema.applicationId = 'test-123';
        schema.appPackDocumentId = 'test-existing-doc';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(schema));

        EventAppPackProcessor processor = new EventAppPackProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        List<External_Document__c> docsOut = [
            SELECT Opportunity__r.Application_Id__c
            FROM External_Document__c
            WHERE Opportunity__r.Application_Id__c = 'test-123'
        ];

        Assert.areEqual(1, docsOut.size(), 'I expect it to skip creating this document as it already exists');
    }

    @isTest
    private static void itShouldFailOnRequiredFields() {
        AppPackSchema schema = new AppPackSchema();
        schema.applicationId = 'test-123';

        Queue_Job__c queueJob = new Queue_Job__c(Job_Content__c = JSON.serialize(schema));

        EventAppPackProcessor processor = new EventAppPackProcessor();
        processor.processImpl(new List<Queue_Job__c>{ queueJob });

        Assert.areEqual(1, processor.failedJobs.size(), 'I expect the job to fail due to missing required fields');
    }
}