salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of this Instance</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/fields/Instance_ID__c.field-meta.xml
<CustomField>
    <fullName>Instance_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Product Factory ID for this course</description>
    <externalId>true</externalId>
    <label>Product Factory Instance ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location this Instance will be sat</description>
    <label>Default Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abingdon</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Cambridge</fullName>
            </value>
            <value>
                <fullName>Doncaster</fullName>
            </value>
            <value>
                <fullName>Guernsey</fullName>
            </value>
            <value>
                <fullName>Jersey</fullName>
            </value>
            <value>
                <fullName>Leeds</fullName>
            </value>
            <value>
                <fullName>London City</fullName>
            </value>
            <value>
                <fullName>London Holborn</fullName>
            </value>
            <value>
                <fullName>London King&apos;s Cross</fullName>
            </value>
            <value>
                <fullName>London Liverpool Street</fullName>
            </value>
            <value>
                <fullName>London Shepherd&apos;s Bush</fullName>
            </value>
            <value>
                <fullName>London Waterloo</fullName>
            </value>
            <value>
                <fullName>Maidstone</fullName>
            </value>
            <value>
                <fullName>Manchester</fullName>
            </value>
            <value>
                <fullName>Milton Keynes</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Nottingham</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>Southampton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product related to this Instance</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Instances</relationshipLabel>
    <relationshipName>Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start date of this course</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/recordTypes/Instance.recordType-meta.xml
<RecordType>
    <fullName>Instance</fullName>
    <active>true</active>
    <label>Instance</label>
</RecordType>

salesforce-main/src/main/default/objects/Mode__c/Mode__c.object-meta.xml
<CustomObject>
    <description>List of study modes</description>
    <label>Mode</label>
    <nameField>
        <label>Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/outboundEvents/serializers/ProductSyncTest.cls
@isTest
private class ProductSyncTest {
    @TestSetup
    private static void setup() {
        Programme__c programme = new Programme__c(Name = 'Test1Programme', Programme_Id__c = 'test-123');

        insert programme;

        Product2 product = new Product2(
            Name = 'TestCourse',
            BPP_ProductFactoryID__c = 'test-123',
            Programme__c = programme.Id,
            Mode__c = 'Part Time Distance Learning',
            Location__c = 'London - Waterloo',
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addDays(365),
            Eligible_For_Automated_Holiday_Letter__c = true
        );

        insert product;
    }

    @isTest
    private static void itShouldSendFromAProduct() {
        StreamingService.canFetchStreams = true;

        Programme__c programme = [SELECT Id FROM Programme__c WHERE Name = 'Test1Programme'];

        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        // GIVEN We insert a new product
        // WHEN the trigger runs
        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        Product2 product = new Product2(
            Name = 'Test University Product',
            Programme__c = programme.Id,
            Instance_Id__c = 'test-321',
            Mode__c = 'Online',
            Location__c = 'London - Southgate',
            Start_Date__c = Date.today().addDays(10),
            End_Date__c = Date.today().addDays(375),
            Eligible_For_Automated_Holiday_Letter__c = true
        );

        insert product;

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect a product sync event
        Assert.areEqual(1, mock.processedRequests);
    }

    @isTest
    private static void itShouldSendFromProgrammeUpdate() {
        StreamingService.canFetchStreams = true;

        Programme__c programme = new Programme__c(Name = 'Test1Programme', Programme_Id__c = 'test-123');
        insert programme;

        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'TestCourse'];
        product.programme__c = programme.Id;

        update product;

        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        // GIVEN We insert a new programme
        // WHEN the trigger runs
        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        //WHEN we update programme
        programme.Name = 'Updated Programme';
        update programme;

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect a product sync event
        Assert.areEqual(1, mock.processedRequests);
    }

    @isTest
    private static void itShouldSendFromTermDateUpdate() {
        StreamingService.canFetchStreams = true;

        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'TestCourse'];

        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        Term_Date__c termDate = new Term_Date__c(Start_Date__c = Date.today(), End_Date__c = Date.today().addDays(10));
        termDate.Product__c = product.Id;

        insert termDate;

        // GIVEN We insert a new TermDate
        // WHEN the trigger runs
        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        //WHEN we update term date
        termDate.Start_Date__c = Date.today().addDays(1);

        update termDate;

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect a product sync event
        Assert.areEqual(1, mock.processedRequests);
    }

    @isTest
    private static void itShouldSendFromAnInstance() {
        StreamingService.canFetchStreams = true;

        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'TestCourse'];

        MockHttpClient mock = new MockHttpClient();
        mock.addResponse('@', 200);

        // Disable outbound events killswitch by default
        TestUtilities.mockKillswitch(killswitch.BLOCK_OUTBOUND_EVENTS, false);

        // GIVEN we insert a new instance
        // WHEN the trigger runs
        System.Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, mock);

        Instance__c instance = new Instance__c(Product__c = product.Id, Instance_ID__c = 'test-123');

        insert instance;

        System.Test.getEventBus().deliver();
        System.Test.stopTest();

        // THEN I expect a product sync event
        Assert.areEqual(1, mock.processedRequests);
    }
}