salesforce-main/src/main/default/objects/Campaign/fields/Billboard_Postcodes__c.field-meta.xml
<CustomField>
    <fullName>Billboard_Postcodes__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Billboard Postcodes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Campaign_Member_Source__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Source__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Campaign Member Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Existing Leads</fullName>
            </value>
            <value>
                <fullName>Existing Contacts - Non Members</fullName>
            </value>
            <value>
                <fullName>Existing Contacts - Members</fullName>
            </value>
            <value>
                <fullName>List - One off</fullName>
            </value>
            <value>
                <fullName>List - Longer Term</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Delivery_Day__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Day__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Delivery Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Time__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Delivery Time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Design_Costs__c.field-meta.xml
<CustomField>
    <fullName>Design_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Design Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Display_Costs__c.field-meta.xml
<CustomField>
    <fullName>Display_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Display Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Distribution_Costs__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Distribution Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Email_Template_Used__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Used__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Email Template Used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/End_of_Use_Date__c.field-meta.xml
<CustomField>
    <fullName>End_of_Use_Date__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>End of Use Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Fax_Costs__c.field-meta.xml
<CustomField>
    <fullName>Fax_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Fax Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Handling_Costs__c.field-meta.xml
<CustomField>
    <fullName>Handling_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Handling Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/List_Costs__c.field-meta.xml
<CustomField>
    <fullName>List_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>List Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to campus that the event will be held at.</description>
    <label>Location</label>
    <referenceTo>Campus__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Print_Costs__c.field-meta.xml
<CustomField>
    <fullName>Print_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Print Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link the programme that the event is promoting.</description>
    <label>Programme</label>
    <referenceTo>Programme__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Publication__c.field-meta.xml
<CustomField>
    <fullName>Publication__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Publication</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>124 Law</fullName>
            </value>
            <value>
                <fullName>Accountancy</fullName>
            </value>
            <value>
                <fullName>Accountancy Age</fullName>
            </value>
            <value>
                <fullName>Accounting &amp; Business</fullName>
            </value>
            <value>
                <fullName>AWS Link</fullName>
            </value>
            <value>
                <fullName>Best Practice</fullName>
            </value>
            <value>
                <fullName>CFA Magazine</fullName>
            </value>
            <value>
                <fullName>City AM</fullName>
            </value>
            <value>
                <fullName>CLC Chronicle</fullName>
            </value>
            <value>
                <fullName>Constabulary</fullName>
            </value>
            <value>
                <fullName>Corporate Financier</fullName>
            </value>
            <value>
                <fullName>Counsel</fullName>
            </value>
            <value>
                <fullName>Epoch Times</fullName>
            </value>
            <value>
                <fullName>Finance Director</fullName>
            </value>
            <value>
                <fullName>Financial Management</fullName>
            </value>
            <value>
                <fullName>Financial News</fullName>
            </value>
            <value>
                <fullName>Financial Times</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>India Times</fullName>
            </value>
            <value>
                <fullName>In-House Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Society Gazette</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Legal Week</fullName>
            </value>
            <value>
                <fullName>Muslim Weekly</fullName>
            </value>
            <value>
                <fullName>NQ Magazine</fullName>
            </value>
            <value>
                <fullName>PASS</fullName>
            </value>
            <value>
                <fullName>Police Life</fullName>
            </value>
            <value>
                <fullName>Police Review</fullName>
            </value>
            <value>
                <fullName>PQ Magazine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/SMS_Costs__c.field-meta.xml
<CustomField>
    <fullName>SMS_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>SMS Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Staging_PK__c.field-meta.xml
<CustomField>
    <fullName>Staging_PK__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11

Staging ID was once used as part of a nightly process to push in data from external systems.

This process was disabled and subsequently these fields have been removed on other objects.</description>
    <externalId>true</externalId>
    <label>[REMOVE] Staging PK</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start time of the event (e.g. open day).  Required for some events and used to populate email templates.</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Target_Group__c.field-meta.xml
<CustomField>
    <fullName>Target_Group__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Target Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Random</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Targeted_Faculty__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Faculty__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Targeted Faculty</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A&amp;T</fullName>
            </value>
            <value>
                <fullName>FS</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>LM</fullName>
            </value>
            <value>
                <fullName>PD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Web_Costs__c.field-meta.xml
<CustomField>
    <fullName>Web_Costs__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Web Costs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Website</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T&amp;C</fullName>
            </value>
            <value>
                <fullName>www.accaglobal.com</fullName>
            </value>
            <value>
                <fullName>www.accountancyage.com</fullName>
            </value>
            <value>
                <fullName>www.cfainstitute.org</fullName>
            </value>
            <value>
                <fullName>www.cimaglobal.com</fullName>
            </value>
            <value>
                <fullName>www.icaew.co.uk</fullName>
            </value>
            <value>
                <fullName>www.passmagazine.com</fullName>
            </value>
            <value>
                <fullName>www.sii.org.uk</fullName>
            </value>
            <value>
                <fullName>www.sourcethecourse.com</fullName>
            </value>
            <value>
                <fullName>www.taxationweb.com</fullName>
            </value>
            <value>
                <fullName>www.thelawyer.com</fullName>
            </value>
            <value>
                <fullName>www.thesolicitorsgroup.co.uk</fullName>
            </value>
            <value>
                <fullName>www.thisislondon.co.uk</fullName>
            </value>
            <value>
                <fullName>www.timeslondon.co.uk</fullName>
            </value>
            <value>
                <fullName>www.tsg.org</fullName>
            </value>
            <value>
                <fullName>www.uksip.org</fullName>
            </value>
            <value>
                <fullName>www.waterlow.com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Campaign/fields/Workplace_Company__c.field-meta.xml
<CustomField>
    <fullName>Workplace_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[BD] Predates Apollo Salesforce team.  5/11/11</description>
    <label>Workplace Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaign</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/eventsCallout_AC.cls
public class eventsCallout_AC {
/*
this class forwards data to a soap callout

Chris Roberts

v0.1 Aug, 09, 2011
*/
 //this is the class method constructor 
 public eventsCallout_AC() {
  
 }

 // do the call out
 @Future(callout=true)
 public static void SendTo(List <string> theids) {
    
     //  do select here to create the data to pass to the callout     
     list <campaign> Campaigns = [SELECT Id, Name, Location__r.Name,  Programme__r.Name, IsDeleted, 
     ParentId, Type, RecordTypeId, Status, StartDate, 
     EndDate, ExpectedRevenue, BudgetedCost, ActualCost, ExpectedResponse, NumberSent, IsActive, 
     Description, NumberOfLeads, NumberOfConvertedLeads, NumberOfContacts, NumberOfResponses, 
     NumberOfOpportunities, NumberOfWonOpportunities, AmountAllOpportunities, AmountWonOpportunities, 
     OwnerId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
     LastActivityDate, CampaignMemberRecordTypeId, Start_Time__c, Target_Group__c, Staging_PK__c, 
     Targeted_Faculty__c, Publication__c, Website__c, Billboard_Postcodes__c, Workplace_Company__c, 
     Delivery_Day__c, Delivery_Time__c, Email_Template_Used__c, End_of_Use_Date__c, Campaign_Member_Source__c, 
     Print_Costs__c, Handling_Costs__c, List_Costs__c, Display_Costs__c, Distribution_Costs__c, 
     Design_Costs__c, Web_Costs__c, Fax_Costs__c, SMS_Costs__c, Telemarketing_Costs__c, 
     Trade_Show_Seminar_Costs__c, Total_Costs__c, Email_Fulfilment_Costs__c, Advertising_Costs__c, 
     End_Time__c, Location__c, Location_Address__c, CNID__c, Programme__c, Level__c, School__c 
     FROM Campaign WHERE id in:theids AND RecordType.Name = 'event'];  
                
     for(Campaign CampaignRec : Campaigns ) {   
         String eventId = CampaignRec.Id;
         String eventName = CampaignRec.name; 
         String eventDescription='None';
         
         if (CampaignRec.Description != Null && CampaignRec.Description != ''){
             eventDescription= CampaignRec.Description;
         }
         String eventType = CampaignRec.type;
         String eventProductLevel = CampaignRec.Programme__r.Name;  
         String eventQualification;
         String eventSchool = CampaignRec.School__c;
         string eventMaxCapacity ='0'; // not in sfdc
         string eventCurrentCapacity= '0';// not in sfdc
         //format('yyyy-MM-dd hh:mm.ss');
         string evemtDate ='2001-01-01';
         string evemtTime ='00:00:00';
         string evemtDuration= '01:00:00';
         if (CampaignRec.Start_Time__c !=Null){
             evemtDate = datetime.valueof(CampaignRec.Start_Time__c).format('yyyy-MM-dd') ;       
             evemtTime = datetime.valueof(CampaignRec.Start_Time__c).format('hh:mm:ss');
             // calculate duration
             if( CampaignRec.End_Time__c !=Null){
                 long dur = (CampaignRec.End_Time__c.getTime() - CampaignRec.Start_Time__c.getTime()) ;      
                 evemtDuration = datetime.newInstance(dur).format('hh:mm:ss');
             }
         } 
         
         String evemtLocation = CampaignRec.Location__r.Name;
         String evemtSubLocation = CampaignRec.Location_Address__c;
         //  define the result type
         ApolloglobalComEvents2.EventSOAP callit = new ApolloglobalComEvents2.EventSOAP();
         ApolloglobalComEvents2.Response coResult = callit.AddEvent(eventId,eventName,eventDescription,eventType,eventProductLevel,eventQualification,eventSchool,eventMaxCapacity,eventCurrentCapacity,evemtDate,evemtTime,evemtDuration,evemtLocation, evemtSubLocation);
         System.debug(logginglevel.INFO, '*************** Result message *************** '+coResult.Message+' '+coResult.StatusCode);
 
     }
 } 
 
 //test method(s)
 static testMethod  void EventsCallount_AC_Test1() {   
    User acct = [SELECT Id from User limit 1];
    list<string> testmap = new list<string>();
    testmap.add(acct.id);
    test.starttest();
        //test related classes by creating instances
        eventsCallout_AC evc = new eventsCallout_AC();   
        ApolloglobalComEvents2.Event te = new ApolloglobalComEvents2.Event();
        ApolloglobalComEvents2.Response tr = new ApolloglobalComEvents2.Response();
        ApolloglobalComEvents2.EventSOAP ct = new ApolloglobalComEvents2.EventSOAP();
        SendTo(testmap);
        // ApolloglobalComEvents2.EventSOAP callit = new ApolloglobalComEvents2.EventSOAP();
        // ApolloglobalComEvents2.Response coResult = callit.AddEvent('a','b','c','d','e','f','g',1,1,Date.today(),datetime.now(),datetime.now(),'','');
    test.stoptest();
 } 
  
}