salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this booking.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student that will be attending this booking</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <formula>TEXT(Product__r.Qualification__c)</formula>
    <label>Qualification</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/classes/StudentCoursesBatch.cls
/**
 * Batch job to create Student Courses from existing Booking objects
 */
global class StudentCoursesBatch implements Database.Batchable<SObject> {
    /**
     * Queries all bookings where status is confirmed
     * @param bc BatchableContext
     * @return  Database QueryLocator
     */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT Id, Student__c, Instance__r.Qualification__c
                FROM Booking__c
                WHERE
                    Status__c = 'Confirmed'
                    AND RecordTypeId = :Schema.SObjectType.Booking__c.getRecordTypeInfosByName()
                        .get('Booking')
                        .getRecordTypeId()
                    AND Instance__c != NULL
                    AND Student__c != NULL
            ]
        );
    }

    /**
     * Creates student courses where they do not already exist
     * @param bc Batchable Context
     * @param bookings List of bookings
     */
    public void execute(Database.BatchableContext bc, List<Booking__c> bookings) {
        StreamingService.preventStream = true;

        Set<String> uniqueQualification = new Set<String>();
        Set<Id> createdBookings = new Set<Id>();
        Set<Id> studentIds = new Set<Id>();

        for (Booking__c booking : bookings) {
            studentIds.add(booking.Student__c);
        }

        for (Student_Course__c course : [
            SELECT Booking__c, Student__c, Qualification__c
            FROM Student_Course__c
            WHERE Student__c IN :studentIds
        ]) {
            createdBookings.add(course.Booking__c);
            uniqueQualification.add(course.Student__c + course.Qualification__c);
        }

        List<Student_Course__c> toInsert = new List<Student_Course__c>();

        for (Booking__c booking : bookings) {
            String compoundKey = booking.Student__c + booking.Instance__r.Qualification__c;

            if (createdBookings.contains(booking.Id) || uniqueQualification.contains(compoundKey)) {
                continue;
            }

            uniqueQualification.add(compoundKey);
            toInsert.add(new Student_Course__c(Student__c = booking.Student__c, Booking__c = booking.Id));
        }

        if (!toInsert.isEmpty()) {
            insert toInsert;
        }
    }

    public void finish(Database.BatchableContext bc) {
    }
}