salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/BookedAPI__c.field-meta.xml
<CustomField>
    <fullName>BookedAPI__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This gets checked when an API call is made to hub</description>
    <label>BookedAPI</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Hub_Account__c.field-meta.xml
<CustomField>
    <fullName>Hub_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student&apos;s Hub account that will be provisioned against this booking</description>
    <label>Hub Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Hub account is not associated with the student on the booking</errorMessage>
        <filterItems>
            <field>Hub_Account__c.Student__c</field>
            <operation>equals</operation>
            <valueField>$Source.Student__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hub_Account__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/recordTypes/Booking.recordType-meta.xml
<RecordType>
    <fullName>Booking</fullName>
    <active>true</active>
    <label>Booking</label>
</RecordType>

salesforce-main/src/main/default/objects/Hub_Account__c/Hub_Account__c.object-meta.xml
<CustomObject>
    <description>Hub accounts associated with the student account</description>
    <label>Hub Account</label>
    <nameField>
        <displayFormat>HUB-{0000000}</displayFormat>
        <label>Hub Account Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Hub_Account__c/fields/Hub_Username__c.field-meta.xml
<CustomField>
    <fullName>Hub_Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address registered as the Hub username</description>
    <inlineHelpText>Email address</inlineHelpText>
    <label>Hub Username</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Instance__c/fields/Instance_ID__c.field-meta.xml
<CustomField>
    <fullName>Instance_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Product Factory ID for this course</description>
    <externalId>true</externalId>
    <label>Product Factory Instance ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce-main/src/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL - {00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/AWSsampleAPIcallCancelled.cls
public with sharing class AWSsampleAPIcallCancelled {
    public static HttpCalloutMock mock = null;

    @future(callout=true)
    public static void awsBookingCancelledCallout(Set<Id> bookingIds) {
        if (bookingIds.isEmpty()) {
            return;
        }

        List<Booking__c> bookingListToUpdate = new List<Booking__c>();
        List<Integration_Log__c> integrationListToInsert = new List<Integration_Log__c>();

        AWSsampleAPIUtil.AuthToken at = AWSsampleAPIUtil.getAccessToken();

        List<Booking__c> bookingList = [
            SELECT Id, Instance__r.Instance_ID__c, Hub_Account__r.Hub_Username__c
            FROM Booking__c
            WHERE Id = :bookingIds AND Instance__r.Instance_ID__c != NULL AND Hub_Account__r.Hub_Username__c != NULL
        ];
        for (Booking__c booking : bookingList) {
            String message = constructMessage(booking);

            String endpoint =
                AWSsampleAPIUtil.retrieveAWSEndpoint() +
                '/booking/cancelled?message=' +
                EncodingUtil.urlEncode(message, 'UTF-8');

            HttpRequest httpRequest = new HttpRequest();
            httpRequest.setMethod('POST');
            httpRequest.setEndpoint(endpoint);
            httpRequest.setHeader('Authorization', 'Bearer ' + at.token);

            Integration_Log__c integ = new Integration_Log__c();
            String response;

            try {
                HttpResponse httpResponse = new Http().send(httpRequest);
                response = httpResponse.getStatusCode() + ': ' + httpResponse.getBody();
                if (httpResponse.getStatusCode() == 200) {
                    booking.BookedAPI__c = false;
                    bookingListToUpdate.add(booking);
                }
                integ = AWSsampleAPIUtil.createIntegrationLog('HUB', endpoint, response, booking.Id);
                integrationListToInsert.add(integ);
            } catch (System.Exception e) {
                response += ' : ' + String.valueOf(e.getMessage());
                integ = AWSsampleAPIUtil.createIntegrationLog('HUB', endpoint, response, booking.Id);
                integrationListToInsert.add(integ);
            }
        }
        if (integrationListToInsert.size() > 0) {
            insert integrationListToInsert;
        }
        if (bookingListToUpdate.size() > 0) {
            update bookingListToUpdate;
        }
        if (!at.valid) {
            update at.authToken;
        }
    }

    private static String constructMessage(Booking__c booking) {
        return '{"email": "' +
            booking.Hub_Account__r.Hub_Username__c +
            '","productId": "' +
            booking.Instance__r.Instance_ID__c +
            '"}';
    }
}