salesforce-main/src/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking is for</description>
    <label>Instance</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Instance__c.BPP_Instance_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>PO number related to this booking. This field is mandatory if the account requires PO&apos;s</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student that will be attending this booking</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Batch_Processed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Processed</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Account__c.field-meta.xml
<CustomField>
    <fullName>blng_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that will be invoiced for the booking</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines (Account)</relationshipLabel>
    <relationshipName>Booking_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_EndDateTime__c</fullName>
    <description>End date of the booking line. If session this will be session date, if material this will be the instance start date. This field will be populated by the booking line code</description>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_MatchingId__c.field-meta.xml
<CustomField>
    <fullName>blng_MatchingId__c</fullName>
    <description>This field will be the matching ID from the related booking summary. This field will be populated by the booking line creation code</description>
    <externalId>true</externalId>
    <label>Matching ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_Order__c.field-meta.xml
<CustomField>
    <fullName>blng_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order this booking relates to</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>blng_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order product line this booking line relates to.This field is populated by the booking line creation code</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>blng_StartDateTime__c</fullName>
    <description>The start date of the session if product family is session or the instance start date if product family is materials</description>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <description>Booking this booking line relates to</description>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Instance__c.field-meta.xml
<CustomField>
    <fullName>Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The instance this booking line relates to</description>
    <label>Instance</label>
    <referenceTo>Instance__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>The PO number this booking line is associated to</description>
    <label>PO Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <description>This field will hold the date used for revenue recognition for billing. For a session line the date will be the date of the session, for a material line the date will show the instance start date</description>
    <inlineHelpText>This field will hold the date used for revenue recognition for billing. For a session line the date will show the date of the actual session, for a material line the date will show the instance start date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The session record related to this booking line</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Booking Lines (Old)</relationshipLabel>
    <relationshipName>Booking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student attending this session or receiving these materials</description>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Instance__c/Instance__c.object-meta.xml
<CustomObject>
    <label>Instance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/classes/BookingLineBatch.cls
public class BookingLineBatch implements Schedulable, Database.Batchable<sObject>, Database.Stateful {
    private Map<String, String> fieldMapping = new Map<String, String>{
        'Id'                        => 'Booking_Line__c',
            'blng_Account__c'           => 'blng__Account__c',
            'blng_Order__c'             => 'blng__Order__c',
            'blng_OrderProduct__c'      => 'blng__OrderProduct__c',
            'blng_MatchingId__c'        => 'blng__MatchingId__c',
            'blng_StartDateTime__c'     => 'blng__StartDateTime__c',
            'blng_EndDateTime__c'       => 'blng__EndDateTime__c',
            'Booking__c'                => 'Booking__c',
            'Student__c'                => 'Student__c',
            'Instance__c'               => 'Instance__c',
            'Session__c'                => 'Session__c',
            'Rev_Rec_Date__c'           => 'Rev_Rec_Date__c',
            'PO_Number__c'              => 'PO_Number__c',
            'Booking__r.OwnerId'        => 'OwnerId'
            };
                private String objectName = 'Booking_Line__c';
    private String query;
    private String dateFieldName = 'blng_StartDateTime__c';
    private String boolField = 'Batch_Processed__c';
    private String statusField = 'On_Hold__c';
    private String statusValue = 'Cancelled';
    private Map<Id, List<String>> userIdToErrors;
    
    private String processName = Label.BATCH_Process_Name;
    private String errorMessageHeader = Label.BATCH_Error_Message_header;
    private String errorMessageLine = Label.BATCH_Error_Message;
    private String errorMessageNoReply = Label.BATCH_Error_no_reply;
    
    public BookingLineBatch() {
        this.userIdToErrors = new Map<Id, List<String>>();
        String whereClause = buildWhereClause('blng_StartDateTime__c', boolField, this.statusField, this.statusValue);
        this.query = buildQueryString(fieldMapping.keySet(), this.objectName, whereClause);
        System.debug(query);
    }
    
    public BookingLineBatch(String dateFieldName, String boolField, String statusField, String statusValue) {
        this.userIdToErrors = new Map<Id, List<String>>();
        this.dateFieldName = dateFieldName != null ? dateFieldName : this.dateFieldName;
        this.boolField = boolField != null ? boolField : this.boolField;
        this.statusField = statusField != null ? statusField : this.statusField;
        this.statusValue = statusValue != null ? statusValue : this.statusValue;
        String whereClause = buildWhereClause(this.dateFieldName, this.boolField, this.statusField, this.statusValue);
        this.query = buildQueryString(fieldMapping.keySet(), this.objectName, whereClause);
        System.debug(this.query);
    }
    
    private String buildWhereClause(String dateFieldName, String boolField, String statusField, String statusValue) {
        //Datetime dateToCalc = Date.today().addDays(-numOfDays);
        //String formattedDateTime = dateToCalc.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        statusValue = '\'' + statusValue + '\'';
        return String.format(
            '{0} = TODAY AND {1} = FALSE AND {2} != {3}', 
            new List<String>{dateFieldName, boolField, statusField, statusValue}
        );
    }
    
    private String buildQueryString(Set<String> fieldNames, String objectName, String whereClause) {
        String queryString = String.format(
            'SELECT {0} FROM {1}', 
            new List<String>{
                String.join(new List<String>(fieldMapping.keySet()), ','),
                    this.objectName
                    }
        );
        return queryString + ' WHERE ' + whereClause;
    }
    
    public void execute(SchedulableContext SC) {
        Database.executeBatch(this);
    }
    
    public static String cronBuilder(Datetime dateToStart) {
        return dateToStart.second() + ' '
            + dateToStart.minute() + ' '
            + dateToStart.hour() + ' '
            + dateToStart.day() + ' '
            + dateToStart.month() + ' '
            + '? '
            + dateToStart.year();
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<sObject> recordsToInsert = new List<sObject>();
        for(sObject sobj : scope) {
            blng__Usage__c usage = new blng__Usage__c();
            for(String bookingLineField : fieldMapping.keySet()) {
                Object fieldValue   = bookingLineField.contains('.') 
                    ? getParentFieldValue(sobj, bookingLineField) 
                    : sobj.get(bookingLineField);
                
                usage.put(fieldMapping.get(bookingLineField), fieldValue);
            }
            usage.put('blng__Quantity__c',1);
            recordsToInsert.add(usage);
            sobj.put(boolField, true);
        }
        try{
            insert recordsToInsert;
        } catch (DmlException e) {
            System.debug('Error is ' + e.getCause() + e.getMessage());
        }
        
        List<Database.SaveResult> saveResults = Database.insert(recordsToInsert, false);
        Map<Id, List<String>> errorsMap = processSaveResults(saveResults, scope);
        mergeErrors(this.userIdToErrors, errorsMap);
        saveResults = Database.update(scope, false);
        errorsMap = processSaveResults(saveResults, recordsToInsert);
        mergeErrors(this.userIdToErrors, errorsMap);
    }
    
    private Object getParentFieldValue(SObject inputSObject,String fieldName){
        if(inputSObject != null) {
            if (fieldName.contains('.')) {
                String nextFieldOrRelation = fieldName.substringAfter('.');
                String parentSObject = fieldName.substringBefore('.');
                return getParentFieldValue((SObject)inputSObject.getSObject(parentSObject), nextFieldOrRelation);
            } else {
                return inputSObject.get(fieldName);
            }
        }else {
            return null;
        }
    }
    
    private Map<Id, List<String>> processSaveResults(List<Database.SaveResult> saveResults, List<sObject> records) {
        Map<Id, List<String>> userIdToErrors = new Map<Id, List<String>>();
        for(Integer i=0; i<saveResults.size(); i++) {
            Database.SaveResult result = saveResults[i];
            if(!result.isSuccess()) {
                List<Database.Error> errors = result.getErrors();
                sObject originalRecord = records[i];
                Id userId = (Id) getParentFieldValue(originalRecord, 'Booking__r.OwnerId');
                String recordId = originalRecord.Id;
                List<String> errorMessages = new List<String>();
                for(Database.Error err : errors) {
                    errorMessages.add(
                        buildSingleErrorMessage(recordId, err.getMessage())
                    );
                }
                if(!userIdToErrors.containsKey(userId)) {
                    userIdToErrors.put(userId, new List<String>());
                }
                userIdToErrors.get(userId).addAll(errorMessages);
            }
        }
        return userIdToErrors;
    }
    
    private String buildSingleErrorMessage(Id recordId, String errorMessage) {
        return String.format(this.errorMessageLine, new List<String>{recordId, errorMessage});
    }
    
    private Map<Id, List<String>> mergeErrors(Map<Id, List<String>> targetMap, Map<Id, List<String>> newMap) {
        for(Id userId : newMap.keySet()) {
            if(!targetMap.containsKey(userId)) {
                targetMap.put(userId, new List<String>()); 
            }
            targetMap.get(userId).addAll(newMap.get(userId));
        }
        return targetMap;
    }
    
    private Map<Id, String> buildUserIdToErrorMessageMap(Map<Id, List<String>> userIdToErrors) {
        Map<Id, String> userIdToErrorMessageMap = new Map<Id, String>();
        for(Id userId : userIdToErrors.keySet()) {
            String message = String.format(this.errorMessageHeader, new List<String>{processName});
            message += '\n';
            for(String error : userIdToErrors.get(userId)) {
                message += error;
            }
            message += '\n';
            message += this.errorMessageNoReply;
            userIdToErrorMessageMap.put(userId, message);
        }
        return userIdToErrorMessageMap;
    }
    
    public void finish(Database.BatchableContext BC){
        Map<Id, String> userIdToErrorMessageMap = buildUserIdToErrorMessageMap(this.userIdToErrors);
        EmailUtils.sendEmailToUsers(userIdToErrorMessageMap, this.processName);
    }
    
    
}