salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Delivery record that is associated with this booking line (this is the parent object &amp; value is set automatically when the child record establishes the relationship)</description>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <description>Delivery object to track order items that need to be dispatched relating to either booking lines or order products (for LM only orders)</description>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DEL-{0000000}</displayFormat>
        <label>Delivery Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Delivery__c/fields/Booking_Line__c.field-meta.xml
<CustomField>
    <fullName>Booking_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking line that delivery is for - course orders</description>
    <label>Booking Line</label>
    <referenceTo>Booking_Line__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/classes/RevenueManager.cls
public with sharing class RevenueManager {
    /*public static void processBookingLineRevenue(List<Booking_Line__c> bookingLines) {
        List<blng.RevenueRecognitionResponse> revenueResponses = RevenueScheduleGenerator.generateFromBookingLines(bookingLines);
        for (blng.RevenueRecognitionResponse response : revenueResponses) {
            System.debug(response);
        }
    }*/

    public static void processDeliveryRevenue(List<Delivery__c> deliveries) {
        List<blng.RevenueRecognitionResponse> revenueResponses = RevenueScheduleGenerator.generateFromDeliveries(deliveries);
        for (blng.RevenueRecognitionResponse response : revenueResponses) {
            if (response.totalNumberOfInputsWithErrors > 0) {
                deliveries.get(0).addError('The system has encountered an issue whilst attempting to generate a Revenue Schedule record: ' + response.inputValidationStatus);
            } else {
                System.debug('@processDeliveryRevenue SUCCESS: ' + response.jobId + ' : ' + response.inputValidationStatus);
            }
        }
    }
}