salesforce-main/src/main/default/objects/Booking_Line__c/Booking_Line__c.object-meta.xml
<CustomObject>
    <label>Booking Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Booking Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>blng_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The order product line this booking line relates to.This field is populated by the booking line creation code</description>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/blng_PreratedAmount__c.field-meta.xml
<CustomField>
    <fullName>blng_PreratedAmount__c</fullName>
    <description>Field to hold the unit price of each booking line. This figure will be pulled from the order product line by the code creating the booking line</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Delivery record that is associated with this booking line (this is the parent object &amp; value is set automatically when the child record establishes the relationship)</description>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Booking Lines</relationshipLabel>
    <relationshipName>Booking_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <description>Delivery Status from the related delivery record</description>
    <formula>TEXT( Delivery__r.Delivery_Status__c )</formula>
    <label>Delivery Status</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/On_Hold__c.field-meta.xml
<CustomField>
    <fullName>On_Hold__c</fullName>
    <description>Status copied from the Booking record on creation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Rev_Rec_Date__c.field-meta.xml
<CustomField>
    <fullName>Rev_Rec_Date__c</fullName>
    <description>This field will hold the date used for revenue recognition for billing. For a session line the date will be the date of the session, for a material line the date will show the instance start date</description>
    <inlineHelpText>This field will hold the date used for revenue recognition for billing. For a session line the date will show the date of the actual session, for a material line the date will show the instance start date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Revenue_Recognition_Excluded__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Excluded__c</fullName>
    <description>Indicates whether booking line should be excluded from revenue recognition.  If true, no Revenue Transaction will be created.</description>
    <formula>OR(ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Apprenticeship bookings&quot;),
ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Poland bookings&quot;),
ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Channel Island bookings&quot;),
ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Learning Media Only&quot;),
ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Fixed Price Key Client Invoiced Off System&quot;),
ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Romania Bookings&quot;),
ISPICKVAL(blng_Order__r.Booking_Type__c, &quot;Malaysia Bookings&quot;),
ISPICKVAL(blng_Order__r.Billing_Mode__c, &quot;Billed off-system&quot;)
)</formula>
    <inlineHelpText>Indicates whether booking line should be excluded from revenue recognition.  If true, no Revenue Transaction will be created.</inlineHelpText>
    <label>Revenue Recognition Excluded</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Booking_Line__c/fields/Revenue_Recognition_Triggered__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Triggered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when call is made to Rev Rec API and used to prevent duplicate calls.</description>
    <inlineHelpText>Checked when call is made to Rev Rec API and used to prevent duplicate calls.</inlineHelpText>
    <label>Revenue Recognition Triggered</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <description>Delivery object to track order items that need to be dispatched relating to either booking lines or order products (for LM only orders)</description>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DEL-{0000000}</displayFormat>
        <label>Delivery Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-main/src/main/default/objects/Delivery__c/fields/Booking_Line__c.field-meta.xml
<CustomField>
    <fullName>Booking_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Booking line that delivery is for - course orders</description>
    <label>Booking Line</label>
    <referenceTo>Booking_Line__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_API_Call_Identifier__c.field-meta.xml
<CustomField>
    <fullName>BPP_API_Call_Identifier__c</fullName>
    <formula>IF(INCLUDES(Order_Product__r.blng__RevenueRecognitionRule__r.API_Call_Identifiers__c , &quot;Delivery - Full - RR Date&quot;), &quot;Delivery - Full - RR Date&quot;, null)</formula>
    <label>API Call Identifier</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>BPP_Legal_Entity__c</fullName>
    <formula>Order_Product__r.blng__LegalEntity__c</formula>
    <label>Legal Entity</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Order_Product_Bookings__c.field-meta.xml
<CustomField>
    <fullName>BPP_Order_Product_Bookings__c</fullName>
    <formula>Order_Product__r.SBQQ__OrderProductBookings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Product Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>BPP_Revenue_Amount__c</fullName>
    <formula>Booking_Line__r.blng_PreratedAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/BPP_Revenue_Recognition_Rule__c.field-meta.xml
<CustomField>
    <fullName>BPP_Revenue_Recognition_Rule__c</fullName>
    <formula>Order_Product__r.blng__RevenueRecognitionRule__c</formula>
    <label>Revenue Recognition Rule</label>
    <type>Text</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <description>Status of delivery</description>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Awaiting Allocation</fullName>
                <default>true</default>
                <label>Awaiting Allocation</label>
            </value>
            <value>
                <fullName>Ready for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Sent for Fulfilment</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Dispatched_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_Date__c</fullName>
    <description>Date the item was dispatched for delivery</description>
    <label>Dispatched Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Revenue_Recognised_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognised_Date__c</fullName>
    <description>If the booking line is for an item being delivered to centre the value is derived from the instance start date. If it is being delivered to student or is an LM order it matches the dispatch date.</description>
    <formula>IF( 
NOT( ISBLANK(Booking_Line__c))
 &amp;&amp;
NOT( ISBLANK(Delivered_to_BPP_Address__c)),
Booking_Line__r.Instance_Start_Date__c ,
Dispatched_Date__c
)</formula>
    <label>Revenue Recognised Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Revenue_Recognition_Excluded__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Excluded__c</fullName>
    <description>Indicates whether delivery should be excluded from revenue recognition.  If true, no Revenue Transaction will be created.</description>
    <formula>OR(ISPICKVAL(Order_Product__r.Order.Booking_Type__c, &quot;Apprenticeship bookings&quot;),
ISPICKVAL(Order_Product__r.Order.Booking_Type__c, &quot;Poland bookings&quot;),
ISPICKVAL(Order_Product__r.Order.Booking_Type__c, &quot;Channel Island bookings&quot;),
ISPICKVAL(Order_Product__r.Order.Booking_Type__c, &quot;Fixed Price Key Client Invoiced Off System&quot;),
ISPICKVAL(Order_Product__r.Order.Booking_Type__c, &quot;Romania Bookings&quot;),
ISPICKVAL(Order_Product__r.Order.Booking_Type__c, &quot;Malaysia Bookings&quot;),
ISPICKVAL(Order_Product__r.Order.Billing_Mode__c , &quot;Billed off-system&quot;)
)</formula>
    <inlineHelpText>Indicates whether delivery should be excluded from revenue recognition.  If true, no Revenue Transaction will be created.</inlineHelpText>
    <label>Revenue Recognition Excluded</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Revenue_Recognition_Triggered__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Triggered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>New checkbox, checked when call is made to Rev Rec API and used to prevent duplicate calls.</description>
    <label>Revenue Recognition Triggered</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/objects/Delivery__c/fields/Stock_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Stock_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows stock has been allocated for this delivery</description>
    <label>Stock Allocated</label>
    <type>Checkbox</type>
</CustomField>

salesforce-main/src/main/default/classes/RevenueScheduleGenerator.cls
/*
* @who   David Lovejoy <davidlovejoy@bpp.com>
* @what  To create Revenue Schedule records for Booking Line and Deliveries
* @when  28/06/2021
*/
public with sharing class RevenueScheduleGenerator {
    private static blng.RevenueRecognitionInput createRevenueRecognitionInput(Id source, String sourceFieldName, Decimal revenueAmount, Date startDate, Date endDate, Id revenueRecognitionRuleId, Id legalEntityId) {
        blng.RevenueRecognitionInput input = new blng.RevenueRecognitionInput();
        input.source = source;
        input.sourceFieldName = sourceFieldName;
        input.revenueAmount = revenueAmount;
        input.startDate = startDate;
        input.endDate = endDate;
        input.revenueRecognitionRuleId = revenueRecognitionRuleId;
        input.legalEntityId = legalEntityId;
        return input;
    }

    /*public static List<blng.RevenueRecognitionResponse> generateFromBookingLines(List<Booking_Line__c> bookingLines) {
        blng.RevenueRecognitionInput[] inputs = new List<blng.RevenueRecognitionInput>();

        for (Booking_Line__c bookingLine : bookingLines) {
            if (isBookingLineEligible(bookingLine)) {
                Date revRecDate = (bookingline.Rev_Rec_Date__c < System.TODAY()) ? System.TODAY() : bookingline.Rev_Rec_Date__c;
                Id revRecRuleId = bookingLine.blng_OrderProduct__r.blng__RevenueRecognitionRule__c;
                Id legalEntityId = bookingLine.blng_OrderProduct__r.blng__LegalEntity__c;

                inputs.add(createRevenueRecognitionInput(bookingLine.Id, 'Booking_Line__c', bookingLine.blng_PreratedAmount__c, revRecDate, null, revRecRuleId, legalEntityId));
            }
        }
        return blng.RevenueRecognition.recognizeRevenue(inputs);
    }*/

    public static List<blng.RevenueRecognitionResponse> generateFromDeliveries(List<Delivery__c> deliveries) {
        blng.RevenueRecognitionInput[] inputs = new List<blng.RevenueRecognitionInput>();
        Map<Id, blng__FinancePeriod__c> legalEntityFinancePeriodMap = createLegalEntityFinancePeriodMap(deliveries);
        
        for (Delivery__c delivery : deliveries) {
            System.debug(delivery);
            blng__FinancePeriod__c financePeriod = legalEntityFinancePeriodMap.get(delivery.BPP_Legal_Entity__c);
            Date revRecDate = (delivery.Dispatched_Date__c < System.TODAY()) && financePeriod != null && financePeriod.blng__PeriodStatus__c == 'Open' ? delivery.Dispatched_Date__c : System.TODAY();
            Decimal amountToRecognize = (delivery.Booking_Line__c != null ? delivery.BPP_Revenue_Amount__c : delivery.BPP_Order_Product_Bookings__c); 
            Id revRecRuleId = delivery.BPP_Revenue_Recognition_Rule__c;
            Id legalEntityId = delivery.BPP_Legal_Entity__c;
            inputs.add(createRevenueRecognitionInput(delivery.Id, 'Delivery__c', amountToRecognize, revRecDate, null, revRecRuleId, legalEntityId));
        }
        System.debug(inputs);
        return blng.RevenueRecognition.recognizeRevenue(inputs);
    }

    /*public static Boolean isBookingLineEligible(Booking_Line__c bookingLine) {
        return bookingLine.On_Hold__c == 'Confirmed' 
            && bookingline.Rev_Rec_Date__c != null 
            && bookingLine.Revenue_Recognition_Triggered__c == FALSE 
            && bookingLine.Revenue_Recognition_Excluded__c == FALSE 
            && bookingLine.blng_OrderProduct__r.blng__RevenueRecognitionRule__r.API_Call_Identifiers__c == 'Booking Line - Full - RR Date';
    }*/

    public static Boolean isDeliveryEligible(Delivery__c delivery) {
        return delivery.Delivery_Status__c == 'Dispatched' 
            && delivery.Revenue_Recognised_Date__c != null 
            && delivery.Revenue_Recognition_Triggered__c == FALSE 
            && delivery.Revenue_Recognition_Excluded__c == FALSE 
            && delivery.BPP_API_Call_Identifier__c == 'Delivery - Full - RR Date'
            && delivery.Stock_Allocated__c == FALSE;
    }

    public static Map<Id, blng__FinancePeriod__c> createLegalEntityFinancePeriodMap(List<Delivery__c> deliveries) {
        Set<Id> legalEntityIds = new Set<Id>();
        List<Date> deliveryDispatchedDates = new List<Date>();
        for (Delivery__c delivery : deliveries) {
            legalEntityIds.add(delivery.BPP_Legal_Entity__c);
            deliveryDispatchedDates.add(delivery.Dispatched_Date__c);
        }

        Map<Id, blng__FinancePeriod__c> legalEntityFinancePeriodMap = new Map<Id, blng__FinancePeriod__c>();
        List<blng__FinancePeriod__c> financePeriodList = [SELECT Id, blng__PeriodStatus__c, blng__PeriodStartDate__c, blng__PeriodEndDate__c, blng__LegalEntity__c FROM blng__FinancePeriod__c WHERE blng__FinanceBook__r.Name = 'Revenue Finance Book' AND blng__LegalEntity__c IN: legalEntityIds];
        for (Date dispatchedDate : deliveryDispatchedDates) {
            for (blng__FinancePeriod__c financePeriod : financePeriodList) {
                if (financePeriod.blng__PeriodStartDate__c <= dispatchedDate && financePeriod.blng__PeriodEndDate__c >= dispatchedDate) {
                    legalEntityFinancePeriodMap.put(financePeriod.blng__LegalEntity__c, financePeriod);
                }
            }
        }
        return legalEntityFinancePeriodMap;
    }
}