salesforce-main/src/main/default/objects/Lead/fields/Owner_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Owner_Change_Date__c</fullName>
    <label>Owner Change Date</label>
    <type>Date</type>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/rfi_Are_you_currently_studying_with_us__c.field-meta.xml
<CustomField>
    <fullName>rfi_Are_you_currently_studying_with_us__c</fullName>
    <label>Are you currently studying with us?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/rfi_Are_you_EU_UK__c.field-meta.xml
<CustomField>
    <fullName>rfi_Are_you_EU_UK__c</fullName>
    <label>Are you EU/UK?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UK Student</fullName>
            </value>
            <value>
                <fullName>EU Student</fullName>
            </value>
            <value>
                <fullName>International Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/rfi_Area_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>rfi_Area_of_Interest__c</fullName>
    <description>this is the select list for rfi</description>
    <label>Area of Interest - RFI</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>rfi_Are_you_EU_UK__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Accountancy</fullName>
            </value>
            <value>
                <fullName>Administration and Company Secretarial</fullName>
            </value>
            <value>
                <fullName>Alumni services and events</fullName>
            </value>
            <value>
                <fullName>Apprenticeships</fullName>
            </value>
            <value>
                <fullName>Banking and Finance</fullName>
            </value>
            <value>
                <fullName>Books and learning materials</fullName>
            </value>
            <value>
                <fullName>Business and Management</fullName>
            </value>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Careers service</fullName>
            </value>
            <value>
                <fullName>Clubs and societies</fullName>
            </value>
            <value>
                <fullName>Courses</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Foundation Courses</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Insolvency</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>Leadership and Personal Development</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Management and Leadership</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Open days and education events</fullName>
            </value>
            <value>
                <fullName>Pre-Masters Courses</fullName>
            </value>
            <value>
                <fullName>Preparatory English</fullName>
            </value>
            <value>
                <fullName>Probono</fullName>
            </value>
            <value>
                <fullName>Retail Distribution Review</fullName>
            </value>
            <value>
                <fullName>Secondary education (MPW)</fullName>
            </value>
            <value>
                <fullName>Student finance (loans and scholarships)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/rfi_Course_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>rfi_Course_of_Interest__c</fullName>
    <label>Course of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AAT</fullName>
            </value>
            <value>
                <fullName>ACA</fullName>
            </value>
            <value>
                <fullName>Academic English</fullName>
            </value>
            <value>
                <fullName>ACCA</fullName>
            </value>
            <value>
                <fullName>ACCA Professional Level Papers</fullName>
            </value>
            <value>
                <fullName>Accountancy/Taxation Professional Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Actuarial Technician Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Actuary Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Advanced Diploma in Accounting and Finance [ACCA Route]</fullName>
            </value>
            <value>
                <fullName>Agile Thinking in a Changing Business World</fullName>
            </value>
            <value>
                <fullName>Analytical and Critical Thinking</fullName>
            </value>
            <value>
                <fullName>Application Support Lead - Level 4</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Accounting</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Business and Administration</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Customer Service</fullName>
            </value>
            <value>
                <fullName>Apprenticeship General</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Law</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Professional Services</fullName>
            </value>
            <value>
                <fullName>Assistant Accountant Apprenticeship</fullName>
            </value>
            <value>
                <fullName>Associate Project Manager Apprenticeship</fullName>
            </value>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>Barrister Training Course (BTC)</fullName>
            </value>
            <value>
                <fullName>Bar Transfer Test (BTT)</fullName>
            </value>
            <value>
                <fullName>BSc Accounting and Finance</fullName>
            </value>
            <value>
                <fullName>BSc Nursing (Adult)</fullName>
            </value>
            <value>
                <fullName>BSc Nursing (Child)</fullName>
            </value>
            <value>
                <fullName>BSc Nursing (Mental Health)</fullName>
            </value>
            <value>
                <fullName>BTC Part 1</fullName>
            </value>
            <value>
                <fullName>BTC Part 2</fullName>
            </value>
            <value>
                <fullName>Building Effective Coaching Skills</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Rfi_Level_of_study__c.field-meta.xml
<CustomField>
    <fullName>Rfi_Level_of_study__c</fullName>
    <description>used in the rfi Form</description>
    <label>Level of study</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Professional Qualifications</fullName>
            </value>
            <value>
                <fullName>CPD/Professional Development</fullName>
            </value>
            <value>
                <fullName>Apprenticeships</fullName>
            </value>
            <value>
                <fullName>Higher Education Certificate in Health and Social Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/classes/LeadOwnerReassignment.cls
public class LeadOwnerReassignment {

public static Boolean firstRun = true;

public static ID reassignLead(Id leadid, ID userid, String rolename) {

               Lead l = [Select id,Name, ownerid, owner.name, rfi_Are_you_currently_studying_with_us__c,rfi_Area_of_Interest__c,rfi_Course_of_Interest__c,
                        rfi_Are_you_EU_UK__c,Rfi_Level_of_study__c from Lead where id=: leadid];
                    Set<ID> userIDSet = new Set<ID>();
                    List<USer> ulist = new List<User>();
                    List<Group> qlist = new List<Group>();  
                    Set<ID> existingSet = new Set<ID>();
                    Boolean done = false;                  
                    ID newOwnerid ;
                    if(done == false) {                    
                        if(rolename != null) {
                            ulist = [Select Id from User where userrole.developerName =: rolename and isactive = true order by Name];
                        }
                     }   
                        system.debug('***************ulist '+ulist);                    
                   
                        //ulist = [Select Id from User where userrole.Name =: 'DomesticTeamRecordAssignment' and isactive = true];
                        if(ulist.size() > 0) {
                           for(User u : ulist) {
                               if(u.id != userid) {
                                   userIDSet.add(u.id);
                               }
                            }                    
                        }
                        
                        system.debug('useridset.size()' + useridset.size());

                        List<AggregateResult> leadList = new List<AggregateResult>();
                        List<User> userlist1 = new List<User>();
                        leadList = [SELECT OwnerId,Owner.Name,  Count(id) FROM Lead where ownerid in:userIDSet and (CreatedDate = TODAY OR Owner_Change_Date__c = TODAY) group by ownerid, Owner.Name order by count(ownerid), Owner.Name];    
                          
                        if(leadList.size() == 0) {
                             if(ulist.size() > 0) {
                                 l.ownerid = ulist[0].Id;
                                 newOwnerid = ulist[0].Id;
                                 done = true;
                             }                               
                        }
                        
                        system.debug('leadlist.size(): ' + leadlist.size());
                        system.debug('done: ' + done);
                        if(leadlist.size() > 0 && done == false) {                            
                            system.debug('***************leadlist '+leadlist);    
                            for(AggregateResult g : leadList) {
                                existingSet.add((ID)g.get('OwnerId'));
                            }
                            if(existingSet.size() == userIdSet.size()) {                                                
                                l.ownerid = (ID)leadList[0].get('OwnerId');   
                                newOwnerid = (ID)leadList[0].get('OwnerId');                   
                                done = true;
                            }
                             else {
                              for(ID i : existingSet) {
                                   if(userIDSet.contains(i)) { userIDset.remove(i); }
                                   
                                 }                    
                              //List<ID> finalIDList = new List<ID>();
                              //finalIDList.addAll(userIDSet);                         
                               List<User> finalUserList = new List<User>();
                               finalUserList = [Select Id, Name from User where Id in: userIDSet order by Name];        
                               if(finalUserList.size() > 0) {
                                   l.ownerid = finalUserList[0].Id;
                                   newOwnerid = finalUserList[0].Id;
                                   done = true;
                               }                                                                                                                  
                            }
                       }
                       LeadOwnerReassignment.firstRun = false;
                   
                      //Database.SaveResult sr;
                      
                      //if(done = true) {                                                                  
                        // try {
                             //update l;
                            // LeadOwnerReassignment.firstRun = false;
                             //sr  = database.update(l);
                             //if(sr.isSuccess() == True) {
                               //  LeadOwnerReassignment.firstRun = false;
                             //}                             
                        // } Catch(DMLException ex1) { System.debug('Exception1    '+ ex1); }             
                    //}
                    system.debug('**************** '+l.ownerid);
                 //if(thelead.owner.type != 'Queue') 
                   if(done == true) {                 
                       Task t = new Task();
                       t.whoid = l.id;
                       t.ownerid = newOwnerid;
                       t.Subject = 'A New Lead is Assigned to you';                       
                   try {
                       insert t;
                   } Catch(DMLException ex){ system.debug('exception '+ex);  }
                   system.debug('*********************task '+t.owner.Name +'   '+ t);
                   }
                   
       return newOwnerid ;
       
        }


}