salesforce-main/src/main/default/objects/Lead/fields/Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Email__c</fullName>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/fields/Preferred_Phone__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Phone__c</fullName>
    <label>Preferred Phone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Parents/Guardian/Emergency</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce-main/src/main/default/objects/Lead/recordTypes/Business_Development.recordType-meta.xml
<RecordType>
    <fullName>Business_Development</fullName>
    <active>true</active>
    <businessProcess>Business Development</businessProcess>
    <description>Business_Development Lead</description>
    <label>Business Development</label>
</RecordType>

salesforce-main/src/main/default/objects/Lead/recordTypes/Prospective_Student.recordType-meta.xml
<RecordType>
    <fullName>Prospective_Student</fullName>
    <active>true</active>
    <businessProcess>Prospective Student</businessProcess>
    <description>Prospective Student</description>
    <label>Prospective Student</label>
</RecordType>

salesforce-main/src/main/default/classes/Test_BypassDuplicateCheck.cls
@isTest
public with sharing class Test_BypassDuplicateCheck {
    public static Integer i = 2;
    public static Id newRecordType = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
        .get('Prospective_Student')
        .getRecordTypeId();
    public static Id startingRecordType = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName()
        .get('Business_Development')
        .getRecordTypeId();
    public static String uniqueString = TestDataFactory.generateUniqueString();
    public static Map<String, Object> additionalFields = new Map<String, Object>{
        'FirstName' => 'Test Lead ' + uniqueString,
        'LastName' => 'Test Lead ' + uniqueString,
        'RecordTypeId' => startingRecordType,
        'Personal_Email__c' => 'test@test.test',
        'Preferred_Email__c' => 'Personal',
        'MobilePhone' => '+447234567890',
        'Preferred_Phone__c' => 'Mobile',
        'Company' => 'Test Company'
    };

    @isTest
    public static void duplicateRecordsCanBeInserted() {
        //GIVEN a number of Leads have the same details
        List<Lead> leadList = TestDataFactory.createLeads(2, false, additionalFields);
        List<BypassDuplicateCheck.Inputs> inputList = new List<BypassDuplicateCheck.Inputs>();
        for (Lead leadRecord : leadList) {
            BypassDuplicateCheck.Inputs input = new BypassDuplicateCheck.Inputs();
            input.recordToSave = leadRecord;
            input.insertOrUpdate = 'insert';
            inputList.add(input);
        }

        //WHEN the duplicates are passed to the BypassDuplicateCheck class
        Test.startTest();
        List<BypassDuplicateCheck.OutPuts> output = BypassDuplicateCheck.execute(inputList);

        //THEN both records are inserted regardless of any duplicate rules
        Test.stopTest();
        Assert.isTrue([SELECT Id FROM Lead].size() == i, 'Incorrect number of Leads inserted');
    }

    @isTest
    public static void duplicateRecordCanBeUpdated() {
        //GIVEN a number of Leads have the same details
        List<Lead> leadList = TestDataFactory.createLeads(2, false, additionalFields);
        List<BypassDuplicateCheck.Inputs> inputList = new List<BypassDuplicateCheck.Inputs>();
        for (Lead leadRecord : leadList) {
            BypassDuplicateCheck.Inputs input = new BypassDuplicateCheck.Inputs();
            input.recordToSave = leadRecord;
            input.insertOrUpdate = 'insert';
            inputList.add(input);
        }
        List<BypassDuplicateCheck.OutPuts> insertOutput = BypassDuplicateCheck.execute(inputList);

        List<BypassDuplicateCheck.Inputs> updateList = new List<BypassDuplicateCheck.Inputs>();
        BypassDuplicateCheck.Inputs updateRecord = new BypassDuplicateCheck.Inputs();
        Lead leadRecord = (Lead) inputList[0].recordToSave;
        leadRecord.RecordTypeId = newRecordType;
        leadRecord.Company = null;
        updateRecord.recordToSave = leadRecord;
        updateRecord.insertOrUpdate = 'update';
        updateList.add(updateRecord);

        //WHEN an existing duplicate is passed to the BypassDuplicateCheck class to be updated
        Test.startTest();
        List<BypassDuplicateCheck.OutPuts> updateOutput = BypassDuplicateCheck.execute(updateList);

        //THEN the duplicate record is updated regardless of any duplicate rules
        Test.stopTest();

        System.debug([SELECT Id, Name, RecordTypeId FROM Lead WHERE RecordTypeId = :newRecordType].size());
        Assert.isTrue(
            [SELECT Id FROM Lead WHERE RecordTypeId = :newRecordType].size() > 0,
            'Lead record type not updated'
        );
    }
}